#!/usr/bin/env dothttp

# imported from 35240-28db29ee-ca8d-4539-8a7a-6cde82dcfb73.postman_collection.json

// Retrieves all of the user's projects.

@name("Get Projects")
GET "https://{{baseUrl}}/projects"



