#!/usr/bin/env dothttp

# imported from 35240-f27f798d-07bf-410e-bc36-81f925cac47d.postman_collection.json

// [IPv6 only] Creates an egress-only internet gateway for your VPC.

@name("Create Egress Only Internet Gateway")
GET "https://{{aws_ec2_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "ClientToken"= ""
? "DryRun"= ""
? "VpcId"= ""
? "Action"= "CreateEgressOnlyInternetGateway"


// Deletes an egress-only internet gateway.

@name("Delete Egress Only Internet Gateway")
GET "https://{{aws_ec2_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "DryRun"= ""
? "EgressOnlyInternetGatewayId"= ""
? "Action"= "DeleteEgressOnlyInternetGateway"


// Describes one or more of your egress-only internet gateways.

@name("Describe Egress Only Internet Gateways")
GET "https://{{aws_ec2_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "DryRun"= ""
? "EgressOnlyInternetGatewayId.N"= ""
? "MaxResults"= ""
? "NextToken"= ""
? "Action"= "DescribeEgressOnlyInternetGateways"



