#!/usr/bin/env dothttp

# imported from 35240-b4284fc2-719c-44f6-8790-5e73e68963c4.postman_collection.json

// Retrieve the draft logical interface with the specified id.

@name("Get a draft logical interface")
GET "https://{{baseUrl}}/draft/logicalinterfaces/:logicalInterfaceId"



