#!/usr/bin/env dothttp

# imported from 35240-4cff9dbd-dc9e-457a-8421-41b9b4a7bdef.postman_collection.json

// Get a compliance reports previously created.n##### PermissionsnMust have `manage_system` permission.n

@name("Get a report")
GET "https://{{baseUrl}}/compliance/reports/:report_id"


// Download the full contents of a report as a file.n##### PermissionsnMust have `manage_system` permission.n

@name("Download a report")
GET "https://{{baseUrl}}/compliance/reports/:report_id/download"



