#!/usr/bin/env dothttp

# imported from 35240-81e3517b-5c56-4500-b086-0e52eb5d86ca.postman_collection.json

// Locales.

@name("locales")
GET "https://{{baseUrl}}/rest/v1/locales"


// Assuming that the given code is the code of an existing locale

@name("locale")
GET "https://{{baseUrl}}/rest/v1/locales/en_US"



