#!/usr/bin/env dothttp

# imported from 35240-e04c6fb1-e891-4983-80ec-38175b6c944e.postman_collection.json

// Add api margintrading account balance.

@name("Add API Margintrading Account Balance")
POST "https://{{baseUrl}}/api/MarginTrading/account/balance"
"Authorization": "<>"


// Delete api margintrading account reset account.

@name("Delete API Margintrading Account Reset Account")
DELETE "https://{{baseUrl}}/api/MarginTrading/account/reset/:accountId"
"Authorization": "<>"



