#!/usr/bin/env dothttp

# imported from 35240-7871656e-e03d-47bc-b756-528d4b913bbd.postman_collection.json

// This operation list or find ReserveBalance entities

@name("List or find ReserveBalance objects")
GET "https://{{baseUrl}}/reserveBalance"
? "fields"= "id voluptate"
? "offset"= "6696224"
? "limit"= "6696224"


// This operation creates a ReserveBalance entity.

@name("Creates a ReserveBalance")
POST "https://{{baseUrl}}/reserveBalance"
"Content-Type": "application/json;charset=utf-8"
json({
    "amount": {
        "amount": 1,
        "units": "dolor dolore enim quis eiusmod"
    },
    "confirmationDate": "2020-09-07T21:11:47.297Z",
    "description": "sunt dolore",
    "reason": "enim reprehenderit",
    "requestedDate": "1982-09-27T01:04:10.547Z",
    "status": "sed sint",
    "usageType": "consequat dolore mollit ut dolore",
    "bucket": {
        "id": "consequat",
        "href": "https://dAznyOxDMMZtkqJWQzGLQhQAoUiRjPrG.vmwhY,KzbGMt-H3S1hbrj19qwYRI0H-AZ",
        "name": "non tempor deserunt",
        "usageType": "sit elit",
        "@baseType": "non est ad dolore eiusmod",
        "@schemaLocation": "http://xOlgbUdCQHjDSwsxtKeGhkhUJogLiPKdL.vcJuxKEZTQlOzS2jPFLduZTMP0q-E4R",
        "@type": "ad qui irure officia",
        "@referredType": "Lorem fugiat laborum"
    },
    "channel": {
        "id": "Excepteur deserunt eu",
        "href": "http://UnmQHUOfUWFLhjaosRKw.iuyl8K7aSh3Bj",
        "name": "eu in elit in",
        "@baseType": "ut veniam",
        "@schemaLocation": "https://zzJcQnbJajabubfbGHEVJyR.mglQi3DAkg6P6WpKpT1WJwXaZQXxD9N4mNMc0BZ2tSRgTTs9WFHjoVkdwOAnXUvnDrKbTEOze",
        "@type": "mini",
        "@referredType": "dolore est"
    },
    "impactedBucket": [
        {
            "item": [
                {
                    "description": "aliquip officia in",
                    "itemType": "sed reprehenderit in",
                    "name": "sit adipisicing qui proident deserunt",
                    "reason": "eu velit reprehenderit dolor",
                    "amount": {
                        "amount": 1,
                        "units": "magna in"
                    },
                    "@baseType": "dolor in nisi",
                    "@schemaLocation": "https://hYzqqjCbXzZqFBmcelKrjOana.nem9thXDUv+i+p+kztroAG3T7hdy1bJu",
                    "@type": "ullamco dolore"
                }
            ],
            "confirmationDate": "2017-06-28T18:41:00.475Z",
            "description": "et ex ",
            "name": "ullamco pariatur ut enim",
            "requestedDate": "1973-04-10T02:03:44.778Z",
            "amountAfter": {
                "amount": 1,
                "units": "cupidatat incididunt in"
            },
            "amountBefore": {
                "amount": 1,
                "units": "id in nulla"
            },
            "bucket": {
                "id": "mollit cupidatat sit",
                "href": "https://CURaDsOeuym.sesyuMNdH-1qCJwcMxIgygMrukbgrSPaePD55r9WkiES-feRN,wh9vPAx1KC",
                "name": "est in",
                "usageType": "dolor in",
                "@baseType": "in",
                "@schemaLocation": "https://MWFF.xeyktd7nGvN837Wsing0lrskR5dfV2Q46xjGZEQht83cUFXiCw-7gXqOlWMGxMb",
                "@type": "et sint",
                "@referredType": "non"
            },
            "@baseType": "dolor voluptate deserunt",
            "@schemaLocation": "http://sSzBwfHbvKvugvOyRVQpDcKJqQA.akmCWT4AXB.-ZNyWCmnMFd1HFmouvQM8A1b4-UoAZU++XJx,DrLFQkI1juYUhMJewxuDUz8AL.I,6Lb",
            "@type": "officia amet incididunt id Ut"
        },
        {
            "item": [
                {
                    "description": "reprehenderit Ut nisi elit ad",
                    "itemType": "adipisicing Lorem sit",
                    "name": "laborum",
                    "reason": "anim ut proident",
                    "amount": {
                        "amount": 1,
                        "units": "nostrud aliqua ullamco"
                    },
                    "@baseType": "in dolor cillum",
                    "@schemaLocation": "https://R.skbrk0nTeyd2-KGxKRU4S1WWBuDxtbk,LKRZai2AVqVh8C",
                    "@type": "Ut sit"
                }
            ],
            "confirmationDate": "1969-10-27T14:29:59.075Z",
            "description": "Ut aute",
            "name": "laboris nulla",
            "requestedDate": "1967-12-20T01:52:13.846Z",
            "amountAfter": {
                "amount": 1,
                "units": "do commodo esse"
            },
            "amountBefore": {
                "amount": 1,
                "units": "nisi elit ad consectetur"
            },
            "bucket": {
                "id": "est volupta",
                "href": "https://UyxYoTUGmetctBnqofoeNpCXxBPJJ.tqq7+rxtq70QtV7vPMtpPTcTcNoczwZ3SCI",
                "name": "consectetur",
                "usageType": "veniam et ",
                "@baseType": "Duis Ut nostrud",
                "@schemaLocation": "http://YcvIwzYoABDCGcXuKwskkNVFvIkYVuPJ.irqrM8ZJMrsGOF0uohUmQRgMZSPNUC-.iU.CSZ0ngxrEjgtaTiXl-bTrjOxx4HHHIr",
                "@type": "et laboris aliquip ullamco",
                "@referredType": "occaecat minim adipisicing reprehenderit"
            },
            "@baseType": "magna deserunt culpa irure",
            "@schemaLocation": "http://IHSsawDMzGMLnFxVncUCfDBxmeIocvP.fjtZRVDLs,LWfaT3SRfbRwJpv4qnWIOMGvHlG7qI77w",
            "@type": "laborum reprehenderit dolore"
        }
    ],
    "logicalResource": {
        "id": "anim ea quis qui",
        "href": "http://JOUsrxICXewlVolBWfuajwvT.ftmneOO9zgzzLYpvn56SMKyZgAhgAh",
        "name": "officia",
        "value": "laborum dolor elit voluptate cupidatat",
        "@baseType": "ullamco adipisicing quis",
        "@schemaLocation": "https://bpZihE.nrjd8mvT+LxGbILtrZHhvSKM0,ppBf0aEAYhmxGVyMcGfDE0DpzbBP0t0pPiqa-i2oOpmFzEervyCL",
        "@type": "Ut fugiat cillum ipsum",
        "@referredType": "tempor non dolore"
    },
    "partyAccount": {
        "id": "ullamco qui",
        "href": "in",
        "description": "Ut veniam",
        "name": "reprehenderit cupidatat dolor dolore qui",
        "status": "eu magna labore nostrud qui",
        "@baseType": "officia id do",
        "@schemaLocation": "http://looirQYfiuOkQFhWmuVukNiC.weyeJwpv,zQdSsEdl7VpNA",
        "@type": "do voluptate dolor",
        "@referredType": "consectetur dolore"
    },
    "product": {
        "id": "sed in dolor reprehenderit eu",
        "href": "https://QQnHydPEG.fvebdQzjOh8-MtJ-VEAr-F82AGRc.HL2Q6VLrptpNVnPY+-Oup+bZs3sw",
        "name": "ex",
        "@baseType": "sunt elit commodo amet non",
        "@schemaLocation": "http://kbJlSDFhDpHJSNdFMoiEexdwPf.wzojFmQ.OAKg97Z5c2u-xrshrefUPeSRxL1Qwblu1fEFdzkMVyUevFyeaY0AuyAYZVNZTGxgc",
        "@type": "occaecat ipsum velit",
        "@referredType": "quis"
    },
    "relatedParty": [
        {
            "@referredType": "nostrud la",
            "id": "in consectetur",
            "href": "https://ohoWqCpfzowwleoaXqIapomiGRtUC.nvioqQbzWRrXI,RBwUxnzniMGPqS0c1b69oWP3owrubG.Zr4wWu+KIjqb",
            "name": "in ea",
            "role": "pariatur exercitation reprehenderit",
            "@baseType": "dolore",
            "@schemaLocation": "http://eVNQvk.elavl+B53hg9hSqIWYKQua6qFAD3UtPvQucUrR1XIMdfmklKaerTOBElSBnPpF",
            "@type": "nisi consequat reprehenderit elit"
        },
        {
            "@referredType": "ullamco anim",
            "id": "sed magna elit consequat",
            "href": "http://qqFrTITfRwcQXkcZBwqEXM.qwkwlNXHsqixzSKD",
            "name": "irure laboris do",
            "role": "Ut fugiat",
            "@baseType": "tempor",
            "@schemaLocation": "https://xmMcwnugJdifzpZegwcXwEuVUSUNK.nemzS,O3XTghhPDRT,.qSLQC92zKqrwtiwrGX94vsJTYQBJr8nZ",
            "@type": "Ut dolor velit"
        }
    ],
    "requestor": {
        "@referredType": "voluptate id eiusmod et",
        "id": "ut non laboris",
        "href": "http://roSPcUEcgZorkFedhFqVuj.mvicCNmdrye1pdN",
        "name": "sunt ex et laborum in",
        "role": "pariatur est nostrud elit sit",
        "@baseType": "culpa commodo",
        "@schemaLocation": "https://dUSemUbMbpKEOQhhjDeZrJrIBgucrc.byXmCECDEShZ",
        "@type": "ex eiusmod minim"
    },
    "@baseType": "Ut culpa elit amet",
    "@schemaLocation": "https://OcunI.gjcy-CsqM9Fp0TFPDFLQhF2TYhytukSaTcoAuaADE3FK",
    "@type": "e"
})



