#!/usr/bin/env dothttp

# imported from 35240-d76987fb-f2f9-425d-9645-ecebd487c07d.postman_collection.json

// A list of available Railguns the zone can use

@name("A list of available Railguns the zone can use")
GET "https://{{baseUrl}}/zones/:zone_identifier/railguns"



