#!/usr/bin/env dothttp

# imported from 35240-ac6561cd-0334-4ee5-8280-57b4086d4c3d.postman_collection.json

// **Deprecation Notice:** This endpoint route is deprecated and will be removed from the Teams API. We recommend migrating your existing code to use the new [`List team members`](https://developer.github.com/v3/teams/members/#list-team-members) endpoint.
// 
// Team members will include the members of child teams.

@name("List team members (Legacy)")
GET "https://{{baseUrl}}/teams/:team_id/members"
? "role"= "all"
? "per_page"= "30"
? "page"= "1"



