#!/usr/bin/env dothttp

# imported from 35240-a96221e2-b43c-4973-9be0-3ec0566f4cd9.postman_collection.json

// Get a list of all fulfillments for an order..

@name("Get a list of all fulfillments for an order.")
GET "https://{{baseUrl}}/admin/orders/4495703502/fulfillments.json"
"Content": "<>"



