#!/usr/bin/env dothttp

# imported from 35240-b4ad2590-7a09-4b2a-9ac8-f9039ba10098.postman_collection.json

// This operation list or find PartyRoleProductOfferingRiskAssessment entities

@name("List or find PartyRoleProductOfferingRiskAssessment objects")
GET "https://{{baseUrl}}/partyRoleProductOfferingRiskAssessment"
? "fields"= "quis elit commodo tempor"
? "offset"= "-80657290"
? "limit"= "-80657290"


// This operation creates a PartyRoleProductOfferingRiskAssessment entity.

@name("Creates a PartyRoleProductOfferingRiskAssessment")
POST "https://{{baseUrl}}/partyRoleProductOfferingRiskAssessment"
"Content-Type": "application/json;charset=utf-8"
json({
    "partyRole": {
        "@referredType": "consectetur",
        "id": "Duis magna enim non exercitation",
        "href": "https://rmmDP.ivmO8YfpWP,8DUd-ThldMguKUSyTlIccuC88naqOuoy1p54YBSfIHkVyqfgnT",
        "name": "et aliquip exercitation",
        "role": "fugiat cillum et incididunt",
        "@baseType": "irure",
        "@schemaLocation": "http://Uw.anghOE8ncnMpDAuWnF2cBxUkL8Rg3hNV6OJ6NgpslFGsU6bvfQRmzrRgxipcFJ-",
        "@type": "laborum dolor exercitation nulla"
    },
    "productOffering": {
        "id": "consequat ut",
        "href": "https://CPoLgnmDXlSnOBhtZsGzaYijGgBL.opnsPwzLI2",
        "name": "adipisicing elit",
        "@baseType": "ma",
        "@schemaLocation": "http://ukrEZJzKChaicTzijOHSMkddUmxj.gaziWed0YRqILb.hLXu2o3Cv9f0q8qSjcSDm4kxhIbWsAyhZ",
        "@type": "reprehenderit minim Duis",
        "@referredType": "aliqua culpa id Excepteur in"
    },
    "status": "ipsum dolore magna",
    "characteristic": [
        {
            "name": "Lorem culpa mollit",
            "value": {},
            "id": "sunt pariatur",
            "valueType": "veniam labore in",
            "characteristicRelationship": [
                {
                    "id": "elit magna",
                    "href": "https://LsJ.wogdWbS,REgljILVIRcjKuRyyjx3HQXx",
                    "relationshipType": "ipsum officia ad",
                    "@baseType": "ad enim exercitation laboris",
                    "@schemaLocation": "http://GqcjWIMv.pcfNtrEftb5l7hYQNQdPlaR.Pv7Zua7RD4gvktcS5ofl9FyaJr.sdsnrsRpYQ5CpItq8LwWz",
                    "@type": "amet ullamco nostrud Excepteur magna"
                },
                {
                    "id": "nostrud",
                    "href": "https://QsbocJtLo.sbI,mEUPmke677JwKaAAdlJ-Jack352Uv3",
                    "relationshipType": "incididunt ullamco",
                    "@baseType": "laboris do",
                    "@schemaLocation": "https://HagOeNUUbgROGcMzkxdSlRa.lwuvQRMsErZ5j-R9TEdD00CMuXs6bZlxmz-NRnE0rc2VSOYuOzC0QB.GsO",
                    "@type": "ut dolor in sed"
                }
            ],
            "@baseType": "cupidatat sit",
            "@schemaLocation": "http://kELIrrlwYJOjpnwVv.bwpgLY36ncgxN1B,Wsw+bGwpXIfHWYpTUOzsG,IW",
            "@type": "consectetur"
        },
        {
            "name": "cillum in Excepteur id",
            "value": {},
            "id": "et laborum minim",
            "valueType": "exercitation amet Duis veniam",
            "characteristicRelationship": [
                {
                    "id": "quis cupidatat voluptate exercitation dolore",
                    "href": "https://PONVjoOVQBJNOiDqYu.uihsbJL,awwGB6Fsxe6NBp1EO2iR6",
                    "relationshipType": "irure dolore in enim Lorem",
                    "@baseType": "qui Lorem proident dolore ipsum",
                    "@schemaLocation": "http://hxdmuwppcDrAfqbfQOoTMiH.alhQZdOLGpRdDvzvDLdVy",
                    "@type": "culpa nulla"
                },
                {
                    "id": "mollit exercitation ut",
                    "href": "https://yMqeINOvVxEIoonAatmX.sjfgVqV-Pb3zlVQ4y.mv",
                    "relationshipType": "cillum anim",
                    "@baseType": "occaecat",
                    "@schemaLocation": "https://bZQTrbJvMNVirk.kjlYbIP2Dj.1iFG3yxFFcqtpp.o7qvsf+qgq",
                    "@type": "ut pariatur"
                }
            ],
            "@baseType": "ut ex veniam",
            "@schemaLocation": "http://BPWh.ggDvOeWKqJiCT9KCOMW8czbkTqW-,LZt",
            "@type": "cupidatat adipisicing ullamco"
        }
    ],
    "place": {
        "id": "aliqua Ut",
        "href": "consectetur et",
        "name": "culpa incididunt",
        "role": "dolore in consequat exerci",
        "@baseType": "irure est",
        "@schemaLocation": "https://fsIkYSoPssmVSxgTNwDDxSKEpMqiL.nssuPxtRi",
        "@type": "officia voluptate",
        "@referredType": "elit laborum velit Lorem"
    },
    "riskAssessmentResult": {
        "overallScore": -21455001.061626345,
        "score": [
            {
                "score": 84198875.72747466,
                "riskName": "PaymentMethodRisk",
                "@baseType": "officia id nisi ex elit",
                "@schemaLocation": "http://r.xaPVHRARagw7xTlMCIBrJzf1rKjSGSXclpQYx4ODMK",
                "@type": "amet"
            },
            {
                "score": 24534104.99013731,
                "riskName": "CreditGamingRisk",
                "@baseType": "dolore veniam ",
                "@schemaLocation": "http://Up.felqhLJOHeb.YYs+iWKZPZFV7OWMhP2V+xGrE9HtRZOpWO+bimmiegwc6XXIojp.7FBHRDh64gb1",
                "@type": "cupidatat consectetur incididunt in"
            }
        ],
        "validFor": {
            "id": "ut voluptate est",
            "href": "http://EqvtcdGRQtxSy.kwiMlZ6kOGUrqevxSh-ZufENC3,lEgXFR,Yz53WpHK3vsdQtzcleswkeE+lS5I3OO+",
            "endDateTime": "1985-04-12T23:20:50.52Z",
            "startDateTime": "1985-04-12T23:20:50.52Z",
            "@baseType": "do",
            "@schemaLocation": "https://QAzPVNjQxpkcxARH.tuvooVtksBHyBT",
            "@type": ""
        },
        "@baseType": "labore sed cupidatat in",
        "@schemaLocation": "http://poBBwUUecA.ihgjbLgXzXUnPrMKyfWcaBuGloN+pdwcJzMBBET7x",
        "@type": "enim consequat"
    },
    "@baseType": "ut",
    "@schemaLocation": "https://fajldHtaMqaNZZwDwVCYGGI.osbC+hgMFPVVAaurnYU5I",
    "@type": "Ut ex enim"
})



