#!/usr/bin/env dothttp

# imported from 35240-582f30d6-554e-4cb2-a58f-34f9aa631c05.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


@name("Custom Brand Asset") : "base-inherit-auth"
GET "https://{{host}}/services/data/v47.0/sobjects/CustomBrandAsset/"


@name("Custom Brand Asset Detail") : "base-inherit-auth"
GET "https://{{host}}/services/data/v47.0/sobjects/CustomBrandAsset/{ID}/"


@name("Describe Custom Brand Asset") : "base-inherit-auth"
GET "https://{{host}}/services/data/v47.0/sobjects/CustomBrandAsset/describe/"



