#!/usr/bin/env dothttp

# imported from 35240-adc2da4d-b751-4bf5-9e03-e1950af35609.postman_collection.json

@name("Get suggestions")
GET "https://{{baseUrl}}/suggest/v1/:type"
"X-App-Token": "<string>"
? "query"= "<string>"
? "limit"= "5"
? "variable_id"= "<string>"
? "app_token"= "<string>"



