#!/usr/bin/env dothttp

# imported from 35240-af2f73d6-96cf-46d7-a9a8-7e4e19ca898b.postman_collection.json

@name("Provides team versus team data")
GET "https://{{baseUrl}}/competitors/:competitor_id1/versus/:competitor_id2/matches{{format}}"



