#!/usr/bin/env dothttp

# imported from 35240-e8996367-eb05-4e8c-bb28-641af265ab9d.postman_collection.json

// Lists the blocks for a connected blockchain network.

@name("Get Ledgers Connections Blocks")
GET "https://{{baseUrl}}/api/v1/ledgers/connections/:connectionId/blocks"
? "top"= "<>"
? "skip"= "<>"


// Gets the block matching a specific block ID.

@name("Get Ledgers Connections Blocks Blockid")
GET "https://{{baseUrl}}/api/v1/ledgers/connections/:connectionId/blocks/:blockId"



