#!/usr/bin/env dothttp

# imported from 35240-fea163a7-948d-4076-bc08-6fdcc26865e0.postman_collection.json

// A paginated list of the node's contributors, sorted by their index.nnContributors are users who can make changes to the node or, in the case of private nodes, have read access to the node.nnContributors are categorized as either bibliographic or non-bibliographic. From a permissions standpoint, both are the same, but bibliographic contributors are included in citations and are listed on the project overview page on the OSF, while non-bibliographic contributors are not.nnNote that if an anony

@name("List all contributors")
GET "https://{{baseUrl}}/nodes/:node_id/contributors/"


// Removes a contributor from a node. This request only removes the relationship between the node and the user, it does not delete the user itself.nnA node must always have at least one admin, and attempting to remove the only admin from a node will result in a **400 Bad Request** response.n#### PermissionsnA user can remove themselves as a node contributor. Otherwise, only project administrators can remove contributors.n#### ReturnsnIf the request is successful, no content is returned.nnIf the req

@name("Delete a contributor")
DELETE "https://{{baseUrl}}/nodes/:node_id/contributors/:user_id/"



