#!/usr/bin/env dothttp

# imported from 35240-6990c4c3-ec47-4850-8d11-1a18a1fbabeb.postman_collection.json

// Remove a mapping from this domain.

@name("/Accounts/:AccountSid/SIP/Domains/:SipDomainSid/IpAccessControlListMappings/{{ALSid}}{{mediaTypeExtension}}")
DELETE "https://{{baseUrl}}/Accounts/:AccountSid/SIP/Domains/:SipDomainSid/IpAccessControlListMappings/{{ALSid}}{{mediaTypeExtension}}"


// Remove a mapping from this domain.

@name("Accounts.Account Sid.SIP.Domains.Sip Domain Sid.Ip Access Control List Mappings.AL Sid.json.delete")
DELETE "https://{{baseUrl}}/Accounts/:AccountSid/SIP/Domains/:SipDomainSid/IpAccessControlListMappings/{{ALSid}}.json"



