#!/usr/bin/env dothttp

# imported from 35240-438c1bb3-fd17-4abc-9513-4f1edde0dc3d.postman_collection.json

// Adds a new data entry

@name("Get Service Data Action Add")
GET "https://{{baseUrl}}/service/data/action/add"
? "dataEntry[name]"= "<>"
? "dataEntry[description]"= "<>"
? "dataEntry[userId]"= "<>"
? "dataEntry[creatorId]"= "<>"
? "dataEntry[tags]"= "<>"
? "dataEntry[adminTags]"= "<>"
? "dataEntry[categories]"= "<>"
? "dataEntry[categoriesIds]"= "<>"
? "dataEntry[type]"= "<>"
? "dataEntry[groupId]"= "<>"
? "dataEntry[partnerData]"= "<>"
? "dataEntry[licenseType]"= "<>"
? "dataEntry[accessControlId]"= "<>"
? "dataEntry[startDate]"= "<>"
? "dataEntry[endDate]"= "<>"
? "dataEntry[referenceId]"= "<>"
? "dataEntry[partnerSortValue]"= "<>"
? "dataEntry[conversionProfileId]"= "<>"
? "dataEntry[redirectEntryId]"= "<>"
? "dataEntry[parentEntryId]"= "<>"
? "dataEntry[operationAttributes]"= "<>"
? "dataEntry[entitledUsersEdit]"= "<>"
? "dataEntry[entitledUsersPublish]"= "<>"
? "dataEntry[templateEntryId]"= "<>"
? "dataEntry[displayInSearch]"= "<>"
? "dataEntry[dataContent]"= "<>"
? "dataEntry[retrieveDataContentByGet]"= "<>"


// Delete a data entry.

@name("Get Service Data Action Delete")
GET "https://{{baseUrl}}/service/data/action/delete"
? "entryId"= "<>"


// Get data entry by ID.

@name("Get Service Data Action Get")
GET "https://{{baseUrl}}/service/data/action/get"
? "entryId"= "<>"
? "version"= "<>"


// List data entries by filter with paging support.

@name("Get Service Data Action List")
GET "https://{{baseUrl}}/service/data/action/list"
? "filter[orderBy]"= "<>"
? "filter[advancedSearch][objectType]"= "<>"
? "filter[advancedSearch][value]"= "<>"
? "filter[advancedSearch][categoriesMatchOr]"= "<>"
? "filter[advancedSearch][categoryEntryStatusIn]"= "<>"
? "filter[advancedSearch][orderBy]"= "<>"
? "filter[advancedSearch][categoryIdEqual]"= "<>"
? "filter[advancedSearch][memberIdEq]"= "<>"
? "filter[advancedSearch][memberIdIn]"= "<>"
? "filter[advancedSearch][memberPermissionsMatchOr]"= "<>"
? "filter[advancedSearch][memberPermissionsMatchAnd]"= "<>"
? "filter[advancedSearch][noDistributionProfiles]"= "<>"
? "filter[advancedSearch][distributionProfileId]"= "<>"
? "filter[advancedSearch][distributionSunStatus]"= "<>"
? "filter[advancedSearch][entryDistributionFlag]"= "<>"
? "filter[advancedSearch][entryDistributionStatus]"= "<>"
? "filter[advancedSearch][hasEntryDistributionValidationErrors]"= "<>"
? "filter[advancedSearch][entryDistributionValidationErrors]"= "<>"
? "filter[advancedSearch][contentLike]"= "<>"
? "filter[advancedSearch][contentMultiLikeOr]"= "<>"
? "filter[advancedSearch][contentMultiLikeAnd]"= "<>"
? "filter[advancedSearch][cuePointsFreeText]"= "<>"
? "filter[advancedSearch][cuePointTypeIn]"= "<>"
? "filter[advancedSearch][cuePointSubTypeEqual]"= "<>"
? "filter[advancedSearch][watermarkId]"= "<>"
? "filter[advancedSearch][indexIdGreaterThan]"= "<>"
? "filter[advancedSearch][depthGreaterThanEqual]"= "<>"
? "filter[advancedSearch][isQuiz]"= "<>"
? "filter[advancedSearch][field]"= "<>"
? "filter[advancedSearch][type]"= "<>"
? "filter[advancedSearch][items]"= "<>"
? "filter[advancedSearch][idEqual]"= "<>"
? "filter[advancedSearch][idIn]"= "<>"
? "filter[advancedSearch][userIdEqual]"= "<>"
? "filter[advancedSearch][userIdIn]"= "<>"
? "filter[advancedSearch][updatedAtGreaterThanOrEqual]"= "<>"
? "filter[advancedSearch][updatedAtLessThanOrEqual]"= "<>"
? "filter[advancedSearch][extendedStatusEqual]"= "<>"
? "filter[advancedSearch][extendedStatusIn]"= "<>"
? "filter[advancedSearch][comparison]"= "<>"
? "filter[advancedSearch][not]"= "<>"
? "filter[advancedSearch][attribute]"= "<>"
? "filter[advancedSearch][metadataProfileId]"= "<>"
? "filter[idEqual]"= "<>"
? "filter[idIn]"= "<>"
? "filter[idNotIn]"= "<>"
? "filter[nameLike]"= "<>"
? "filter[nameMultiLikeOr]"= "<>"
? "filter[nameMultiLikeAnd]"= "<>"
? "filter[nameEqual]"= "<>"
? "filter[partnerIdEqual]"= "<>"
? "filter[partnerIdIn]"= "<>"
? "filter[userIdEqual]"= "<>"
? "filter[userIdIn]"= "<>"
? "filter[userIdNotIn]"= "<>"
? "filter[creatorIdEqual]"= "<>"
? "filter[tagsLike]"= "<>"
? "filter[tagsMultiLikeOr]"= "<>"
? "filter[tagsMultiLikeAnd]"= "<>"
? "filter[adminTagsLike]"= "<>"
? "filter[adminTagsMultiLikeOr]"= "<>"
? "filter[adminTagsMultiLikeAnd]"= "<>"
? "filter[categoriesMatchAnd]"= "<>"
? "filter[categoriesMatchOr]"= "<>"
? "filter[categoriesNotContains]"= "<>"
? "filter[categoriesIdsMatchAnd]"= "<>"
? "filter[categoriesIdsMatchOr]"= "<>"
? "filter[categoriesIdsNotContains]"= "<>"
? "filter[categoriesIdsEmpty]"= "<>"
? "filter[statusEqual]"= "<>"
? "filter[statusNotEqual]"= "<>"
? "filter[statusIn]"= "<>"
? "filter[statusNotIn]"= "<>"
? "filter[moderationStatusEqual]"= "<>"
? "filter[moderationStatusNotEqual]"= "<>"
? "filter[moderationStatusIn]"= "<>"
? "filter[moderationStatusNotIn]"= "<>"
? "filter[typeEqual]"= "<>"
? "filter[typeIn]"= "<>"
? "filter[createdAtGreaterThanOrEqual]"= "<>"
? "filter[createdAtLessThanOrEqual]"= "<>"
? "filter[updatedAtGreaterThanOrEqual]"= "<>"
? "filter[updatedAtLessThanOrEqual]"= "<>"
? "filter[totalRankLessThanOrEqual]"= "<>"
? "filter[totalRankGreaterThanOrEqual]"= "<>"
? "filter[groupIdEqual]"= "<>"
? "filter[searchTextMatchAnd]"= "<>"
? "filter[searchTextMatchOr]"= "<>"
? "filter[accessControlIdEqual]"= "<>"
? "filter[accessControlIdIn]"= "<>"
? "filter[startDateGreaterThanOrEqual]"= "<>"
? "filter[startDateLessThanOrEqual]"= "<>"
? "filter[startDateGreaterThanOrEqualOrNull]"= "<>"
? "filter[startDateLessThanOrEqualOrNull]"= "<>"
? "filter[endDateGreaterThanOrEqual]"= "<>"
? "filter[endDateLessThanOrEqual]"= "<>"
? "filter[endDateGreaterThanOrEqualOrNull]"= "<>"
? "filter[endDateLessThanOrEqualOrNull]"= "<>"
? "filter[referenceIdEqual]"= "<>"
? "filter[referenceIdIn]"= "<>"
? "filter[replacingEntryIdEqual]"= "<>"
? "filter[replacingEntryIdIn]"= "<>"
? "filter[replacedEntryIdEqual]"= "<>"
? "filter[replacedEntryIdIn]"= "<>"
? "filter[replacementStatusEqual]"= "<>"
? "filter[replacementStatusIn]"= "<>"
? "filter[partnerSortValueGreaterThanOrEqual]"= "<>"
? "filter[partnerSortValueLessThanOrEqual]"= "<>"
? "filter[rootEntryIdEqual]"= "<>"
? "filter[rootEntryIdIn]"= "<>"
? "filter[parentEntryIdEqual]"= "<>"
? "filter[entitledUsersEditMatchAnd]"= "<>"
? "filter[entitledUsersEditMatchOr]"= "<>"
? "filter[entitledUsersPublishMatchAnd]"= "<>"
? "filter[entitledUsersPublishMatchOr]"= "<>"
? "filter[tagsNameMultiLikeOr]"= "<>"
? "filter[tagsAdminTagsMultiLikeOr]"= "<>"
? "filter[tagsAdminTagsNameMultiLikeOr]"= "<>"
? "filter[tagsNameMultiLikeAnd]"= "<>"
? "filter[tagsAdminTagsMultiLikeAnd]"= "<>"
? "filter[tagsAdminTagsNameMultiLikeAnd]"= "<>"
? "filter[freeText]"= "<>"
? "filter[isRoot]"= "<>"
? "filter[categoriesFullNameIn]"= "<>"
? "filter[categoryAncestorIdIn]"= "<>"
? "filter[redirectFromEntryId]"= "<>"
? "pager[pageSize]"= "<>"
? "pager[pageIndex]"= "<>"



