#!/usr/bin/env dothttp

# imported from 35240-0b8cbe34-0af1-44a6-992a-ffe13940e455.postman_collection.json

@name("Add Application Output")
POST "https://{{aws_kinesis_data_analytics_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_kinesis_data_analytics_service}}", region="{{aws_kinesis_data_analytics_region}}")
? "Action"= "AddApplicationOutput"
data('{"ApplicationName":"string","CurrentApplicationVersionId":42,"Output":{"DestinationSchema":{"RecordFormatType":"string"},"KinesisFirehoseOutput":{"ResourceARN":"string","RoleARN":"string"},"KinesisStreamsOutput":{"ResourceARN":"string","RoleARN":"string"},"LambdaOutput":{"ResourceARN":"string","RoleARN":"string"},"Name":"string"}}')


@name("Delete Application Output")
POST "https://{{aws_kinesis_data_analytics_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_kinesis_data_analytics_service}}", region="{{aws_kinesis_data_analytics_region}}")
? "Action"= "DeleteApplicationOutput"
data('{"ApplicationName":"string","CurrentApplicationVersionId":42,"OutputId":"string"}')



