#!/usr/bin/env dothttp

# imported from 35240-46004eee-d776-4226-9cc0-a4f178c7a0e1.postman_collection.json

@name("List Event Subscriptions")
POST "https://{{aws_inspector_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_inspector_service}}", region="{{aws_inspector_region}}")
"Content-Type": "application/x-amz-json-1.1"
"User-Agent": "Postman-Collection"
"X-Amz-Target": "InspectorService.ListEventSubscriptions"
? "Action"= "ListEventSubscriptions"
data('{"maxResults":42,"nextToken":"string","resourceArn":"string"}')



