#!/usr/bin/env dothttp

# imported from 35240-30e1be77-9844-4b74-bf90-bfab68be417c.postman_collection.json

@name("By Base Path Base Path Mapping")
GET "https://{{aws_api_gateway_base_url}}/domainnames/a.b.c.com/basepathmappings/TestApi&base_path="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")
? "base_path"= ""


@name("By Path Base Path Mapping")
GET "https://{{aws_api_gateway_base_url}}/domainnames/a.b.c.com/basepathmappings/TestApi&base_path="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")
? "base_path"= ""


@name("Create Base Path Mapping")
POST "https://{{aws_api_gateway_base_url}}/domainnames/a.b.c.com/basepathmappings"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")


@name("Basepathmappingdelete")
DELET "https://{{aws_api_gateway_base_url}}/domainnames/a.b.c.com/basepathmappings/TestApi"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")


@name("Basepathmappingupdate")
PATCH "https://{{aws_api_gateway_base_url}}/domainnames/a.b.c.com/basepathmappings/TestApi"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")



