#!/usr/bin/env dothttp

# imported from 35240-4ff70fc9-8539-43e5-b513-382f49f2c6a5.postman_collection.json

// This operation retrieves a TestEnvironmentProvisioningExecution entity. Attribute selection is enabled for all first level attributes.

@name("Retrieves a TestEnvironmentProvisioningExecution by ID")
GET "https://{{baseUrl}}/testEnvironmentProvisioningExecution/:id"
? "fields"= "ex aute dolore dolore"


// This operation deletes a TestEnvironmentProvisioningExecution entity.

@name("Deletes a TestEnvironmentProvisioningExecution")
DELETE "https://{{baseUrl}}/testEnvironmentProvisioningExecution/:id"



