#!/usr/bin/env dothttp

# imported from 35240-52d5e6de-1810-40a8-bdcd-b528e6645a8d.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// Returns scan details.<p>Requires BASIC [16] user permissions and CAN VIEW [16] scan permissions. See [Permissions](doc:permissions).</p>

@name("Get scan details") : "base-inherit-auth"
GET "https://{{baseUrl}}/was/v2/scans/:scan_id"


// Update the `requested_action` attribute for a scan. The requested action must be valid for the scan's current status. For example, you can stop a scan if it has a status of `running`. Otherwise, Tenable.io Web Application Scanning returns a 409 reponse code. This request creates an asynchronous update job.<p>Requires SCAN OPERATOR [24] user permissions and CAN CONTROL [32] scan permissions. See [Permissions](doc:permissions).</p>

@name("Update scan status") : "base-inherit-auth"
PATCH "https://{{baseUrl}}/was/v2/scans/:scan_id"
"Content-Type": "application/json"
json({
    "requested_action": "stop"
})


// Removes the specified scan and all vulnerabilities it detected. This request creates an asynchronous deletion job.<p>Requires SCAN MANAGER [40] user permissions and CAN CONFIGURE [64] scan permissions. See [Permissions](doc:permissions).</p>

@name("Delete scan") : "base-inherit-auth"
DELETE "https://{{baseUrl}}/was/v2/scans/:scan_id"


// Returns a list of notes for the specified scan. <p>Requires BASIC [16] user permissions and CAN VIEW [16] scan permissions. See [Permissions](doc:permissions).</p>

@name("Get scan notes") : "base-inherit-auth"
GET "https://{{baseUrl}}/was/v2/scans/:scan_id/notes"
? "limit"= "-54086346"
? "offset"= "-54086346"
? "sort"= "last_seen:desc,ipv4:asc"



