#!/usr/bin/env dothttp

# imported from 35240-c06f082c-7c18-4317-b196-8ad07101a2f4.postman_collection.json

@name("Returns a list of annotations by RGD ID")
GET "https://{{baseUrl}}/annotations/rgdId/:rgdId"


@name("Returns a list of annotations by RGD ID and ontology prefix")
GET "https://{{baseUrl}}/annotations/rgdId/:rgdId/:ontologyPrefix"



