#!/usr/bin/env dothttp

# imported from 35240-c49a34ba-ca49-4e12-bd50-71617960cf26.postman_collection.json

// This operation list or find ImportJob entities

@name("List or find ImportJob objects")
GET "https://{{baseUrl}}/importJob"
? "fields"= "id Ut Excepteur"
? "offset"= "256391"
? "limit"= "256391"


// This operation creates a ImportJob entity.

@name("Creates a ImportJob")
POST "https://{{baseUrl}}/importJob"
"Content-Type": "application/json;charset=utf-8"
json({
    "url": "https://CvbRpPsCHThVbmuPMakogJVoluLR.qpkvwDuR6nUCXT1Eb,sXA,IUEcdfPGM05N0YsyxhnoQp",
    "completionDate": "1992-03-07T08:06:14.076Z",
    "contentType": "in officia sed labore commodo",
    "creationDate": "1957-10-24T02:25:10.148Z",
    "errorLog": "velit nostrud",
    "path": "aliquip occaecat officia e",
    "status": "Failed",
    "@baseType": "laborum irure",
    "@schemaLocation": "https://yEGTeYZxjKaNSryByXbtoOwSSgm.vokcKhg7BJJJ+dhFypjft0RyXpCnjotEaRCsxFFJSTr4GoDGo",
    "@type": "Excepteur consectetur elit ad"
})



