#!/usr/bin/env dothttp

# imported from 35240-a9cd9bcc-93b2-4c15-8ff4-f9bd9b31f543.postman_collection.json

// Authentication - access token.

@name("Authentication - Access Token")
POST "https://{{baseUrl}}/v2/token"
"Content": "<>"



