#!/usr/bin/env dothttp

# imported from 35240-c446a4c9-8dd6-45c4-99f2-688a96fe76ae.postman_collection.json

@name("Get a repository subscription")
GET "https://{{baseUrl}}/repos/:owner/:repo/subscription"


// If you would like to watch a repository, set `subscribed` to `true`. If you would like to ignore notifications made within a repository, set `ignored` to `true`. If you would like to stop watching a repository, [delete the repository's subscription](https://developer.github.com/v3/activity/watching/#delete-a-repository-subscription) completely.

@name("Set a repository subscription")
PUT "https://{{baseUrl}}/repos/:owner/:repo/subscription"
"Content-Type": "application/json"
json({
    "subscribed": "<boolean>",
    "ignored": "<boolean>"
})


// This endpoint should only be used to stop watching a repository. To control whether or not you wish to receive notifications from a repository, [set the repository's subscription manually](https://developer.github.com/v3/activity/watching/#set-a-repository-subscription).

@name("Delete a repository subscription")
DELETE "https://{{baseUrl}}/repos/:owner/:repo/subscription"



