#!/usr/bin/env dothttp

# imported from 35240-baa21855-56c4-411b-b54e-86741f2e4115.postman_collection.json

// Post shoppers.

@name("Post Shoppers")
POST "https://{{baseUrl}}/v1/shoppers"


// Get shoppers token.

@name("Get Shoppers Token")
GET "https://{{baseUrl}}/v1/shoppers/token"



