#!/usr/bin/env dothttp

# imported from 35240-9e00a78d-2317-4bed-9060-4dce0609c34f.postman_collection.json

@name("Describe Identity Pool Usage")
GET "https://{{aws_cognito_sync_base_url}}/identitypools/:IdentityPoolId"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_cognito_sync_service}}", region="{{aws_cognito_sync_region}}")


@name("List Identity Pool Usage")
GET "https://{{aws_cognito_sync_base_url}}/:identitypools"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_cognito_sync_service}}", region="{{aws_cognito_sync_region}}")
? "maxResults"= "MaxResults"
? "nextToken"= "NextToken"



