#!/usr/bin/env dothttp

# imported from 35240-2dd3b81c-4b11-4e46-b2e6-83bc9a4638dc.postman_collection.json

// Return a list of all license types supported by the service

@name("License Types list")
GET "https://{{baseUrl}}/utility/licenseTypes"


// Return a list of all licensing models supported by the service

@name("Licensing Models list")
GET "https://{{baseUrl}}/utility/licensingModels"



