#!/usr/bin/env dothttp

# imported from 35240-6dd4b6b5-e2d1-4630-9235-6d7bb1d13702.postman_collection.json

// Get All

@name("Get All")
GET "https://{{baseUrl}}/sdars/getall.{{format}}"


// SDARS Entity Details

@name("SDARS Entity Details")
GET "https://{{baseUrl}}/sdars/frn/{{frn}}.{{format}}"


// Update licensee address

@name("Update licensee address")
POST "https://{{baseUrl}}/sdars/licenseeAddress/update.json"
"Content-Type": "application/json"
json({
    "licensee": "<string>",
    "addressLine1": "<string>",
    "addressLine2": "<string>",
    "city": "<string>",
    "state": "<string>",
    "zipCode": "<string>",
    "zipExt": "<string>",
    "phone": "<string>",
    "email": "<string>",
    "website": "<string>",
    "facilityId": "<string>",
    "accessToken": "<string>"
})


// SDARS EEO

@name("SDARS EEO")
GET "https://{{baseUrl}}/sdars/eeo/facility/{{facilityID}}.{{format}}"



