#!/usr/bin/env dothttp

# imported from 35240-af938bfe-d636-455e-9182-83ae080c0f19.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"
"Authorization": "Bearer <Bearer Token>"


// Retrieves information for a policy condition criteria specified by its ID for a condition specified by its ID associated with a policy specified by its ID.

@name("Get details for a specified policy condition criteria") : "base-inherit-auth"
GET "https://{{baseUrl}}/v1/policies/:id/policycondition/:conditionid/criteria/:criteriaid"
"Authorization": "Bearer <Bearer Token>"
? "datasource"= "Excepteur nisi in"


// Updates policy condition criteria

@name("Updates policy condition criteria") : "base-inherit-auth"
PUT "https://{{baseUrl}}/v1/policies/:id/policycondition/:conditionid/criteria/:criteriaid"
"Authorization": "Bearer <Bearer Token>"
"Content-Type": "application/json"
? "datasource"= "Excepteur nisi in"
json({
    "id": -99939842,
    "logic": "aliquip id deserunt exercitation fugiat",
    "openPar": "aute ex sunt",
    "field": "dolor ad Duis do amet",
    "operator": "Lorem minim dolore culpa",
    "value": "nostrud aute",
    "closePar": "anim eiusmod par"
})


// Deletes a policy condition criteria

@name("Deletes a policy condition criteria") : "base-inherit-auth"
DELETE "https://{{baseUrl}}/v1/policies/:id/policycondition/:conditionid/criteria/:criteriaid"
"Authorization": "Bearer <Bearer Token>"
? "datasource"= "Excepteur nisi in"



