#!/usr/bin/env dothttp

# imported from 35240-9c094246-719d-4054-bede-5834f64bb4b7.postman_collection.json

@name("Create Interconnect")
POST "https://{{aws_direct_connect_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_direct_connect_service}}", region="{{aws_direct_connect_region}}")
? "Action"= "CreateInterconnect"
data('{
   "bandwidth": "string",
   "interconnectName": "string",
   "lagId": "string",
   "location": "string",
   "providerName": "string",
   "tags": [ 
      { 
         "key": "string",
         "value": "string"
      }
   ]
}')


@name("Delete Interconnect")
POST "https://{{aws_direct_connect_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_direct_connect_service}}", region="{{aws_direct_connect_region}}")
? "Action"= "DeleteInterconnect"
data('{
   "interconnectId": "string"
}')


@name("Describe Interconnects")
POST "https://{{aws_direct_connect_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_direct_connect_service}}", region="{{aws_direct_connect_region}}")
? "Action"= "DescribeInterconnects"
data('{
   "interconnectId": "string"
}')



