#!/usr/bin/env dothttp

# imported from 35240-4d3f2edc-e0e7-4b26-a712-076a7e2780a4.postman_collection.json

// ### Retrieve a GroupnnGet a single group with its information by specifying its ```group_id```.n

@name("Get Groups Group")
GET "https://{{baseUrl}}/groups/:group_id"



