#!/usr/bin/env dothttp

# imported from 35240-baa21855-56c4-411b-b54e-86741f2e4115.postman_collection.json

// Get shoppers me.

@name("Get Shoppers Me")
GET "https://{{baseUrl}}/v1/shoppers/me"


// Get shoppers me account.

@name("Get Shoppers Me Account")
GET "https://{{baseUrl}}/v1/shoppers/me/account"


// Get shoppers me product search.

@name("Get Shoppers Me Product Search")
GET "https://{{baseUrl}}/v1/shoppers/me/product-search"



