#!/usr/bin/env dothttp

# imported from 35240-078f0c0e-f03d-4124-bda1-c7d8042a0e64.postman_collection.json

// Loads a think!ehr form..

@name("Loads a Think!Ehr form.")
GET "https://{{baseUrl}}/form/:name/:version"
? "resources"= "<get>"


// Loads a think!ehr form resource content..

@name("Loads a Think!Ehr form resource content.")
GET "https://{{baseUrl}}/form/:name/:version/resource/:resource"
? "envelope"= "<>"



