#!/usr/bin/env dothttp

# imported from 35240-5c55623d-8457-49a6-aa88-825447c3d4ee.postman_collection.json

// Returns the default encryption configuration for an Amazon S3 bucket. For information about the Amazon S3 default encryption feature, see Amazon S3 Default Bucket Encryption. 

@name("Bucket Encryption")
GET "https://s3.amazonaws.com/{{bucket}}/"
awsauth(access_id="AKIAIVHZOWYJ3P3IBXNA", secret_key="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", service="s3", region="us-east-1")
"x-amz-content-sha256": "UNSIGNED-PAYLOAD"
? "encryption"= ""


// This implementation of the PUT operation uses the encryption subresource to set the default encryption state of an existing bucket. 

@name("Bucket Encryption")
PUT "https://s3.amazonaws.com/{{bucket}}/"
awsauth(access_id="AKIAIVHZOWYJ3P3IBXNA", secret_key="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", service="s3", region="us-east-1")
? "encryption"= ""
data('<?xml version="1.0" encoding="UTF-8"?>
<ServerSideEncryptionConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
   <Rule><ApplyServerSideEncryptionByDefault><SSEAlgorithm>AES256</SSEAlgorithm></ApplyServerSideEncryptionByDefault></Rule>
</ServerSideEncryptionConfiguration>')


// This implementation of the DELETE operation removes default encryption from the bucket.

@name("Delete Bucket Encryption")
DELETE "https://s3.amazonaws.com/{{bucket}}/"
awsauth(access_id="AKIAIVHZOWYJ3P3IBXNA", secret_key="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", service="s3", region="us-east-1")
? "encryption"= ""




