#!/usr/bin/env dothttp

# imported from 35240-17a6f18b-38c5-42cb-a11e-28f755ffce28.postman_collection.json

// Get a list of all CRMs

@name("Get all CRMs")
GET "https://{{baseUrl}}/3dCartWebAPI/v1/CRM/savedreply"
? "title"= "<string>"
? "limit"= "<integer>"
? "offset"= "<integer>"
? "countonly"= "<integer>"


// Get a specific CRM Saved Reply

@name("Get a specific CRM Saved Reply")
GET "https://{{baseUrl}}/3dCartWebAPI/v1/CRM/savedreply/:id"



