#!/usr/bin/env dothttp

# imported from 35240-5da4bd40-1308-4c08-9688-8cbdcd14f62d.postman_collection.json

@name("Ttpoverlap")
GET "https://{{baseUrl}}/api/ttpoverlap/"
? "token"= "anim commodo Ut ad"


@name("Deprecatedttpoverlap")
GET "https://{{baseUrl}}/api/ttpoverlap/:ttp"
? "token"= "anim commodo Ut ad"



