#!/usr/bin/env dothttp

# imported from 35240-81e3517b-5c56-4500-b086-0e52eb5d86ca.postman_collection.json

// Channels.

@name("channels")
GET "https://{{baseUrl}}/rest/v1/channels"


// Assuming that the given code is the code of an existing channel

@name("channel")
GET "https://{{baseUrl}}/rest/v1/channels/ecommerce"


// Channel (2.x only).

@name("channel (2.x only)")
PATCH "https://{{baseUrl}}/rest/v1/channels/my_new_channel_3"
"Content": "<>"



