#!/usr/bin/env dothttp

# imported from 35240-c446a4c9-8dd6-45c4-99f2-688a96fe76ae.postman_collection.json

// List the users you've blocked on your personal account.

@name("List users blocked by the authenticated user")
GET "https://{{baseUrl}}/user/blocks"



