#!/usr/bin/env dothttp

# imported from 35240-f27f798d-07bf-410e-bc36-81f925cac47d.postman_collection.json

// Creates a NAT gateway in the specified public subnet.

@name("Create Nat Gateway")
GET "https://{{aws_ec2_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "AllocationId"= ""
? "ClientToken"= ""
? "SubnetId"= ""
? "Action"= "CreateNatGateway"


// Deletes the specified NAT gateway.

@name("Delete Nat Gateway")
GET "https://{{aws_ec2_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "NatGatewayId"= ""
? "Action"= "DeleteNatGateway"


// Describes one or more of your NAT gateways.

@name("Describe Nat Gateways")
GET "https://{{aws_ec2_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "Filter.N"= ""
? "MaxResults"= ""
? "NatGatewayId.N"= ""
? "NextToken"= ""
? "Action"= "DescribeNatGateways"



