#!/usr/bin/env dothttp

# imported from 35240-5c55623d-8457-49a6-aa88-825447c3d4ee.postman_collection.json

// Returns the logging status of a bucket and the permissions users have to view and modify that status. To use GET, you must be the bucket owner. 

@name("Bucket Logging")
GET "https://s3.amazonaws.com/{{bucket}}/"
awsauth(access_id="AKIAIVHZOWYJ3P3IBXNA", secret_key="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", service="s3", region="us-east-1")
"x-amz-content-sha256": "UNSIGNED-PAYLOAD"
? "logging"= ""


// Set the logging parameters for a bucket and to specify permissions for who can view and modify the logging parameters. All logs are saved to buckets in the same AWS Region as the source bucket. To set the logging status of a bucket, you must be the bucket owner. 

@name("Bucket Logging")
PUT "https://s3.amazonaws.com/{{bucket}}/"
awsauth(access_id="AKIAIVHZOWYJ3P3IBXNA", secret_key="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", service="s3", region="us-east-1")
"Content-MD5": "{{contentMD5}}"
? "logging"= ""
data('<?xml version="1.0" encoding="UTF-8"?>
<BucketLoggingStatus xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
   <LoggingEnabled>
      <TargetBucket>working-demo-2</TargetBucket>
   </LoggingEnabled>
</BucketLoggingStatus>')



