#!/usr/bin/env dothttp

# imported from 35240-7d2c214b-77c4-4e90-8dc4-3cd4493a1c9a.postman_collection.json

// User Search

@name("User Search")
GET "https://{{baseUrl}}/users/search"
? "slug"= "<>"



