#!/usr/bin/env dothttp

# imported from 35240-7871656e-e03d-47bc-b756-528d4b913bbd.postman_collection.json

// This operation list or find TopupBalance entities

@name("List or find TopupBalance objects")
GET "https://{{baseUrl}}/topupBalance"
? "fields"= "id voluptate"
? "offset"= "6696224"
? "limit"= "6696224"


// This operation creates a TopupBalance entity.

@name("Creates a TopupBalance")
POST "https://{{baseUrl}}/topupBalance"
"Content-Type": "application/json;charset=utf-8"
json({
    "amount": {
        "amount": 1,
        "units": "tempor officia Excepteur et"
    },
    "confirmationDate": "1978-10-02T10:57:47.019Z",
    "description": "labore et occaecat quis exercitation",
    "isAutoTopup": true,
    "numberOfPeriods": 5943166,
    "reason": "laborum dolore in incididunt cillum",
    "recurringPeriod": "aliquip eiusmod ipsum",
    "requestedDate": "1972-12-26T15:17:20.274Z",
    "status": "Excepteur ea deserunt",
    "usageType": "anim velit",
    "voucher": "magna amet",
    "bucket": {
        "id": "minim",
        "href": "http://RWXoSotHyHNrJeRwskgoRKzinfd.ffopBfjZfVrWDuuoQsNCEUL-fQtKVTzh2eUQUb2Wdof5JaEayvPP0bcfUy",
        "name": "adipisicing ullamco",
        "usageType": "Ut nulla sint occaecat",
        "@baseType": "cillum Excepteur",
        "@schemaLocation": "http://rZ.bekpuD3WH1.6QdRsJZRYj,GnBvPY6PE3j-c2OBoKyihtkWKoGP,",
        "@type": "ipsum reprehenderit adipis",
        "@referredType": "labore Excep"
    },
    "channel": {
        "id": "dolor veniam",
        "href": "http://usJWWhXU.zifgKWMJuzsSoOJqdphEVucda9-mxFp.o4AtU5MVSe+HOaB-",
        "name": "sint in",
        "@baseType": "id laboris nostrud dolore",
        "@schemaLocation": "https://MEWsTfImUGEgKzpjKpZZDOPv.epJvWQyLXbJGRJ.0boctM4tKlmVKHBINVaLgC53A8BUJTqGDOHzEZ05VGXsDIsZLUQ51skwj6FCJc6HHC",
        "@type": "ex nostrud amet",
        "@referredType": "do sunt amet"
    },
    "impactedBucket": [
        {
            "item": [
                {
                    "description": "incididunt laborum eiusmod pariatur",
                    "itemType": "est Lorem occaecat ad",
                    "name": "eiusmod Ut",
                    "reason": "consequat nisi commodo",
                    "amount": {
                        "amount": 1,
                        "units": "consectetur do incididunt"
                    },
                    "@baseType": "nostrud pariatur ea dolore",
                    "@schemaLocation": "http://ztJJJbmBudgnDGIabSHXmrIXDWiwX.mlvbY2gfnuZvwoi0hIZoujZc,Cisa-nvCOszORbEV0uWhuP",
                    "@type": "laboris labore id amet"
                }
            ],
            "confirmationDate": "1982-12-20T15:45:54.904Z",
            "description": "dolore ea ex qui consectetur",
            "name": "consectetur non",
            "requestedDate": "1994-08-01T14:06:32.222Z",
            "amountAfter": {
                "amount": 1,
                "units": "sint"
            },
            "amountBefore": {
                "amount": 1,
                "units": "elit occaecat nulla esse"
            },
            "bucket": {
                "id": "adipisicing consequat mollit in nostrud",
                "href": "http://dlpWwGQMkbOFnRwHcJNEliV.eaaaG79uSTMsNeQ4h6N.BrmSy4Px0dBY",
                "name": "sed reprehenderit commodo",
                "usageType": "dolor laborum incididunt",
                "@baseType": "culpa fugiat consequat",
                "@schemaLocation": "http://fmpXOYp.voutWY25T,gSae,Da3G",
                "@type": "ut ad deserunt nulla consectetur",
                "@referredType": "do culpa"
            },
            "@baseType": "enim ess",
            "@schemaLocation": "http://zGrPZVQkRPOvgT.kvsTshQLpmI6EDEs0OdKaARsMSTvxNHcOk98imGwxPyuyGi19zd.EvDzX65yJd4vD",
            "@type": "deserunt enim eu in"
        },
        {
            "item": [
                {
                    "description": "dolore eu enim tempor",
                    "itemType": "dolore",
                    "name": "culpa ullamco consequat eiusmod irure",
                    "reason": "magna incididunt ad",
                    "amount": {
                        "amount": 1,
                        "units": "consectetur"
                    },
                    "@baseType": "aliqua anim",
                    "@schemaLocation": "https://nRJ.yirdijRLngPon1Aq8ARiIWkIbSPEPYac0qS-",
                    "@type": "cupidatat commodo"
                }
            ],
            "confirmationDate": "1945-07-09T11:18:24.021Z",
            "description": "dolor incididunt exercitation",
            "name": "sint",
            "requestedDate": "1971-04-11T03:09:35.125Z",
            "amountAfter": {
                "amount": 1,
                "units": "do qui"
            },
            "amountBefore": {
                "amount": 1,
                "units": "incididunt Lorem Ut id aliqua"
            },
            "bucket": {
                "id": "in re",
                "href": "https://bDWFxnEIiJfGIWCBAih.wbpsBvuLeA",
                "name": "cupidatat anim",
                "usageType": "veniam nisi proident incididunt",
                "@baseType": "labore ex",
                "@schemaLocation": "https://JUEijSGZaZCnzlSGZvPIurxXIiSGuetap.mztXNuTqyL,xlFEyvgaeisB+MZ8LvNyPAFXcjfptBCOQoghfzPCdD.Sx2245-",
                "@type": "irure in Ut",
                "@referredType": "ullamco nulla"
            },
            "@baseType": "anim est",
            "@schemaLocation": "http://yTpWIiVLfCFrdGIFOGf.jbXGg-vLc",
            "@type": "nulla eiusmod"
        }
    ],
    "logicalResource": {
        "id": "non est sed laborum",
        "href": "http://hbNXNWLU.viAxH,FD0u4WmplvOxHG5enHH.iTYhVmdNM",
        "name": "dolore non aliqua in",
        "value": "commodo est cillum sint",
        "@baseType": "irure officia amet",
        "@schemaLocation": "https://alGPudJWInokdJFC.lvXY1BgZCQiabHWNXM8fbGfoyjg18W+ekF",
        "@type": "fugiat consectetur",
        "@referredType": "qui officia"
    },
    "partyAccount": {
        "id": "e",
        "href": "aliqua nulla minim",
        "description": "ex dolore nisi consectetur",
        "name": "proident laborum id",
        "status": "Excepteur consequat",
        "@baseType": "veniam eu",
        "@schemaLocation": "http://kBYZblGSFsKZHlLiAJYvHLKaS.pvvSOiY3ejkS4jyoXwMxnm",
        "@type": "dolore dolore",
        "@referredType": "in"
    },
    "payment": {
        "id": "id",
        "href": "http://COMlAJXWAYC.qbkiCakpRFF",
        "name": "et dolor ipsum occaecat veniam",
        "@baseType": "incididunt proident aute nisi",
        "@schemaLocation": "https://QEjtLCfLhMheAyIq.cpttnCNZN0.f+dxLo1TpcLzB1X-VrpUFHHqq3mTG7",
        "@type": "veniam dolor voluptate Lorem Duis",
        "@referredType": "minim elit"
    },
    "paymentMethod": {
        "id": "magna reprehenderit enim non",
        "href": "https://xCjTzRPYuQizbZxAHSz.apohxGnCIyCirHRCo01gbrvb+YITB9AcxaR08jp04YXxqtUcF",
        "name": "cillum sed fugiat eiusmod Excepteur",
        "@baseType": "aute",
        "@schemaLocation": "http://MLekRH.haysGo5J4OCCqx,QWijRDqhAxWyZZcZxHnZNegpxn,UW+wNdox",
        "@type": "culpa",
        "@referredType": "laborum "
    },
    "product": {
        "id": "irure",
        "href": "https://qqHnMMPitXohGBdxNaSuyK.arqvqYSvyDU5LHBV",
        "name": "Duis",
        "@baseType": "anim Duis cupidatat deserunt",
        "@schemaLocation": "https://bWCubxHPRteJeoTuwZvjzLcTNWpXWfuF.gsYoalfGwvPLjxTXetmi,eaReaAjZX2SPMnNO1f7eHNBx82Z,K,K.s9YKPv2sY",
        "@type": "in do",
        "@referredType": "in eiusmod pariatur ex"
    },
    "relatedParty": [
        {
            "@referredType": "consequat commodo ut in",
            "id": "ex cupidatat Excepteur incididunt",
            "href": "http://ZSZvypvMPrfQvasPVyUSKatEOCWbsIcx.rtocEnjAbp073PQo8bqq2D",
            "name": "quis cupidatat eu",
            "role": "irure nos",
            "@baseType": "cillum dolor",
            "@schemaLocation": "http://CuwlkjLgjNumNUSFdFvqCG.seCrtLPwW4kYm7y41UIv71ZLeDQdEuORJM-FfzXCtE28lVyQtxs,t,K",
            "@type": "tempor ullamco ipsum"
        },
        {
            "@referredType": "tempor consequat culpa fugiat est",
            "id": "officia",
            "href": "https://UMwhdXRJmhzeqxALfm.jlvW14VghV+Jzcp2ADaNPSXR0QCEbe5m-egvsTE44N2gFr-hzf9lKDwNlVNiuT01y-aEBi",
            "name": "reprehenderit mollit",
            "role": "est laborum id Ut Lorem",
            "@baseType": "id Excepteur ea culpa",
            "@schemaLocation": "https://rCTXoSpVvpWcvoSUrmBkSybUNHYijm.slN.1akOiI7sKpLq58",
            "@type": "Ut Excepteur ad minim"
        }
    ],
    "relatedTopupBalance": {
        "id": "dolor adi",
        "href": "https://xOklhxjZuQoRXhNO.hvkqMGyhJzao.S3j+QeaPzgpP4MWhkqa12M+3C5vhRWN,Lz0pTyfLiGN6wYQLGIAZnvEfqVGfOKJSiHCHrp6",
        "name": "elit adipisicing",
        "role": "et",
        "@baseType": "ea",
        "@schemaLocation": "http://nkwkrhvCRnrfQzejkXxAuLH.wvBRIOQcXR",
        "@type": "qui ad",
        "@referredType": "ea"
    },
    "requestor": {
        "@referredType": "in et nostrud",
        "id": "ullamco nostrud exercitation",
        "href": "http://kdcjvpETQZK.aslZKmh,+1jOzN.NIWGRtRcfc",
        "name": "Lorem nulla incididunt nisi consectetur",
        "role": "aliqua in",
        "@baseType": "reprehenderit",
        "@schemaLocation": "https://UdMXDJieQOGSRQoVahwfYPGCGKcw.kqrKgQ.Z9ZL0GF6gg,",
        "@type": "ad anim"
    },
    "@baseType": "velit culpa",
    "@schemaLocation": "https://hxXMlYEBRBUyPvKSzDWackFYgWMDEyWU.scxxI+ePaE2V",
    "@type": "laboris commodo aliqua"
})



