#!/usr/bin/env dothttp

# imported from 35240-3de643e0-77af-41e6-9270-0b386f4ca61d.postman_collection.json

// Used to manage text notes.

@name("DELETE Note Text for User Monetary Account Mastercard Action")
DELETE "https://{{baseUrl}}/user/:userID/monetary-account/:monetary-accountID/mastercard-action/:mastercard-actionID/note-text/:itemId"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"


// Used to manage text notes.

@name("READ Note Text for User Monetary Account Mastercard Action")
GET "https://{{baseUrl}}/user/:userID/monetary-account/:monetary-accountID/mastercard-action/:mastercard-actionID/note-text/:itemId"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"


// Used to manage text notes.

@name("UPDATE Note Text for User Monetary Account Mastercard Action")
PUT "https://{{baseUrl}}/user/:userID/monetary-account/:monetary-accountID/mastercard-action/:mastercard-actionID/note-text/:itemId"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"
"Content-Type": "application/json"
json({
    "content": "<string>"
})



