#!/usr/bin/env dothttp

# imported from 35240-9c094246-719d-4054-bede-5834f64bb4b7.postman_collection.json

@name("Allocate Hosted Connection")
POST "https://{{aws_direct_connect_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_direct_connect_service}}", region="{{aws_direct_connect_region}}")
? "Action"= "AllocateHostedConnection"
data('{
   "bandwidth": "string",
   "connectionId": "string",
   "connectionName": "string",
   "ownerAccount": "string",
   "tags": [ 
      { 
         "key": "string",
         "value": "string"
      }
   ],
   "vlan": number
}')


@name("Associate Hosted Connection")
POST "https://{{aws_direct_connect_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_direct_connect_service}}", region="{{aws_direct_connect_region}}")
? "Action"= "AssociateHostedConnection"
data('{
   "connectionId": "string",
   "parentConnectionId": "string"
}')


@name("Describe Hosted Connections")
POST "https://{{aws_direct_connect_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_direct_connect_service}}", region="{{aws_direct_connect_region}}")
? "Action"= "DescribeHostedConnections"
data('{
   "connectionId": "string"
}')



