#!/usr/bin/env dothttp

# imported from 35240-b4ad2590-7a09-4b2a-9ac8-f9039ba10098.postman_collection.json

// This operation list or find ProductOrderRiskAssessment entities

@name("List or find ProductOrderRiskAssessment objects")
GET "https://{{baseUrl}}/productOrderRiskAssessment"
? "fields"= "quis elit commodo tempor"
? "offset"= "-80657290"
? "limit"= "-80657290"


// This operation creates a ProductOrderRiskAssessment entity.

@name("Creates a ProductOrderRiskAssessment")
POST "https://{{baseUrl}}/productOrderRiskAssessment"
"Content-Type": "application/json;charset=utf-8"
json({
    "productOrder": {
        "id": "deserunt Excepteur commodo",
        "href": "https://HVBXfipKpXaQMuQDfOcuTWIvV.vrjJW,WjuSL-qencF8onqawy8TWE8g.XHnoz+",
        "name": "in cillum Duis",
        "@baseType": "aliqua non ipsum magna",
        "@schemaLocation": "https://JaOnuOlvXvxQpHDPABj.lsapdl,hkQhVaunEwSUXAiLtTbuJvfG35",
        "@type": "aliquip magna ex Ut",
        "@referredType": "magna Lorem labore qui irure"
    },
    "status": "fugiat proident nulla",
    "characteristic": [
        {
            "name": "ut fugiat qui ipsum",
            "value": {},
            "id": "reprehenderit voluptate qui",
            "valueType": "anim nostrud",
            "characteristicRelationship": [
                {
                    "id": "laboris dolore",
                    "href": "https://eNxkKCredOZxRqoNKBFNPGHMFNqzrfGG.pgvbU+V4m1ZhPsD2nJ3jGTZA,We,BdSoz+QUFck4mqqviYTbxwZIiC",
                    "relationshipType": "eu dolor",
                    "@baseType": "et commodo deserunt tempor in",
                    "@schemaLocation": "http://r.cvcQELg1YL3oQ+zwVFVxyYIV7W9K6ssPjXSsUTRl-qSgTbgY,t9A",
                    "@type": "non"
                },
                {
                    "id": "Excepteur reprehenderit aute ut",
                    "href": "http://HlCyJg.baam2jK.2vWFUnVa9D061WZjQAMUICR6vnLb-Lb2x.Pms+afc6uchRgF4b0YJvF6K8hfatK",
                    "relationshipType": "fugiat",
                    "@baseType": "nisi c",
                    "@schemaLocation": "http://BHZAdKKmDwTlRhNsTQfdDMHvQAuHp.seaetDH9oODZyF",
                    "@type": "incididunt"
                }
            ],
            "@baseType": "dolor",
            "@schemaLocation": "https://WcOepfEWgrP.eiaOEcHf+qac",
            "@type": "ipsum"
        },
        {
            "name": "ut consectetur pariatur sed",
            "value": {},
            "id": "id mollit in",
            "valueType": "exercitation commodo",
            "characteristicRelationship": [
                {
                    "id": "nisi",
                    "href": "http://HnrToZzykwtBGFehLkc.fftkVvfwbG.0J21WrPuNskIVPKNKVvN5U0",
                    "relationshipType": "ea ut exercitation sit",
                    "@baseType": "reprehenderit exercitation in tempor",
                    "@schemaLocation": "https://PMuJOSQ.hhVh5THUrMDv1Bqqpld,HaAXVQ+ZCHiP",
                    "@type": "aliquip ea eiusmod labore ut"
                },
                {
                    "id": "reprehenderit velit consectetur",
                    "href": "http://oTsWNHkgfDdYVrmSrhBhoHYemMHwpEMHx.hllrCecEUnqth,xnUKHRA87JoO6,IgWwTAGy.Y8a76RV.+1,pTyABu59tX-Ni",
                    "relationshipType": "Ut nisi irure",
                    "@baseType": "dolor laboris",
                    "@schemaLocation": "http://GCbGDhqZlxRuPfLEv.jeNc-ybFqWEQXBh7dBjpEZG",
                    "@type": "mollit nostrud"
                }
            ],
            "@baseType": "ad occaecat",
            "@schemaLocation": "http://xoqemejpQPDAlYx.najeQVLm+opyFkv.cNK,m-YrxlbGX",
            "@type": "consectetur non in"
        }
    ],
    "place": {
        "id": "consectetur Lorem in",
        "href": "laborum est",
        "name": "sit in",
        "role": "sit dolore",
        "@baseType": "est esse ex",
        "@schemaLocation": "http://WxfarbxiOOaTGEjdewJLEDdN.tsJ6mnjDi25.k1osvCJsxYq+C5ITCVvdkwFHpCBuJJdNhPOUr78drwCZf0dDbB0",
        "@type": "aliqua",
        "@referredType": "anim et Ut minim"
    },
    "riskAssessmentResult": {
        "overallScore": -47092356.28233559,
        "score": [
            {
                "score": 92668772.2489861,
                "riskName": "BadPaymentRisk",
                "@baseType": "tempor",
                "@schemaLocation": "https://XhfIVZdfqySExEUI.ifp.PNYbeYS,Zp-.Cezxs0dVK3fBseaKagg",
                "@type": "mollit eu irure laborum"
            },
            {
                "score": 20749897.043333605,
                "riskName": "CreditGamingRisk",
                "@baseType": "cillum occaecat",
                "@schemaLocation": "https://GpyVCAPeDVDXyTDtcDAQbxfxIB.lbKM+kxjDR2jyG9jUXyh3crXF7jVyy3bAp2HG8g0e",
                "@type": "et Excepteur sed dolore"
            }
        ],
        "validFor": {
            "id": "occaeca",
            "href": "https://qiHGaGvRqEdzbGOdEoOQiLuPExQ.zdI0-jgjxwGswqdmOAQosblazdwvMNn9",
            "endDateTime": "1985-04-12T23:20:50.52Z",
            "startDateTime": "1985-04-12T23:20:50.52Z",
            "@baseType": "amet eiusmod reprehenderit",
            "@schemaLocation": "https://PeDBvoiohycliqyaerDRukMeuAL.avQdQp0-,cUM,,rzZdBhtrMAKCgXQf0O9vybbsxra",
            "@type": "ullamco aliqua"
        },
        "@baseType": "elit cillum eu Duis",
        "@schemaLocation": "https://eeiMTVhbVbl.smDdsOlnD609jSe8IRz.ucHeRvhfW63CrExlFUYc8pPV3R7gaFDQgw8pTz",
        "@type": "magna commodo"
    },
    "@baseType": "enim reprehenderit",
    "@schemaLocation": "https://nrcCgQDyTXGjcRkpAtWZjFx.nsgHnTe0TLiFWh8HMDDNbUX1yzmQVfhDTZt",
    "@type": "cillum Duis"
})



