#!/usr/bin/env dothttp

# imported from 35240-6135048e-d8f2-4063-a921-e9f54a73ef03.postman_collection.json

// **This endpoint allows you to generate a new batch ID. This batch ID can be associated with scheduled sends via the mail/send endpoint.**
// 
// If you set the SMTPAPI header `batch_id`, it allows you to then associate multiple scheduled mail/send requests together with the same ID. Then at anytime up to 10 minutes before the schedule date, you can cancel all of the mail/send requests that have this batch ID by calling the Cancel Scheduled Send endpoint. 
// 
// More Information:
// 
// * [Scheduling Parameters >

@name("Create a batch ID")
POST "https://{{baseUrl}}/mail/batch"


// This endpoint allows you to send email over SendGrid’s v3 Web API, the most recent version of our API. If you are looking for documentation about the v2 Mail Send endpoint, see our [v2 API Reference](https://sendgrid.com/docs/API_Reference/Web_API/mail.html).
// 
// **SendGrid provides libraries to help you quickly and easily integrate with the v3 Web API in 7 different languages: [C#](https://github.com/sendgrid/sendgrid-csharp), [Go](https://github.com/sendgrid/sendgrid-go), [Java](https://github.

@name("v3 Mail Send")
POST "https://{{baseUrl}}/mail/send"



