#!/usr/bin/env dothttp

# imported from 35240-17a6f18b-38c5-42cb-a11e-28f755ffce28.postman_collection.json

// Get a list of all Admin Users

@name("Get all Admin Users")
GET "https://{{baseUrl}}/3dCartWebAPI/v1/Admins"
? "limit"= "<integer>"
? "offset"= "<integer>"
? "name"= "<string>"
? "username"= "<string>"
? "external_id"= "<string>"
? "countonly"= "<integer>"



