#!/usr/bin/env dothttp

# imported from 35240-81fcc13e-3a8a-40bc-80e5-96d892760eaa.postman_collection.json

// Create a new video, optionally setting some metadata fields. You may optionally set some of the metadata associated with the video. Only fields inside the userdata field can be set.

@name("Create a new video, optionally setting some metadata fields.")
POST "https://{{baseUrl}}/video/create"


// Return details about a video. You may optionally request that only some of the metadata fields are returned.

@name("Return details about a video.")
POST "https://{{baseUrl}}/video/details"


// Find videos matching any criteria, by running a JavaScript function over each video object. A detailed tutorial on how to use this functionality is available on the [documentation page](https://www.synq.fm/queries-video-api/).

@name("Perform a JavaScript query to return video objects matching any desired criteria.")
POST "https://{{baseUrl}}/video/query"


// Returns a stream url that you can stream to from your broadcasting software, and a playback url people can use to watch the stream.

@name("Returns urls for streaming.")
POST "https://{{baseUrl}}/video/stream"


// Update a video's metadata through JavaScript code. Only fields inside the userdata object can be set.

@name("Update a video's metadata.")
POST "https://{{baseUrl}}/video/update"


// Return parameters needed for uploading a video file to Amazon Simple Storage Service. See http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html as well as the language-specific code-examples.n#### *Example request*n```shellncurl -s https://api.synq.fm/v1/video/upload 
//   -F api_key=${SYNQ_API_KEY} 
//   -F video_id=2d81c30ce62f4dfdb501dbca96c7ae56n```nn#### *Example response*n```jsonn{n  action: https://synqfm.s3.amazonaws.com/,n  AWSAccessKeyId: AKIAIP77Y7MMX3ITZMFA,n  C

@name("Return parameters needed for uploading a video file.")
POST "https://{{baseUrl}}/video/upload"


// Returns an embeddable url, that contains an uploader widget that allows you to easily upload any mp4. Great way to simplify the uploading process for end users.

@name("Return embeddable url to an uploader widget")
POST "https://{{baseUrl}}/video/uploader"



