#!/usr/bin/env dothttp

# imported from 35240-95c79ece-4a26-4cb3-b39a-08ef802111c4.postman_collection.json

// Returns a listing of all Users collections and sets.

@name("Get Collections")
GET "https://{{baseUrl}}/collections"
? "photos_per_collection_limit"= "<>"


// Deletes collection.

@name("Delete Collections")
DELETE "https://{{baseUrl}}/collections/:id"
? "Forkn      n      n        69"= "<>"
? "Starn  nn    n      281"= "<>"



