#!/usr/bin/env dothttp

# imported from 35240-9876bee9-39f3-4f65-888c-2127fc6d667c.postman_collection.json

@name("Gets all reviews of the specified restaurant.")
GET "https://{{baseUrl}}/api/v{{version}}/:restaurantUid/review/:startDate/:endDate/:skip/:take"


@name("Gets the review of the specified booking.")
GET "https://{{baseUrl}}/api/v{{version}}/:restaurantUid/review/booking/:bookingUid"


@name("Review Get Review For Takeaway")
GET "https://{{baseUrl}}/api/v{{version}}/:restaurantUid/review/takeaway/:takeawayUid"



