#!/usr/bin/env dothttp

# imported from 35240-5f0de24a-12d4-4bb7-a222-68e7bfdfd2e8.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// List all code inclusions

@name("List all code inclusions") : "base-inherit-auth"
GET "https://{{baseUrl}}/services/:env_id/settings/code-redaction/include"


// Add a bulk of code inclusions

@name("Add a bulk of code inclusions") : "base-inherit-auth"
POST "https://{{baseUrl}}/services/:env_id/settings/code-redaction/include"
"Content-Type": "application/json"
json({
    "classes": [
        "com.company.ClassName",
        "com.company.ClassName"
    ],
    "packages": [
        "com.company.package.name",
        "com.company.package.name"
    ]
})



