#!/usr/bin/env dothttp

# imported from 35240-396d9363-dad9-4f4b-8418-119dc20d1211.postman_collection.json

@name("Cancel Job Execution")
GET "https://{{aws_internet_of_things_base_url}}/things/thingName/jobs/jobId/cancel"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("Delete Job Execution")
GET "https://{{aws_internet_of_things_base_url}}/things/thingName/jobs/jobId/executionNumber/executionNumber"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("Describe Job Execution")
GET "https://{{aws_internet_of_things_base_url}}/things/thingName/jobs/jobId"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")



