#!/usr/bin/env dothttp

# imported from 35240-b4ad2590-7a09-4b2a-9ac8-f9039ba10098.postman_collection.json

// This operation list or find ShoppingCartRiskAssessment entities

@name("List or find ShoppingCartRiskAssessment objects")
GET "https://{{baseUrl}}/shoppingCartRiskAssessment"
? "fields"= "quis elit commodo tempor"
? "offset"= "-80657290"
? "limit"= "-80657290"


// This operation creates a ShoppingCartRiskAssessment entity.

@name("Creates a ShoppingCartRiskAssessment")
POST "https://{{baseUrl}}/shoppingCartRiskAssessment"
"Content-Type": "application/json;charset=utf-8"
json({
    "shoppingCart": {
        "id": "cupidatat non voluptate aute",
        "href": "mollit ut sunt aliqua in",
        "@baseType": "officia mollit Lorem veniam",
        "@schemaLocation": "https://KbfbVjuqFLwugtA.odMOUm7u5zjJyyY.Qu1Aw1AIj9BLgSFYp+ozTA7+G5",
        "@type": "in labore deserunt",
        "@referredType": "in laboris dolor sed"
    },
    "status": "laborum non",
    "characteristic": [
        {
            "name": "mollit aliqua pariatur",
            "value": {},
            "id": "magna deserunt",
            "valueType": "pariatur",
            "characteristicRelationship": [
                {
                    "id": "deserunt Excepteur",
                    "href": "http://VxfjbUnqkhFPEVxTXnAIWO.ywxka3kCqfbL-QucMA8SijlFaXH58BR9R",
                    "relationshipType": "ut tempor Excepteur",
                    "@baseType": "adipisicing eiusmod in in",
                    "@schemaLocation": "http://WsxYt.ijlHOPH58hkSw",
                    "@type": "ut"
                },
                {
                    "id": "deserunt tempor",
                    "href": "http://VVExejzjRnUDPOLhEZbSNyZAHZK.ysRh9ewJc8m4arhOqlQZM7A6ksRzI4j3uI,NukwZykK2c1Jxr2JnnlCMqJaAxqGDFqTQBLxGVlv",
                    "relationshipType": "consectetur no",
                    "@baseType": "dolor labore exercitation",
                    "@schemaLocation": "http://jLeCJXMFzIjhdLtNLXxIwabLgJev.kipvyiXixqYMpQa",
                    "@type": "et voluptate"
                }
            ],
            "@baseType": "ea sed",
            "@schemaLocation": "http://J.wvS0NpNTdkoRnpjz7VHZu5U+0p2qmnRn9pvJ-M",
            "@type": "proident dolore ali"
        },
        {
            "name": "non adipisicing velit",
            "value": {},
            "id": "c",
            "valueType": "qui do dolor cillum",
            "characteristicRelationship": [
                {
                    "id": "id aliqua in quis",
                    "href": "http://KHPRDRTStJOWlgRciuDBZo.ipjos4qz,mW.MbipHvuxjF67Y.,dSJC0Z5tk2Zoiew4fT5ZAzWOOnmu",
                    "relationshipType": "in eu deserunt non sint",
                    "@baseType": "do consectetur",
                    "@schemaLocation": "https://LunAJkbBPBjMEdzLkV.igytBnk2KDZzNHX1.itb2XnVbRYAqEZvnhMCSKWydrTf3VlhHSF,R6TMG.NMs6y-R,R62P",
                    "@type": "aliquip Ut adipisicing elit"
                },
                {
                    "id": "nostrud adipisicing nisi est",
                    "href": "https://jt.wzxxY3wBY3wSuU3nVx1LfzqNj6xLLTnoiQ,Eumtwdc2rqPFHCqiie1p",
                    "relationshipType": "amet",
                    "@baseType": "ea",
                    "@schemaLocation": "https://ZDk.jqfzfG5H0lQmPHgsS.caeiWMoY1MZ2fbOGkGB4GZsQY",
                    "@type": "cupidatat ipsum commodo sint labore"
                }
            ],
            "@baseType": "ut magna eiusmod officia deserunt",
            "@schemaLocation": "http://dtCwkowx.gprzN6zo8uJohNlvGrRl0bXmMQMPq4noW1z",
            "@type": "incididun"
        }
    ],
    "place": {
        "id": "ullamco elit",
        "href": "sit officia anim",
        "name": "ipsum cupidatat do",
        "role": "amet dolore id",
        "@baseType": "laboris dolore voluptate est",
        "@schemaLocation": "https://tqrROoamvhjknJyAz.ywYYOahh8XIiBpOfB0OS4BwOTWKB7eCKXkHCgRl0+ykMVazS88ej2+suW.34-n2Z-J.DMkU",
        "@type": "non deserunt",
        "@referredType": "ut dolor Ut adipisicing magna"
    },
    "riskAssessmentResult": {
        "overallScore": -11789990.315781742,
        "score": [
            {
                "score": 35005452.52667761,
                "riskName": "PaymentMethodRisk",
                "@baseType": "ipsum",
                "@schemaLocation": "http://fbHbWiabbOoY.csjnKpgX3fZUZlfio0UkmNFPjNbtJKXmiWzzcipdaAI.c",
                "@type": "enim elit"
            },
            {
                "score": -14602673.01958464,
                "riskName": "IDConfidenceRisk",
                "@baseType": "in Lorem",
                "@schemaLocation": "https://TUHfBA.wnxxS,GVnIqLuWAxuPHDnlPL9mbfhU2ImOnw8bM-pb4XE",
                "@type": "cillum irure anim sit"
            }
        ],
        "validFor": {
            "id": "ea id",
            "href": "https://qyoH.nayde9yJmawUjkIJbWvd8c0,HWPc7aMLSGVNQyvulaP",
            "endDateTime": "1985-04-12T23:20:50.52Z",
            "startDateTime": "1985-04-12T23:20:50.52Z",
            "@baseType": "eiusmod culpa",
            "@schemaLocation": "http://uKbeKtipcnQT.rhsxelFTPmNShVtB8hj+gzkku7zm1hEFJ388RIGp9M4,ZOHsBONbZ",
            "@type": "Ut amet in est"
        },
        "@baseType": "est dolor",
        "@schemaLocation": "https://AGsoDoxITow.jjLLhoWVpcUbR5onkHcl8j3iYWEemZx3AV2soRT",
        "@type": "quis irure "
    },
    "@baseType": "dolor tempor",
    "@schemaLocation": "https://owv.tgrzQim65YiNOFgvXWeFTrzVZHfS+gMzCG7r1nUGtRuV-B1IekvLwdZ",
    "@type": "consequat labore laborum"
})



