#!/usr/bin/env dothttp

# imported from 35240-b82d3de0-b39b-41b9-ae9b-f12023f67d54.postman_collection.json

@name("universities/all/")
GET "https://{{url}}/universities/all/"



@name("universities/us/")
GET "https://{{url}}/universities/all/"




