#!/usr/bin/env dothttp

# imported from 35240-5f0de24a-12d4-4bb7-a222-68e7bfdfd2e8.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// List all data redactions

@name("List all data redactions") : "base-inherit-auth"
GET "https://{{baseUrl}}/services/:env_id/settings/data-redaction"


// Enable / disable data redaction for a selected environment. This call is allowed for admins only. **IMPORTANT:** *This call affects all filters*

@name("Enable / disable data redaction") : "base-inherit-auth"
POST "https://{{baseUrl}}/services/:env_id/settings/data-redaction"
"Content-Type": "application/json"
json({
    "enabled": true
})



