#!/usr/bin/env dothttp

# imported from 35240-57b8bd73-4de0-40d6-a897-419d0ea5b8dd.postman_collection.json

// Delete applications.

@name("Delete Applications")
DELETE "https://{{baseUrl}}/applications"
? "Content"= "<>"


// Delete applications appid addresses.

@name("Delete Applications Appid Addresses")
DELETE "https://{{baseUrl}}/applications/:AppId/addresses"
? "applicationId"= "<>"



