#!/usr/bin/env dothttp

# imported from 35240-4cff9dbd-dc9e-457a-8421-41b9b4a7bdef.postman_collection.json

// Create an outgoing webhook for a team.n##### Permissionsn`manage_webhooks` for the team the webhook is in.n

@name("Create an outgoing webhook")
POST "https://{{baseUrl}}/hooks/outgoing"



