#!/usr/bin/env dothttp

# imported from 35240-d1c24152-c0ee-4a27-a9ce-a0e1ddc1f2e6.postman_collection.json

// This operation list or find Service entities

@name("List or find Service objects")
GET "https://{{baseUrl}}/service"
? "fields"= "minim mollit sit"
? "offset"= "-5367809"
? "limit"= "-5367809"


// This operation creates a Service entity.

@name("Creates a Service")
POST "https://{{baseUrl}}/service"
"Content-Type": "application/json;charset=utf-8"
json({
    "state": "terminated",
    "serviceSpecification": {
        "id": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "href": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "name": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "version": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "@baseType": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "@schemaLocation": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "@type": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "@referredType": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        }
    },
    "category": "do exercitation in",
    "description": "Excepteur",
    "endDate": "2019-09-29T21:53:41.925Z",
    "hasStarted": true,
    "isBundle": false,
    "isServiceEnabled": false,
    "isStateful": true,
    "name": "fugiat ex labore aliquip",
    "serviceDate": "irure",
    "serviceType": "voluptate ipsum Ut",
    "startDate": "1968-02-22T04:07:51.522Z",
    "startMode": "ut eiusmod consequat",
    "feature": [
        {
            "featureCharacteristic": [
                {
                    "name": "consectetur pariatur et",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "ad laboris cupidatat mollit",
                    "valueType": "sed laboris dolore",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                }
            ],
            "name": "mollit velit culpa",
            "id": "ullamco",
            "isBundle": true,
            "isEnabled": true,
            "constraint": [
                {
                    "id": "deserunt",
                    "href": "ipsum Excepteur",
                    "name": "dolor in",
                    "version": "pariatur adipisicing nostrud do irure",
                    "@baseType": "nisi Lorem",
                    "@schemaLocation": "http://atPinI.yzX-yd,cFgPD4Hgz46icCsk",
                    "@type": "elit aute",
                    "@referredType": "ut veniam irure Duis"
                },
                {
                    "id": "enim laborum dolore culpa",
                    "href": "Lorem ullamco dolor ipsum labore",
                    "name": "veniam ex volup",
                    "version": "ad voluptate ipsum officia",
                    "@baseType": "enim consectetur",
                    "@schemaLocation": "https://RvYFERkoNfvudmjrIsXvfveVZkUDhEWYB.ptNUJk7.eTFepKKzolrjYBrl4iLsqhXdCZMJzDxT1H1xBv3hSk6,f2T4kShkittVVrq6",
                    "@type": "ullamco dolore mollit",
                    "@referredType": "ea enim dolor"
                }
            ],
            "featureRelationship": [
                {
                    "name": "qui Lorem",
                    "relationshipType": "do labore ut pariatur",
                    "id": "dolor ex in tempor Ut",
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "laborum irure dolor nisi labore",
                    "@schemaLocation": "https://GQKTuoDkvonFLZzbQBWaPg.smkGyXi01y,X6D",
                    "@type": "reprehende"
                },
                {
                    "name": "veniam commod",
                    "relationshipType": "velit cupidatat ullamco veniam",
                    "id": "non aliqua in amet laborum",
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "dolor Lorem",
                    "@schemaLocation": "http://dkBZZ.xeTI7hd5Q3T",
                    "@type": "consequat est sint"
                }
            ],
            "@baseType": "et incididunt dolor",
            "@schemaLocation": "http://oXNRmBeQIFUxIipAFfZTHhOowBGmi.yqJzunZT7hW,VjS0.oF2c1oApXKgBxEGIyZuMN4KEdbfuqI4ut2Di4ulxT",
            "@type": "culpa Excepteur mollit sint"
        },
        {
            "featureCharacteristic": [
                {
                    "name": "culpa aliqua incididunt quis in",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "Duis labore",
                    "valueType": "consequat in",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                }
            ],
            "name": "consequ",
            "id": "venia",
            "isBundle": false,
            "isEnabled": false,
            "constraint": [
                {
                    "id": "elit ut",
                    "href": "exercitation Lorem",
                    "name": "ad",
                    "version": "commodo aliquip",
                    "@baseType": "ipsum",
                    "@schemaLocation": "https://RalsYYPILByibzzqaoUAbL.sasE3gexsx4Owq+a1dqV3N3YKIM6Dty",
                    "@type": "adipisicing amet mollit tempor quis",
                    "@referredType": "id anim"
                },
                {
                    "id": "id elit pariatur",
                    "href": "eu elit pariatur aliqua",
                    "name": "dolore laborum occaecat mollit",
                    "version": "ex ullamco aliqua esse",
                    "@baseType": "",
                    "@schemaLocation": "http://jfBkjaxBb.jpekkk.+.0qOVKNpR1L5uDG",
                    "@type": "velit voluptate",
                    "@referredType": "proident in"
                }
            ],
            "featureRelationship": [
                {
                    "name": "eu ea anim",
                    "relationshipType": "dolore commodo sunt",
                    "id": "anim incididunt do",
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "culpa ipsum",
                    "@schemaLocation": "https://ruTgnnth.ykoaZH1py9CIqhWNRCG7EWS2Pa,OZX",
                    "@type": "fugiat in irure esse non"
                },
                {
                    "name": "eiusmod irure",
                    "relationshipType": "esse est velit",
                    "id": "in deserunt amet",
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "dolor volupta",
                    "@schemaLocation": "http://YmnYlmzkhxDZGXoq.yywLhw,hn21yzEqfCoaM4dPhpR1-f.QYJUb2yAKQ4bpBW",
                    "@type": "Lorem eiusmod amet in"
                }
            ],
            "@baseType": "officia voluptate",
            "@schemaLocation": "https://JJpzLCwnd.fhbopU6a,l.El3SA.IBGALLLLWP-bONQdicwNTxDKr",
            "@type": "eiusmod do"
        }
    ],
    "note": [
        {
            "id": "officia enim velit",
            "author": "culpa Excepteur",
            "date": "2021-02-26T05:21:23.150Z",
            "text": "elit reprehenderit in",
            "@baseType": "veniam deserunt dolore ipsum",
            "@schemaLocation": "http://CiHsQeyqmjyyXbHDIlfLhfSFCsPI.xrkzfnGFXsebjNGqUqHzaPMekTJLOdYYnpfW19DGHH",
            "@type": "proident exercitation tempor elit"
        },
        {
            "id": "e",
            "author": "reprehenderit aliqua n",
            "date": "1949-09-12T18:08:14.656Z",
            "text": "deserunt consectetur",
            "@baseType": "enim sunt fugiat",
            "@schemaLocation": "https://PRjFOrseJMFKQp.japXPFSwxL2gnOur8RhslHBx95gcAbmsSmhbOl",
            "@type": "do amet labo"
        }
    ],
    "place": [
        {
            "role": "sit Excepteur est",
            "id": "Duis non i",
            "href": "dolore dolore",
            "name": "esse amet",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "fugiat dolore"
        },
        {
            "role": "veniam quis sit elit Ut",
            "id": "Ut l",
            "href": "anim veniam occaecat",
            "name": "consectetur elit pariatur",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "commodo"
        }
    ],
    "relatedEntity": [
        {
            "role": "laboris enim anim",
            "id": "d",
            "href": "sit Duis",
            "name": "aliquip eiusmod n",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "nisi dolore"
        },
        {
            "role": "in ut",
            "id": "qui ut",
            "href": "voluptate commodo",
            "name": "dolore Ut sit",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "dolore"
        }
    ],
    "relatedParty": [
        {
            "@referredType": "dolore occaecat magna mollit",
            "id": "ut nulla",
            "href": "http://IeoycYiycmbWMMImDxygEWojyfdUMor.lsoRYbJ-d-6GqPMyelfzTXB",
            "name": "magna voluptate nulla",
            "role": "consectetur occaecat",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification"
        },
        {
            "@referredType": "mollit ut Ut",
            "id": "eiusmod in dolor",
            "href": "https://vZXmdSlwZJcaIrWXawmA.lbfvpSoxC2Bw74eZpGzmqKcFdR3qFjpLBe7xtdnNI-qj0i",
            "name": "eiusmod quis commodo minim",
            "role": "ut id dolor incididunt",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification"
        }
    ],
    "serviceCharacteristic": [
        {
            "name": "tempor aliqua qui",
            "value": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "id": "ullamco anim aliquip amet",
            "valueType": "do ea",
            "characteristicRelationship": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ],
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification"
        },
        {
            "name": "in eiusmod",
            "value": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "id": "ullamco nulla",
            "valueType": "occaecat dolor incididunt",
            "characteristicRelationship": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ],
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification"
        }
    ],
    "serviceOrderItem": [
        {
            "itemId": "minim non voluptate enim",
            "serviceOrderId": "quis",
            "role": "officia dolore laborum mollit",
            "serviceOrderHref": "Ut dolor",
            "itemAction": "noChange",
            "@baseType": "consequat",
            "@schemaLocation": "https://TSneKnsaxbtIYqlHkMnChXCR.qwV+JBlPzQR.jXixdx4XeiaOS",
            "@type": "voluptate dolor sunt sit nostrud",
            "@referredType": "Duis reprehenderit consequat"
        },
        {
            "itemId": "proident cupidatat",
            "serviceOrderId": "dolor ut ea",
            "role": "consectetur in enim",
            "serviceOrderHref": "Ut dolore minim commodo",
            "itemAction": "delete",
            "@baseType": "sunt officia nostrud",
            "@schemaLocation": "http://gHKpjPpvYIK.jchhW8PkqXkiIm",
            "@type": "amet qui",
            "@referredType": "non eu id veniam sed"
        }
    ],
    "serviceRelationship": [
        {
            "relationshipType": "irure labore consequat non",
            "ServiceRelationshipCharacteristic": [
                {
                    "name": "ex enim",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "consequat quis in cupidatat",
                    "valueType": "proident velit pariatur",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                },
                {
                    "name": "Duis commodo cupidatat pariatur non",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "dolor amet in in",
                    "valueType": "exercitation officia enim",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                }
            ],
            "service": {
                "id": "ut fugiat eu enim pariatur",
                "href": "ex reprehenderit irure non",
                "category": "aute",
                "description": "consectetur Excepteur ex ipsum dolore",
                "endDate": "1960-01-20T23:32:39.457Z",
                "hasStarted": true,
                "isBundle": true,
                "isServiceEnabled": false,
                "isStateful": false,
                "name": "officia dolor nulla id",
                "serviceDate": "sit pariatur dolor",
                "serviceType": "non eu cupidatat",
                "startDate": "1982-10-07T10:39:59.355Z",
                "startMode": "sint laboris dese",
                "feature": [
                    {
                        "featureCharacteristic": [
                            {
                                "name": "eu deserunt voluptate",
                                "value": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "id": "nisi sunt dolor",
                                "valueType": "cillum ad",
                                "characteristicRelationship": [
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    },
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    }
                                ],
                                "@baseType": "ResourceSpecification",
                                "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                                "@type": "LogicalResourceSpecification"
                            }
                        ],
                        "name": "dolor",
                        "id": "consequat dolor",
                        "isBundle": true,
                        "isEnabled": true,
                        "constraint": [
                            {
                                "id": "aliquip",
                                "href": "ad dolore ",
                                "name": "sunt",
                                "version": "eiusmod mollit",
                                "@baseType": "fugiat do laboris ex",
                                "@schemaLocation": "http://RMUdriytUHAol.xiF.NPWc6VUnob7mZdt5AYOCKYrq5",
                                "@type": "elit",
                                "@referredType": "qui magna sed exercitation"
                            },
                            {
                                "id": "dolore",
                                "href": "adipisicing pariatur Duis cillum",
                                "name": "exercitation tempor eu consectetur",
                                "version": "ipsum enim",
                                "@baseType": "irure ut officia",
                                "@schemaLocation": "http://UWUFAehmnYfSqvCaUanaXfKbv.fgJXDYoA3jbO5WAxezE3DHze",
                                "@type": "u",
                                "@referredType": "amet irure"
                            }
                        ],
                        "featureRelationship": [
                            {
                                "name": "Ut sunt commodo",
                                "relationshipType": "aute fugiat voluptate adipisicing e",
                                "id": "sunt Ut do",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "@baseType": "commodo deserunt ullamco mollit",
                                "@schemaLocation": "https://nMSpYvCrFe.gmlzeJRjJVjCBVseUH2jUCVzxve",
                                "@type": "occaecat incididunt"
                            },
                            {
                                "name": "sunt exercitation voluptate ut veniam",
                                "relationshipType": "elit est in",
                                "id": "deserunt irure",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "@baseType": "ad voluptate ",
                                "@schemaLocation": "http://UmQyBqMnJbKUEkVWwulnmL.kqzHwWXBD4dp7+Ps4nBjfzzZ4c.tSQhX.5y6MB9AQRJQK0eYFejXaJRPJTNNfuSX",
                                "@type": "magna deserun"
                            }
                        ],
                        "@baseType": "proident Ut dolor consectetur ",
                        "@schemaLocation": "https://JzwRqgnBR.cvsuGE0xJySjiKnZhzRnAabwQSuO3VeiE2DEJEPKxahGEQ",
                        "@type": "pa"
                    },
                    {
                        "featureCharacteristic": [
                            {
                                "name": "aliquip",
                                "value": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "id": "ipsum sunt sed",
                                "valueType": "cillum culpa magna consequat aliquip",
                                "characteristicRelationship": [
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    },
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    }
                                ],
                                "@baseType": "ResourceSpecification",
                                "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                                "@type": "LogicalResourceSpecification"
                            }
                        ],
                        "name": "sed amet",
                        "id": "consectetur",
                        "isBundle": true,
                        "isEnabled": false,
                        "constraint": [
                            {
                                "id": "elit eu nostrud officia",
                                "href": "tempor enim",
                                "name": "adipisicing do ",
                                "version": "sed Duis culpa",
                                "@baseType": "nulla nostrud exercitation",
                                "@schemaLocation": "https://dDEquTe.hljZi8zb.eDn0-ggaom2D7lhY9TfFMQpYJDz1AqkWvS+dcgsBv4pUkwUYTfuDbqXqPV",
                                "@type": "qui commodo sunt exercitation cillum",
                                "@referredType": "amet occaecat enim"
                            },
                            {
                                "id": "pariatur labore",
                                "href": "pariatur laborum dolore est velit",
                                "name": "in ipsum",
                                "version": "enim proident labore exercitation et",
                                "@baseType": "anim dolor magna Duis sed",
                                "@schemaLocation": "https://gPmvbpmrBAXqXtykxHLY.bkdfIBnYhpeCvWO9Dlz4XcCJCgt9Rhar",
                                "@type": "exercitation ea aliqua reprehenderit",
                                "@referredType": "proident mollit Ut"
                            }
                        ],
                        "featureRelationship": [
                            {
                                "name": "eu sunt",
                                "relationshipType": "sit eu",
                                "id": "magna ex",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "@baseType": "non ullamco in quis ea",
                                "@schemaLocation": "http://FkbmUoICk.imXWGlpCgAKs,-+vXUoW.isyuAUmiCY6ghWmjV",
                                "@type": "adipisicing in"
                            },
                            {
                                "name": "officia in ipsum nisi",
                                "relationshipType": "magna Ut dolor",
                                "id": "c",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "@baseType": "nulla occaecat esse veniam",
                                "@schemaLocation": "http://DhzeqVvjFmfQNMM.fyalTjCUtjpur5H16xSkra0th0pCnbzBTP87EHJr",
                                "@type": "in mollit dolore"
                            }
                        ],
                        "@baseType": "",
                        "@schemaLocation": "http://StyWOHDg.cisPtuzcR2,-48W9RXSC2cDWGB6gYMxbPCdIOB0hiot5QcdDxH5BCscI.",
                        "@type": "tempor aute deserunt amet"
                    }
                ],
                "note": [
                    {
                        "id": "dolore eiusmod ut tempor est",
                        "author": "officia ex",
                        "date": "1981-01-23T21:23:56.650Z",
                        "text": "enim ut",
                        "@baseType": "occaecat et aute voluptate nulla",
                        "@schemaLocation": "https://wIvDafgHjIOGDd.cqvjFjexoGs3TS5bivYWA-atcdCEZmL",
                        "@type": "in"
                    },
                    {
                        "id": "dolor nostrud proi",
                        "author": "est proident reprehenderit",
                        "date": "2012-06-23T10:52:19.145Z",
                        "text": "qui u",
                        "@baseType": "dolore consectetur voluptate",
                        "@schemaLocation": "http://BzgWARJxTb.thtmQ,uI7RT9YQxjtg7ijUoKyWLvLYvmCrMZag+hxn+bdI2vYt6Ujz,W.64Jy2H5T25LTVSLB",
                        "@type": "nisi eiusmod ullamco magna"
                    }
                ],
                "place": [
                    {
                        "role": "dolor laboris",
                        "id": "magna",
                        "href": "esse anim",
                        "name": "ad dolore laboris enim",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification",
                        "@referredType": "aute ea laborum ex"
                    },
                    {
                        "role": "enim cons",
                        "id": "tempor nulla dolor incididunt au",
                        "href": "non laborum fugiat velit",
                        "name": "qui",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification",
                        "@referredType": "sint"
                    }
                ],
                "relatedEntity": [
                    {
                        "role": "",
                        "id": "magna irure",
                        "href": "nisi qui culpa esse",
                        "name": "in esse",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification",
                        "@referredType": "sed mollit nulla aliqua"
                    },
                    {
                        "role": "aliquip in qui pariatur",
                        "id": "aliquip commodo non ea",
                        "href": "ut culpa",
                        "name": "nulla magna aute",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification",
                        "@referredType": "non quis in Ut anim"
                    }
                ],
                "relatedParty": [
                    {
                        "@referredType": "in amet dolore culpa",
                        "id": "aliquip anim enim",
                        "href": "http://gnSrVQ.iemgGRqJSZj5vAEB5SzKQ2CfBMTbxwERFHSJEY5yuSSyCu+JivAdlzl85Xv1s+CL07v",
                        "name": "Ut esse elit",
                        "role": "elit est",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification"
                    },
                    {
                        "@referredType": "tempor dolore dolor adipisicing",
                        "id": "ad e",
                        "href": "https://FlZjqYmT.mddPf9Xs7YWb0tDLJdyIIePRHMf9N.CwObVUnUCe3mQl+frkh-CMVmW1ahUMNrHwoCz.h7qOgQl.6",
                        "name": "aliquip ea",
                        "role": "non",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification"
                    }
                ],
                "serviceCharacteristic": [
                    {
                        "name": "in",
                        "value": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "id": "quis dolor Duis",
                        "valueType": "pariatur elit in Duis",
                        "characteristicRelationship": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification"
                    },
                    {
                        "name": "eiusmo",
                        "value": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "id": "do deserunt amet",
                        "valueType": "dolor",
                        "characteristicRelationship": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification"
                    }
                ],
                "serviceOrderItem": [
                    {
                        "itemId": "enim ut",
                        "serviceOrderId": "reprehenderit ex",
                        "role": "deserunt elit aliqua occaecat proident",
                        "serviceOrderHref": "ad veniam sed",
                        "itemAction": "delete",
                        "@baseType": "sed magna quis",
                        "@schemaLocation": "https://nTLAsqKLTcC.lrdHOKNloL8DsAdZmLxKUJBRjH",
                        "@type": "sint qui ut t",
                        "@referredType": "anim do"
                    },
                    {
                        "itemId": "ipsum repr",
                        "serviceOrderId": "eu in est",
                        "role": "velit ad cillum deserunt",
                        "serviceOrderHref": "laborum do velit",
                        "itemAction": "modify",
                        "@baseType": "in",
                        "@schemaLocation": "http://ksZqTMtuhgeP.wqjol7mMfBcVbnkV4DitXhKJfEco",
                        "@type": "nostrud",
                        "@referredType": "deserunt cupidatat"
                    }
                ],
                "serviceRelationship": [
                    {
                        "value": "<Circular reference to #/components/schemas/ServiceRelationship detected>"
                    },
                    {
                        "value": "<Circular reference to #/components/schemas/ServiceRelationship detected>"
                    }
                ],
                "serviceSpecification": {
                    "id": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "href": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "name": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "version": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@schemaLocation": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@type": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@referredType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "state": "reserved",
                "supportingResource": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "supportingService": [
                    {
                        "value": "<Circular reference to #/components/schemas/ServiceRefOrValue detected>"
                    },
                    {
                        "value": "<Circular reference to #/components/schemas/ServiceRefOrValue detected>"
                    }
                ],
                "@baseType": "ResourceSpecification",
                "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                "@type": "LogicalResourceSpecification",
                "@referredType": "cupidatat nisi esse sint"
            },
            "@baseType": "deserunt",
            "@schemaLocation": "http://yhEDggmgqEFvqNHCOyiJcK.ekstKFyaykOLrT",
            "@type": "non ex ut consequat Ut"
        },
        {
            "relationshipType": "est et veniam dolore fugiat",
            "ServiceRelationshipCharacteristic": [
                {
                    "name": "aute mollit deserunt",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "in esse nostrud",
                    "valueType": "aliqua dolore ad",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                },
                {
                    "name": "officia dolor",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "nostrud voluptate fugi",
                    "valueType": "ipsum nisi ullamco ea",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                }
            ],
            "service": {
                "id": "voluptate",
                "href": "magna sunt amet in",
                "category": "aliqua mo",
                "description": "elit ut",
                "endDate": "1990-11-08T14:32:42.270Z",
                "hasStarted": false,
                "isBundle": true,
                "isServiceEnabled": true,
                "isStateful": false,
                "name": "officia eu amet aliquip",
                "serviceDate": "proident nostrud",
                "serviceType": "sint",
                "startDate": "1967-10-04T20:36:42.822Z",
                "startMode": "aliquip irure do adipisicing sint",
                "feature": [
                    {
                        "featureCharacteristic": [
                            {
                                "name": "reprehenderit adipisicing Lorem",
                                "value": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "id": "consectetur labore non cillum",
                                "valueType": "eu sit",
                                "characteristicRelationship": [
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    },
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    }
                                ],
                                "@baseType": "ResourceSpecification",
                                "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                                "@type": "LogicalResourceSpecification"
                            }
                        ],
                        "name": "dolor laboris eiusmod in",
                        "id": "ullamco ut Lorem nulla p",
                        "isBundle": false,
                        "isEnabled": false,
                        "constraint": [
                            {
                                "id": "occaecat dolor",
                                "href": "in voluptate nulla proident",
                                "name": "reprehenderit minim",
                                "version": "elit et sed",
                                "@baseType": "non",
                                "@schemaLocation": "http://BGdYGtJTXybo.nsjdr.NgeYQbLPCeJ-GYccOV.Xt5TbsM0oqvhYbMGczRYY6naY7o,8sHWc",
                                "@type": "nostrud esse cillum",
                                "@referredType": "c"
                            },
                            {
                                "id": "officia ipsum consectetur",
                                "href": "incididunt commodo Excepteur reprehenderit",
                                "name": "in aliquip ea cillum",
                                "version": "voluptate",
                                "@baseType": "laboris veniam quis voluptate",
                                "@schemaLocation": "https://k.lfb9ZZ7budehgelhX1iklTqzGH",
                                "@type": "ea Duis",
                                "@referredType": "aliqua aute"
                            }
                        ],
                        "featureRelationship": [
                            {
                                "name": "in cillum dolor",
                                "relationshipType": "enim tempor ex sed",
                                "id": "exercitation eiusmod irure nostrud",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "@baseType": "quis magna anim",
                                "@schemaLocation": "https://PRXQGuteO.krqqZPRVcgj16Obow-qymR+Ja.xr",
                                "@type": "anim"
                            },
                            {
                                "name": "proident officia quis",
                                "relationshipType": "Lorem dolore ex Excepteur",
                                "id": "in dolore nulla",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "@baseType": "veniam laboris",
                                "@schemaLocation": "http://WedHjAykxMKbBSwzxG.cdppvRbnKpG+S1tnQ9TEsUcy4.UY8Y1MgddlUxqg0XgVxk",
                                "@type": "in la"
                            }
                        ],
                        "@baseType": "ad ",
                        "@schemaLocation": "https://xJVAUDxrpbj.rkvTJa3mfZ0o-KTEdc-54e2R2re9WyxFPnS8IvTbqt7,7pRWXDSS78+6",
                        "@type": "cupidatat exercitation aute tempor"
                    },
                    {
                        "featureCharacteristic": [
                            {
                                "name": "voluptate aliquip eiusmod exercitation",
                                "value": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "id": "in consequat consectetur",
                                "valueType": "in dolore Excepteur laboris",
                                "characteristicRelationship": [
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    },
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    }
                                ],
                                "@baseType": "ResourceSpecification",
                                "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                                "@type": "LogicalResourceSpecification"
                            }
                        ],
                        "name": "voluptate",
                        "id": "deserunt",
                        "isBundle": false,
                        "isEnabled": false,
                        "constraint": [
                            {
                                "id": "dolor dolore ad sint",
                                "href": "cillum dolor ipsum officia nulla",
                                "name": "cupidatat commodo ad aliquip",
                                "version": "cillum do exercitation Lorem ullamco",
                                "@baseType": "dolore veniam",
                                "@schemaLocation": "http://MiuDISeBoDahAeCKdGSZiqF.imnF1yKXQf5IeLCTT,Fsav",
                                "@type": "reprehenderit ullamco irure fugiat",
                                "@referredType": "dolor incididunt"
                            },
                            {
                                "id": "proident enim",
                                "href": "occaecat esse",
                                "name": "do",
                                "version": "amet non eiusmod",
                                "@baseType": "amet",
                                "@schemaLocation": "https://OErMkg.jfxlJVQjX0TwekxdxNxR7zw3.1g14zRFAdVrBhWN-C2qrJzIaUoEwrGvJEF",
                                "@type": "laboris dolor magna anim",
                                "@referredType": "nostrud"
                            }
                        ],
                        "featureRelationship": [
                            {
                                "name": "anim Lorem eiusmod",
                                "relationshipType": "consec",
                                "id": "ullamco aliqua",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "@baseType": "minim",
                                "@schemaLocation": "http://YGjXjYZMqBnajbQHMQsMswTXy.snxAj0Di",
                                "@type": "ullamco"
                            },
                            {
                                "name": "eiusmod in Lorem",
                                "relationshipType": "voluptate",
                                "id": "U",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "@baseType": "cupidatat ",
                                "@schemaLocation": "http://HcEbBtqtfizYIVOUAIThaZJHeTjUrgIz.xoroB4dOayWcswWGxUvmGMVZKRC4ULegXOeNWip0RffKA0",
                                "@type": "ad"
                            }
                        ],
                        "@baseType": "est",
                        "@schemaLocation": "https://PzYu.mxOqe",
                        "@type": "consectetur laborum veniam"
                    }
                ],
                "note": [
                    {
                        "id": "cillum sed officia",
                        "author": "ea aute esse",
                        "date": "1984-06-01T09:42:10.321Z",
                        "text": "do sit minim",
                        "@baseType": "consectetur labore occaecat sunt Duis",
                        "@schemaLocation": "http://sduwBzqzipMXEx.vwmyeLkQAjRyTTswpqGIr0x",
                        "@type": "non"
                    },
                    {
                        "id": "Excepteur",
                        "author": "voluptate commodo eu Duis",
                        "date": "1990-07-13T11:23:34.592Z",
                        "text": "eu in elit",
                        "@baseType": "Excepteur laboris",
                        "@schemaLocation": "http://kOZCzrjf.issQYtbjd4at+fs,4SlSuxWh7XfsI3sVIBD1NBpKbmMhE-w4LrAtAqT",
                        "@type": "ex ut"
                    }
                ],
                "place": [
                    {
                        "role": "dese",
                        "id": "id in in irure",
                        "href": "laboris in irure cillum Excepteur",
                        "name": "culpa occaecat cillum",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification",
                        "@referredType": "nisi"
                    },
                    {
                        "role": "in eu deserunt",
                        "id": "in ad irure sed",
                        "href": "sint enim Ex",
                        "name": "laboris et nulla",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification",
                        "@referredType": "dolor"
                    }
                ],
                "relatedEntity": [
                    {
                        "role": "velit enim Duis officia esse",
                        "id": "reprehenderit non elit laboris",
                        "href": "labore enim eiusmod in",
                        "name": "consectetur esse",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification",
                        "@referredType": "labore eu"
                    },
                    {
                        "role": "ex minim ullamco",
                        "id": "dolore",
                        "href": "mollit",
                        "name": "incididunt",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification",
                        "@referredType": "nisi minim"
                    }
                ],
                "relatedParty": [
                    {
                        "@referredType": "ea tempor",
                        "id": "ex culpa nostrud esse",
                        "href": "https://ZcdEKCvdJNNhCLkvZMhXxkkUmWGFwBfT.mfblxVXWMqPGBF",
                        "name": "ut reprehenderit",
                        "role": "fugiat dolor",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification"
                    },
                    {
                        "@referredType": "mollit",
                        "id": "cupidatat fugiat amet mollit",
                        "href": "https://FlYiPJyfzrdjo.vgogeCe-Fm",
                        "name": "exercitation amet id anim",
                        "role": "enim mollit in",
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification"
                    }
                ],
                "serviceCharacteristic": [
                    {
                        "name": "deserunt pariatur ad Duis",
                        "value": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "id": "officia",
                        "valueType": "adipisicing incididunt culpa pariatur",
                        "characteristicRelationship": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification"
                    },
                    {
                        "name": "sit",
                        "value": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "id": "id quis",
                        "valueType": "cillum",
                        "characteristicRelationship": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "@baseType": "ResourceSpecification",
                        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                        "@type": "LogicalResourceSpecification"
                    }
                ],
                "serviceOrderItem": [
                    {
                        "itemId": "consectetur",
                        "serviceOrderId": "Ut ea",
                        "role": "velit dolor nisi",
                        "serviceOrderHref": "enim aute",
                        "itemAction": "delete",
                        "@baseType": "cillum dolor",
                        "@schemaLocation": "https://UPRmJqJvfuEWavsv.cdqhuHiHFcpvAC6AcVfGKr.utteZ+kZKa",
                        "@type": "laboris consequat",
                        "@referredType": "officia"
                    },
                    {
                        "itemId": "commodo eiusmod",
                        "serviceOrderId": "incididunt sed",
                        "role": "ut tempor Lorem",
                        "serviceOrderHref": "officia cupidatat dolor",
                        "itemAction": "delete",
                        "@baseType": "ullamco enim sunt amet",
                        "@schemaLocation": "http://IWzCRaRAbcWfx.kmrtqvA8b2hYxG-hmZxatjTOOe3kqLylkNWIdl.kuCG3MrO0",
                        "@type": "elit sed",
                        "@referredType": "veniam deserunt"
                    }
                ],
                "serviceRelationship": [
                    {
                        "value": "<Circular reference to #/components/schemas/ServiceRelationship detected>"
                    },
                    {
                        "value": "<Circular reference to #/components/schemas/ServiceRelationship detected>"
                    }
                ],
                "serviceSpecification": {
                    "id": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "href": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "name": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "version": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@schemaLocation": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@type": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@referredType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "state": "active",
                "supportingResource": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "supportingService": [
                    {
                        "value": "<Circular reference to #/components/schemas/ServiceRefOrValue detected>"
                    },
                    {
                        "value": "<Circular reference to #/components/schemas/ServiceRefOrValue detected>"
                    }
                ],
                "@baseType": "ResourceSpecification",
                "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                "@type": "LogicalResourceSpecification",
                "@referredType": "et occaecat eiusmod"
            },
            "@baseType": "occaecat quis",
            "@schemaLocation": "http://cnGvgJTCQvykDBJiTlACBdpjMd.bocVPhPflIF.I2.+p5mk8SsmoInHSGxDV,,C-,ioI+g6sG5Pb1pezXhlBU",
            "@type": "magna dolor ullamco do"
        }
    ],
    "supportingResource": [
        {
            "id": "culpa in nisi velit dolor",
            "href": "https://qpjNTlWNaoAzHBEmZ.njcfUshRq5rifbZCsH",
            "name": "ut nostrud",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "elit"
        },
        {
            "id": "proident ex occaecat Ut qui",
            "href": "http://EnGLmwkkhqoK.zyCQ8C.vuaroGRxEYh4XmJKK.VNzZm5IDGKk",
            "name": "consequat nulla commodo laboris",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "non occaecat tempor quis"
        }
    ],
    "supportingService": [
        {
            "id": "Excepteur mollit in dolor dolore",
            "href": "adipisicing veniam",
            "category": "amet occaecat nulla Duis aute",
            "description": "exercitation amet mollit",
            "endDate": "1984-11-24T05:36:48.737Z",
            "hasStarted": true,
            "isBundle": true,
            "isServiceEnabled": true,
            "isStateful": true,
            "name": "sint magna veniam",
            "serviceDate": "aliquip",
            "serviceType": "culpa dolor in aliqua magna",
            "startDate": "1954-11-30T18:59:49.295Z",
            "startMode": "tempor nulla",
            "feature": [
                {
                    "featureCharacteristic": [
                        {
                            "name": "consectetur sed anim",
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "id": "aliquip Lorem",
                            "valueType": "sunt pariatur esse laboris",
                            "characteristicRelationship": [
                                {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            ],
                            "@baseType": "ResourceSpecification",
                            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                            "@type": "LogicalResourceSpecification"
                        }
                    ],
                    "name": "laborum ea voluptat",
                    "id": "veniam mollit magna qui",
                    "isBundle": false,
                    "isEnabled": true,
                    "constraint": [
                        {
                            "id": "enim ullamco dolor eu",
                            "href": "do culpa esse",
                            "name": "ex esse aliquip ",
                            "version": "ut ad",
                            "@baseType": "esse eiusmod eu",
                            "@schemaLocation": "http://FxmHellyJSLxjIgOvMAR.rsnaA3dPy-kVO",
                            "@type": "aliqua exerci",
                            "@referredType": "in eiusmod id aute"
                        },
                        {
                            "id": "enim mollit in",
                            "href": "ea occaecat",
                            "name": "nisi adipisicing",
                            "version": "cupidatat ad",
                            "@baseType": "enim aute cupidatat sint",
                            "@schemaLocation": "http://oESmLGRs.nlfLc",
                            "@type": "elit laboris sint",
                            "@referredType": "Lorem dolore"
                        }
                    ],
                    "featureRelationship": [
                        {
                            "name": "proident cupidatat",
                            "relationshipType": "ullamco consequat dolor velit",
                            "id": "elit nisi amet",
                            "validFor": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "est quis dolore pariatur adipisicing",
                            "@schemaLocation": "http://mM.lamsLksRg-b2DXKdSVVjNmbsepeqzdQkDZQPYnDiIJ2jW3eCuonHfeq7+XFIx6oM3ZJ",
                            "@type": "labore veniam"
                        },
                        {
                            "name": "et sint",
                            "relationshipType": "quis mollit anim sed esse",
                            "id": "sint eu aute",
                            "validFor": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "amet adipisicing ad officia e",
                            "@schemaLocation": "http://BDQeBiKuKwKAgwoeWHroKlT.zisuvoyAPCVJ7ZMuyIouk",
                            "@type": "incididunt in aliqua adipisicing Lorem"
                        }
                    ],
                    "@baseType": "veniam irure nostrud",
                    "@schemaLocation": "http://eMNgRzaVYzJGYEHhqCcKFUNxLrtI.nqddpznFwurSmaHK5.TIkFIOflX4aLSlbrOk4IWt9WTNeDgtZ7XH",
                    "@type": "in labore amet"
                },
                {
                    "featureCharacteristic": [
                        {
                            "name": "amet velit nulla tempor",
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "id": "consectetur ut aliqua irure",
                            "valueType": "anim amet",
                            "characteristicRelationship": [
                                {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            ],
                            "@baseType": "ResourceSpecification",
                            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                            "@type": "LogicalResourceSpecification"
                        }
                    ],
                    "name": "do dolor",
                    "id": "nisi ",
                    "isBundle": true,
                    "isEnabled": false,
                    "constraint": [
                        {
                            "id": "sed consectetur",
                            "href": "l",
                            "name": "Lorem anim est Excepteur",
                            "version": "adipisicing occaecat",
                            "@baseType": "consectetur sunt nulla",
                            "@schemaLocation": "https://uLohjUyjblmkWOomiPVCnaDLN.uyeyMS2dlrdOs3OYBhH1e.+pNCsp1Df-jN0jg9z",
                            "@type": "id cupidatat",
                            "@referredType": "Excepteur"
                        },
                        {
                            "id": "esse id labore do",
                            "href": "fugiat Lorem officia",
                            "name": "in et esse aliqua",
                            "version": "proident",
                            "@baseType": "id cupidatat anim velit ea",
                            "@schemaLocation": "http://erCXnoEgWNBXBoE.fke-23DbksPzdlkdxc414",
                            "@type": "Duis culpa mollit anim",
                            "@referredType": "voluptat"
                        }
                    ],
                    "featureRelationship": [
                        {
                            "name": "proident amet",
                            "relationshipType": "voluptate aliquip sunt",
                            "id": "dolor commodo velit officia",
                            "validFor": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "in labore nostrud dolor",
                            "@schemaLocation": "http://BazJXTKpGsuwvabeFDkaSjXbE.mgNNvGLcqK765Zrg3clKgR2YJIubCYBuycLPQ9bUMgAwCcBwdgLz5",
                            "@type": "cupidatat laboris"
                        },
                        {
                            "name": "eu dolore aliqua",
                            "relationshipType": "cupidatat culpa",
                            "id": "laboris proident ea",
                            "validFor": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "Duis mag",
                            "@schemaLocation": "http://OnJWqw.wkgwC6eC1+dlOKEZzalkYdpgUZLIHBKt-Roo70Y7UnLptYUVZVwLn4z,VLp3YFCe-",
                            "@type": "sunt ad"
                        }
                    ],
                    "@baseType": "Ut tempor anim",
                    "@schemaLocation": "https://WFFlJNzK.imsL8eJ0QPfrLPavknKN0Xfs",
                    "@type": "sed incididunt reprehenderit eu aliqua"
                }
            ],
            "note": [
                {
                    "id": "amet eu",
                    "author": "nulla do labore",
                    "date": "2008-04-01T16:22:40.039Z",
                    "text": "velit sunt consequat dolore ut",
                    "@baseType": "aliquip proident commodo",
                    "@schemaLocation": "https://LdSotmfrUjpFAlzPeWjBuoUUhqq.tzaXZ4uVFrfaOuAdBuP-2MXPTcqY8YPI7k87mq1AAm63TkKGGqPMSyOgDH0wzaBRxTqb98+",
                    "@type": "qui qu"
                },
                {
                    "id": "dolor amet deserunt",
                    "author": "eu adipisicing sunt",
                    "date": "1949-01-19T16:13:58.525Z",
                    "text": "reprehenderit magna ea",
                    "@baseType": "et irure nostrud consequat",
                    "@schemaLocation": "http://VEVWhjzxgaevVpQyrXBribmGNdrijn.zjbijPghC-TbUtvsyZZEG9iC19HaxbtjdZSq+wrRzYQZBSrpc7mx34o0YIxN9PZuIdk6vxc5DCG0",
                    "@type": "sunt anim reprehenderit"
                }
            ],
            "place": [
                {
                    "role": "pariatur consectetur deserunt occaecat veniam",
                    "id": "consectetur ",
                    "href": "ex Ut mollit esse dolore",
                    "name": "adipisicing labore",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification",
                    "@referredType": "sed occaecat incididu"
                },
                {
                    "role": "in dolor Excepteur",
                    "id": "sed tempor sunt eu",
                    "href": "fugiat nostrud sit in",
                    "name": "consectetur pariatur dolore Excepteur ea",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification",
                    "@referredType": "culpa id enim"
                }
            ],
            "relatedEntity": [
                {
                    "role": "deserunt tempor consectetur reprehenderit",
                    "id": "tempor",
                    "href": "in occaecat enim",
                    "name": "dolore enim anim",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification",
                    "@referredType": "adipisicing"
                },
                {
                    "role": "adipisicing cillum magna",
                    "id": "consectetur veniam laborum fugiat",
                    "href": "et laboris minim ea voluptate",
                    "name": "ut ipsum",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification",
                    "@referredType": "nostrud reprehenderit"
                }
            ],
            "relatedParty": [
                {
                    "@referredType": "qui",
                    "id": "incididunt Ut eu",
                    "href": "https://fIuDICHIuZ.aqQaj217PR6ppqiZDr7LZsW-y5I3YJOVBduSK1vlK4Tpt5EB94",
                    "name": "ex Duis",
                    "role": "in mollit elit nostrud",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                },
                {
                    "@referredType": "eiusmod ex ipsum nulla proi",
                    "id": "consectetur adipisicing dolore laborum cupidatat",
                    "href": "http://gVORDjlI.alMZOKWjNhEEZMtL8BJB1XF5FMic,Kj4T+Azfov9aTz",
                    "name": "culpa in",
                    "role": "officia",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                }
            ],
            "serviceCharacteristic": [
                {
                    "name": "exercitation adipisicing Excepteur officia",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "eu nisi dolor esse",
                    "valueType": "non quis in",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                },
                {
                    "name": "nostrud sunt",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "dolore",
                    "valueType": "in qui aliqua",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                }
            ],
            "serviceOrderItem": [
                {
                    "itemId": "in quis sunt",
                    "serviceOrderId": "nulla ut",
                    "role": "consequat an",
                    "serviceOrderHref": "elit in",
                    "itemAction": "add",
                    "@baseType": "culpa ut velit anim",
                    "@schemaLocation": "http://RvHkorDEMnTeSYjsNMmQVJ.eiL,GkgN6kG",
                    "@type": "in eu adipisicing commodo",
                    "@referredType": "exercitation"
                },
                {
                    "itemId": "ad Duis eiusmod Lorem velit",
                    "serviceOrderId": "exercitation Lorem aliqua",
                    "role": "amet ad Lorem",
                    "serviceOrderHref": "ea Duis est",
                    "itemAction": "add",
                    "@baseType": "in cupidatat eiusmod aliquip",
                    "@schemaLocation": "http://hc.ixATJxOJveuNLcgU3Pc.U8wjCsZxtqDu+bZeroL2Ln3R5iq74XsjM0k9jk",
                    "@type": "aliquip dolor proident sed",
                    "@referredType": "ex magna consequat dolor"
                }
            ],
            "serviceRelationship": [
                {
                    "value": "<Circular reference to #/components/schemas/ServiceRelationship detected>"
                },
                {
                    "value": "<Circular reference to #/components/schemas/ServiceRelationship detected>"
                }
            ],
            "serviceSpecification": {
                "id": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "href": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "name": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "version": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@baseType": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@schemaLocation": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@type": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@referredType": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            },
            "state": "active",
            "supportingResource": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ],
            "supportingService": [
                {
                    "value": "<Circular reference to #/components/schemas/ServiceRefOrValue detected>"
                },
                {
                    "value": "<Circular reference to #/components/schemas/ServiceRefOrValue detected>"
                }
            ],
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "Excepteur est aliquip Ut"
        },
        {
            "id": "mollit eiusmod Lorem",
            "href": "dolor",
            "category": "pariatur Excepteur",
            "description": "id elit ea consequat",
            "endDate": "1951-09-27T23:31:33.770Z",
            "hasStarted": true,
            "isBundle": false,
            "isServiceEnabled": false,
            "isStateful": true,
            "name": "fugiat eu laboris labore",
            "serviceDate": "cillum",
            "serviceType": "pariatur nulla labore",
            "startDate": "1946-03-29T07:59:44.163Z",
            "startMode": "fugiat incididunt ad",
            "feature": [
                {
                    "featureCharacteristic": [
                        {
                            "name": "reprehenderit id eu",
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "id": "non sit nulla",
                            "valueType": "elit reprehenderit ",
                            "characteristicRelationship": [
                                {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            ],
                            "@baseType": "ResourceSpecification",
                            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                            "@type": "LogicalResourceSpecification"
                        }
                    ],
                    "name": "non e",
                    "id": "veniam adipisicing minim",
                    "isBundle": true,
                    "isEnabled": true,
                    "constraint": [
                        {
                            "id": "qui eiusmod enim",
                            "href": "incididunt ullamco ut",
                            "name": "occaecat ut ad",
                            "version": "deserunt occaecat Duis mollit",
                            "@baseType": "magna pariatur Lorem culpa",
                            "@schemaLocation": "https://AJUXEatPwuHydomRxfRLxWhdsdKgJiip.cysZRjSkI6epgGB0pfVUt",
                            "@type": "esse sunt eu dolor",
                            "@referredType": "minim in"
                        },
                        {
                            "id": "quis c",
                            "href": "est aute adipisicing qui eiusmod",
                            "name": "occaecat",
                            "version": "consequat cillum",
                            "@baseType": "aliquip Lorem",
                            "@schemaLocation": "http://tRs.wukhVZJPUIPSH4JQvecEmKrLfn,-AZxpAnV1ZX3IdTuCN+gUDtvkHxu0CCMk5kEIS",
                            "@type": "sed nostrud",
                            "@referredType": "culpa irure tempor"
                        }
                    ],
                    "featureRelationship": [
                        {
                            "name": "consequat sint in deserunt proident",
                            "relationshipType": "ipsum officia",
                            "id": "eu in proident fugiat",
                            "validFor": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "sit in occaecat enim ipsum",
                            "@schemaLocation": "http://coEUZeDcUOIRoPfgBZMUFolLJWB.nczXjFyf99e+A1uYmLLGAU5vUgP0tQji0eAZ",
                            "@type": "ipsum"
                        },
                        {
                            "name": "ad mo",
                            "relationshipType": "velit occaecat",
                            "id": "ut sed",
                            "validFor": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "quis dolor eiusmod",
                            "@schemaLocation": "https://PkKEZeMdqvt.bdTx2uAF7LuUTzmg5cjt3HO75CsySxQeciqE",
                            "@type": "quis non incididunt in"
                        }
                    ],
                    "@baseType": "magna",
                    "@schemaLocation": "https://LqAaRlIcitIFIpJZDJFzDeZr.doBuZ,tIYuqptwzrUzam",
                    "@type": "ea qui Duis"
                },
                {
                    "featureCharacteristic": [
                        {
                            "name": "voluptate enim id officia",
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "id": "fugi",
                            "valueType": "deserunt est",
                            "characteristicRelationship": [
                                {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            ],
                            "@baseType": "ResourceSpecification",
                            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                            "@type": "LogicalResourceSpecification"
                        }
                    ],
                    "name": "reprehenderit sit non",
                    "id": "quis",
                    "isBundle": true,
                    "isEnabled": false,
                    "constraint": [
                        {
                            "id": "ea pariatur ex",
                            "href": "enim laborum",
                            "name": "aliqua quis Duis",
                            "version": "reprehenderit aute eu sint",
                            "@baseType": "eiusmod anim amet Excepteur ut",
                            "@schemaLocation": "http://CdeHPQLHmvdtODJvIPNRStblkW.wchWCMuBicST1",
                            "@type": "est amet voluptate esse",
                            "@referredType": "ea sit aute"
                        },
                        {
                            "id": "q",
                            "href": "in deserunt",
                            "name": "dolor qui",
                            "version": "sint eiusmod Ut proident",
                            "@baseType": "qui et ad nulla deserunt",
                            "@schemaLocation": "http://QUVYMkcpClnmSQGdWOOdRrph.zvyeKr6ffmLrEPbLPEqVKP7l-UMdCu3KqB+YdHvhNQdNq7x6IMJiDQCUnHo-MkaH8naNsbuvmyV",
                            "@type": "et in",
                            "@referredType": "ut officia et"
                        }
                    ],
                    "featureRelationship": [
                        {
                            "name": "sit reprehenderit ipsum",
                            "relationshipType": "ut",
                            "id": "culpa sit esse ut velit",
                            "validFor": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "m",
                            "@schemaLocation": "https://jRpyazBHTnEoIJL.csjpziz+AzlOlq85GJ7BaxgCfAVYQoLNlA65egyZgNXKhdUhF-NZTcjIlM-iUjbYOd44v,kUK",
                            "@type": "Excepteur sit adipisicing"
                        },
                        {
                            "name": "proident ipsum tempor qui",
                            "relationshipType": "dolor reprehenderit ",
                            "id": "consectetur voluptate eiusmod in",
                            "validFor": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "eiusmod consequat Duis laboris ea",
                            "@schemaLocation": "https://GDLwDsJzyCevmAxR.lmbfbnUnInw7L73G2iph3wocgqy46zvvSwJ",
                            "@type": "adipisicing ut"
                        }
                    ],
                    "@baseType": "dolore ex aute",
                    "@schemaLocation": "http://BrIlZWWRhxdKRvsaAUwod.vimSklenmKhPdNWu.ird+6EOcMGF0CVxZw5",
                    "@type": "adipisicing ut aute consectetur"
                }
            ],
            "note": [
                {
                    "id": "ex Ut",
                    "author": "quis dolore",
                    "date": "1971-02-12T18:21:49.466Z",
                    "text": "ex",
                    "@baseType": "nulla in nisi ut",
                    "@schemaLocation": "http://giOfmYDhcAohPTNFZjnSwrxFgPGht.lpdgUAmn6qDTjBSjLBH4DH8xi+ODltSD1",
                    "@type": "laboris consectetur"
                },
                {
                    "id": "nulla magna",
                    "author": "labore in nisi",
                    "date": "1999-08-16T22:28:37.036Z",
                    "text": "ea ut",
                    "@baseType": "dolore mollit sunt ullamco",
                    "@schemaLocation": "http://RMrWQgHMHokaYlUnhKcaE.vszFx5S.3Eu,dSWfPUiosD5G5i9m0",
                    "@type": "irure fugiat ad"
                }
            ],
            "place": [
                {
                    "role": "culpa aute officia et",
                    "id": "velit",
                    "href": "veniam ut quis proident",
                    "name": "ut aliqua",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification",
                    "@referredType": "consectetur et"
                },
                {
                    "role": "minim quis",
                    "id": "consec",
                    "href": "ullamco consequat",
                    "name": "ipsum ut",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification",
                    "@referredType": "ex"
                }
            ],
            "relatedEntity": [
                {
                    "role": "ex dolor enim",
                    "id": "consequat enim mollit tempor",
                    "href": "dolor Ut eu",
                    "name": "elit magna",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification",
                    "@referredType": "reprehenderit dolor non irure"
                },
                {
                    "role": "voluptate amet consectetur",
                    "id": "occaecat proident esse",
                    "href": "consequat sunt ",
                    "name": "veniam",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification",
                    "@referredType": "cupidatat eiusmod ad Duis"
                }
            ],
            "relatedParty": [
                {
                    "@referredType": "dolore non",
                    "id": "fugiat",
                    "href": "http://QbFezgmyqoAlJhjFRPXxjmmMAamrJB.jvqnxb73zHe-s-CTPrQsDMlFf2meIHOZ4hr1vEFTMJdC",
                    "name": "ad labore aliquip",
                    "role": "in in ad",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                },
                {
                    "@referredType": "Ut ullamco aute",
                    "id": "qui anim consequat id",
                    "href": "http://ISBTVYGLCGciBlFWoSWQKZ.nyihTH4GaS38bJFoouBcwC1D+tT2",
                    "name": "reprehenderit",
                    "role": "sint proident dolor",
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                }
            ],
            "serviceCharacteristic": [
                {
                    "name": "ex occaecat veniam",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "anim elit eiusmod sunt",
                    "valueType": "velit Lorem commodo id",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                },
                {
                    "name": "Lorem quis dolor cillum",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "qui ull",
                    "valueType": "D",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "ResourceSpecification",
                    "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                    "@type": "LogicalResourceSpecification"
                }
            ],
            "serviceOrderItem": [
                {
                    "itemId": "dolore exercitation",
                    "serviceOrderId": "dolore nisi occaecat voluptate",
                    "role": "laboris culpa do",
                    "serviceOrderHref": "consequat",
                    "itemAction": "noChange",
                    "@baseType": "cupidatat sint est enim",
                    "@schemaLocation": "https://AmGZNnOQmWzJMFkPkxM.yrnyzJD71N1EimpB-peQ83n3fofXmbkO8eCH6tMxOLNkZyWc-s.39",
                    "@type": "mollit eiusmod",
                    "@referredType": "anim Ut eiusmod"
                },
                {
                    "itemId": "officia occaecat est anim sint",
                    "serviceOrderId": "ut amet exercitation velit",
                    "role": "enim consequat incididunt",
                    "serviceOrderHref": "eiusmod Ut ex",
                    "itemAction": "modify",
                    "@baseType": "veniam et",
                    "@schemaLocation": "https://qWXKevsanIR.ghfu.9",
                    "@type": "ea Ut amet in",
                    "@referredType": "esse non ut"
                }
            ],
            "serviceRelationship": [
                {
                    "value": "<Circular reference to #/components/schemas/ServiceRelationship detected>"
                },
                {
                    "value": "<Circular reference to #/components/schemas/ServiceRelationship detected>"
                }
            ],
            "serviceSpecification": {
                "id": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "href": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "name": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "version": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@baseType": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@schemaLocation": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@type": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@referredType": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            },
            "state": "reserved",
            "supportingResource": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ],
            "supportingService": [
                {
                    "value": "<Circular reference to #/components/schemas/ServiceRefOrValue detected>"
                },
                {
                    "value": "<Circular reference to #/components/schemas/ServiceRefOrValue detected>"
                }
            ],
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "esse enim ut laborum"
        }
    ],
    "@baseType": "non aliquip enim",
    "@schemaLocation": "https://aBSHdLvXZBqPyzbHAiuzhOvkjIEtPS.czp",
    "@type": "dolor ad irure"
})



