#!/usr/bin/env dothttp

# imported from 35240-da56505c-d9c4-439c-8d65-62c4dc15cbbc.postman_collection.json

// returns the total alltime video views for a video 

@name("Get Alltime Video Views")
GET "https://{{baseUrl}}/alltime/accounts/:account_id/videos/:video_id"



