#!/usr/bin/env dothttp

# imported from 35240-653858f4-3b7e-41be-b58d-dfd2923d60bc.postman_collection.json

// What is being API-first about, and how can business users be putting APIs to work even if they do not have programming skills.

@name("What")
GET "https://{{baseUrl}}/business/what/"


// Helping business users understand why APIs matter, elevating them out of something that is abstract and technical.

@name("Why")
GET "https://{{baseUrl}}/business/why/"



