#!/usr/bin/env dothttp

# imported from 35240-eabc5422-b0c4-42fc-9bd9-335695a573f1.postman_collection.json

@name("Provides the seasons for a given Tournament")
GET "https://{{baseUrl}}/tournaments/:tournament_id/seasons{{format}}"


// Provides a list of Competitors from a given Tournament

@name("Provides a list of Competitors from a given Tourna...")
GET "https://{{baseUrl}}/tournaments/:tournament_id/info{{format}}"


// Provides the live standings for a given Tournament

@name("Provides the live standings for a given Tournament...")
GET "https://{{baseUrl}}/tournaments/:tournament_id/live_standings{{format}}"


@name("Provides the results for a given tournament")
GET "https://{{baseUrl}}/tournaments/:tournament_id/results{{format}}"


@name("Provides the schedule for a given Tournament")
GET "https://{{baseUrl}}/tournaments/:tournament_id/schedule{{format}}"


@name("Provides the standings for a given Tournament")
GET "https://{{baseUrl}}/tournaments/:tournament_id/standings{{format}}"



