#!/usr/bin/env dothttp

# imported from 35240-bc9332c4-d7ba-4398-b9a9-51c6aaf5271c.postman_collection.json

// List all topics

@name("Get Topics")
GET "https://{{baseUrl}}/topics/"
? "page"= "<string>"
? "page_size"= "<string>"


// Delete a given topic

@name("Delete Topics Topic")
DELETE "https://{{baseUrl}}/topics/:topic/"



