#!/usr/bin/env dothttp

# imported from 35240-39359504-af25-4f48-954b-e7dd332ed9ff.postman_collection.json

// Request rate limited to 10 requests per second with bursts up to 100 requests.

@name("Return the current status code of an invoice.")
GET "https://{{baseUrl}}/api/v1/Invoices/:LogicbrokerKey/Status"


// Request rate limited to 10 requests per second with bursts up to 100 requests.

@name("Updates an invoice to the specified status.")
PUT "https://{{baseUrl}}/api/v1/Invoices/:LogicbrokerKey/Status/:Status"



