#!/usr/bin/env dothttp

# imported from 35240-aa655ea0-f6d4-4615-b1ce-a1873e7cfc4c.postman_collection.json

// Returns an author that has written content available via this API.

@name("Author")
GET "https://{{baseUrl}}/author/"
? "access_key"= "<>"



