#!/usr/bin/env dothttp

# imported from 35240-c446a4c9-8dd6-45c4-99f2-688a96fe76ae.postman_collection.json

@name("List milestones")
GET "https://{{baseUrl}}/repos/:owner/:repo/milestones"
? "state"= "open"
? "sort"= "due_on"
? "direction"= "asc"
? "per_page"= "30"
? "page"= "1"


@name("Create a milestone")
POST "https://{{baseUrl}}/repos/:owner/:repo/milestones"
"Content-Type": "application/json"
json({
    "title": "<string>",
    "state": "open",
    "description": "<string>",
    "due_on": "<string>"
})



