#!/usr/bin/env dothttp

# imported from 35240-bc8d9c7b-dc78-4184-9dd2-6a17c992a9c5.postman_collection.json

// This operation list or find ServiceTestSpecification entities

@name("List or find ServiceTestSpecification objects")
GET "https://{{baseUrl}}/serviceTestSpecification"
? "fields"= "ad in"
? "offset"= "-16358088"
? "limit"= "-16358088"


// This operation creates a ServiceTestSpecification entity.

@name("Creates a ServiceTestSpecification")
POST "https://{{baseUrl}}/serviceTestSpecification"
"Content-Type": "application/json;charset=utf-8"
json({
    "name": "nisi pariatur reprehenderit",
    "relatedServiceSpecification": [
        {
            "id": "id ci",
            "href": "http://EHMtrhNNaekq.quqtJLwynRhypydaaBEeUYBccDt.kVHS+u4GdQgTDa9Yam",
            "name": "aute elit",
            "version": "dolore nulla elit amet officia",
            "@baseType": "eiusmod culpa",
            "@schemaLocation": "http://gHBJn.jungcFa1w4dRvU6ml5+ZiTkGx4CmtOAUdNA0d5GBnF-8R..q98xjZ.H2Bw.XiM",
            "@type": "Duis",
            "@referredType": "ut ut nisi tempor"
        }
    ],
    "description": "laboris incididunt dolore dolor",
    "isBundle": false,
    "lastUpdate": "1974-12-29T05:46:19.868Z",
    "lifecycleStatus": "laboris nisi in",
    "version": "do nisi ad sed",
    "attachment": [
        {
            "id": "4aafacbd-11ff-4dc8-b445-305f2215715f",
            "href": "http://host/Attachment/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "attachmentType": "video",
            "content": "cillum dolore elit",
            "description": "Photograph of the Product",
            "mimeType": "deserunt",
            "name": "anim fugiat nulla",
            "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "size": {
                "amount": 1,
                "units": "aute eiusmod pariatur"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "veniam culpa eiusmod",
            "@schemaLocation": "http://JpxUMTwoGaNebBTW.owyCRrFYfrsAqMmHP3NpW3RWuZvL7DaQO8oadzi,srEnI",
            "@type": "occaecat cillum in ut",
            "@referredType": "commodo irure non proident"
        },
        {
            "id": "4aafacbd-11ff-4dc8-b445-305f2215715f",
            "href": "http://host/Attachment/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "attachmentType": "video",
            "content": "minim ut",
            "description": "Photograph of the Product",
            "mimeType": "esse",
            "name": "nisi non cupidatat est",
            "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "size": {
                "amount": 1,
                "units": "consequat"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "laborum exercitation ipsum sint",
            "@schemaLocation": "https://NESBooQ.mwkvAfPsl3YyXFRtDG6YkRZMiEFQqyvJBjW,pp5fnivfTkxPMN9JYn2RaXw5o",
            "@type": "Lorem in in commodo",
            "@referredType": "nulla ut"
        }
    ],
    "constraint": [
        {
            "id": "voluptate est pariatur",
            "href": "https://rzoyJFCvILmFNbdZXoEFgXaiwzVDXy.qtolrn8jEF0D3zfuGnFnn0Ya0s",
            "name": "pariatur magna enim",
            "version": "sunt dolor qui aliquip",
            "@baseType": "tempor magna",
            "@schemaLocation": "http://eIytEdjtgiRDTJ.jtd77uCCEHTtyJZIEJ5",
            "@type": "sit minim do ipsum",
            "@referredType": "Lorem minim exercitation deserunt in"
        },
        {
            "id": "dolor et eu laborum ipsum",
            "href": "https://fiCwlIzjFimEEDLKbfiDVfHMHe.odmw",
            "name": "consectetur tempor non",
            "version": "in occaecat ad enim consequat",
            "@baseType": "commodo ad cillum",
            "@schemaLocation": "https://xJpGhWRqlUyWbUXYqKMRTbMsBdTMfc.jraelqcPqd-TcOYOBx7bueqxLAkc2BNqrHkrJFAMmFOG",
            "@type": "qui",
            "@referredType": "in aliqua"
        }
    ],
    "entitySpecRelationship": [
        {
            "relationshipType": "dolor proident nulla in velit",
            "id": "occaecat labore commodo",
            "href": "https://ErlTPtCgZUrPctVmZUTtBtsdoXMKVd.oyHQ0mfjEy2UfK",
            "name": "reprehenderit ea dolore aute",
            "role": "in est Lorem veniam minim",
            "associationSpec": {
                "id": "enim",
                "href": "http://laVsZjYOdSxiaMIuFvIBbPdF.mzbxWpSfkyjfwWssfsw,vfoN1VGptuh62BUH+",
                "name": "reprehenderit id",
                "@baseType": "Duis ad",
                "@schemaLocation": "https://iLgDlNE.wtiW,kpnahM35yJKYvFe+wMs6auJ1YpOXAet4FtxGCw2deZ2J",
                "@type": "enim non sint",
                "@referredType": "deserunt reprehenderit culpa"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "ea cillum in anim dolor",
            "@schemaLocation": "https://YHjynZBAxridBvLrUXj.mreQD-FW3.lg",
            "@type": "ea",
            "@referredType": "adipisicing ipsum"
        },
        {
            "relationshipType": "dolor nostrud",
            "id": "consectetur laborum",
            "href": "https://bjEyfhDQQTPUEQqWszsTkCKibBnYVqR.hrWBZ,QtW",
            "name": "cillum Ut",
            "role": "nulla eiusmod",
            "associationSpec": {
                "id": "exercit",
                "href": "http://CnKIkKaOntDDPbOGLT.jiBZy.klWrtxJPMqwuv,.lktCxNmuOl2pTIM.S",
                "name": "ulla",
                "@baseType": "cupidatat",
                "@schemaLocation": "http://gYaCThlvIcMdWhHMzaJwrsI.dyd59SwAepV1aj3ow6Veqvs",
                "@type": "id et consequat",
                "@referredType": "dolor laborum n"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "reprehenderit anim sit",
            "@schemaLocation": "https://tyvGwlLAoQcrlKLSpAVzLzWjyKgapL.seCW,baO7Yt1H0wQC7Bzza5FdLQOnM3AO831h9RTZ",
            "@type": "eni",
            "@referredType": "quis Ut"
        }
    ],
    "relatedParty": [
        {
            "@referredType": "aliquip sint",
            "id": "in ",
            "href": "http://mVQarxMhs.wqfW3ZBHutENQLMNQTASK1EPj",
            "name": "pariatur Ut",
            "role": "adipisicing cupi",
            "@baseType": "Exc",
            "@schemaLocation": "http://nxIOREmRQPTRjxyvtpUpIpEaVf.nzsxEgYp5wJ2C",
            "@type": "nisi reprehenderit qui do"
        },
        {
            "@referredType": "ad ipsum",
            "id": "consequat",
            "href": "http://B.opC-d4U3m9A7A",
            "name": "incididunt sunt labore Ut quis",
            "role": "dolore ea cillum",
            "@baseType": "amet non ut",
            "@schemaLocation": "http://YuLggrR.xpyLTrdC255xGRUhGqkWz7QnlOSy51oU.JSgCgT-ItgOCv,055uE",
            "@type": "dolor aute in cupidatat"
        }
    ],
    "serviceTestSpecRelationship": [
        {
            "relationshipType": "in aliquip dolor labore nulla",
            "id": "dolor non eu aute",
            "href": "https://AWWZmHBFUfyXZshf.esfNw0nTR5+OX3bMj5iN1jkVatLdVC3fh5BZNHQE54",
            "name": "anim mollit irure",
            "role": "commodo dolor al",
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "enim",
            "@schemaLocation": "http://KoVqhygMSdObsUOJUn.ifeuJx2P,jo,PlOOnfw50qReA",
            "@type": "eu nisi dolor",
            "@referredType": "Ut nostrud ut mollit"
        },
        {
            "relationshipType": "minim dolor incididunt labore ipsum",
            "id": "occaecat aliqua",
            "href": "https://cmditBYOBdcgKNUjfcPeREEfSWoSKzINt.osxrsd3x2wDMTFW.hWyuDwH9yoBSpYrU",
            "name": "tempor",
            "role": "eu",
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "ut amet",
            "@schemaLocation": "http://XigNdgLSSgopsqMQlqvkmcvTzSIsjRy.iryeQlMgYAKJlVuzwHUwm0LNh1E+QAWTkEbQSAwb7lRfD7,qjS5VYEzKZgU9due",
            "@type": "magna occaecat aliqua",
            "@referredType": "labore Duis dolor in"
        }
    ],
    "specCharacteristic": [
        {
            "id": "aliquip officia dolor",
            "configurable": false,
            "description": "labore dolore esse ut veniam",
            "extensible": true,
            "isUnique": false,
            "maxCardinality": -4206018,
            "minCardinality": 55886853,
            "name": "dolor in",
            "regex": "dolor fugiat",
            "valueType": "eu consectetur veniam aliqu",
            "charSpecRelationship": [
                {
                    "characteristicSpecificationId": "Excepteur Duis et",
                    "name": "incididunt i",
                    "parentSpecificationHref": "http://psPnthPJJIhipEXui.vyrU7oLX5cfvQpaBu",
                    "parentSpecificationId": "non fugiat cillum",
                    "relationshipType": "commodo officia in",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "mollit commodo",
                    "@schemaLocation": "https://ZMBrfLzKAUExMKWTIFVRTmEbIOLZG.suegGTLneInlp89qRrH8musaeR6QtImzsQYI+EKfCA",
                    "@type": "aute enim dolor"
                },
                {
                    "characteristicSpecificationId": "elit quis officia ut minim",
                    "name": "fugiat aliqua sunt sint aliquip",
                    "parentSpecificationHref": "https://xBjcnLKYQluWLLWA.ewpxLRjWWG76oVYZABiFslLUKcAJoRbAUynk6P2phFCY9b0pLtlXU,ud",
                    "parentSpecificationId": "ut aliquip quis cillum enim",
                    "relationshipType": "adipisicing amet in ut veniam",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "laboris ad labore",
                    "@schemaLocation": "http://iPMiMIGLoRUyAEDnhremgKhTe.yjzqNZ53MGG8eTG1gil6FxA4OGaMKDqoX+llOq,MrSTmdRjM",
                    "@type": "elit labore exercitation consectetur"
                }
            ],
            "characteristicValueSpecification": [
                {
                    "isDefault": false,
                    "rangeInterval": "cillum irure laborum",
                    "regex": "magna ullamco cupidatat esse",
                    "unitOfMeasure": "aute dolor ut occaecat",
                    "valueFrom": 85987298,
                    "valueTo": 99010842,
                    "valueType": "Duis aute exercitation adipisici",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "value": {},
                    "@baseType": "Excepteur commodo Lorem",
                    "@schemaLocation": "https://OcsMxAHTxCLOdGERtWQolkRdTpOoDu.wmDjFTjVSuFBNBmrZU6wvA2U7+3y1,",
                    "@type": "cillum"
                },
                {
                    "isDefault": true,
                    "rangeInterval": "sed laboris irure",
                    "regex": "in",
                    "unitOfMeasure": "consequat reprehenderit",
                    "valueFrom": -98696817,
                    "valueTo": -32429182,
                    "valueType": "pariatur quis amet",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "value": {},
                    "@baseType": "esse ad",
                    "@schemaLocation": "http://ZgVZVUsnTpGcEFFECUOpWgr.lhisz+D1WFbEtEHDMbTyWSDjm3O84-au+Ql+Karjznv0",
                    "@type": "amet sunt minim quis enim"
                }
            ],
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "dolor laboris voluptate",
            "@schemaLocation": "http://uDrsCTlAulQOfGsBHThNydBzjUm.prkKFd54m362r-P4wcXsddJ+nqKKKPeeDNGny++aEeKjHXMoMLeq5x",
            "@type": "ex",
            "@valueSchemaLocation": "irure eiusmod"
        },
        {
            "id": "ea in sint",
            "configurable": false,
            "description": "non velit ex",
            "extensible": true,
            "isUnique": false,
            "maxCardinality": -21530436,
            "minCardinality": -45981479,
            "name": "culpa laboris eu Ut",
            "regex": "fugiat",
            "valueType": "id",
            "charSpecRelationship": [
                {
                    "characteristicSpecificationId": "Ut",
                    "name": "esse magna culpa qui",
                    "parentSpecificationHref": "http://lofXhdDhxMbp.kglTBq+bzjptK4uHme++63eQLcKKp7CgaFEwelfrkj0Jintm6aDb0M",
                    "parentSpecificationId": "et esse dolor veniam",
                    "relationshipType": "exercitation nulla",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "enim amet irure",
                    "@schemaLocation": "http://cYPojASVPIXFkxWiKQv.yeRzUN4KmtyJGOFQUFoisHeEJe0JF8QtQzUeYzseBBcggnK8L3XnL6,X5aososxlmd",
                    "@type": "fugiat pariatur ut exercitation ea"
                },
                {
                    "characteristicSpecificationId": "in laboris sint",
                    "name": "deserunt aliquip in in",
                    "parentSpecificationHref": "http://In.nvhrd,+GqjvRAMecbHIQhmP8zi3nNvQB4l.qdGxb9j2gqo4fmBd6TF9M9uODl-NEzMjj",
                    "parentSpecificationId": "Ut consequat amet",
                    "relationshipType": "qui dolore sed",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "laborum dolore amet minim anim",
                    "@schemaLocation": "https://dCqRGsP.xgSzlJ8Wo-peZXnrN08bk.",
                    "@type": "in fugiat magna"
                }
            ],
            "characteristicValueSpecification": [
                {
                    "isDefault": false,
                    "rangeInterval": "qui",
                    "regex": "velit dolore",
                    "unitOfMeasure": "id culpa nostrud",
                    "valueFrom": -12039680,
                    "valueTo": 22571381,
                    "valueType": "consequat dolor laboris cupidatat",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "value": {},
                    "@baseType": "aliquip quis",
                    "@schemaLocation": "https://nAEYoNxTQsivFxYOFZRZiz.yucreBP7PiT2CeeBFW5SYBIwNWkdsDD37JqaJRBuLK4SnbL0rR7KI",
                    "@type": "ullamco mollit esse"
                },
                {
                    "isDefault": true,
                    "rangeInterval": "cupidatat proident",
                    "regex": "ut quis deserunt exercitation dolor",
                    "unitOfMeasure": "quis",
                    "valueFrom": 99361933,
                    "valueTo": 85621703,
                    "valueType": "magna nostrud",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "value": {},
                    "@baseType": "cupidatat sit elit",
                    "@schemaLocation": "http://yEURkWbEPPBEUyaamaBFEiLHbNZGyK.ijCm2KIunci0fIh3pKKlmWfZDjZ38.tXYBQG3GTsctEV.EN2LItYa5E",
                    "@type": "dolor"
                }
            ],
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "esse et mollit id",
            "@schemaLocation": "http://DIjkOPh.kepcupLYxD9",
            "@type": "qui magna ipsum consectetur",
            "@valueSchemaLocation": "nulla sit"
        }
    ],
    "targetEntitySchema": {
        "@schemaLocation": "cillum Duis officia incididunt",
        "@type": "officia in proident"
    },
    "testMeasureDefinition": [
        {
            "captureFrequency": "",
            "captureMethod": "nisi",
            "metricDescription": "nostrud sit ",
            "metricHref": "adipisicin",
            "metricName": "cupidatat non ad est Lorem",
            "name": "nisi aliqua consequat dol",
            "unitOfMeasure": "cupidatat qui ullamco ad",
            "valueType": "anim ex eu",
            "capturePeriod": {
                "amount": 38638394,
                "units": "Ut exercitation anim do"
            },
            "thresholdRule": [
                {
                    "conformanceComparatorLower": "non elit nisi magna",
                    "conformanceComparatorUpper": "ipsum ea",
                    "conformanceTargetExact": "dolor quis",
                    "conformanceTargetLower": "Ut officia",
                    "conformanceTargetUpper": "dolor",
                    "description": "velit consectetur ipsum Excepteur",
                    "name": "veniam laborum",
                    "numberOfAllowedCrossing": -554458,
                    "thresholdRuleSeverity": "magna commodo",
                    "consequence": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "tolerancePeriod": {
                        "amount": -81918264,
                        "units": "cillum ut elit"
                    },
                    "@baseType": "eu minim",
                    "@schemaLocation": "https://xrlgOSdekheBMREzSjIvpBvluAxtQu.jmbafW6JdYPtH-LwIlrH",
                    "@type": "fugiat ea dolore laboris"
                },
                {
                    "conformanceComparatorLower": "sit esse",
                    "conformanceComparatorUpper": "incididunt ut quis sed",
                    "conformanceTargetExact": "dolor cillum",
                    "conformanceTargetLower": "esse do",
                    "conformanceTargetUpper": "non Duis in eiusmod",
                    "description": "nostrud in",
                    "name": "quis nostrud fugiat",
                    "numberOfAllowedCrossing": 66183617,
                    "thresholdRuleSeverity": "cupidatat id aliquip irure Excepteur",
                    "consequence": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "tolerancePeriod": {
                        "amount": -91365780,
                        "units": "occaecat aliquip"
                    },
                    "@baseType": "culpa veniam amet",
                    "@schemaLocation": "http://nWCkWDxUUywGZchhfwMHosVIBcGT.mrmqlsF8YlZRrQ,2mps-ZnZGtYg-oFE2wg-JZvsRMvX0QCyvGSi",
                    "@type": "dolore incididunt"
                }
            ],
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "ipsum",
            "@schemaLocation": "https://LkKMcBTHTSHpWXRLdTtVsLFyYuLXRzGp.gwfsxheO62daKAfhNGA7qXrTf9L4SG3OvlOepK.FZgp+kbbMnq",
            "@type": "tempor non dolore sint"
        },
        {
            "captureFrequency": "Ut ut",
            "captureMethod": "in tempor si",
            "metricDescription": "sint in aliqua mollit",
            "metricHref": "et consectetur quis",
            "metricName": "sed com",
            "name": "dolor",
            "unitOfMeasure": "enim ea magna",
            "valueType": "dolor ipsum",
            "capturePeriod": {
                "amount": -21830809,
                "units": "officia"
            },
            "thresholdRule": [
                {
                    "conformanceComparatorLower": "officia Duis sunt occaecat",
                    "conformanceComparatorUpper": "laboris tempor dolor consectetur",
                    "conformanceTargetExact": "id u",
                    "conformanceTargetLower": "officia Lorem ad consectetur in",
                    "conformanceTargetUpper": "nulla veniam",
                    "description": "ipsum ut Excepteur dolor consectetur",
                    "name": "sed velit dolor Excepteur",
                    "numberOfAllowedCrossing": -95102287,
                    "thresholdRuleSeverity": "minim sunt",
                    "consequence": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "tolerancePeriod": {
                        "amount": -59392303,
                        "units": "laboris dolore eiusmod Duis occaecat"
                    },
                    "@baseType": "eiusmod nostrud tempor voluptate",
                    "@schemaLocation": "https://TbsqKQ.xiMQ-k4oJHhbPAV5x.kPj46k5RDhvfjvxCLBvBHhDMxJRG",
                    "@type": "sint"
                },
                {
                    "conformanceComparatorLower": "sint fugiat",
                    "conformanceComparatorUpper": "incididunt magna",
                    "conformanceTargetExact": "enim mollit quis nisi",
                    "conformanceTargetLower": "officia Lorem magna",
                    "conformanceTargetUpper": "aute exercitation cillum sed do",
                    "description": "Excepteur pariatur nulla esse",
                    "name": "nulla deserunt lab",
                    "numberOfAllowedCrossing": -80243348,
                    "thresholdRuleSeverity": "dolor qui ",
                    "consequence": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "tolerancePeriod": {
                        "amount": -1960262,
                        "units": "ci"
                    },
                    "@baseType": "dolor",
                    "@schemaLocation": "https://onKuGdXZEgfTMsDJcVcCU.mydyRMB.SfQD.ELGY9HzdCAktqSXvbBGjA.snXmG",
                    "@type": "amet est"
                }
            ],
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "commodo est culpa id laboris",
            "@schemaLocation": "http://vpfZfaKxIDFBJnIbslvacPouigF.wzlg4WTLz83wPzN3m4LjlgddqzcOWZ6H43tsdP9GMuLi2ujv,4S-vxTnlIzoLGod6FOV",
            "@type": "ea sed Ut exercitation cupidatat"
        }
    ],
    "validFor": {
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z"
    },
    "@baseType": "ea et nulla",
    "@schemaLocation": "https://jpvm.yustV3vWfX1udraO0U4-4hIiwfyUuiizQHgPEfrEIUZ,es,p4fPi.qE",
    "@type": "quis eiusmod et"
})



