#!/usr/bin/env dothttp

# imported from 35240-cc40b3de-1093-44e1-94c4-498c2fe3c9bb.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"
basicauth("{{atlassian_email}}", "{{atlassian_token}}")


// Returns a [paginated](#pagination) list of all field configurations.
// 
// Only field configurations used in classic projects are returned.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Get All Field Configurations") : "base-inherit-auth"
GET "https://{{baseUrl}}/rest/api/3/fieldconfiguration"
? "startAt"= "0"
? "maxResults"= "50"
? "id"= "<long>"
? "isDefault"= "false"


// Returns a [paginated](#pagination) list of all fields for a configuration.
// 
// Only the fields from configurations used in classic projects are returned.
// 
// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).

@name("Get Field Configuration Items") : "base-inherit-auth"
GET "https://{{baseUrl}}/rest/api/3/fieldconfiguration/:id/fields"
? "startAt"= "0"
? "maxResults"= "50"



