#!/usr/bin/env dothttp

# imported from 35240-dd5960a5-2c65-4b02-9725-60e805efed1f.postman_collection.json

// Provides the registrar, IP and name server history for a domain name

@name("Domain History")
GET "https://{{baseUrl}}/:domain/hosting-history/"



