#!/usr/bin/env dothttp

# imported from 35240-4d2eb79d-4cff-4c67-86d1-40ed00bf1510.postman_collection.json

// The upload attachment command is used to upload an attachment for sending.  

@name("Upload Attachment")
GET "https://{{baseUrl}}/attachments/upload/"
? "api_key"= "<>"
? "file"= "<>"
? "username"= "<>"



