#!/usr/bin/env dothttp

# imported from 35240-3de643e0-77af-41e6-9270-0b386f4ca61d.postman_collection.json

// Used to create new and read existing statement exports. Statement exports can be created in either CSV, MT940 or PDF file format.

@name("List all Customer Statement for User Monetary Account")
GET "https://{{baseUrl}}/user/:userID/monetary-account/:monetary-accountID/customer-statement"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"


// Used to create new and read existing statement exports. Statement exports can be created in either CSV, MT940 or PDF file format.

@name("CREATE Customer Statement for User Monetary Account")
POST "https://{{baseUrl}}/user/:userID/monetary-account/:monetary-accountID/customer-statement"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"
"Content-Type": "application/json"
json({
    "statement_format": "<string>",
    "date_start": "<string>",
    "date_end": "<string>",
    "include_attachment": "<boolean>",
    "regional_format": "<string>"
})


// Fetch the raw content of a statement export. The returned file format could be MT940, CSV or PDF depending on the statement format specified during the statement creation. The doc won't display the response of a request to get the content of a statement export.

@name("List all Content for User Monetary Account Customer Statement")
GET "https://{{baseUrl}}/user/:userID/monetary-account/:monetary-accountID/customer-statement/:customer-statementID/content"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"



