#!/usr/bin/env dothttp

# imported from 35240-a496d7b6-180f-456c-ac3d-540e777764e6.postman_collection.json

// This operation list or find Topic entities

@name("List or find Topic objects")
GET "https://{{baseUrl}}/topic"
? "fields"= "Excepteur vo"
? "offset"= "-96743296"
? "limit"= "-96743296"


// This operation creates a Topic entity.

@name("Creates a Topic")
POST "https://{{baseUrl}}/topic"
"Content-Type": "application/json;charset=utf-8"
json({
    "contentQuery": "ea tempor elit",
    "headerQuery": "occaecat labore",
    "name": "do Ut",
    "@baseType": "enim exe",
    "@schemaLocation": "https://jh.zhkN0ba,oehrKiOyT8NUPFO1im9ybQarsga",
    "@type": "c"
})



