#!/usr/bin/env dothttp

# imported from 35240-4ff70fc9-8539-43e5-b513-382f49f2c6a5.postman_collection.json

// This operation list or find TestCaseExecution entities

@name("List or find TestCaseExecution objects")
GET "https://{{baseUrl}}/testCaseExecution"
? "fields"= "ex aute dolore dolore"
? "offset"= "-66922574"
? "limit"= "-66922574"


// This operation creates a TestCaseExecution entity.

@name("Creates a TestCaseExecution")
POST "https://{{baseUrl}}/testCaseExecution"
"Content-Type": "application/json;charset=utf-8"
json({
    "testEnvironmentProvisioningExecution": {
        "testEnvironmentAllocationExecution": {
            "resourceManagerUrl": "https://myserver.com/resourceManager",
            "id": "voluptate dolor proident",
            "href": "https://KRqFnUM.zdqM1",
            "dataCorrelationId": "aac9969d-219d-4ff1-b256-1765dcf9b342",
            "abstractEnvironment": {
                "id": "ad ea",
                "href": "http://PyaJhQGooigpYkHXOzXHIQ.hjbkVawBh5kd-ETbvAoP6dyCXR0cAjD",
                "name": "officia do",
                "@baseType": "in Duis adipisicing officia",
                "@schemaLocation": "https://UEbwHBrPSziFKuHBBpndPO.wbdCUR.D17TVw3N5Qt8nWlSa-tbicMiQ",
                "@type": "reprehenderit est",
                "@referredType": "tempor aliquip mollit Ut"
            },
            "concreteResourceMapping": [
                {
                    "id": "anim esse qui proident laboris",
                    "href": "http://WvtkSJFOtuJbgMKPfY.hsrj5E9B",
                    "abstractResource": "phone",
                    "concreteResource": [
                        {
                            "name": "iPhone_1289",
                            "id": "occaecat ullamco sit elit",
                            "href": "http://gOAkEBhIfFnoapbbPGupkp.ioaXHPBXycPXQEs7Z4oTzglI+9qZ5KSbpqKOQ-cg9xjmKAZbNIqei0SIInh",
                            "@baseType": "nisi culpa Lorem irure aliqua",
                            "@schemaLocation": "https://CvhakSKhm.faZ72ax1AMVh-g8D3OJ85snAnkVQ1fJ-n9mJTPYsuNEDL9FIe1pjsBvwXPcNx40",
                            "@type": "non occaecat amet incididunt laboris"
                        },
                        {
                            "name": "iPhone_1289",
                            "id": "veniam est ut",
                            "href": "https://uYUmdoXzNfcBKKqzvOY.wogvaYHR15aXjM",
                            "@baseType": "culpa sit laborum commodo",
                            "@schemaLocation": "https://VlWXHFIdwffxqrgYUjTjrJAukF.febtMH",
                            "@type": "ut cillum anim"
                        }
                    ],
                    "@baseType": "elit enim Duis nostrud",
                    "@schemaLocation": "http://YkfFqmZfkRqvG.xucwnufx2Rf0R2sQ4WWzNLiG3j05-xQDm59,.",
                    "@type": "est"
                },
                {
                    "id": "et",
                    "href": "http://WypmCWaylzdpSxpmjAHEnXjIysrAwPRO.arKqD+9TgoHZmuWpVGTdekcrwZg,Wmpec4a",
                    "abstractResource": "phone",
                    "concreteResource": [
                        {
                            "name": "iPhone_1289",
                            "id": "consectetur t",
                            "href": "http://GjPEhZoWFKFoTZALWWsBnkDAkYTjNDG.azvdmLt9abUfUChPETFDnoLvNvBuXjMc+E",
                            "@baseType": "est dolore esse",
                            "@schemaLocation": "https://PONGGSOJiy.qllqVSzjK",
                            "@type": "ea commodo proident"
                        },
                        {
                            "name": "iPhone_1289",
                            "id": "est Ut",
                            "href": "http://wycsbkxVesfTWYvSKt.ncO9VpMUV+J2Xa.mUZdJ2h+IM1n8uKYo-dgnnmH+rwH-q.UnrI+",
                            "@baseType": "exercitation dolore veniam consequat",
                            "@schemaLocation": "http://Vwouvs.djYCqlrhimz9o0N3Ye2Cj.Z2LMNKw5OJvBoG.DkwsP3YBUGfUPM.lQNcegpKMW2GYhBLjA",
                            "@type": "dolore et"
                        }
                    ],
                    "@baseType": "ullamco minim ex",
                    "@schemaLocation": "http://meSABYMwIzjANloXMryDqyCKSXGC.bejzreZi.9c5qoKs57,iY-kLws4Wypt2NwHUTsajsn0Fv1PCTXe",
                    "@type": "id fugiat nulla do"
                }
            ],
            "generalTestArtifact": [
                {
                    "id": "dolor aliqua sunt",
                    "href": "https://JOSTTcqrpD.cgibOV.dJ",
                    "name": "Excepteur veniam enim",
                    "@baseType": "nostrud irure minim et",
                    "@schemaLocation": "http://QHnDwPtnGwytpyFDtWrQAbvrD.eolhlYTJVNa+AAFskjfRY,mHV+NAka-iCU3xQvXncxI",
                    "@type": "esse sunt dolor",
                    "@referredType": "minim et consequa"
                },
                {
                    "id": "tempor ullamco",
                    "href": "https://hqVTwFgOHS.begyHLR1weLs+puSqx2BcVsU3B9J0vPUvGTUvOGm",
                    "name": "sed ea fugiat ipsum",
                    "@baseType": "ipsum in",
                    "@schemaLocation": "http://wMqhEFEpTAirbJhVRCdrtLlt.ufukp0LODvoIztwns1F",
                    "@type": "occaecat elit",
                    "@referredType": "eu non tempor velit Ut"
                }
            ],
            "state": "inProgress",
            "testScenario": {
                "id": "anim",
                "href": "http://HWTqiSmpxQIYtvy.mkawyMR2l,.AWO+vKQD0f5.HnMQlRF5aJ1NfPbqVWn,Y.nBLNdvB5YQNmNHaq2+npuMwYH",
                "name": "magna cupidatat occaecat",
                "@baseType": "ut Excepteur nulla",
                "@schemaLocation": "https://qHGzMJwiXbkXyXrkGOEKhspZbvXb.snxqOFgCXogYkb5RGYceC",
                "@type": "eiusmod in",
                "@referredType": "sit Lorem an"
            },
            "@baseType": "eiusmod enim voluptate elit Ut",
            "@schemaLocation": "https://iijIZIuRQAvhlr.ilqxPhFCDQ",
            "@type": "ut cillum occaecat"
        },
        "id": "consequat fugiat nostrud",
        "href": "https://rZikDanGViOqZBaI.hjexxVmlvBICDYXnw+kIFN-6JFFbl2LdYMJ8cvT8y+ItwTcZEDHECfPNgFzGT8S",
        "dataCorrelationId": "aac9969d-219d-4ff1-b256-1765dcf9b342",
        "generalTestArtifact": [
            {
                "id": "Duis deserunt consect",
                "href": "https://XDlsIQkO.bhiKFNPxbwwdy,nVZXTcbiOgsgZdL950sPqWJAAmYmkuioF+jL5Hy2a+F",
                "name": "sit ut",
                "@baseType": "Excepteur elit",
                "@schemaLocation": "https://lsFlcnLJCnLvqe.pqYFViiq87S.4",
                "@type": "culpa amet adipisicing Lorem consectetur",
                "@referredType": "consectetur aute"
            },
            {
                "id": "officia nostrud",
                "href": "https://lPSumFtSwlNZfchdbNfHppxXLFJK.dozpTMO+7BCvYu1J9WNHSp9btE3ufcg2AE0rGbsEtUYcNS6q3d3XZfkQXTJlX",
                "name": "elit ipsum deserunt",
                "@baseType": "in dolor",
                "@schemaLocation": "http://IWtUdFewTSdJhVAGZBixczokR.tcqaYXyKLtyWICUjFsECgUQgX4Y88J7XpFsTFCnTjWbU1d+QozFGdEF",
                "@type": "ex id",
                "@referredType": "sed culpa"
            }
        ],
        "provisioningArtifact": [
            {
                "id": "officia exercitation consequat",
                "href": "https://RTeZNfWjMqD.nbiW7klezsTaHqyH5feBOzgAsGOQayzLYT30QceAw6nA5NCAjY8N-L",
                "name": "pariatur magna laborum",
                "@baseType": "deserunt fugiat",
                "@schemaLocation": "http://UxvWHCAFxkiBVAvkT.yinxQvZ8",
                "@type": "ad aliqua mollit",
                "@referredType": "ut nisi occaecat"
            },
            {
                "id": "ut in",
                "href": "https://eHNKNDwuQlYaoDTCT.podUSvsLF",
                "name": "fugiat ad irure est eiusmod",
                "@baseType": "id adipisicing",
                "@schemaLocation": "https://lnkZDkuRybE.qivuwPaA-3lgQuzLudGtGWLzHgbz,9RX",
                "@type": "amet",
                "@referredType": "proident ut dolor voluptate"
            }
        ],
        "state": "inProgress",
        "@baseType": "cillum qui culpa",
        "@schemaLocation": "http://AgxAlTWWQyEgTEcQKlyE.jjnfHQso-oQVAMELLJHE6RTrT.WMOtxkioy",
        "@type": "sit amet pariatur cupidatat"
    },
    "dataCorrelationId": "aac9969d-219d-4ff1-b256-1765dcf9b342",
    "generalTestArtifact": [
        {
            "id": "in c",
            "href": "http://tTgniNmYMDPtk.mdyOId-WZUYzDQJS18TnYGPjVjPHDopqDaQWJGbi+tmB3UR09sn",
            "name": "est aute aliquip ",
            "@baseType": "magna sit dolor Ut velit",
            "@schemaLocation": "http://ZHeYBMHFHYBjdTVGDIHi.cmrVDHKlrBLic5S0Q3FPwxes+oMqU",
            "@type": "labore culpa dolor ut sed",
            "@referredType": "ad do i"
        },
        {
            "id": "reprehenderit Excepteur",
            "href": "https://oShTUdRxsPpwqsCqaJ.saoH9D4DoBZQeD6gPhrDf-",
            "name": "aliquip enim labore do",
            "@baseType": "do",
            "@schemaLocation": "https://WMPLatOPOESMuTndiqXeiZiiUpzdrBWR.xgxjIPN",
            "@type": "commodo irure reprehenderit",
            "@referredType": "id enim Lorem pariatur"
        }
    ],
    "state": "pending",
    "testCase": {
        "id": "commodo non",
        "href": "http://eL.tijov5Re",
        "name": "nostrud laborum tempor",
        "@baseType": "velit occaecat",
        "@schemaLocation": "http://ZLhByLobtimrGIfZDwpbbfUnY.ikhH5xhqcxsspSuw",
        "@type": "magna incid",
        "@referredType": "eu"
    },
    "testDataInstance": [
        {
            "id": "cupidatat aliquip do qui",
            "href": "https://PqyEfwfsvrPRziPXM.zgouSBXtndmHSAEsQ0uUg-In1CEoz83K.GGZXKOyxxoFozg",
            "name": "incididunt reprehenderit Ut in",
            "@baseType": "cupidatat aliqua consequat",
            "@schemaLocation": "https://MZiUNmVrgrDoB.rbqQfi2YppvCLe47TE9NOkZWHSZiOpT0yD8hwy3uTT",
            "@type": "ut Ut minim elit voluptate",
            "@referredType": "irure in nostrud do"
        },
        {
            "id": "qui s",
            "href": "https://wedwNmNRLIsbSFjCpdXeBDarVKmqvz.ojcSn8eOc,KwR4kjp6uEYwTlW4epZwMG8lwCTguH94,nrasgaLKEA5x3,O",
            "name": "fugiat ullamco",
            "@baseType": "in Lorem",
            "@schemaLocation": "https://piruwZTiZnQSOroJKendEcPR.aheIhCaFxAKhzyp7w+Cb-LiciK0cWZ2hxmQjv95tdP6lpRB-gzVGLMBVT",
            "@type": "Duis aute",
            "@referredType": "reprehenderit aliqua"
        }
    ],
    "@baseType": "proident deserunt magna",
    "@schemaLocation": "https://ubZlFgUBaquvbIoGZvExNOtaFQTorGu.fujYpL,y1vhMBFd,pNlxT,+xBh7z-T0H",
    "@type": "in dolore sunt"
})



