#!/usr/bin/env dothttp

# imported from 35240-011764bd-72c5-48b3-824e-2109820e9c6b.postman_collection.json

// Post proxy signature.

@name("Post Proxy Signature")
POST "https://{{baseUrl}}/v1/proxy/signature"
"Predix": "<>"
"Authorization": "<>"


// Post proxy signature details.

@name("Post Proxy Signature Details")
POST "https://{{baseUrl}}/v1/proxy/signature/details"
"Predix": "<>"
"Authorization": "<>"


// Post proxy signature extension.

@name("Post Proxy Signature Extension")
POST "https://{{baseUrl}}/v1/proxy/signature/extension"
"Predix": "<>"
"Authorization": "<>"



