#!/usr/bin/env dothttp

# imported from 35240-3296e101-3586-4bea-89ab-7061a33a7d96.postman_collection.json

// Retrieve queue details

@name("get Queue")
GET "https://{{baseUrl}}/queue/api/json"


// Retrieve queued item details

@name("get Queue Item")
GET "https://{{baseUrl}}/queue/item/:number/api/json"



