#!/usr/bin/env dothttp

# imported from 35240-d90fe3bc-a342-4867-915e-44120619da60.postman_collection.json

// Returns data for the specified season, queue, team, and league.
// 
// **queueId**: the standard available queueIds are: 1=WoL 1v1, 2=WoL 2v2, 3=WoL 3v3, 4=WoL 4v4, 101=HotS 1v1, 102=HotS 2v2, 103=HotS 3v3, 104=HotS 4v4, 201=LotV 1v1, 202=LotV 2v2, 203=LotV 3v3, 204=LotV 4v4, 206=LotV Archon. Note that other available queues may not be listed here.
// 
// **teamType**: there are two available teamTypes: 0=arranged, 1=random.
// 
// **leagueId**: available leagueIds are: 0=Bronze, 1=Silver, 2=Gold, 3=Platinum, 4=Diamond, 5=Master, 6=Grandmaster.

@name("League Data")
GET "https://{{battle-net-host}}/data/sc2/league/{{sc2.season-id}}/{{sc2.queue-id}}/{{sc2.item-type-id}}/{{sc2.league-id}}"
? "locale"= "{{locale}}"
? "access_token"= "{{access-token}}"



