#!/usr/bin/env dothttp

# imported from 35240-562f9ba4-1e56-4555-a99c-b5228c26d947.postman_collection.json

// Gets all issues.

@name("Issues")
GET "https://992f0ac2-d8cb-4682-80df-d742797b44a9.mock.pstmn.io/issues"
"Accept": "application/json"
"User-Agent": "API-Evangelist-Network"
? "q"= "postman"



