#!/usr/bin/env dothttp

# imported from 35240-c06f082c-7c18-4317-b196-8ad07101a2f4.postman_collection.json

@name("Return a list of pathways based on search term")
GET "https://{{baseUrl}}/pathways/diagrams/search/:searchString"


@name("Return a list of pathways based on category provided")
GET "https://{{baseUrl}}/pathways/diagramsForCategory/:category"



