#!/usr/bin/env dothttp

# imported from 35240-f27f798d-07bf-410e-bc36-81f925cac47d.postman_collection.json

// Describes your Elastic IP addresses that are being moved to the EC2-VPC platform,
//                         or that are being restored to the EC2-Classic platform.

@name("Describe Moving Addresses")
GET "https://{{aws_ec2_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "DryRun"= ""
? "Filter.N"= ""
? "MaxResults"= ""
? "NextToken"= ""
? "PublicIp.N"= ""
? "Action"= "DescribeMovingAddresses"



