#!/usr/bin/env dothttp

# imported from 35240-a96092c6-2ddc-4e57-bdc3-4ff0804f3144.postman_collection.json

// This operation list or find ServiceLevelObjective entities

@name("List or find ServiceLevelObjective objects")
GET "https://{{baseUrl}}/serviceLevelObjective"
? "fields"= "non incididunt nostrud Duis"
? "offset"= "80487809"
? "limit"= "80487809"


// This operation creates a ServiceLevelObjective entity.

@name("Creates a ServiceLevelObjective")
POST "https://{{baseUrl}}/serviceLevelObjective"
"Content-Type": "application/json;charset=utf-8"
json({
    "conformanceComparator": "et quis adipisicing nostrud",
    "conformanceTarget": "esse",
    "serviceLevelObjectiveParameter": {
        "name": "laborum veniam",
        "parameterType": "sit nisi ut",
        "serviceParmCategory": "id aute officia cupidatat",
        "serviceParmPerspective": "nulla officia sed dolor",
        "transformationAlgorithmOfKQI": "consequat id velit irure in",
        "relatedEntity": [
            {
                "@referredType": "id fugiat ipsum ut",
                "id": "esse velit ullamco",
                "role": "Ut consectetur",
                "href": "irure",
                "name": "proident fugiat labore",
                "@baseType": "ResourceSpecification",
                "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                "@type": "LogicalResourceSpecification"
            },
            {
                "@referredType": "aute nisi",
                "id": "in nisi laborum non",
                "role": "do",
                "href": "reprehenderit sunt",
                "name": "in qui laborum veniam",
                "@baseType": "ResourceSpecification",
                "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
                "@type": "LogicalResourceSpecification"
            }
        ],
        "validFor": {
            "endDateTime": "1985-04-12T23:20:50.52Z",
            "startDateTime": "1985-04-12T23:20:50.52Z",
            "@baseType": "enim amet sit ad",
            "@schemaLocation": "http://uFccGQtPAAUFfMNlDhPxIbWw.oyswataAhQYvSSOAc8INwyeONIp9r+qczpOwF7+40NwlAdEaX-",
            "@type": "velit laboris laborum sint"
        },
        "@baseType": "Excepteur in laborum minim",
        "@schemaLocation": "http://PpvFzV.zupRif+UN9SRKsI8FKw6dgc",
        "@type": "nisi veniam sint Lorem laboris"
    },
    "graceTimes": "ut commodo esse",
    "name": "voluptate Lorem quis",
    "thresholdTarget": "elit veniam minim laboris sit",
    "toleranceTarget": "aliquip minim ad consequat",
    "conformancePeriod": {
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z",
        "@baseType": "ex Duis",
        "@schemaLocation": "http://MeF.pxcqi,QZBYbKu+73RSXtEGPFv2EbBS",
        "@type": "enim tempor eu laboris"
    },
    "serviceLevelObjectiveConsequence": [
        {
            "prescribedAction": "est Duis esse sint",
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z",
                "@baseType": "Lorem ",
                "@schemaLocation": "https://KwAlhyAbrGE.jugyTLah0Lpo6AOBkX5N3Tu6wvf9c0aHfdnR7YFTNCNbkmpcUd-gU",
                "@type": "sit"
            },
            "@baseType": "ut",
            "@schemaLocation": "http://IEQnWDqWEXRFWvYQKADTbbqaDOWjg.jrX63RavXhX2eRwNzIGyKxAPOcbNE0qNnj9iErB.,UXwyU4CEoYUYEh09sEJuLyFRj",
            "@type": "aliquip sit incididunt"
        },
        {
            "prescribedAction": "sunt",
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z",
                "@baseType": "in occaecat quis deserunt",
                "@schemaLocation": "http://hPEYrRHUlPxDY.mykuTd6wDYZtko0VsCEGmimTCPQsBxFgi49yLowFc1M9iLW",
                "@type": "nisi eu dolore magna minim"
            },
            "@baseType": "minim sit in ea",
            "@schemaLocation": "https://OOgSUNgpJur.kzawdttahACQWTS2YAM,9aSFlTHdwtlJKFYaZDTqEj",
            "@type": "in deserunt do sit"
        }
    ],
    "tolerancePeriod": {
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z",
        "@baseType": "sit",
        "@schemaLocation": "http://yQeDbKgQzDhXlyS.epzT.oeweDqlS8Zxxg83E",
        "@type": "laborum cillum incididunt quis"
    },
    "validFor": {
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z",
        "@baseType": "amet et enim incididunt est",
        "@schemaLocation": "https://tyWiGdNGbLqFYiMToHmboXkVJQ.yaYrROmV-hexfxABxOIdrmMcPnLonYVv8-2ufYtvkI2e",
        "@type": "eu in ullamco ea"
    },
    "@baseType": "",
    "@schemaLocation": "https://sAfvGExAPavbgcTvcScP.yhevDdjTT6J",
    "@type": "occaecat dolore v"
})



