#!/usr/bin/env dothttp

# imported from 35240-c07d1c61-6030-4647-bb60-23a96c126bb9.postman_collection.json

// This operation list or find NonFunctionalTestModel entities

@name("List or find NonFunctionalTestModel objects")
GET "https://{{baseUrl}}/nonFunctionalTestModel"
? "fields"= "ad exercitation quis elit"
? "offset"= "3409138"
? "limit"= "3409138"


// This operation creates a NonFunctionalTestModel entity.

@name("Creates a NonFunctionalTestModel")
POST "https://{{baseUrl}}/nonFunctionalTestModel"
"Content-Type": "application/json;charset=utf-8"
json({
    "nonFunctionalTestModelDefinition": {
        "id": "culpa ut Duis",
        "href": "https://kzOEaIRkRfxUr.onrpOemeQ9rktLHWadcXvUIGZEw5lqgtTIAnMUtTQkB",
        "attachmentType": "video",
        "content": "aute esse velit et",
        "description": "Photograph of the Product",
        "mimeType": "nostru",
        "name": "ad et Excepteur Ut",
        "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
        "size": {
            "amount": 1,
            "units": "officia ut ut quis sed"
        },
        "validFor": {
            "endDateTime": "1985-04-12T23:20:50.52Z",
            "startDateTime": "1985-04-12T23:20:50.52Z"
        },
        "@baseType": "ipsum",
        "@schemaLocation": "http://juezDhrPTjYQtKjYBiFgEUzmDbEdZ.zenoMBDB6X2hPMCy4zrnUYqivOtcRyObqgt5sbnm695Hnl",
        "@type": "fugiat"
    },
    "description": "",
    "version": "1.2.3",
    "versionDescription": "What's changed: ...",
    "agreement": {
        "name": "My Agreement",
        "terms": "<EULA>",
        "url": "http://myagreement.com"
    },
    "attribute": [
        {
            "description": "fugiat non incididunt tempor",
            "characteristic": {
                "name": "consectetur quis",
                "value": {},
                "id": "laborum sed nostrud",
                "valueType": "et ut reprehenderit voluptate dolore",
                "characteristicRelationship": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "@baseType": "laboris esse",
                "@schemaLocation": "http://zUJkWNVZzJkQewbalkKYsJse.qzihch5LFl2GSPdhLg2EHuGTOmsW3bHKvnRLUNGZamLfg8HT0RyqdaFj",
                "@type": "in Lorem in mollit"
            }
        },
        {
            "description": "consectetur",
            "characteristic": {
                "name": "ullamco officia ex labore",
                "value": {},
                "id": "ex minim",
                "valueType": "aliqua commodo consequat",
                "characteristicRelationship": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "@baseType": "laboris culpa voluptate",
                "@schemaLocation": "http://M.kcuT31OQbGdy-0",
                "@type": "est magna"
            }
        }
    ],
    "relatedParty": [
        {
            "@referredType": "repreh",
            "id": "consequat nisi Ut non",
            "href": "http://q.tgBVJNYUSD58VrneRvWnjTxvNjgDXJeObMP",
            "name": "irure dolor adipisicing magna",
            "role": "aute veniam deserunt",
            "contact": [
                {
                    "id": "cillum",
                    "href": "http://yYx.qaig2qI+JU7PPUSOIGVcxO1aB1Lo7OZLXij,J6ZZ15LCtSWRYSM3kGhFZG2+W6RBmgQQ",
                    "mediumType": "cillum",
                    "preferred": true,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "nisi",
                    "@schemaLocation": "http://lihZUWgAYCwppbubRBmKJmbItHrv.ymtwG5aD7MKZV-H,jqGdwhoQWqHJYu6guw9XbeXKjw",
                    "@type": "ut consequat consectetur do"
                },
                {
                    "id": "amet voluptate et",
                    "href": "http://CECtsgeztA.ziied.C0pvzvsSF2C93tjB89HGlKonHYYDRVcE84Qk.0rCW+p,PEQ3i71LZP0zEjhIyY2wR",
                    "mediumType": "ea minim",
                    "preferred": true,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "esse Ut ea aliqua",
                    "@schemaLocation": "http://KRvyZivAkgJaQtoIuZkkIRGfTZfhXTk.kxdbOw4.s8sJKx6",
                    "@type": "sint commodo sed labore"
                }
            ],
            "@baseType": "mollit consectetur",
            "@schemaLocation": "https://hsKTTNQbCfCPfCnJoYwymLhxsGGen.lwmsGUL",
            "@type": "ut non"
        },
        {
            "@referredType": "tempor",
            "id": "consequat enim cupidatat officia",
            "href": "http://TFFRLnzrBZjFEpbzIxuvvhVJfm.cbhuBOLDgOF0Nqnp+L92vgNqRtmor88NhCXgdXZ9paWOCYSIPACjTnQL0bwNU5wIPM0BuV4dd",
            "name": "ut elit culpa Ut sint",
            "role": "est nostrud incididunt",
            "contact": [
                {
                    "id": "quis non Excepteur",
                    "href": "https://Bgzv.vaH2MSWBT9BIyWqlRzIH3QFhXi6NywJOqvmjWRMJR-Qm-h5yTOD8",
                    "mediumType": "Ut sint nostrud eiusmod anim",
                    "preferred": true,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "eiusmod do sit fugiat",
                    "@schemaLocation": "http://QcaA.ddhSAn8ssmwP4Rwi",
                    "@type": "aliquip ea Ut incididunt occ"
                },
                {
                    "id": "Ut dolore aliquip minim sunt",
                    "href": "http://KTrFYASSPbvFLsCMghPjIo.gdzfPNLb9",
                    "mediumType": "ad",
                    "preferred": false,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "cillum elit sint est",
                    "@schemaLocation": "https://YVlpqjFTbOFMrNEpZELBjRv.ljpMGMP5pGiNl6Rmdf,zfZ1IwH2KxLXnUpVfjDDk3SpG+ASJhMHKFkNpMrd6yioz",
                    "@type": "eiusmod pariatur Ut et in"
                }
            ],
            "@baseType": "non et dolore",
            "@schemaLocation": "https://AuyPqUsTeeTZZw.ghMscIeC.szAYSi8KNra+eTuqHVSENz.JoHnlcF+H0D.yANQWZbGLBp7CqXGVzrSdYEGlQ2",
            "@type": "deserunt"
        }
    ],
    "state": "beta",
    "@baseType": "laboris dolore labore qui deserunt",
    "@schemaLocation": "http://lgtkBCfGxlDGXgijicNi.ujti84429IMU--,7j0jzso.SMuxKllVoRYXf1DWEfl",
    "@type": "tempor exercitation"
})



