#!/usr/bin/env dothttp

# imported from 35240-0100df38-567e-4c29-9c56-293119ed67af.postman_collection.json

// This operation lists the currently available city layers. nThe returned strings can then be used as a layerId path parameter in the /layers operations included in this API.

@name("Retrieve available layers")
GET "https://{{baseUrl}}/layers"



