#!/usr/bin/env dothttp

# imported from 35240-1eafd448-a35c-467b-bb97-09ace45ef013.postman_collection.json

// Returns the accounts that have been assigned to you.

@name("Get all accounts")
GET "https://{{baseUrl}}/accounts"
? "type"= "<delete>"



