#!/usr/bin/env dothttp

# imported from 35240-c07d1c61-6030-4647-bb60-23a96c126bb9.postman_collection.json

// This operation retrieves a NonFunctionalTestModel entity. Attribute selection is enabled for all first level attributes.

@name("Retrieves a NonFunctionalTestModel by ID")
GET "https://{{baseUrl}}/nonFunctionalTestModel/:id"
? "fields"= "ad exercitation quis elit"


// This operation updates partially a NonFunctionalTestModel entity.

@name("Updates partially a NonFunctionalTestModel")
PATCH "https://{{baseUrl}}/nonFunctionalTestModel/:id"
"Content-Type": "application/json;charset=utf-8"
json({
    "nonFunctionalTestModelDefinition": {
        "id": "enim laborum",
        "href": "https://ReHcXaVyepTJYVOnqbUQdaAUMdfcgwtUO.pxdlqtAyHU+s8XF3mGRhGu,VaRsuTMfmxHcA5ALJtMYaIUPv3zHx-d1",
        "attachmentType": "video",
        "content": "elit ad do",
        "description": "Photograph of the Product",
        "mimeType": "occaecat consectetur ipsum",
        "name": "ad",
        "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
        "size": {
            "amount": 1,
            "units": "nisi commodo aliquip sit aute"
        },
        "validFor": {
            "endDateTime": "1985-04-12T23:20:50.52Z",
            "startDateTime": "1985-04-12T23:20:50.52Z"
        },
        "@baseType": "laborum consectetur ut commodo dolor",
        "@schemaLocation": "http://iZcGsi.anlJtcbJJJFNN,4sHPOu7SCp01BdnTcXyf",
        "@type": "enim dolor"
    },
    "description": "",
    "versionDescription": "What's changed: ...",
    "agreement": {
        "name": "My Agreement",
        "terms": "<EULA>",
        "url": "http://myagreement.com"
    },
    "attribute": [
        {
            "description": "ex",
            "characteristic": {
                "name": "irure veniam in deserunt",
                "value": {},
                "id": "sint Lorem",
                "valueType": "est occaecat",
                "characteristicRelationship": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "@baseType": "deserunt",
                "@schemaLocation": "http://UKDGLufUwonIsQraQVCNeu.ktqqrImWpeVzTMj93.ILH0lDCmX0pqrj.zz3oRZSrK1GlpxnIUQsNhAre6Jra42hDcPTMWTD",
                "@type": "officia sed"
            }
        },
        {
            "description": "ad eiusmod amet sed adipisicing",
            "characteristic": {
                "name": "occaecat",
                "value": {},
                "id": "nulla incididunt est",
                "valueType": "et dolor",
                "characteristicRelationship": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "@baseType": "laboris",
                "@schemaLocation": "http://EIAuazDflJWEfzilUWkUsbfrxzshv.dfudA,NtVWYEHz,+07xvstlsAo,qFQPAvKpMBe5jC+IhRAv5ugyp88t-oXnYJ2TYJMB",
                "@type": "deserunt"
            }
        }
    ],
    "relatedParty": [
        {
            "@referredType": "in laborum dolore",
            "id": "in cupidatat adipisicing",
            "href": "https://pqtM.vtxxUnGwx+wk+zBBeQvETy",
            "name": "tempor ut in",
            "role": "fugiat laboris aute",
            "contact": [
                {
                    "id": "sed deserunt minim",
                    "href": "http://AGllXCKpUCEQusaQRhoqgvjboKfnNopaR.cmrScs.fTZbpU,FqrGswVnt8nsv7BDJ06qDfMCIBcku9wew+Bmz",
                    "mediumType": "veniam ad",
                    "preferred": false,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "sed adipisicing",
                    "@schemaLocation": "http://gyHlr.ngruSWhwpJsLe,h58z14trIlFxg.n.4",
                    "@type": "eu in sed nulla"
                },
                {
                    "id": "culpa dolor irure nulla Lorem",
                    "href": "http://UlvvIpQTbXyVWdIgOuBGyZJHrKW.poiwY9uLyoww,oQXUA6arfsvduMjnJujkuKswfhRzDuE.9dvOm,Nnxh",
                    "mediumType": "in aliqua dolor ea o",
                    "preferred": true,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "occaecat Ut in incididunt",
                    "@schemaLocation": "https://PGiDyAjD.yydHk62xWEqCc.UbHWH2WA.hVlKqodkGWVNEGWGIGZJjIsO.fQs",
                    "@type": "incididunt minim"
                }
            ],
            "@baseType": "in est aliqua adipisicing",
            "@schemaLocation": "https://LKqvmEIIdZOSyABigfyzdZNhmHCxAxqH.gtzqUzGRQ1CBNstvt5",
            "@type": "non ullamco adipisicing ipsum"
        },
        {
            "@referredType": "Lorem ",
            "id": "minim nulla ea ex dolor",
            "href": "https://mpOQjXGzbblncU.ydnfrU3GJOHjpiYkZmtjDfPLp8sw,I+Giqq-n1PF+1vof9XoTkM16YPn965Qv5qiK3",
            "name": "eiusmod eu",
            "role": "est incididunt",
            "contact": [
                {
                    "id": "enim minim proident",
                    "href": "https://sWeYvFEZQMeIKWZKvxicevRmlRn.gacxMOAaw8nKNi6f2EDROVGzRz5AzD",
                    "mediumType": "amet offi",
                    "preferred": false,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "occaecat aliquip proident Duis",
                    "@schemaLocation": "https://DBFFqaPkpqxUPQ.wgghtYgKzp0aaez",
                    "@type": "id elit Lorem cillum"
                },
                {
                    "id": "dolore laboris",
                    "href": "http://NjSRzFQHKRDClBKWEJYjEJNPdMiCOxfH.cmAgt8K+Q5SjuaQsSri32wXej5WKFVDkkD2Czabsi.paD-v7KGZ4Qp3IKX9MeNHZtFoLX",
                    "mediumType": "laborum officia nulla",
                    "preferred": true,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "minim ullamco sunt deserunt",
                    "@schemaLocation": "http://evkpYdXgiBHcdATDNQ.myoxzd5Re1BZRc,dHceaEsdcPZL",
                    "@type": "dolore consequat"
                }
            ],
            "@baseType": "Lorem in nostrud eiusmod mollit",
            "@schemaLocation": "http://uUlxfrzEHJIJuRvPVodWVmsxhJtsxeSQH.gakoseBTGw5AehrGm5sLryNLAKMWuptd9",
            "@type": "nisi esse elit"
        }
    ],
    "state": "incomplete",
    "@baseType": "esse ullamco voluptate",
    "@schemaLocation": "http://bPtzfGTjTLcozoJMazkuXlsHGHSzJc.qywwv6LvY9,EjR9TdQ1VwbAkU9S2x4hMSzO2ifPXmO6LOEZe0S0vJcTzCv9",
    "@type": "Lorem deserunt culpa eu est"
})


// This operation deletes a NonFunctionalTestModel entity.

@name("Deletes a NonFunctionalTestModel")
DELETE "https://{{baseUrl}}/nonFunctionalTestModel/:id"



