#!/usr/bin/env dothttp

# imported from 35240-bf3948ba-0b98-42ba-afd8-089eb3a8b570.postman_collection.json

@name("Provides a list of matches in progress")
GET "https://{{baseUrl}}/schedules/live/schedule{{format}}"



