#!/usr/bin/env dothttp

# imported from 35240-69935689-abac-4ca3-a7a8-e89ccfe72173.postman_collection.json

// This operation list or find Topic entities

@name("List or find Topic objects")
GET "https://{{baseUrl}}/topic"
? "fields"= "ex ullamco ad"
? "offset"= "-82478083"
? "limit"= "-82478083"


// This operation creates a Topic entity.

@name("Creates a Topic")
POST "https://{{baseUrl}}/topic"
"Content-Type": "application/json;charset=utf-8"
json({
    "contentQuery": "et tempor consequat",
    "headerQuery": "velit adipisicing",
    "name": "anim ipsum sint velit dolore",
    "@baseType": "dolor",
    "@schemaLocation": "http://uoKmWsfYEoZPqiberJRooZmatKqmJZq.yxnGH5H5JWTcuetZd7fcHfkNH1-jgrglMvFU3wR,K5lkDeCRJGXqjIBoLTZfYSmNO",
    "@type": "ullamco proident"
})



