#!/usr/bin/env dothttp

# imported from 35240-2fb0962b-7d35-49c0-8ec6-311647bcabe4.postman_collection.json

// Retrieve service details.

@name("Retrieve service details")
GET "https://{{baseUrl}}/v1/tenant/:tenantName/service/:serviceName"
"Predix": "<>"


// Retrieve service credentials.

@name("Retrieve service credentials")
GET "https://{{baseUrl}}/v1/tenant/:tenantName/service/:serviceName/credentials"
"Predix": "<>"



