#!/usr/bin/env dothttp

# imported from 35240-2fb0962b-7d35-49c0-8ec6-311647bcabe4.postman_collection.json

// Update a provisioned service instance.

@name("update a PROVISIONED service instance")
PUT "https://{{baseUrl}}/v1/tenant/:tenantName/service/:instanceName"
"Predix": "<>"



