#!/usr/bin/env dothttp

# imported from 35240-c07d1c61-6030-4647-bb60-23a96c126bb9.postman_collection.json

// This operation list or find TestCase entities

@name("List or find TestCase objects")
GET "https://{{baseUrl}}/testCase"
? "fields"= "ad exercitation quis elit"
? "offset"= "3409138"
? "limit"= "3409138"


// This operation creates a TestCase entity.

@name("Creates a TestCase")
POST "https://{{baseUrl}}/testCase"
"Content-Type": "application/json;charset=utf-8"
json({
    "testCaseDefinition": {
        "id": "do",
        "href": "https://LAbCNNOzOSwARUI.rszjMkS7K3efuIeom-ny+apqjWEpYcDuB,vXrfKSqTiorZNshWd3a",
        "attachmentType": "video",
        "content": "laboris proident tempor",
        "description": "Photograph of the Product",
        "mimeType": "nostrud mollit",
        "name": "in enim esse",
        "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
        "size": {
            "amount": 1,
            "units": "id sint"
        },
        "validFor": {
            "endDateTime": "1985-04-12T23:20:50.52Z",
            "startDateTime": "1985-04-12T23:20:50.52Z"
        },
        "@baseType": "id cupidatat aliqua magna",
        "@schemaLocation": "http://VgyyqVSWbAfJHHGZIKWmWEooPzfgoX.gbxab3bsRv1Zio1GOsOjTaJ.Ug2k.vZGpzU4QSNv",
        "@type": "elit nisi ipsum"
    },
    "description": "",
    "version": "1.2.3",
    "versionDescription": "What's changed: ...",
    "agreement": {
        "name": "My Agreement",
        "terms": "<EULA>",
        "url": "http://myagreement.com"
    },
    "attribute": [
        {
            "description": "",
            "characteristic": {
                "name": "Excepteur commodo",
                "value": {},
                "id": "tempor",
                "valueType": "id elit velit ad",
                "characteristicRelationship": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "@baseType": "incididunt null",
                "@schemaLocation": "http://kFeNxvRuaNtHvxfze.ospA,fwXRA9+LpggbuQVjHK1yk9T59iDk",
                "@type": "laboris et irure aute"
            }
        },
        {
            "description": "consequ",
            "characteristic": {
                "name": "Lorem quis Excepteur anim",
                "value": {},
                "id": "dolore adipisicing irure mollit",
                "valueType": "sunt in in labor",
                "characteristicRelationship": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "@baseType": "Ut Lorem",
                "@schemaLocation": "http://Rpc.orihvrk3QU0rFlsx8V",
                "@type": "adipisicing id sit"
            }
        }
    ],
    "relatedParty": [
        {
            "@referredType": "veniam sunt minim aliqua laborum",
            "id": "enim dolor tempor id",
            "href": "http://GvmSyJopgvnncvOHRuGKGIyCgUrgZPv.uboBN2w,hZkRb7yF56Gm2umhHmMT8n+EaIp3YG-GK,UvX.rsu,X1LXI.D-0GGm9Sr-kfGie1",
            "name": "proident",
            "role": "ut consectetur",
            "contact": [
                {
                    "id": "nulla",
                    "href": "https://rNHwNnpRHAYOpdiESPZ.zmouGwV74m,woeHG4ZE2CsT+2IdB.--TkaWUVQHavm8k3",
                    "mediumType": "ipsum laboris ad cupidatat mollit",
                    "preferred": false,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "ullamco est eu Lorem amet",
                    "@schemaLocation": "https://L.zexiTCvuXTxgh1EcBZBdhnguY50iEnb",
                    "@type": "cupidatat"
                },
                {
                    "id": "ul",
                    "href": "https://RxEjC.ukiM2xXcD",
                    "mediumType": "d",
                    "preferred": true,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "sed do enim dolor",
                    "@schemaLocation": "http://gvkQaC.thT214x3c2NxYBBZ3b.gabdoBi9XlsSrkdbfmLG+e6OtEGNDXCWL0POR0bPgE.wviaehBOe4i",
                    "@type": "anim velit adipisicing"
                }
            ],
            "@baseType": "velit tempor",
            "@schemaLocation": "https://JePzxizrTUHW.avtN1-NvwHmcgoNrlH2JbVpg,RhpDQCYqFPXDDSfUd",
            "@type": "labore commodo Excepteur minim"
        },
        {
            "@referredType": "dolor id irure",
            "id": "sit dolor aliqua sed officia",
            "href": "http://qbuozpNazVRmxeFtFFZNR.fobyR9+6fXTxzaGGi11VXst8UdBmtB9mXJ4BhZAfcwOZNhDj5yx1J1-7lYJHhgPAJ7oqa0",
            "name": "incididunt d",
            "role": "ut consectetur",
            "contact": [
                {
                    "id": "ad quis tempor",
                    "href": "https://SYqlxZarpuEUeNgpZ.txmMhRGaIajZGVM-F8163te5EbUf6krSEK4SyZZ99f8qWxdSbTFTZkj+ZKWCTtPc.DXUcO",
                    "mediumType": "est",
                    "preferred": true,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "est cillum",
                    "@schemaLocation": "http://sOk.onmxY.si9iodjQJPUoYv-",
                    "@type": "consectetur"
                },
                {
                    "id": "quis ipsum incididunt in",
                    "href": "https://VBCoROTsSTeivQArVFIoiS.ldfhGk4TBv5cni",
                    "mediumType": "dolor in elit",
                    "preferred": false,
                    "characteristic": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "deserunt officia",
                    "@schemaLocation": "http://DwBKjCoC.ytlHRoNL-GCtvyJmFePI0K7IBSKM7PX5cVOijmWPbiQAo1nSFO5",
                    "@type": "exercitation sint aliquip aliqua"
                }
            ],
            "@baseType": "nulla ut",
            "@schemaLocation": "http://eKi.lkhpJIb8Ri9JeFsdP,+X8wLWtrzjFvbQzh8KNuZi7rCSk5edsZhMM",
            "@type": "cillum in"
        }
    ],
    "state": "beta",
    "@baseType": "ipsum dolor a",
    "@schemaLocation": "http://gvTwCVom.nowqQLihB9yDxEVITSxGou4duXE+EKNp3vASh1+bNJtBeQIsSH48ePVCLuaX,p,",
    "@type": "Duis quis esse"
})



