#!/usr/bin/env dothttp

# imported from 35240-d5ddce54-951b-4651-8eae-c4305b89b49c.postman_collection.json

@name("Returns a list of services.")
GET "https://{{baseUrl}}/services"
? "id"= "-40203187"



