#!/usr/bin/env dothttp

# imported from 35240-bddbaf5a-26e6-497b-85a9-b22a2a06054d.postman_collection.json

@name("User Login")
POST "http://{{host}}/vapi/api8/login.php"
data({
    "username": [
        ""
    ],
    "password": [
        ""
    ]
})


@name("Get Key")
GET "http://{{host}}/vapi/api8/getKey.php"



