#!/usr/bin/env dothttp

# imported from 35240-ac6561cd-0334-4ee5-8280-57b4086d4c3d.postman_collection.json

@name("Check if a gist is starred")
GET "https://{{baseUrl}}/gists/:gist_id/star"


// Note that you'll need to set `Content-Length` to zero when calling out to this endpoint. For more information, see "[HTTP verbs](https://developer.github.com/v3/#http-verbs)."

@name("Star a gist")
PUT "https://{{baseUrl}}/gists/:gist_id/star"


@name("Unstar a gist")
DELETE "https://{{baseUrl}}/gists/:gist_id/star"



