#!/usr/bin/env dothttp

# imported from 35240-c446a4c9-8dd6-45c4-99f2-688a96fe76ae.postman_collection.json

// Lists all users, in the order that they signed up on GitHub. This list includes personal user accounts and organization accounts.
// 
// Note: Pagination is powered exclusively by the `since` parameter. Use the [Link header](https://developer.github.com/v3/#link-header) to get the URL for the next page of users.

@name("List users")
GET "https://{{baseUrl}}/users"
? "since"= "<string>"
? "per_page"= "30"



