#!/usr/bin/env dothttp

# imported from 35240-d76987fb-f2f9-425d-9645-ecebd487c07d.postman_collection.json

// List all invitations associated with my user

@name("List all invitations associated with my user")
GET "https://{{baseUrl}}/user/invites"


// Get the details of an invitation

@name("Get the details of an invitation")
GET "https://{{baseUrl}}/user/invites/:identifier"



