#!/usr/bin/env dothttp

# imported from 35240-dbaaeac4-235b-44c3-ba85-7fe9c62e50ba.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


@name("Retrieve server triggers") : "base-inherit-auth"
GET "https://{{baseUrl}}/v1/:namespace/projects/:project/servers/:server/triggers/"
? "name"= "<string>"
? "limit"= "<string>"
? "offset"= "<string>"
? "ordering"= "<string>"


@name("Create a new server trigger") : "base-inherit-auth"
POST "https://{{baseUrl}}/v1/:namespace/projects/:project/servers/:server/triggers/"
"Content-Type": "application/json"
json({
    "name": "<string>",
    "operation": "<string>",
    "webhook": {
        "url": "<string>",
        "payload": "<object>"
    }
})



