#!/usr/bin/env dothttp

# imported from 35240-29a48257-4490-4b0a-b600-43b228f553ff.postman_collection.json

// Checks to make sure all schema have examples.

@name("Do all schema have examples?")
GET "https://{{postman_base_url}}/apis/:api_id/versions/:version_id/schemas/:schema_id"
"x-api-key": "{{postman_api_key}}"


// Checks to make sure all schema have properties.

@name("Do all schema have an identifier?")
GET "https://{{postman_base_url}}/apis/:api_id/versions/:version_id/schemas/:schema_id"
"x-api-key": "{{postman_api_key}}"


// Checks to make sure all schema have properties.

@name("Do all schema have properties?")
GET "https://{{postman_base_url}}/apis/:api_id/versions/:version_id/schemas/:schema_id"
"x-api-key": "{{postman_api_key}}"


// Checks to see if all schema properties have descriptions.

@name("Do all schema properties have descriptions?")
GET "https://{{postman_base_url}}/apis/:api_id/versions/:version_id/schemas/:schema_id"
"x-api-key": "{{postman_api_key}}"



