#!/usr/bin/env dothttp

# imported from 35240-04551e11-ae48-4759-9d58-fef6a7b17230.postman_collection.json

// This method gets all the videos from the specified user's Watch Later queue.

@name("Get all the videos in a user's Watch Later queue")
GET "https://{{baseUrl}}/me/watchlater"
? "direction"= "<string>"
? "filter"= "<string>"
? "filter_embeddable"= "<string>"
? "page"= "<string>"
? "per_page"= "<string>"
? "query"= "<string>"
? "sort"= "<string>"


// This method removes a single video from the specified user's Watch Later queue.

@name("Remove a video from a user's Watch Later queue")
DELETE "https://{{baseUrl}}/me/watchlater/:video_id"



