#!/usr/bin/env dothttp

# imported from 35240-e04c6fb1-e891-4983-80ec-38175b6c944e.postman_collection.json

// Add api ethereum privatewallet generatetransaction.

@name("Add API Ethereum Privatewallet Generatetransaction")
POST "https://{{baseUrl}}/api/Ethereum/privateWallet/generateTransaction"
"Authorization": "<>"


// Add api ethereum privatewallet broadcasttransaction.

@name("Add API Ethereum Privatewallet Broadcasttransaction")
POST "https://{{baseUrl}}/api/Ethereum/privateWallet/broadcastTransaction"
"Authorization": "<>"


// Add api ethereum privatewallet estimatetransaction.

@name("Add API Ethereum Privatewallet Estimatetransaction")
POST "https://{{baseUrl}}/api/Ethereum/privateWallet/estimateTransaction"
"Authorization": "<>"



