#!/usr/bin/env dothttp

# imported from 35240-04144c4b-1296-424d-8a98-b2ae6373c414.postman_collection.json

// Fetch the representation of an existing Project.

@name("Get Project")
GET "https://{{baseUrl}}/:project"



