#!/usr/bin/env dothttp

# imported from 35240-ac6561cd-0334-4ee5-8280-57b4086d4c3d.postman_collection.json

// Lists all repositories that have been selected when the `visibility` for repository access to a secret is set to `selected`. You must authenticate using an access token with the `admin:org` scope to use this endpoint. GitHub Apps must have the `secrets` organization permission to use this endpoint.

@name("List selected repositories for an organization secret")
GET "https://{{baseUrl}}/orgs/:org/actions/secrets/:secret_name/repositories"


// Replaces all repositories for an organization secret when the `visibility` for repository access is set to `selected`. The visibility is set when you [Create or update an organization secret](https://developer.github.com/v3/actions/secrets/#create-or-update-an-organization-secret). You must authenticate using an access token with the `admin:org` scope to use this endpoint. GitHub Apps must have the `secrets` organization permission to use this endpoint.

@name("Set selected repositories for an organization secret")
PUT "https://{{baseUrl}}/orgs/:org/actions/secrets/:secret_name/repositories"
"Content-Type": "application/json"
json({
    "selected_repository_ids": [
        "<integer>",
        "<integer>"
    ]
})



