#!/usr/bin/env dothttp

# imported from 35240-d4cf5606-be3b-4e27-b14f-77855e9137ad.postman_collection.json

// Get a single realtime activity.

@name("Get a single realtime activity.")
GET "https://{{baseUrl}}/projects/:projectId/activities/:activityId"


// Get a list of comments belonging to this activity.

@name("Get a list of comments belonging to this activity.")
GET "https://{{baseUrl}}/projects/:projectId/activities/:activityId/comments"



