#!/usr/bin/env dothttp

# imported from 35240-585a2d49-6eb1-4045-8898-5ab8d446bc39.postman_collection.json

// List your current open orders.

@name("List Your Current Open Orders")
GET "https://{{baseUrl}}/order"
? "symbol"= "<post>"


// Get a single order by clientorderid.

@name("Get A Single Order By ClientOrderId")
GET "https://{{baseUrl}}/order/:clientOrderId"
? "wait"= "<>"



