#!/usr/bin/env dothttp

# imported from 35240-cc491087-45e6-46ba-aa93-9f2f2cc44068.postman_collection.json

// This feature was introduced in GitLab 8.7. This endpoint is deprecated and will be removed in GitLab 9.0.

@name("Get Licenses")
GET "https://{{baseUrl}}/licenses"
? "popular"= "<get>"


// This feature was introduced in GitLab 8.7. This endpoint is deprecated and will be removed in GitLab 9.0.

@name("Get Licenses Name")
GET "https://{{baseUrl}}/licenses/:name"



