#!/usr/bin/env dothttp

# imported from 35240-9a62c01e-3db2-4f66-b90d-a4df9dd9bd07.postman_collection.json

// Activates an inactive application.

@name("Activate Application")
POST "https://{{baseUrl}}/api/v1/apps/:appId/lifecycle/activate"


// Deactivates an active application.

@name("Deactivate Application")
POST "https://{{baseUrl}}/api/v1/apps/:appId/lifecycle/deactivate"



