#!/usr/bin/env dothttp

# imported from 35240-0b8cbe34-0af1-44a6-992a-ffe13940e455.postman_collection.json

@name("Create Application Snapshot")
POST "https://{{aws_kinesis_data_analytics_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_kinesis_data_analytics_service}}", region="{{aws_kinesis_data_analytics_region}}")
? "Action"= "CreateApplicationSnapshot"
data('null')


@name("Delete Application Snapshot")
POST "https://{{aws_kinesis_data_analytics_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_kinesis_data_analytics_service}}", region="{{aws_kinesis_data_analytics_region}}")
? "Action"= "DeleteApplicationSnapshot"
data('null')


@name("Describe Application Snapshot")
POST "https://{{aws_kinesis_data_analytics_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_kinesis_data_analytics_service}}", region="{{aws_kinesis_data_analytics_region}}")
? "Action"= "DescribeApplicationSnapshot"
data('null')


@name("List Application Snapshots")
POST "https://{{aws_kinesis_data_analytics_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_kinesis_data_analytics_service}}", region="{{aws_kinesis_data_analytics_region}}")
? "Action"= "ListApplicationSnapshots"
data('null')



