#!/usr/bin/env dothttp

# imported from 35240-5d5a5b61-567e-4d70-af1c-b7788d27e854.postman_collection.json

@name("Schedule")
GET "https://{{baseUrl}}/schedule/"


@name("Speakers")
GET "https://{{baseUrl}}/speakers/"


@name("Topics")
GET "https://{{baseUrl}}/topics/"



