#!/usr/bin/env dothttp

# imported from 35240-5af4ed67-4654-4363-a86d-3c7bcff23c51.postman_collection.json

// Lists all attribute value maps..

@name("Lists all attribute value maps.")
GET "https://{{baseUrl}}/rest/items/attributes/values/maps"


// Creates a new attribute value map..

@name("Creates a new attribute value map.")
POST "https://{{baseUrl}}/rest/items/attributes/values/markets/maps"



