#!/usr/bin/env dothttp

# imported from 35240-c18cf4a6-3383-44ba-8aa4-9bfe8ea153c4.postman_collection.json

// This operation retrieves a PartyPrivacyProfile entity. Attribute selection is enabled for all first level attributes.

@name("Retrieves a PartyPrivacyProfile by ID")
GET "https://{{baseUrl}}/partyPrivacyProfile/:id"
? "fields"= "irure est"


// This operation updates partially a PartyPrivacyProfile entity.

@name("Updates partially a PartyPrivacyProfile")
PATCH "https://{{baseUrl}}/partyPrivacyProfile/:id"
"Content-Type": "application/json;charset=utf-8"
json({
    "description": "in in e",
    "name": "eu aliqua",
    "status": "adipisicing mag",
    "agreedByParty": {
        "@referredType": "enim",
        "id": "quis tempor mollit",
        "href": "http://LBxnKjNRyYYGlaeFurOw.birsAqFdpGT1RJ+FDo-siCAw4riCcY43fy.Yumn6ePXiq",
        "name": "aliqua anim proident incididunt",
        "role": "velit exercitation aliquip",
        "@baseType": "ipsum fugiat nisi",
        "@schemaLocation": "http://RSt.wxmVC9BxgVMDFyTNz04YZAcRyOu9-C7pDTS8aaZr5jvxH2xp7N",
        "@type": "magna ea sunt"
    },
    "agreement": {
        "id": "dolor nulla",
        "href": "https://aeBgwrTriBH.rzMyA+3VtRNQAWaeICfoka0FoCNuLovN2ri3U8Ayh",
        "name": "ad do aliquip minim",
        "@baseType": "sit et id dolore",
        "@schemaLocation": "http://OEVrsMtaTZlyBNnNampnQUgQw.rvvvzYK7ra3qG9dnmY2.5rrTheeN0fV9HhT,6iPRBsVhp4Oz5Ku-a,vQ",
        "@type": "ad ut Duis",
        "@referredType": "Ut minim occaecat"
    },
    "applicableForParty": {
        "@referredType": "occaecat fugiat",
        "id": "Lorem labore",
        "href": "http://nTDhwhjcsCQEwWYGNoAoLUepvH.bgdps4dWvzM0KKEUVM+ctygU-zJAZXHcYPasXJKoT8nQk.ouJ30TzrZ3KoCjowYokoCvwDdl.n",
        "name": "Ut mollit",
        "role": "in aliquip occaecat et",
        "@baseType": "sit ",
        "@schemaLocation": "http://oZumTUjIziRhvDMMf.hliwddq1iSmKRxX7IPgab05Zm.F4R22CBN6",
        "@type": "eu nostrud laborum incididunt est"
    },
    "partyPrivacyProfileCharacteristic": [
        {
            "name": "dolore Excepteur velit qui",
            "value": {},
            "id": "voluptate",
            "privacyUsagePurpose": "labore Lorem laborum",
            "valueType": "commodo velit voluptate ut quis",
            "characteristicRelationship": [
                {
                    "id": "laboris aliquip Excepteur",
                    "href": "http://cYCUttzztkgDwH.ctzwHXezmw+33NOhnCG.8YF3Vnh-pAHgaq",
                    "relationshipType": "id voluptate qui in",
                    "@baseType": "laborum conse",
                    "@schemaLocation": "https://nHurBvCfLLIKenEOlcUYNaosi.lptsMFfthMPfObbAjAGIkfB1RGrIdvUy+MmYEjmnB6t5zZCfaUspTVb3KRssBJ",
                    "@type": "laborum dolore"
                },
                {
                    "id": "aute",
                    "href": "https://qYFwePdOWJXeUcnLGKlbTZwvRISofXI.yejp.Qtpp4YsWAMBD4W5rrg1x6YUMlVUXFPlniTLu9AJc",
                    "relationshipType": "ex",
                    "@baseType": "quis fugiat",
                    "@schemaLocation": "https://aBTvIy.zjZaGi6wXfEAZEpot,m8AT4iKINONdGed,6bYAqQ-whkiWMTGdA1aeI-9",
                    "@type": "ut in dolor officia"
                }
            ],
            "relatedParty": [
                {
                    "@referredType": "ipsum consequat voluptate non nisi",
                    "id": "irure consectetur sunt",
                    "href": "https://kFGIQlcIVoGyqMnGhEtvRxEe.fpoXIFxT.In1nP62kjJjP2-ejhkBrK1cFE",
                    "name": "Excepteur ullamco anim",
                    "role": "veniam",
                    "@baseType": "aute qui sed laboris",
                    "@schemaLocation": "https://lVBVej.jlcW+rFyusc4Clc5eb-vgvHYBECY2",
                    "@type": "voluptate tempor"
                },
                {
                    "@referredType": "nisi Duis",
                    "id": "amet es",
                    "href": "http://Qocd.essSHJGCpa9Sii9kwbYMuM6Tbz8Myg4K76s",
                    "name": "aliquip pariatur",
                    "role": "minim occaecat pariatur veniam",
                    "@baseType": "reprehenderit in",
                    "@schemaLocation": "https://TUKujKosOMUcOtJSclHSivDkZ.mhtfukUU8g4wPhzpkw3IjLTWOB+GKtYd+zZm04V0v",
                    "@type": "nulla sit"
                }
            ],
            "@baseType": "ut laborum magna",
            "@schemaLocation": "https://ZTbLgBSNcHphut.fgthxRp5uomtAAuefU3.YPaE,vs1c-",
            "@type": "a"
        },
        {
            "name": "id ut nostrud",
            "value": {},
            "id": "nostrud",
            "privacyUsagePurpose": "ea volu",
            "valueType": "ut cupidatat minim",
            "characteristicRelationship": [
                {
                    "id": "ea cillum",
                    "href": "https://kZvmNfWQJxZvlSsayQqirxq.bdvAvXLDmIbiWUoN1xamNgD1qDDWQzFNa3,ichXyLoOyjtDxVJUZMz9",
                    "relationshipType": "ut sit officia esse mollit",
                    "@baseType": "occaecat laborum ut quis dolor",
                    "@schemaLocation": "http://WBRnW.uysctFSp9pyW8-4JxPRELW+TkW-SLIExzslHvS3gNp0QX.0f0YPbKYHzaVvGa9",
                    "@type": "dolore proident"
                },
                {
                    "id": "dolore pariatur fugiat elit adipisicing",
                    "href": "https://KidZwIbvfNPn.xyalnpcD.ccUbJltj0H4LjjbHJ-0oNTj4",
                    "relationshipType": "laborum labore",
                    "@baseType": "dolor in",
                    "@schemaLocation": "http://M.royF6QBGq7JXf0-xYO0QMwCRg,TyELON8wvuM.j",
                    "@type": "ex nisi"
                }
            ],
            "relatedParty": [
                {
                    "@referredType": "dolor aliqua sunt amet id",
                    "id": "incididunt non cupidatat",
                    "href": "https://AEcrFasOULPeutZUrXQhgYmDyTX.njaqshaoa431qYfk.pDP,GYQlw+MwuOh2R",
                    "name": "Ut",
                    "role": "aute",
                    "@baseType": "reprehenderit ut",
                    "@schemaLocation": "https://VFjwGKEbtwMJMTdwkKd.ntpkjMCmc,u,jGR0krrUHsuYqf4fNkIZTGd80azIBzqn7tg,4jYaFIEK",
                    "@type": "qui ad"
                },
                {
                    "@referredType": "incididunt qui anim commodo",
                    "id": "pariatur ut consectetur exercitation",
                    "href": "https://sRpaIhsSSAoVHHWcokMghtr.pltiF+hOyF",
                    "name": "ea tempor",
                    "role": "esse",
                    "@baseType": "sit ut laborum",
                    "@schemaLocation": "http://WLHMhjXSxFUrDdSmfvn.ikkodDuvy70baUveoqlF8zaX",
                    "@type": "sed veniam ad est"
                }
            ],
            "@baseType": "ad minim Ut",
            "@schemaLocation": "https://euIfCNnavgmFCxyIzaQcNfi.zsbha7xc-6+gYcAb.ebcyrV3gOOQ,.oRD7ByOa8TPvzH0MTwjfyGKU3NGwMP2G-ZALt.37",
            "@type": "anim vol"
        }
    ],
    "partyPrivacyProfileSpecification": {
        "id": "sed e",
        "href": "http://KNcSQvIRYHBjdgWwxdwbetBNUggIlcsD.hauzHSLec4xZ7FhnxD2",
        "name": "aliqua sunt",
        "@baseType": "eiusmod",
        "@schemaLocation": "http://OgUkPjoYyMyFmMQHWtXtgpDRHZe.dixrqD2Ov8B..RhnEHBJEfbMjNgOk3uYNAXIBA4TxTrpL1vJph5UsBNiE0z6tJ1s-y0js9ZEC4YC",
        "@type": "magna irure pariatur consequat enim",
        "@referredType": "Lo"
    },
    "validFor": {
        "id": "in eiusmod",
        "href": "https://ktlmmX.atxyKKUurxI2VnkPmiKpe5IpP2WXpy0ORgs8oxCfrlN7ghcQGp12yCW+DECJL0",
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z",
        "@baseType": "culpa eu dolore",
        "@schemaLocation": "https://ofEC.zhI5ZRqXGTrE7wmn7XlmHdUbBqudRe",
        "@type": "Excepteur amet qui consectetur"
    },
    "@baseType": "minim ipsum quis",
    "@schemaLocation": "https://KcSvNlyPMhi.ciSEv4.D24waX.tUtvz4B6N+1LYT.eGZaLH",
    "@type": "sed minim non"
})


// This operation deletes a PartyPrivacyProfile entity.

@name("Deletes a PartyPrivacyProfile")
DELETE "https://{{baseUrl}}/partyPrivacyProfile/:id"



