#!/usr/bin/env dothttp

# imported from 35240-5093b8f4-a0f0-4f3c-ba64-865b352e5945.postman_collection.json

@name("Retrieve an application")
GET "https://{{baseUrl}}/applications/:id"
"Authorization": "ad cillum non laborum"


@name("Retrieve scorecards for an application")
GET "https://{{baseUrl}}/applications/:id/scorecards"
"Authorization": "ad cillum non laborum"
? "pageSize"= "ad cillum non laborum"
? "nextPage"= "ad cillum non laborum"
? "fields"= "ad cillum non laborum"



