#!/usr/bin/env dothttp

# imported from 35240-81e3517b-5c56-4500-b086-0e52eb5d86ca.postman_collection.json

// Authentification by refresh token.

@name("Authentification by refresh token")
POST "https://{{baseUrl}}/oauth/v1/token"
"Content": "<>"



