#!/usr/bin/env dothttp

# imported from 35240-3b61ade0-60b3-4dcc-a6b1-7acb55b522a0.postman_collection.json

// This will retrieve a list of backup_defintions from all vendors. To view backup_defintions for a particular vendor, see the vendors API. Records are returned in ascending order (by id), with a default of 20 per page. Links to the next, previous, first, and last pages can be found in the response headers.

@name("Retrieve an index of all backup_definitions")
GET "https://{{baseUrl}}/v1/backup_definitions"
"Authorization": "<>"
? "vendor_id"= "<get>"



