#!/usr/bin/env dothttp

# imported from 35240-396d9363-dad9-4f4b-8418-119dc20d1211.postman_collection.json

@name("Accept Certificate Transfer")
GET "https://{{aws_internet_of_things_base_url}}/accept-certificate-transfer/certificateId"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("Cancel Certificate Transfer")
GET "https://{{aws_internet_of_things_base_url}}/cancel-certificate-transfer/certificateId&certificateId="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("Reject Certificate Transfer")
GET "https://{{aws_internet_of_things_base_url}}/reject-certificate-transfer/certificateId&certificateId="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")



