#!/usr/bin/env dothttp

# imported from 35240-cc491087-45e6-46ba-aa93-9f2f2cc44068.postman_collection.json

// Get projects  hooks

@name("Get Projects  Hooks")
GET "https://{{baseUrl}}/projects/:id/hooks"
? "page"= "<>"
? "per_page"= "<>"


// Delete projects  hooks hook

@name("Delete Projects  Hooks Hook")
DELETE "https://{{baseUrl}}/projects/:id/hooks/:hook_id"



