#!/usr/bin/env dothttp

# imported from 35240-edf4e52a-d167-4c2f-bb89-c42269bd9481.postman_collection.json

// Returns comments of a track by track id

@name("Get Tracks Track Comments")
GET "https://{{baseUrl}}/tracks/:track_id/comments.json"
? "consumer_key"= "<>"


// Returns all users with permission for a track by track id

@name("Get Tracks Track Permissions")
GET "https://{{baseUrl}}/tracks/:track_id/permissions.json"
? "consumer_key"= "<>"


// Returns the secret token for a track by track id. This resource can only be used by the track owner.

@name("Get Tracks Track Secret Token")
GET "https://{{baseUrl}}/tracks/:track_id/secret-token.json"


// Returns comments of a track by track id

@name("Get Tracks Track Comments. Format")
GET "https://{{baseUrl}}/tracks/:track_id/comments.{{format}}"
? "consumer_key"= "<>"


// Returns all users with permission for a track by track id

@name("Get Tracks Track Permissions. Format")
GET "https://{{baseUrl}}/tracks/:track_id/permissions.{{format}}"
? "consumer_key"= "<>"


// Returns the secret token for a track by track id. This resource can only be used by the track owner.

@name("Get Tracks Track Secret Token. Format")
GET "https://{{baseUrl}}/tracks/:track_id/secret-token.{{format}}"



