#!/usr/bin/env dothttp

# imported from 35240-9d35e865-46d6-4c1a-9a52-45849e1f2947.postman_collection.json

// This endpoint lets you search for phone numbers by state or rate center, or by your specified search value.

@name("Search for Purchasable Phone Numbers")
GET "https://{{baseUrl}}/v2/numbers/available"
? "starts_with"= "<>"
? "contains"= "<>"
? "ends_with"= "<>"
? "limit"= "<>"
? "offset"= "<>"
? "rate_center"= "<>"
? "state"= "<>"


// Returns a list of all Numbering Plan Area (NPA) codes containing purchasable phone numbers.

@name("List Available Area Codes")
GET "https://{{baseUrl}}/v2/numbers/available/areacodes"
? "limit"= "<>"
? "offset"= "<>"
? "max_setup_cost"= "<>"


// Returns a list of all Central Office (exchange) codes containing purchasable phone numbers.

@name("List Available Exchange Codes")
GET "https://{{baseUrl}}/v2/numbers/available/exchanges"
? "limit"= "<>"
? "offset"= "<>"
? "max_setup_cost"= "<>"
? "areacode"= "<>"



