#!/usr/bin/env dothttp

# imported from 35240-5af4ed67-4654-4363-a86d-3c7bcff23c51.postman_collection.json

// Deletes an attribute map. The ID of the attribute and the ID of the market must be specified.

@name("Deletes an attribute map.")
DELETE "https://{{baseUrl}}/rest/items/attributes/:attributeId/markets/:marketId/maps"



