#!/usr/bin/env dothttp

# imported from 35240-a96221e2-b43c-4973-9be0-3ec0566f4cd9.postman_collection.json

// Create a new comment for an article.

@name("Create a new comment for an article")
POST "https://{{baseUrl}}/admin/comments.json"
"Content": "<>"


// Get a list of all comments.

@name("Get a list of all comments")
GET "https://{{baseUrl}}/admin/comments.json"
"Content": "<>"



