#!/usr/bin/env dothttp

# imported from 35240-9c081086-8dbf-4804-b7c8-4341ba1c240d.postman_collection.json

// Return contacts of an alliance
// 
// ---
// Alternate route: `/dev/alliances/{alliance_id}/contacts/`
// 
// Alternate route: `/v2/alliances/{alliance_id}/contacts/`
// 
// ---
// This route is cached for up to 300 seconds

@name("Get alliance contacts")
GET "https://{{baseUrl}}/alliances/:alliance_id/contacts/"
"If-None-Match": "commodo irure"
? "datasource"= "tranquility"
? "page"= "1"
? "token"= "commodo irure"


// Return custom labels for an alliance's contacts
// 
// ---
// Alternate route: `/dev/alliances/{alliance_id}/contacts/labels/`
// 
// Alternate route: `/legacy/alliances/{alliance_id}/contacts/labels/`
// 
// Alternate route: `/v1/alliances/{alliance_id}/contacts/labels/`
// 
// ---
// This route is cached for up to 300 seconds

@name("Get alliance contact labels")
GET "https://{{baseUrl}}/alliances/:alliance_id/contacts/labels/"
"If-None-Match": "commodo irure"
? "datasource"= "tranquility"
? "token"= "commodo irure"



