#!/usr/bin/env dothttp

# imported from 35240-582f30d6-554e-4cb2-a58f-34f9aa631c05.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


@name("Package License") : "base-inherit-auth"
GET "https://{{host}}/services/data/v47.0/sobjects/PackageLicense/"


@name("Package License Detail") : "base-inherit-auth"
GET "https://{{host}}/services/data/v47.0/sobjects/PackageLicense/{ID}/"


@name("Describe Package License") : "base-inherit-auth"
GET "https://{{host}}/services/data/v47.0/sobjects/PackageLicense/describe/"



