#!/usr/bin/env dothttp

# imported from 35240-97c6871f-8a54-42bd-a4f1-a3ada62aa1b0.postman_collection.json

// List all versions of a Query Lambda.

@name("List Query Lambda Versions")
GET "https://{{baseUrl}}/v1/orgs/self/ws/:workspace/lambdas/:queryLambda/versions"


// Create a new version of a Query Lambda in given workspace.

@name("Update Query Lambda")
POST "https://{{baseUrl}}/v1/orgs/self/ws/:workspace/lambdas/:queryLambda/versions"
"Content-Type": "application/json"
? "create"= "true"
json({
    "description": "production version foo",
    "sql": {
        "query": "SELECT 'Foo'",
        "default_parameters": [
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            }
        ]
    }
})



