#!/usr/bin/env dothttp

# imported from 35240-6765e1cc-2c5d-40bb-8932-494c6fbb000a.postman_collection.json

// Move lists to folder

@name("Move lists to folder")
POST "https://{{baseUrl}}/api/v1/contacts/folders/:folderId/lists"
"Authorization": "Bearer <Bearer Token>"
"Content-Type": "application/json"
json({
    "listsIds": [
        "irure",
        "enim consequat"
    ]
})


// Retrive all lists related to folder

@name("Get folder lists")
GET "https://{{baseUrl}}/api/v1/contacts/folders/:folderId/lists"
"Authorization": "Bearer <Bearer Token>"


// Remove lists from folder

@name("Remove lists from folder")
DELETE "https://{{baseUrl}}/api/v1/contacts/folders/:folderId/lists"
"Authorization": "Bearer <Bearer Token>"
"Content-Type": "application/json"
json({
    "listsIds": [
        "magna dolore",
        "Duis do quis"
    ]
})



