#!/usr/bin/env dothttp

# imported from 35240-cfd5624c-b930-4725-aa14-55f9a44206d1.postman_collection.json

// Create a job using the given settings.

@name("Create PDF stamper job")
POST "https://{{baseUrl}}/jobs"



