#!/usr/bin/env dothttp

# imported from 35240-cc40b3de-1093-44e1-94c4-498c2fe3c9bb.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"
basicauth("{{atlassian_email}}", "{{atlassian_token}}")


// Returns the [project's sender email address](https://confluence.atlassian.com/x/dolKLg).
// 
// **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.

@name("Get Project's Sender Email") : "base-inherit-auth"
GET "https://{{baseUrl}}/rest/api/3/project/:projectId/email"


// Sets the [project's sender email address](https://confluence.atlassian.com/x/dolKLg).
// 
// If `emailAddress` is an empty string, the default email address is restored.
// 
// **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.

@name("Set Project's Sender Email") : "base-inherit-auth"
PUT "https://{{baseUrl}}/rest/api/3/project/:projectId/email"
"Content-Type": "application/json"
json({
    "emailAddress": "<string>"
})



