#!/usr/bin/env dothttp

# imported from 35240-b8e673bd-409c-4ff2-af9c-bb3a976bd9dd.postman_collection.json

@name("Get Account Settings")
POST "https://{{aws_device_farm_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_device_farm_service}}", region="{{aws_device_farm_region}}")
? "Action"= "GetAccountSettings"
? "Version"= "2015-06-23"
data('{
   "accountSettings": { 
      "awsAccountNumber": "string",
      "defaultJobTimeoutMinutes": number,
      "maxJobTimeoutMinutes": number,
      "maxSlots": { 
         "string" : number 
      },
      "skipAppResign": boolean,
      "trialMinutes": { 
         "remaining": number,
         "total": number
      },
      "unmeteredDevices": { 
         "string" : number 
      },
      "unmeteredRemoteAccessDevices": { 
         "string" : number 
      }
   }
}')



