#!/usr/bin/env dothttp

# imported from 35240-afbc2083-42c9-4108-83db-0b859aa69233.postman_collection.json

@name("Attach Group Policy")
GET "https://{{aws_identtity_and_access_management_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_identtity_and_access_management_service}}", region="{{aws_identtity_and_access_management_region}}")
? "Version"= "2010-05-08"


@name("Delete Group Policy")
GET "https://{{aws_identtity_and_access_management_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_identtity_and_access_management_service}}", region="{{aws_identtity_and_access_management_region}}")
? "Version"= "2010-05-08"


@name("Detach Group Policy")
GET "https://{{aws_identtity_and_access_management_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_identtity_and_access_management_service}}", region="{{aws_identtity_and_access_management_region}}")
? "Version"= "2010-05-08"


@name("Get Group Policy")
GET "https://{{aws_identtity_and_access_management_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_identtity_and_access_management_service}}", region="{{aws_identtity_and_access_management_region}}")
? "Version"= "2010-05-08"


@name("Put Group Policy")
GET "https://{{aws_identtity_and_access_management_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_identtity_and_access_management_service}}", region="{{aws_identtity_and_access_management_region}}")
? "Version"= "2010-05-08"



