#!/usr/bin/env dothttp

# imported from 35240-04144c4b-1296-424d-8a98-b2ae6373c414.postman_collection.json

// Enumerate ManagedZones that have been created but not yet deleted.

@name("Get Managed Zones")
GET "https://{{baseUrl}}/:project/managedZones"
? "dnsName"= "<parameters>"
? "maxResults"= "<>"
? "pageToken"= "<>"



