#!/usr/bin/env dothttp

# imported from 35240-d1558e58-fe26-4cd3-9c99-0411fa0967e1.postman_collection.json

// Lists all the available Cognitive Services account operations.

@name("Operations List")
GET "https://{{baseUrl}}/providers/Microsoft.CognitiveServices/operations"



