#!/usr/bin/env dothttp

# imported from 35240-2f393c49-f959-4f18-bf04-79f6c8910daa.postman_collection.json

@name("Get Id")
POST "https://{{aws_cognito_federated_identities_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_cognito_federated_identities_service}}", region="{{aws_cognito_federated_identities_region}}")
"X-AMZ-TARGET": "com.amazonaws.cognito.identity.model.AWSCognitoIdentityService.GetId"
"Content-Type": "application/x-amz-json-1.1"
? "Action"= "GetId"
data('{
    "AccountId": "123456789012",
    "IdentityPoolId": "us-east-1:177a950c-2c08-43f0-9983-28727EXAMPLE"
}')



