#!/usr/bin/env dothttp

# imported from 35240-20eaed55-6256-4049-a8c9-74a7e5e0ac65.postman_collection.json

@name("Obtain a boxscore for a specific MLB game.")
GET "https://{{baseUrl}}/mlb-t6/games/:event_id/boxscore{{format}}"


@name("Obtain a game summary for a specific MLB game.")
GET "https://{{baseUrl}}/mlb-t6/games/:event_id/summary{{format}}"


// Obtain the play-by-play data for a specific MLB game.

@name("Obtain the play-by-play data for a specific MLB ga...")
GET "https://{{baseUrl}}/mlb-t6/games/:event_id/pbp{{format}}"



