#!/usr/bin/env dothttp

# imported from 35240-02fae580-11a1-41da-afdc-655537d58f8f.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// This endpoint shows information about an editorial image, including a URL to a preview image and the sizes that it is available in.

@name("Get editorial content details") : "base-inherit-auth"
GET "https://{{baseUrl}}/v2/editorial/images/:id"
? "country"= "<country-code-3>"



