#!/usr/bin/env dothttp

# imported from 35240-edf4e52a-d167-4c2f-bb89-c42269bd9481.postman_collection.json

// Returns a user by user id

@name("Get Users")
GET "https://{{baseUrl}}/users/{{user_id}}.json"
? "consumer_key"= "<>"


// Returns a user by user id

@name("Get Users . Format")
GET "https://{{baseUrl}}/users/{{user_id}}.{{format}}"
? "consumer_key"= "<>"



