#!/usr/bin/env dothttp

# imported from 35240-915791f2-3848-4b1a-8980-931a3ff18cd1.postman_collection.json

// Post shipping group.

@name("Post Shipping Group")
POST "https://{{baseUrl}}/shipping/:cartId/group"
? "priceOrder"= "<>"



