#!/usr/bin/env dothttp

# imported from 35240-c446a4c9-8dd6-45c4-99f2-688a96fe76ae.postman_collection.json

// Lists the people who the authenticated user follows.

@name("List the people the authenticated user follows")
GET "https://{{baseUrl}}/user/following"
? "per_page"= "30"
? "page"= "1"



