#!/usr/bin/env dothttp

# imported from 35240-3de643e0-77af-41e6-9270-0b386f4ca61d.postman_collection.json

// Get a specific MonetaryAccountSavings.

@name("READ Monetary Account Savings for User")
GET "https://{{baseUrl}}/user/:userID/monetary-account-savings/:itemId"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"


// Update a specific existing MonetaryAccountSavings.

@name("UPDATE Monetary Account Savings for User")
PUT "https://{{baseUrl}}/user/:userID/monetary-account-savings/:itemId"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"
"Content-Type": "application/json"
json({
    "currency": "<string>",
    "all_co_owner": [
        {
            "alias": {
                "avatar": {
                    "anchor_uuid": "est ad irure proident",
                    "image": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "uuid": "<string>"
                },
                "country": "laboris",
                "display_name": "culpa elit",
                "public_nick_name": "amet aliqua aliquip",
                "uuid": "occaecat esse Excepteur"
            },
            "status": "ad"
        },
        {
            "alias": {
                "avatar": {
                    "anchor_uuid": "Duis in dolor",
                    "image": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "uuid": "<string>"
                },
                "country": "enim l",
                "display_name": "minim Duis",
                "public_nick_name": "ullamco ad",
                "uuid": "ullamco amet proident in mollit"
            },
            "status": "Duis fugiat veniam"
        }
    ],
    "avatar_uuid": "<string>",
    "daily_limit": {
        "currency": "nisi cupidatat",
        "value": "id ipsum eu"
    },
    "description": "<string>",
    "reason": "<string>",
    "reason_description": "<string>",
    "savings_goal": {
        "currency": "voluptate laborum ad",
        "value": "cillum adipisicing"
    },
    "setting": {
        "color": "exercitation ea laboris nisi",
        "default_avatar_status": "aute nisi anim",
        "icon": "ex anim",
        "restriction_chat": "pariatur eiusmod sit"
    },
    "status": "<string>",
    "sub_status": "<string>"
})



