#!/usr/bin/env dothttp

# imported from 35240-152a01a0-5a89-47e3-8c66-2f1e0de12c73.postman_collection.json

// Get Registrant

@name("Get Registrant")
GET "https://{{baseUrl}}/:username/events/:event-id/registrants/:registrant-id"


// Get Attendance Status

@name("Get Attendance Status")
GET "https://{{baseUrl}}/:username/events/:event-id/registrants/:registrant-id/attendancestatus"


// Get Payment Status

@name("Get Payment Status")
GET "https://{{baseUrl}}/:username/events/:event-id/registrants/:registrant-id/paymentstatus"



