#!/usr/bin/env dothttp

# imported from 35240-cc491087-45e6-46ba-aa93-9f2f2cc44068.postman_collection.json

// Get the list of users

@name("Get Users")
GET "https://{{baseUrl}}/users"
? "username"= "<get>"
? "search"= "<>"
? "active"= "<get>"
? "external"= "<get>"
? "blocked"= "<>"
? "page"= "<>"
? "per_page"= "<>"



