#!/usr/bin/env dothttp

# imported from 35240-4cff9dbd-dc9e-457a-8421-41b9b4a7bdef.postman_collection.json

// Get SAML metadata from the server. SAML must be configured properly.n##### PermissionsnNo permission required.n

@name("Get metadata")
GET "https://{{baseUrl}}/saml/metadata"



