#!/usr/bin/env dothttp

# imported from 35240-5644cab0-9c66-4267-8edc-0eb31fcb9896.postman_collection.json

// Warp subject and reference arrays.

@name("Warp subject and reference arrays")
POST "https://{{baseUrl}}/warp"



