#!/usr/bin/env dothttp

# imported from 35240-07b8f9ff-4fab-4f58-a64e-0549bc880422.postman_collection.json

// Get any useru2019s public information with their ID.

@name("Show a user")
GET "https://{{baseUrl}}/users/:user_id"



