#!/usr/bin/env dothttp

# imported from 35240-8824bc37-1915-40a8-a822-a8c05d269e34.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"
basicauth("{{atlassian_email}}", "{{atlassian_token}}")


// Edits an issue. A transition may be applied and issue properties updated as part of the edit.
// 
// The edits to the issue's fields are defined using `update` and `fields`. The fields that can be edited are determined using [ Get edit issue metadata](#api-rest-api-3-issue-issueIdOrKey-editmeta-get).
// 
// The parent field may be set by key or ID. For standard issue types, the parent may be removed by setting `update.parent.set.none` to *true*. Note that the `description`, `environment`, and any `textarea` type custom fields (multi-line text fields) take Atlassian Document Format content. Single line custom fields (`textfield`) accept a string and don't handle Atlassian Document Format content.
// 
// Connect app users with admin permissions (from user permissions and app scopes) can override the screen security configuration using `overrideScreenSecurity` and `overrideEditableFlag`.
// 
// This operation can be accessed anonymously.
// 
// **[Permissions](#permissions) required:**
// 
//  *  *Browse projects* and *Edit issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.
//  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.

@name("Update the Summary for An Issue") : "base-inherit-auth"
PUT "https://{{baseUrl}}/rest/api/3/issue/:issueIdOrKey"
"Content-Type": "application/json"
? "notifyUsers"= "true"
? "overrideScreenSecurity"= "false"
? "overrideEditableFlag"= "false"
json({
    "fields": {
        "summary": "Summary Description"
    }
})



