#!/usr/bin/env dothttp

# imported from 35240-af938bfe-d636-455e-9182-83ae080c0f19.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"
"Authorization": "Bearer <Bearer Token>"


// Retrieves a list of table spaces for a named domain.

@name("Get list of table spaces for a domain") : "base-inherit-auth"
GET "https://{{baseUrl}}/v1/domains/:domainname/tablespace"
"Authorization": "Bearer <Bearer Token>"



