#!/usr/bin/env dothttp

# imported from 35240-c68e2fa9-6659-44c8-b526-051d761f5037.postman_collection.json

// <p>The <code>Get user</code> call returns comprehensive information of an existing user account. The information returned includes details of the stacks owned by and shared with the specified user account.<br><p>To use the API Request, you will need to authenticate yourself either with a&nbsp;<a href="https://www.contentstack.com/docs/developers/create-tokens/about-management-tokens">Management Token (highly recommended)</a>&nbsp;or an <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#how-to-get-authtoken">Authtoken.</a>&nbsp;<br>Read more about it in <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#authentication">Authentication.</a>
// </p><br>
//                           For more information, refer to the <a href=www.contentstack.com/docs/developers/apis/content-management-api/#get-user>Get User</a> API Reference document

@name("Get user")
GET "https://{{base_url}}/v3/user"
"authtoken": "{{authtoken}}"
"Content-Type": "application/json"


// <p>The <code>Update User</code> API Request updates the details of an existing user account. Only the&nbsp;information entered here will be updated, the existing data will remain unaffected.<br><p>To use the API Request, you will need to authenticate yourself either with a&nbsp;<a href="https://www.contentstack.com/docs/developers/create-tokens/about-management-tokens">Management Token (highly recommended)</a>&nbsp;or an <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#how-to-get-authtoken">Authtoken.</a>&nbsp;<br>Read more about it in <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#authentication">Authentication.</a>
// </p><br>
//                           For more information, refer to the <a href=www.contentstack.com/docs/developers/apis/content-management-api/#update-user>Update User</a> API Reference document

@name("Update user")
PUT "https://{{base_url}}/v3/user"
"authtoken": "{{authtoken}}"
"Content-Type": "application/json"
json({
    "user": {
        "company": "company name inc."
    }
})


// <p>The <code>Activate a user account</code> call activates the account of a user after signing up. For account activation, you will require the token received in the activation email.
// <br><p>To use the API Request, you will need to authenticate yourself either with a&nbsp;<a href="https://www.contentstack.com/docs/developers/create-tokens/about-management-tokens">Management Token (highly recommended)</a>&nbsp;or an <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#how-to-get-authtoken">Authtoken.</a>&nbsp;<br>Read more about it in <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#authentication">Authentication.</a>
// </p><br>
//                           For more information, refer to the <a href=www.contentstack.com/docs/developers/apis/content-management-api/#activate-user>Activate User</a> API Reference document

@name("Activate a user account")
POST "https://{{base_url}}/v3/user/activate/{{user_activation_token}}"
"Content-Type": "application/json"
json({
    "user": {
        "first_name": "your_first_name",
        "last_name": "your_last_name",
        "password": "your_password",
        "password_confirmation": "confirm_your_password"
    }
})


// <p>The <code>Request for a password</code> call sends a request for a temporary password to log in to an account in case a user has forgotten the login password.
// <br><p>To use the API Request, you will need to authenticate yourself either with a&nbsp;<a href="https://www.contentstack.com/docs/developers/create-tokens/about-management-tokens">Management Token (highly recommended)</a>&nbsp;or an <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#how-to-get-authtoken">Authtoken.</a>&nbsp;<br>Read more about it in <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#authentication">Authentication.</a>
// </p><br>
//                           For more information, refer to the <a href=www.contentstack.com/docs/developers/apis/content-management-api/#request-password>Request Password</a> API Reference document

@name("Request for a password")
POST "https://{{base_url}}/v3/user/forgot_password"
"Content-Type": "application/json"
json({
    "user": {
        "email": "john.doe@contentstack.com"
    }
})


// <p>The <code>Reset password</code> call sends a request for resetting the password of your Contentstack account.
// <br><p>To use the API Request, you will need to authenticate yourself either with a&nbsp;<a href="https://www.contentstack.com/docs/developers/create-tokens/about-management-tokens">Management Token (highly recommended)</a>&nbsp;or an <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#how-to-get-authtoken">Authtoken.</a>&nbsp;<br>Read more about it in <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#authentication">Authentication.</a>
// </p><br>
//                           For more information, refer to the <a href=www.contentstack.com/docs/developers/apis/content-management-api/#reset-password>Reset Password</a> API Reference document

@name("Reset password")
POST "https://{{base_url}}/v3/user/reset_password"
"Content-Type": "application/json"
json({
    "user": {
        "reset_password_token": "abcdefghijklmnop1234567890",
        "password": "Simple@123",
        "password_confirmation": "Simple@123"
    }
})



