#!/usr/bin/env dothttp

# imported from 35240-7d2c214b-77c4-4e90-8dc4-3cd4493a1c9a.postman_collection.json

// Pulls the accreditation for a startup and users.

@name("Get Accreditation")
GET "https://{{baseUrl}}/accreditation"


// Add like.

@name("Add Like")
POST "https://{{baseUrl}}/like"
? "likable_id"= "<>"
? "likable_type"= "<>"


// Get Me

@name("Get Me")
GET "https://{{baseUrl}}/me"


// Get Startup Roles

@name("Get Startup Roles")
GET "https://{{baseUrl}}/startup_roles"
? "startup_id"= "<get>"
? "v"= "<>"



