#!/usr/bin/env dothttp

# imported from 35240-93f02d77-d29c-4b5c-8f98-5e285995302f.postman_collection.json

// Parameters can be one of the following: rnXXXXXXX for US registration number, snXXXXXXXX for US serial number, refXXXXXXXX and irXXXXXXX for Madrid numbers. Example: https://tsdrapi.uspto.gov/ts/cd/casedocs/sn78787878/bundle

@name("Returns information about the searched document in the case in XML format.")
GET "https://{{baseUrl}}/casedocs/:caseid/bundle"


// Parameters can be one of the following: rnXXXXXXX for US registration number, snXXXXXXXX for US serial number, refXXXXXXXX and irXXXXXXX for Madrid numbers. Example: https://tsdrapi.uspto.gov/ts/cd/casedocs/sn78787878/content.pdf

@name("Returns information about all documents in the case in PDF format.")
GET "https://{{baseUrl}}/casedocs/:caseid/content.pdf"


// Parameters can be one of the following: rnXXXXXXX for US registration number, snXXXXXXXX for US serial number, refXXXXXXXX and irXXXXXXX for Madrid numbers. Example: https://tsdrapi.uspto.gov/ts/cd/casedocs/sn78787878/content.zip

@name("Returns information about all documents in the case in ZIP format.")
GET "https://{{baseUrl}}/casedocs/:caseid/content.zip"


// Parameters can be one of the following: rnXXXXXXX for US registration number, snXXXXXXXX for US serial number, refXXXXXXXX and irXXXXXXX for Madrid numbers. Example: https://tsdrapi.uspto.gov/ts/cd/casedocs/sn78787878/download.pdf

@name("Returns information about all documents in the case in PDF format.")
GET "https://{{baseUrl}}/casedocs/:caseid/download.pdf"


// Parameters can be one of the following: rnXXXXXXX for US registration number, snXXXXXXXX for US serial number, refXXXXXXXX and irXXXXXXX for Madrid numbers. Example: https://tsdrapi.uspto.gov/ts/cd/casedocs/sn78787878/download.zip

@name("Returns information about all documents in the case in ZIP format.")
GET "https://{{baseUrl}}/casedocs/:caseid/download.zip"


@name("Returns information about all documents in the case in XML format.")
GET "https://{{baseUrl}}/casedocs/:caseid/info"



