#!/usr/bin/env dothttp

# imported from 35240-c5e56645-bf09-4e5c-8f01-15f069cbfb0f.postman_collection.json

// Parameters user keys.

@name("Parameters User Keys")
GET "https://{{baseUrl}}/user/keys"


// Parameters user keys key.

@name("Parameters User Keys Key")
GET "https://{{baseUrl}}/user/keys/:key"



