#!/usr/bin/env dothttp

# imported from 35240-daa7ecf3-bea2-44a6-8a62-868217e1296e.postman_collection.json

// Returns an array containing the names of all asset collections for thenspecified customer.n

@name("List all asset collections for a customer")
GET "https://{{baseUrl}}/v1/collections"



