#!/usr/bin/env dothttp

# imported from 35240-83d768b1-950f-434d-8ea8-e2e63edbcbef.postman_collection.json

// Returns a list of schools

@name("get Schools")
GET "https://{{baseUrl}}/schools"
? "limit"= "<integer>"
? "starting_after"= "<string>"
? "ending_before"= "<string>"
? "where"= "<string>"



