#!/usr/bin/env dothttp

# imported from 35240-e04c6fb1-e891-4983-80ec-38175b6c944e.postman_collection.json

// Get api operations.

@name("Get API Operations")
GET "https://{{baseUrl}}/api/Operations/:id"
"Authorization": "<>"


// Add api operations  cancel.

@name("Add API Operations  Cancel")
POST "https://{{baseUrl}}/api/Operations/:id/cancel"
"Authorization": "<>"



