#!/usr/bin/env dothttp

# imported from 35240-5af4ed67-4654-4363-a86d-3c7bcff23c51.postman_collection.json

// Deletes an export. The ID of the export must be specified.

@name("Delete export")
DELETE "https://{{baseUrl}}/rest/exports/:exportId"



