#!/usr/bin/env dothttp

# imported from 35240-152a01a0-5a89-47e3-8c66-2f1e0de12c73.postman_collection.json

// Get All Mailing Lists

@name("Get All Mailing Lists")
GET "https://{{baseUrl}}/:username/lists"



