#!/usr/bin/env dothttp

# imported from 35240-b4284fc2-719c-44f6-8790-5e73e68963c4.postman_collection.json

// Retrieves the metadata for the draft schema definition with the
// specified id.

@name("Get draft schema definition metadata")
GET "https://{{baseUrl}}/draft/schemas/:schemaId"


// Retrieves the content of the draft schema definition file with the
// specified id.

@name("Get the contents of the draft schema definition file")
GET "https://{{baseUrl}}/draft/schemas/:schemaId/content"



