#!/usr/bin/env dothttp

# imported from 35240-5af4ed67-4654-4363-a86d-3c7bcff23c51.postman_collection.json

// Get export keys.

@name("Get Export Keys")
GET "https://{{baseUrl}}/export/:exportKey"


// Get export keys..

@name("Get Export Key")
GET "https://{{baseUrl}}/export/:exportKey/:token"



