#!/usr/bin/env dothttp

# imported from 35240-1f22e2cb-c653-40b3-ae3e-8b9e732d13bc.postman_collection.json

// Clock punch event instance

@name("Clock Punch")
POST "https://{{baseUrl}}/events/time/v1/clock.punch"
? "No Name"= "<string>"


// Retrieve event metadata

@name("Clock Punch Meta")
GET "https://{{baseUrl}}/events/time/v1/clock.punch/meta"
? "No Name"= "<string>"



