#!/usr/bin/env dothttp

# imported from 35240-3b61ade0-60b3-4dcc-a6b1-7acb55b522a0.postman_collection.json

// Only backup_instances you have permission to view will be returned

@name("Retrieve a backup_instance by backup_instance_id")
GET "https://{{baseUrl}}/v1/backup_instances/:backup_instance_id"
"Authorization": "<>"



