#!/usr/bin/env dothttp

# imported from 35240-4295a9be-5ee4-4ee8-bfc7-54202492a909.postman_collection.json

@name("Put Action Revision")
POST "https://{{aws_codepipeline_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_codepipeline_service}}", region="{{aws_codepipeline_region}}")
"Content-Type": "application/x-amz-json-1.1"
"User-Agent": "aws-cli/1.7.38 Python/2.7.9 Windows/7"
"X-Amz-Target": "CodePipeline_20150709.PutActionRevision"
? "Action"= "PutActionRevision"
data('{
   "actionName": "Source",
   "actionRevision": { 
      "created": 1446726163.571,
	  "revisionChangeId": "3fdd7b9196697a096d5af1d649e26a4a",
      "revisionId": "HYGp7zmwbCPPwo234xsCEM7d6ToeAqIl"
   },
   "pipelineName": "MyFirstPipeline",
   "stageName": "Staging"
}')



