#!/usr/bin/env dothttp

# imported from 35240-87a729f1-d8d7-41e7-be76-efdf141cf643.postman_collection.json

@name("Query")
GET "http://stats.oecd.org/SDMX-JSON/data/:dataset identifier/:filter expression/:agency name"
? "startTime"= "2009-Q2"
? "endTime"= "2011-Q4"
? "detail"= "serieskeysonly"



@name("All")
GET "http://stats.oecd.org/sdmx-json/data/QNA/all/all"
? "endTime"= "2011-Q4"
? "startTime"= "2009-Q1"




