#!/usr/bin/env dothttp

# imported from 35240-2fb0962b-7d35-49c0-8ec6-311647bcabe4.postman_collection.json

// Delete tenant credentials .

@name("Delete tenant credentials ")
DELETE "https://{{baseUrl}}/v1/client-credentials/client-ids/:clientId"
"TMS": "<>"


// Delete tenant credentials .

@name("Delete tenant credentials ")
DELETE "https://{{baseUrl}}/v1/client-credentials/client-ids/:clientId/authorized-clients/:authorizedClientId"
"TMS": "<>"



