#!/usr/bin/env dothttp

# imported from 35240-396d9363-dad9-4f4b-8418-119dc20d1211.postman_collection.json

@name("Create Policy Version")
GET "https://{{aws_internet_of_things_base_url}}/policies/policyName/version"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("Delete Policy Version")
GET "https://{{aws_internet_of_things_base_url}}/policies/policyName/version/policyVersionId&policyName=&policyVersionId="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("Get Policy Version")
GET "https://{{aws_internet_of_things_base_url}}/policies/policyName/version/policyVersionId&policyName=&policyVersionId="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("List Policy Versions")
GET "https://{{aws_internet_of_things_base_url}}/policies/policyName/version&policyName="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")



