#!/usr/bin/env dothttp

# imported from 35240-572303ba-d57b-42f8-9c05-98fcc3c05154.postman_collection.json

// Gets all `Server Group` objects for authenticated usern

@name("Get Servergroups")
GET "https://{{baseUrl}}/servergroups"
? "o"= "<>"


// Gets a specific `Server Group` object for the authenticated user.n

@name("Get Servergroups")
GET "https://{{baseUrl}}/servergroups/:id"
? "o"= "<>"



