#!/usr/bin/env dothttp

# imported from 35240-940631ab-b80d-496e-a8ee-7bdf98c1ca94.postman_collection.json

// Returns an array of maps for the specified customer. The array containsnthe name and identifier for each map.n

@name("List all maps for a customer")
GET "https://{{baseUrl}}/v1/maps"



