#!/usr/bin/env dothttp

# imported from 35240-22a10f2d-8624-488d-95c0-85a6c45216c5.postman_collection.json

// Retrieve the draft thing type with the specified id.n

@name("Get a draft thing type")
GET "https://{{baseUrl}}/draft/thing/types/:thingTypeId"



