#!/usr/bin/env dothttp

# imported from 35240-2b30fdb4-df71-430c-bca5-582cc0c9e09b.postman_collection.json

@name("Deregister Ecs Cluster")
POST "https://{{aws_opsworks_cm_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_opsworks_cm_service}}", region="{{aws_opsworks_cm_region}}")
? "Version"= "2013-02-18"
data('{"EcsClusterArn":"string"}')


@name("Describe Ecs Clusters")
POST "https://{{aws_opsworks_cm_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_opsworks_cm_service}}", region="{{aws_opsworks_cm_region}}")
? "Version"= "2013-02-18"
data('{"EcsClusterArns":["string"],"MaxResults":42,"NextToken":"string","StackId":"string"}')


@name("Register Ecs Cluster")
POST "https://{{aws_opsworks_cm_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_opsworks_cm_service}}", region="{{aws_opsworks_cm_region}}")
? "Version"= "2013-02-18"
data('{"EcsClusterArn":"string","StackId":"string"}')



