#!/usr/bin/env dothttp

# imported from 35240-9cd3d393-331a-43bc-b306-c5d3f7618e89.postman_collection.json

@name("Retrieve all linked WebServices for the specified Reference.")
GET "https://{{baseUrl}}/rest/Reference/:referenceId/WebServices"


@name("Retrieve a Web Service (link) by its Resource Id.")
GET "https://{{baseUrl}}/rest/Reference/:referenceId/WebServices/:resourceId"



