#!/usr/bin/env dothttp

# imported from 35240-396d9363-dad9-4f4b-8418-119dc20d1211.postman_collection.json

@name("Create Scheduled Audit")
GET "https://{{aws_internet_of_things_base_url}}/audit/scheduledaudits/scheduledAuditName&scheduledAuditName="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("Delete Scheduled Audit")
GET "https://{{aws_internet_of_things_base_url}}/audit/scheduledaudits/scheduledAuditName&scheduledAuditName="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("Describe Scheduled Audit")
GET "https://{{aws_internet_of_things_base_url}}/audit/scheduledaudits/scheduledAuditName&scheduledAuditName="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("List Scheduled Audits")
GET "https://{{aws_internet_of_things_base_url}}/audit/scheduledaudits"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("Update Scheduled Audit")
GET "https://{{aws_internet_of_things_base_url}}/audit/scheduledaudits/scheduledAuditName&scheduledAuditName="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")



