#!/usr/bin/env dothttp

# imported from 35240-9b526cd3-0f35-4ef8-ad1e-b13d97933210.postman_collection.json

@name("Create DB Cluster Endpoint")
GET "https://{{aws_rds_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_rds_service}}", region="{{aws_rds_region}}")
? "Action"= "CreateDBClusterEndpoint"
? "Version"= "2014-10-31"


@name("Delete DB Cluster Endpoint")
GET "https://{{aws_rds_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_rds_service}}", region="{{aws_rds_region}}")
? "Action"= "DeleteDBClusterEndpoint"
? "Version"= "2014-10-31"


@name("Describe DB Cluster Endpoints")
GET "https://{{aws_rds_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_rds_service}}", region="{{aws_rds_region}}")
? "Action"= "DescribeDBClusterEndpoints"
? "Version"= "2014-10-31"


@name("Modify DB Cluster Endpoint")
GET "https://{{aws_rds_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_rds_service}}", region="{{aws_rds_region}}")
? "Action"= "ModifyDBClusterEndpoint"
? "Version"= "2014-10-31"



