#!/usr/bin/env dothttp

# imported from 35240-078f0c0e-f03d-4124-bda1-c7d8042a0e64.postman_collection.json

// Retrieves the demographics info for the specified party..

@name("Retrieves the demographics info for the specified party.")
GET "https://{{baseUrl}}/demographics/ehr/:ehrId/party"
? "when"= "<>"



