#!/usr/bin/env dothttp

# imported from 35240-6990c4c3-ec47-4850-8d11-1a18a1fbabeb.postman_collection.json

// Delete this application.

@name("/Accounts/:AccountSid/Applications/{{ApplicationSid}}{{mediaTypeExtension}}")
DELETE "https://{{baseUrl}}/Accounts/:AccountSid/Applications/{{ApplicationSid}}{{mediaTypeExtension}}"


// Delete this application.

@name("Accounts.Account Sid.Applications.Application Sid.json.delete")
DELETE "https://{{baseUrl}}/Accounts/:AccountSid/Applications/{{ApplicationSid}}.json"



