#!/usr/bin/env dothttp

# imported from 35240-62c6cc63-de15-4694-9302-08ed4981816f.postman_collection.json

// Returns a paginated list of brands.

@name("Get a list of all current brands.")
GET "https://{{baseUrl}}/brands"
? "page"= "<>"
? "count"= "<get>"
? "sort"= "<>"



