#!/usr/bin/env dothttp

# imported from 35240-af938bfe-d636-455e-9182-83ae080c0f19.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"
"Authorization": "Bearer <Bearer Token>"


// Get a location bi detail

@name("Get a location bi detail") : "base-inherit-auth"
GET "https://{{baseUrl}}/v1/locations/:id/locationbidetail/:locationbidetailid"
"Authorization": "Bearer <Bearer Token>"
? "datasource"= "Excepteur nisi in"


// Updates bi detail

@name("Updates bi detail") : "base-inherit-auth"
PUT "https://{{baseUrl}}/v1/locations/:id/locationbidetail/:locationbidetailid"
"Authorization": "Bearer <Bearer Token>"
"Content-Type": "application/json"
? "datasource"= "Excepteur nisi in"
json({
    "id": 34935164,
    "redundancy": {
        "id": 46569765,
        "code": "dolor ullamco consequat",
        "name": "irure"
    },
    "siWaitingPeriod": 14299701.177770078,
    "siLimit": -67374696.9950046,
    "preparedness": {
        "id": 57897669,
        "code": "est proident",
        "name": "enim anim consectetur ut"
    },
    "serviceInterruption": {
        "id": -89632259,
        "code": "eu s",
        "name": "sint aute"
    },
    "isValid": true
})


// Deletes a location bi detail

@name("Deletes a location bi detail") : "base-inherit-auth"
DELETE "https://{{baseUrl}}/v1/locations/:id/locationbidetail/:locationbidetailid"
"Authorization": "Bearer <Bearer Token>"
? "datasource"= "Excepteur nisi in"



