#!/usr/bin/env dothttp

# imported from 35240-5af4ed67-4654-4363-a86d-3c7bcff23c51.postman_collection.json

// List categories.

@name("List categories")
GET "https://{{baseUrl}}/rest/categories"
? "categoryId"= "<post>"
? "page"= "<post>"
? "itemsPerPage"= "<>"
? "with"= "<>"
? "lang"= "<post>"
? "type"= "<post>"
? "parentId"= "<post>"
? "plentyId"= "<post>"
? "name"= "<post>"
? "level"= "<post>"
? "linklist"= "<post>"
? "updatedAt"= "<post>"



