#!/usr/bin/env dothttp

# imported from 35240-2bffe23f-b4b3-4496-a04b-ae9619d1f10e.postman_collection.json

// Describes the type of authorization an access token provides on a resource. The information returned contains information about the granted scopes, account number, or transaction ID.

@name("Get Consentinfo")
GET "https://{{baseUrl}}/consentinfo"



