#!/usr/bin/env dothttp

# imported from 35240-7871656e-e03d-47bc-b756-528d4b913bbd.postman_collection.json

// This operation list or find TransferBalance entities

@name("List or find TransferBalance objects")
GET "https://{{baseUrl}}/transferBalance"
? "fields"= "id voluptate"
? "offset"= "6696224"
? "limit"= "6696224"


// This operation creates a TransferBalance entity.

@name("Creates a TransferBalance")
POST "https://{{baseUrl}}/transferBalance"
"Content-Type": "application/json;charset=utf-8"
json({
    "amount": {
        "amount": 1,
        "units": "adipisicing consequat anim nulla"
    },
    "confirmationDate": "2018-05-15T18:06:14.603Z",
    "costOwner": "do cillum occaecat culpa",
    "description": "aliqua",
    "reason": "ex qui esse Excepteur",
    "receiverBucketUsageType": "labore",
    "requestedDate": "1961-02-14T23:02:14.415Z",
    "status": "velit ",
    "usageType": "exercitation in",
    "bucket": {
        "id": "culpa esse consectetur",
        "href": "http://YjWbx.nbrrfhz",
        "name": "labore commodo voluptate",
        "usageType": "laboris incididunt nisi sint",
        "@baseType": "Lorem anim voluptate",
        "@schemaLocation": "https://tcQUzgkjasWrmACtzKYJNHnMNq.cuVOOy3g30-Hu8rzKXsuA7E94I4Zc3MTDs",
        "@type": "cillum labore",
        "@referredType": "Excepteur"
    },
    "channel": {
        "id": "elit fugiat Excepteur",
        "href": "http://USZYwjRLsSRcP.pjsfxEYZDHUwrTC",
        "name": "aute sed aliqua ad",
        "@baseType": "non dolor veniam",
        "@schemaLocation": "https://ZVivYDBlVAbOaIRH.jvumErHc4WYreLlBChVcWAdxZJEtueVHJDhVI+eU",
        "@type": "sit dolor qui",
        "@referredType": "dolor"
    },
    "impactedBucket": [
        {
            "item": [
                {
                    "description": "consectetur deserunt eiusmod nisi",
                    "itemType": "aute aliqua irure",
                    "name": "dolor est laborum",
                    "reason": "Duis velit",
                    "amount": {
                        "amount": 1,
                        "units": "incididunt ipsum quis elit"
                    },
                    "@baseType": "esse eiusmod ex consectetur",
                    "@schemaLocation": "http://teNScEnEyAdiHi.jyilW",
                    "@type": "amet in sunt"
                }
            ],
            "confirmationDate": "1976-06-07T09:40:44.850Z",
            "description": "exercitation",
            "name": "aliqua eiusmod tempor irure",
            "requestedDate": "2007-12-29T03:32:45.626Z",
            "amountAfter": {
                "amount": 1,
                "units": "non minim irure ex"
            },
            "amountBefore": {
                "amount": 1,
                "units": "nostru"
            },
            "bucket": {
                "id": "consequat",
                "href": "https://ymyzMg.kevZCNW0VX",
                "name": "Ut dolore",
                "usageType": "deserunt dolore minim Lorem consectetur",
                "@baseType": "veniam fugiat",
                "@schemaLocation": "http://yheQ.barnaXJpeFeVv3oGdb+t-AzPmPxG0FcK3TOWvGa8on",
                "@type": "magna minim reprehenderi",
                "@referredType": "laborum consequat"
            },
            "@baseType": "non voluptate",
            "@schemaLocation": "http://Rch.byoik1AEcUKU7vHwdrP1-bppsIIddf7UtxxNI8L,prH0EnQrw3a5uws0EDjHyMrW+QXjDxy8m",
            "@type": "qui minim"
        },
        {
            "item": [
                {
                    "description": "ex proident",
                    "itemType": "nisi non est voluptate",
                    "name": "adipisicing in esse dolore",
                    "reason": "Duis Lorem",
                    "amount": {
                        "amount": 1,
                        "units": "ex sit officia magna"
                    },
                    "@baseType": "nostrud adipisicing",
                    "@schemaLocation": "https://XwmKwsSWshwOlMrLjlYMxr.zkeqKRE6CySsCnrhwIUl1Viy+gGGmiXRRLWEYtPmZZBfX2XMTuVi+g6cmFJOJetr1c",
                    "@type": "ut dolo"
                }
            ],
            "confirmationDate": "1992-04-04T14:31:20.693Z",
            "description": "ut reprehenderit pariatur tempor fugiat",
            "name": "elit ut commodo",
            "requestedDate": "1994-12-11T12:57:21.628Z",
            "amountAfter": {
                "amount": 1,
                "units": "veniam deserunt"
            },
            "amountBefore": {
                "amount": 1,
                "units": "anim"
            },
            "bucket": {
                "id": "sit ea ut",
                "href": "https://InnISpCijWXyknPgDZJkgXcVz.jpVdCK-sm6zB7Jf",
                "name": "minim magna",
                "usageType": "eu in ipsum",
                "@baseType": "commodo fugiat labore",
                "@schemaLocation": "http://VnCcDVFd.gzguCxo9czjcS8RX6cEGOX",
                "@type": "Ut eiusmod laboris",
                "@referredType": "pariatur "
            },
            "@baseType": "proident dolor elit",
            "@schemaLocation": "https://yGpHTE.bgvJYrZx7RX8VSbu4c",
            "@type": "c"
        }
    ],
    "logicalResource": {
        "id": "veniam nulla aute non",
        "href": "https://nDVdSBFprfgINe.yesuUsF8lhTZKk-duxn6WtSlVWIddHMv.QLaSSzAytl4z+vbMo1jBBvUfq.u9RxV",
        "name": "velit exercitation c",
        "value": "et est ullamco",
        "@baseType": "ad magna",
        "@schemaLocation": "https://HsnlPEGGEnRYoQvaQrOmgbLtGutW.wdDRDLqAi8KbblHggOsmVfJaooXva5KSAGNgTv3K7S8rIsqaW39DLpC",
        "@type": "do Ut",
        "@referredType": ""
    },
    "partyAccount": {
        "id": "laboris ut aliqua fugiat",
        "href": "voluptate enim",
        "description": "nulla nisi officia dolor",
        "name": "in cillum irure velit",
        "status": "sunt Duis irure ",
        "@baseType": "",
        "@schemaLocation": "http://YErrElOoH.wffXInF+kmWGx",
        "@type": "magna dolore enim dolor",
        "@referredType": "Ut nostrud sed reprehenderit"
    },
    "product": {
        "id": "dolor sit mollit dolore",
        "href": "https://LlzoCQlxJNkwSibIusVgXYSTTMdb.utdcZiHkka6oszUSRwAp2iUNcjASkTq7Rg2g8TeDewESeVMOvfide",
        "name": "quis",
        "@baseType": "id deserunt",
        "@schemaLocation": "https://aFzjHeJtSfBPnxbZhIzDzLrooNYVc.hsvtJ3dHNN-r",
        "@type": "fugi",
        "@referredType": "qui pariatur nostrud"
    },
    "receiver": {
        "@referredType": "non qui Excepteur eu labore",
        "id": "veniam exerc",
        "href": "http://rATjhESkIGLyLQtPfCp.jnjuuI..HYPIBBVly44.T+pDSvvQjjFakinuHR1ZNUI",
        "name": "culpa fugiat",
        "role": "mi",
        "@baseType": "mollit",
        "@schemaLocation": "http://AorCm.ffIgOjb8NXeDAQ",
        "@type": "ve"
    },
    "receiverBucket": {
        "id": "reprehenderit Lorem",
        "href": "http://Ytmb.abUTkGGSaYtQIPwClr94etNngLg45Yz,45SuXnxA380SJZlqtZ,JP+sm",
        "name": "laborum nulla proident ut",
        "usageType": "ex",
        "@baseType": "voluptate commodo quis culpa",
        "@schemaLocation": "https://IEACoWKCqM.nkZdLxTAAh3WUieTv90ABJ7QkyJExHkfnBHpM2NPE1uAsZn4nV-l,MD,utpSQmH1JMi2ktWA0L",
        "@type": "ullamco elit deser",
        "@referredType": "dolore dolo"
    },
    "receiverLogicalResource": {
        "id": "ut amet cupidatat mollit proident",
        "href": "https://UesQsLt.ajTKypejTttyg97an0mZV,C+TWI",
        "name": "consequat nulla Excepteur",
        "value": "nisi sint culpa",
        "@baseType": "magna et nostrud",
        "@schemaLocation": "https://LDPhPwvXOVYMs.mvugaFoDxUjMuA6NNqToeURGnz.zohC,N",
        "@type": "esse eu Excepteur",
        "@referredType": "pariatur cillum l"
    },
    "receiverPartyAccount": {
        "id": "i",
        "href": "do enim officia",
        "description": "esse",
        "name": "dolore aliquip incididunt",
        "status": "dolor nulla do ut occaecat",
        "@baseType": "Lorem",
        "@schemaLocation": "http://gc.jhm3FSvgjzXIZujlrq,26Au4cnwNrE3B+,V6lEK04,sdOwoK8M3rCJVK6",
        "@type": "qui eiusmod aute elit",
        "@referredType": "adipisicing dolor nostrud"
    },
    "receiverProduct": {
        "id": "laboris",
        "href": "http://zbpNbuPmQczDjjCrZHzpdYoXccxhBX.mrkcui20lIVG.zf0.P-SDeA1sz",
        "name": "magna nostrud officia sed",
        "@baseType": "incididunt occaecat Lorem",
        "@schemaLocation": "http://fVUawmVxNcMkmy.rlpbDc7WDk5ggWThkFLqDOqDJ4+SE,u+,DkBMnWzxAFAY6bynjygLHmQCQTLVlAazzg",
        "@type": "sunt veniam irure",
        "@referredType": "quis"
    },
    "relatedParty": [
        {
            "@referredType": "in laboris",
            "id": "eiusmod mollit exercitation tempor reprehenderit",
            "href": "http://ZsepacJyYmWGzEYLCcrtMbBPgwMtmwH.rta6dGbOI,rTxOGSs2e,EweX4bdBmGMb",
            "name": "dolor nulla nostrud dolor",
            "role": "commodo veniam in",
            "@baseType": "ex Ut",
            "@schemaLocation": "http://yJVsQtGaTGmVUsMzQYpgnzP.nmlxD5f7",
            "@type": "exercitation proident in"
        },
        {
            "@referredType": "ad ut",
            "id": "amet officia fugiat",
            "href": "http://SktoymdU.cdzcKV2PJWANfx.VWdyiaaNijTishOabyQWgLHgGUa+maEwTL1",
            "name": "aute consequat magna dolore",
            "role": "Duis irure",
            "@baseType": "id dolore non cillum sunt",
            "@schemaLocation": "http://SQqidaaIhQsh.fnYOsKkCa",
            "@type": "ad quis"
        }
    ],
    "requestor": {
        "@referredType": "mollit dolore velit ullamco in",
        "id": "adipisicing qui",
        "href": "http://gHpnKlLEj.whpkOtXMhLlLMdrOJWdRdu+E",
        "name": "exercitation occaecat",
        "role": "irure in",
        "@baseType": "consectetur exercitation",
        "@schemaLocation": "https://ihuvrA.ozcP9.vuDNSwdCfmCPMbho46SuUmmL.2GLfpuIvPEbqXr+W.n0",
        "@type": "nostrud qui"
    },
    "transferCost": {
        "amount": 1,
        "units": "minim Duis ut aute sit"
    },
    "@baseType": "quis ex dolo",
    "@schemaLocation": "https://gIhAKUeogNMYwHR.bferoXmTljc4JhJ,oOOQ7LGKd2WzA1jR",
    "@type": "in id anim"
})



