#!/usr/bin/env dothttp

# imported from 35240-a96221e2-b43c-4973-9be0-3ec0566f4cd9.postman_collection.json

// Get a list of all theme assets.

@name("Get a list of all theme assets")
GET "https://{{baseUrl}}/admin/themes/110163843/assets.json"
"Content": "<>"


// Get a single theme.

@name("Get a single theme")
GET "https://{{baseUrl}}/admin/themes/110163843.json"
"Content": "<>"


// Update a theme's attributes.

@name("Update a theme's attributes")
PUT "https://{{baseUrl}}/admin/themes/164593742.json"
"Content": "<>"



