#!/usr/bin/env dothttp

# imported from 35240-f7210373-de2f-4259-aec5-4d8fab19ca46.postman_collection.json

// List all API Management services within a resource group.

@name("API Management Services ListByResourceGroup")
GET "https://{{baseUrl}}/subscriptions/:subscriptionId/resourceGroups/:resourceGroupName/providers/Microsoft.ApiManagement/service/"



