#!/usr/bin/env dothttp

# imported from 35240-b03a023f-71a0-4ba1-9905-b5580a2efba0.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// Get an individual datasource metadata

@name("Get an individual datasource metadata") : "base-inherit-auth"
GET "https://{{baseUrl}}/metadata/data/sources/:owner/:sourceid"



