#!/usr/bin/env dothttp

# imported from 35240-5f0de24a-12d4-4bb7-a222-68e7bfdfd2e8.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// Get advanced settings for an environment

@name("Get advanced settings for an environment") : "base-inherit-auth"
GET "https://{{baseUrl}}/services/:env_id/settings/advanced-settings"


// Set advanced settings for an environment

@name("Set advanced settings for an environment") : "base-inherit-auth"
POST "https://{{baseUrl}}/services/:env_id/settings/advanced-settings"
"Content-Type": "application/json"
json({
    "allowed_ips": [
        "127.0.0.1",
        "127.0.0.1"
    ],
    "show_rethrows": true,
    "show_log_links": false,
    "clear_env_filters": false,
    "enhanced_decompilation": true
})



