#!/usr/bin/env dothttp

# imported from 35240-07b8f9ff-4fab-4f58-a64e-0549bc880422.postman_collection.json

// Lists current useru2019s accounts to which the authentication method has access to.

@name("List accounts")
GET "https://{{baseUrl}}/accounts"



