#!/usr/bin/env dothttp

# imported from 35240-6ca9c728-f778-4fd2-9734-eedda095abb8.postman_collection.json

// This operation list or find Migrate entities

@name("List or find Migrate objects")
GET "https://{{baseUrl}}/migrate"
? "fields"= "eiusmod deserunt Ut"
? "offset"= "20911156"
? "limit"= "20911156"


// This operation creates a Migrate entity.

@name("Creates a Migrate")
POST "https://{{baseUrl}}/migrate"
"Content-Type": "application/json;charset=utf-8"
json({
    "cause": "exercitation consequat",
    "resourceFunction": {
        "id": "adipisicing velit ",
        "href": "https://dIhAPTmRIzUpWhLZbh.pmwaVYzhfWjMazR-SHb0dRqjRV6sn-CWeXbL7m,xa.QSKP.6vjqdnFfEAgn4biSWQ",
        "name": "et dolor esse culpa",
        "version": "adipisicing deserunt tempor eu magna",
        "@baseType": "ResourceSpecification",
        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
        "@type": "LogicalResourceSpecification",
        "@referredType": "mollit elit aute"
    },
    "adminStateModification": "sed culpa consequat",
    "completionMode": "Duis dolor",
    "name": "do aliqua laborum tempor nostrud",
    "priority": -62108595,
    "startTime": "labore ea ipsum cillum commodo",
    "addConnectionPoint": [
        {
            "id": "esse sunt ad eu",
            "href": "http://veWAgehtVQaLqlzlTcUeLwFPsEXRtnVSW.dfnrnR.HtWaIKtduAH.OXAkkSZwqqePz,ypSK7A+wq.7gg7G3RqeF",
            "name": "enim cupidatat mollit amet",
            "version": "in culpa elit",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "dolor Duis"
        },
        {
            "id": "dolor anim nostrud quis aute",
            "href": "http://oskWQOQzomsEKtwGGelczTvTokcFuundD.amfchXh7sGqaIiWDNVenMZeppur8BizSThpD7kRJlXzcHc3..NrFTpxbH,g",
            "name": "nulla quis qui aliquip consectetur",
            "version": "nulla adipisicing",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "deserunt d"
        }
    ],
    "characteristics": [
        {
            "name": "ullamco non incididunt cupidatat",
            "value": {},
            "id": "commodo sint laborum esse eiusmod",
            "valueType": "ut sunt",
            "characteristicRelationship": [
                {
                    "id": "ullamco ex dolor",
                    "relationshipType": "esse in aliquip nulla",
                    "@baseType": "aliqua veniam ut id elit",
                    "@schemaLocation": "https://wkOaYfBOKiYrypLqlaR.qlsKRmwnk-RFJtzu8nQw2LvKQfNtIbt9Hl+ztp7j4rNjZNwajxIcYcB",
                    "@type": "labore id nulla"
                },
                {
                    "id": "eiusmod id",
                    "relationshipType": "Lorem adipis",
                    "@baseType": "eu",
                    "@schemaLocation": "http://KfnFopXaNNzFxB.scszMk.hUIwEo5CDEi.C7pCHD",
                    "@type": "exercitation nisi"
                }
            ],
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification"
        },
        {
            "name": "proident occaecat laboris dolore cupidatat",
            "value": {},
            "id": "dolore labore",
            "valueType": "non velit ipsum sit laborum",
            "characteristicRelationship": [
                {
                    "id": "irure",
                    "relationshipType": "non pariatur Excepteur",
                    "@baseType": "ea sint sit",
                    "@schemaLocation": "https://ChfDBePJlqvuEW.ixrvZqKP-7j-Yjrn3DqtDPZgqfBxW6JLQtLLe3uRrJGdcPPhoBla",
                    "@type": "est dolore nostrud"
                },
                {
                    "id": "id",
                    "relationshipType": "sit adipisicing",
                    "@baseType": "min",
                    "@schemaLocation": "http://oronPNHvHupmoAjKVHxWyojvjjVUr.sxtDw4V5LSRl4Ln7BKqQCyoCctQUzMdzO-XK5LmM2PZBibMAE",
                    "@type": "deserunt enim"
                }
            ],
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification"
        }
    ],
    "place": {
        "id": "esse nisi enim ",
        "href": "https://fOeCtCyfSG.cgpmXs9hmq6YjTuYp6gBENG",
        "name": "fugiat occaecat consequat",
        "@baseType": "ResourceSpecification",
        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
        "@type": "LogicalResourceSpecification",
        "@referredType": "et Ut"
    },
    "removeConnectionPoint": [
        {
            "id": "anim exercitation",
            "href": "https://ucJSGOYSOSvNuOeTHGj.fnxwPrDv2uq2affAnaCM29YfrTG8keQVxFu6fOn75HORTOZFkGILIcH.MTv",
            "name": "dolor consequat laborum aute",
            "version": "veniam in tempor dolo",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "dolor pariatur ut"
        },
        {
            "id": "commodo tempor",
            "href": "https://tKtQbkuiQ.umPKpgcrsKAX0Myl+I-eKXjqLbTAOVtgIqO,M6QY,pPD3lU,U0DBfh7AT",
            "name": "in culpa",
            "version": "est cupidatat sint officia",
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification",
            "@referredType": "laboris ex pariatur velit incididunt"
        }
    ],
    "state": "accepted",
    "@baseType": "culpa veniam Lorem",
    "@schemaLocation": "https://DwwqUvEAdmQJzInjqeSEATbyqI.xbwFHm9z4dMmruFiTUKAwNHLRNMqloWkPGui2xYlHQmFVJFDpZfL7aFXc",
    "@type": "Duis deserunt pariatur"
})


// This operation retrieves a Migrate entity. Attribute selection is enabled for all first level attributes.

@name("Retrieves a Migrate by ID")
GET "https://{{baseUrl}}/migrate/:id"
? "fields"= "eiusmod deserunt Ut"



