#!/usr/bin/env dothttp

# imported from 35240-175bce79-8928-437d-8db8-aad1709514f2.postman_collection.json

// This operation list or find ImportJob entities

@name("List or find ImportJob objects")
GET "https://{{baseUrl}}/importJob"
? "fields"= "tempor sint Ut"
? "offset"= "-48829778"
? "limit"= "-48829778"


// This operation creates a ImportJob entity.

@name("Creates a ImportJob")
POST "https://{{baseUrl}}/importJob"
"Content-Type": "application/json;charset=utf-8"
json({
    "url": "tempor",
    "completionDate": "1997-06-23T22:47:55.600Z",
    "contentType": "Duis deserunt",
    "creationDate": "1999-05-28T20:43:51.762Z",
    "errorLog": "consectetur occaecat exercitation",
    "path": "laborum minim velit exercitation proident",
    "status": "Not Started",
    "@baseType": "dolor quis ipsum",
    "@schemaLocation": "http://bGAQgEHc.tgviY5enLqXj0CKdHtzwvn7AAR+Ja2GDbxyRELxpRrNR",
    "@type": "veniam"
})



