#!/usr/bin/env dothttp

# imported from 35240-17a6f18b-38c5-42cb-a11e-28f755ffce28.postman_collection.json

// Get a list of all CRM Status

@name("Get all CRM Status")
GET "https://{{baseUrl}}/3dCartWebAPI/v1/CRM/status"
? "limit"= "<integer>"
? "offset"= "<integer>"
? "countonly"= "<integer>"


@name("This method is used to update a single CRM Status record in the database. The {id} parameter specifies which CRM Status record to update.")
PUT "https://{{baseUrl}}/3dCartWebAPI/v1/CRM/status/:id"



