#!/usr/bin/env dothttp

# imported from 35240-a96221e2-b43c-4973-9be0-3ec0566f4cd9.postman_collection.json

// Get a single custom collections.

@name("Get a single custom collections")
GET "https://{{baseUrl}}/admin/custom_collections/246409795.json"
"Content": "<>"


// Get a count of all custom collections.

@name("Get a count of all custom collections")
GET "https://{{baseUrl}}/admin/custom_collections/count.json"
"Content": "<>"



