#!/usr/bin/env dothttp

# imported from 35240-d48cb29d-8b2c-4901-8b4c-1b41fbda12a8.postman_collection.json

//  Sending SMS text messages

@name("Send SMS")
GET "https://{{baseUrl}}/send_sms/"
? "autoconvert"= "<>"
? "charset"= "<>"
? "dlr-url"= "<>"
? "from"= "<>"
? "password"= "<>"
? "text"= "<>"
? "time_to_send"= "<>"
? "to"= "<>"
? "udh"= "<>"
? "username"= "<>"



