#!/usr/bin/env dothttp

# imported from 35240-cc491087-45e6-46ba-aa93-9f2f2cc44068.postman_collection.json

// This feature was introduced in GitLab 8.15.

@name("Get Templates Dockerfiles")
GET "https://{{baseUrl}}/templates/dockerfiles"


// This feature was introduced in GitLab 8.15.

@name("Get Templates Dockerfiles Name")
GET "https://{{baseUrl}}/templates/dockerfiles/:name"



