#!/usr/bin/env dothttp

# imported from 35240-5af4ed67-4654-4363-a86d-3c7bcff23c51.postman_collection.json

// Logs out the front end user from the online store. The access token expires.

@name("Logout")
POST "https://{{baseUrl}}/rest/account/logout"



