#!/usr/bin/env dothttp

# imported from 35240-6ca9c728-f778-4fd2-9734-eedda095abb8.postman_collection.json

// This operation list or find Heal entities

@name("List or find Heal objects")
GET "https://{{baseUrl}}/heal"
? "fields"= "eiusmod deserunt Ut"
? "offset"= "20911156"
? "limit"= "20911156"


// This operation creates a Heal entity.

@name("Creates a Heal")
POST "https://{{baseUrl}}/heal"
"Content-Type": "application/json;charset=utf-8"
json({
    "cause": "sit dolore pariatur",
    "degreeOfHealing": "ipsum nostrud pariatur",
    "resourceFunction": {
        "id": "cillum consequat do",
        "href": "https://xyPVFqEbiTbbU.avdts,lL9P.s22RgETaPaOdRTl6GTd1byutoVAPAk3MUssbxMf1FcPzj75.o,rzzlg01R7uEgzwKas1T",
        "name": "sit est mollit",
        "version": "in ullamco cupidatat",
        "@baseType": "ResourceSpecification",
        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
        "@type": "LogicalResourceSpecification",
        "@referredType": "dolore Ut dolore"
    },
    "healAction": "ullamco deserunt elit nostrud",
    "name": "sunt est incididu",
    "startTime": "mollit aliqua et",
    "additionalParms": [
        {
            "name": "exercitation nost",
            "value": {},
            "id": "qui Lorem",
            "valueType": "est",
            "characteristicRelationship": [
                {
                    "id": "et fugiat",
                    "relationshipType": "sint irure aliquip tempor cillum",
                    "@baseType": "commodo proident in minim",
                    "@schemaLocation": "http://DcbRbKHVJeagqcKYBuZzrzfkOfHN.cdIH4",
                    "@type": "eiusmod nu"
                },
                {
                    "id": "et qui",
                    "relationshipType": "pariatur consectetur",
                    "@baseType": "laboris elit labore",
                    "@schemaLocation": "https://MQnThIAtqUJejWRROqDWkfeX.kblNYE7xrOo2I0xHNbHcCkrIhlzwk8th9Sjo7H8B6gT0NPKnc",
                    "@type": ""
                }
            ],
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification"
        },
        {
            "name": "proident eiusmod dolore ea",
            "value": {},
            "id": "deserunt et quis veniam",
            "valueType": "dolore elit",
            "characteristicRelationship": [
                {
                    "id": "Duis qui",
                    "relationshipType": "eu anim",
                    "@baseType": "reprehenderit amet sunt aliquip pariatur",
                    "@schemaLocation": "http://lZtwIyLkTJL.mwhwfn8DGHv8.8",
                    "@type": "ad adipisicing reprehenderit sunt"
                },
                {
                    "id": "Excepteur ut dolore",
                    "relationshipType": "consectetur fugiat anim",
                    "@baseType": "magna nulla non esse",
                    "@schemaLocation": "http://fzKaCIwfPCWXs.qwrwzx,lVUzejhN6NtK8A",
                    "@type": "sunt"
                }
            ],
            "@baseType": "ResourceSpecification",
            "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
            "@type": "LogicalResourceSpecification"
        }
    ],
    "healPolicy": {
        "id": "incididunt in ullamco Lorem cillum",
        "href": "http://CbVjyJcIRCrpPkEbBmBtyYlV.rrxhzP9bEJPgpIiz,vn0PVQxMZgHHOT.-HRjapoCRClf.REICtzs",
        "name": "labore",
        "@baseType": "ResourceSpecification",
        "@schemaLocation": "https://mycsp.com:8080/tmf-api/schema/Resource/LogicalResourceSpecification.schema.json",
        "@type": "LogicalResourceSpecification",
        "@referredType": "irure ut"
    },
    "state": "inProgress",
    "@baseType": "qui et eiusmod culpa",
    "@schemaLocation": "https://vEnBCwwrSLmNuCjAoERy.zxelpdF75,uJyFu72f+BJULCoQTvF-Fze-WBLGLPVMs-ZoyurwsqxnPER5Y5P12tQQuV2",
    "@type": "aliquip adipisicing mollit"
})


// This operation retrieves a Heal entity. Attribute selection is enabled for all first level attributes.

@name("Retrieves a Heal by ID")
GET "https://{{baseUrl}}/heal/:id"
? "fields"= "eiusmod deserunt Ut"



