#!/usr/bin/env dothttp

# imported from 35240-01e79e8b-0f05-4fff-860a-a88d8c927eac.postman_collection.json

@name("delete Organisations Id Consumers Key")
DELETE "https://{{baseUrl}}/organisations/:id/consumers/:key"


@name("get Organisations Id Consumers Key Secret")
GET "https://{{baseUrl}}/organisations/:id/consumers/:key/secret"



