#!/usr/bin/env dothttp

# imported from 35240-dbaaeac4-235b-44c3-ba85-7fe9c62e50ba.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


@name("Create a new server's run statistics") : "base-inherit-auth"
POST "https://{{baseUrl}}/v1/:namespace/projects/:project/servers/:server/run-stats/"
"Content-Type": "application/json"
json({
    "exit_code": "<integer>",
    "size": "<integer>",
    "stacktrace": "<string>",
    "start": "<string>",
    "stop": "<string>"
})



