#!/usr/bin/env dothttp

# imported from 35240-bfc666ca-94aa-4d7e-b49b-06193ecb21e3.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"
"Authorization": "Bearer <Bearer Token>"


@name("Create a new custom data type.") : "base-inherit-auth"
POST "https://{{baseUrl}}/tenant/datatypes"
"x-api-key": "{{API_KEY}}"
"x-gw-ims-org-id": "{{IMS_ORG}}"
"x-sandbox-name": "{{SANDBOX_NAME}}"
"Content-Type": "application/json"
data('"{{payload}}"')



