#!/usr/bin/env dothttp

# imported from 35240-a96221e2-b43c-4973-9be0-3ec0566f4cd9.postman_collection.json

// Get a countt of all url redirect.

@name("Get a countt of all URL redirect")
GET "https://{{baseUrl}}/admin/redirects/count.json"
"Content": "<>"


// Update a redirect.

@name("Update a redirect")
PUT "https://{{baseUrl}}/admin/redirects/293743566.json"
"Content": "<>"


// Get a single url redirect.

@name("Get a single URL redirect")
GET "https://{{baseUrl}}/admin/redirects/count/7376372.json"
"Content": "<>"



