#!/usr/bin/env dothttp

# imported from 35240-c68e2fa9-6659-44c8-b526-051d761f5037.postman_collection.json

// <p>The <code>Get all environments</code> call fetches the list of all environments available in a stack.
// <br><p>To use the API Request, you will need to authenticate yourself either with a&nbsp;<a href="https://www.contentstack.com/docs/developers/create-tokens/about-management-tokens">Management Token (highly recommended)</a>&nbsp;or an <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#how-to-get-authtoken">Authtoken.</a>&nbsp;<br>Read more about it in <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#authentication">Authentication.</a>
// </p><br>
//                           For more information, refer to the <a href=www.contentstack.com/docs/developers/apis/content-management-api/#environment-collection>Environment Collection</a> API Reference document

@name("Get all environments")
GET "https://{{base_url}}/v3/environments"
"api_key": "{{api_key}}"
"authtoken": "{{authtoken}}"
"authorization": "{{management_token}}"
"Content-Type": "application/json"
? "include_count"= "false"
? "asc"= "created_at"
? "desc"= "updated_at"


// <p>The <code>Get a single environment</code> call returns more details about the specified environment of a stack.
// <br><p>To use the API Request, you will need to authenticate yourself either with a&nbsp;<a href="https://www.contentstack.com/docs/developers/create-tokens/about-management-tokens">Management Token (highly recommended)</a>&nbsp;or an <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#how-to-get-authtoken">Authtoken.</a>&nbsp;<br>Read more about it in <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#authentication">Authentication.</a>
// </p><br>
//                           For more information, refer to the <a href=www.contentstack.com/docs/developers/apis/content-management-api/#environment-collection>Environment Collection</a> API Reference document

@name("Get a single environment")
GET "https://{{base_url}}/v3/environments/{{environment_name}}"
"api_key": "{{api_key}}"
"authtoken": "{{authtoken}}"
"authorization": "{{management_token}}"
"Content-Type": "application/json"


// <p>The <code>Add an environment</code> call will add a publishing environment for a stack.
// <br><p>To use the API Request, you will need to authenticate yourself either with a&nbsp;<a href="https://www.contentstack.com/docs/developers/create-tokens/about-management-tokens">Management Token (highly recommended)</a>&nbsp;or an <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#how-to-get-authtoken">Authtoken.</a>&nbsp;<br>Read more about it in <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#authentication">Authentication.</a>
// </p><br>
//                           For more information, refer to the <a href=www.contentstack.com/docs/developers/apis/content-management-api/#environment-collection>Environment Collection</a> API Reference document

@name("Add an environment")
POST "https://{{base_url}}/v3/environments"
"api_key": "{{api_key}}"
"authtoken": "{{authtoken}}"
"authorization": "{{management_token}}"
"Content-Type": "application/json"
json({
    "environment": {
        "name": "development",
        "servers": [
            {
                "name": "default"
            }
        ],
        "urls": [
            {
                "locale": "en-us",
                "url": "http://example.com/"
            }
        ],
        "deploy_content": true
    }
})


// <p>The <code>Update environment</code> call will update the details of an existing publishing environment for a stack.
// <br><p>To use the API Request, you will need to authenticate yourself either with a&nbsp;<a href="https://www.contentstack.com/docs/developers/create-tokens/about-management-tokens">Management Token (highly recommended)</a>&nbsp;or an <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#how-to-get-authtoken">Authtoken.</a>&nbsp;<br>Read more about it in <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#authentication">Authentication.</a>
// </p><br>
//                           For more information, refer to the <a href=www.contentstack.com/docs/developers/apis/content-management-api/#environment-collection>Environment Collection</a> API Reference document

@name("Update environment")
PUT "https://{{base_url}}/v3/environments/{{environment_name}}"
"api_key": "{{api_key}}"
"authtoken": "{{authtoken}}"
"authorization": "{{management_token}}"
"Content-Type": "application/json"
json({
    "environment": {
        "name": "development",
        "servers": [
            {
                "name": "default"
            }
        ],
        "urls": [
            {
                "locale": "en-us",
                "url": "http://example.com/"
            }
        ],
        "deploy_content": true
    }
})


// <p>The <code>Delete environment</code> call will delete an existing publishing environment from your stack.
// <br><p>To use the API Request, you will need to authenticate yourself either with a&nbsp;<a href="https://www.contentstack.com/docs/developers/create-tokens/about-management-tokens">Management Token (highly recommended)</a>&nbsp;or an <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#how-to-get-authtoken">Authtoken.</a>&nbsp;<br>Read more about it in <a href="https://www.contentstack.com/docs/developers/apis/content-management-api/#authentication">Authentication.</a>
// </p><br>
//                           For more information, refer to the <a href=www.contentstack.com/docs/developers/apis/content-management-api/#environment-collection>Environment Collection</a> API Reference document

@name("Delete environment")
DELETE "https://{{base_url}}/v3/environments/{{environment_name}}"
"api_key": "{{api_key}}"
"authtoken": "{{authtoken}}"
"authorization": "{{management_token}}"
"Content-Type": "application/json"




