#!/usr/bin/env dothttp

# imported from 35240-d47c7988-a7de-44ff-ba08-7608a9285ad4.postman_collection.json

@name("Search")
GET "https://genelab-data.ndc.nasa.gov/genelab/data/search"
? "term"= "mouse liver"
? "type"= "cgene"
? "from"= "0"
? "size"= "25"
? "order"= "ASC"
? "sort"= ""



