#!/usr/bin/env dothttp

# imported from 35240-6851f218-fa13-4c7b-b9c5-0b98d83479d7.postman_collection.json

// /pages/{PAGE_ID}/venues

@name("/pages/{PAGE_ID}/venues")
GET "https://{{baseUrl}}/multi"
? "requests"= "<string>"
? "v"= "<string>"



