#!/usr/bin/env dothttp

# imported from 35240-b982553e-8975-4962-bc9d-a464c11c5f3a.postman_collection.json

@name("All data for current feed in a specific group")
GET "https://{{baseUrl}}/:username/groups/:group_key/feeds/:feed_key/data"
? "No Name"= "<string>"
? "start_time"= "<string>"
? "end_time"= "<string>"
? "limit"= "<integer>"


@name("Create multiple new Data records in a feed belonging to a particular group")
POST "https://{{baseUrl}}/:username/groups/:group_key/feeds/:feed_key/data/batch"
? "No Name"= "<string>"



