#!/usr/bin/env dothttp

# imported from 35240-d8f0a546-2bf3-4572-88c9-9190f362a7c5.postman_collection.json

@name("By Id Deployment")
GET "https://{{aws_api_gateway_base_url}}/restapis/{restapi_id}/deployments/{deployment-id}"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")
? "deployment_id"= ""
? "embed"= ""


@name("Create Deployment")
POST "https://{{aws_api_gateway_base_url}}/restapis/fugvjdxtri/deployments"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")


@name("Delete Deployment")
DELETE "https://{{aws_api_gateway_base_url}}/restapis/fugvjdxtri/deployments/dzacq7"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")


@name("Stages Deployment")
GET "https://{{aws_api_gateway_base_url}}/restapis/<restapi_id>/stages"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")


@name("Update Deployment")
PATCH "https://{{aws_api_gateway_base_url}}/restapis/fugvjdxtri/deployments/dzacq7"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")



