#!/usr/bin/env dothttp

# imported from 35240-1db970f2-8e07-4d80-8a32-9295b3d30bab.postman_collection.json

@name("Start Logging")
GET "https://{{aws_cloudtrail_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_cloudtrail_service}}", region="{{aws_cloudtrail_region}}")
? "Name"= ""
? "Action"= "StartLogging"


@name("Stop Logging")
GET "https://{{aws_cloudtrail_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_cloudtrail_service}}", region="{{aws_cloudtrail_region}}")
? "Name"= ""
? "Action"= "StopLogging"



