#!/usr/bin/env dothttp

# imported from 35240-df55bd21-8efe-4dae-ac10-923f5911c3f0.postman_collection.json

@name("Retrieve weather data from one of the meteostations for a specified time period.  Dates can be entered as yyyymmdd, yyyymm, or yyyy.")
GET "https://{{baseUrl}}/meteodata"
"token": "{{token}}"
? "output_epsg"= "4326"
? "meteostation"= "{{meteostation}}"
? "fromdate"= "{{fromdate}}"
? "todate"= "{{todate}}"
? "page_size"= "25"
? "page_offset"= "0"


@name("Retrieve weather data from one of the meteostations and for a specific date.  The date can be entered as yyyymmdd, yyyymm, or yyyy.")
GET "https://{{baseUrl}}/meteodata/:stationid/:date"
"token": "{{token}}"
? "page_size"= "25"
? "page_offset"= "0"



