#!/usr/bin/env dothttp

# imported from 35240-ce5ace78-796d-4767-ad74-642bd7849201.postman_collection.json

// The Top Stories API returns a list of articles and associated images currently on the specified section.  Support JSON and JSONP.n

@name("Top Stories")
GET "https://{{baseUrl}}/{{section}}.{{format}}"
? "callback"= "<string>"



