#!/usr/bin/env dothttp

# imported from 35240-67d4db18-8ace-40cd-b64c-3d2159129d95.postman_collection.json

// Edit a Widget, please refer to individual widget Add documentation for module specific parameters

@name("Edit a Widget")
PUT "https://{{baseUrl}}/playlist/widget/:widgetId"


// Parameters for edting/adding audio file to a specific widget

@name("Parameters for edting/adding audio file to a specific widget")
PUT "https://{{baseUrl}}/playlist/widget/:widgetId/audio"



