#!/usr/bin/env dothttp

# imported from 35240-72e604f5-6257-4d0e-8b1c-bfbf148e0789.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


@name("Set Custom Field Value") : "base-inherit-auth"
POST "https://api.clickup.com/api/v2/task/task_id/field/field_id"
"Content-Type": "application/json"
data('0')


@name("Remove Custom Field Value") : "base-inherit-auth"
DELETE "https://api.clickup.com/api/v2/task/task_id/field/field_id"
"Content-Type": "application/json"



