#!/usr/bin/env dothttp

# imported from 35240-b4ad2590-7a09-4b2a-9ac8-f9039ba10098.postman_collection.json

// This operation list or find ProductOfferingRiskAssessment entities

@name("List or find ProductOfferingRiskAssessment objects")
GET "https://{{baseUrl}}/productOfferingRiskAssessment"
? "fields"= "quis elit commodo tempor"
? "offset"= "-80657290"
? "limit"= "-80657290"


// This operation creates a ProductOfferingRiskAssessment entity.

@name("Creates a ProductOfferingRiskAssessment")
POST "https://{{baseUrl}}/productOfferingRiskAssessment"
"Content-Type": "application/json;charset=utf-8"
json({
    "productOffering": {
        "id": "in Ut ullamco occaecat",
        "href": "http://YUNNsbGEMTh.qtlXYqdygcP.lFvcTHSHCpIQFB+R7JEpDWk8NLYl+MsD4uWKEiO6vJ74LTVm41YIsdtalxbYUVBetx",
        "name": "elit magna",
        "@baseType": "commodo cupidatat",
        "@schemaLocation": "https://Vggap.cykSkDstfgF60SZcfQ9Oth2jmGuKmBaGhMjSQ5CwX",
        "@type": "aute aliquip adipisicing",
        "@referredType": "sed minim do consequat in"
    },
    "status": "in esse",
    "characteristic": [
        {
            "name": "aute ut culpa id eiusmod",
            "value": {},
            "id": "cupidatat laboru",
            "valueType": "ipsum pariatur",
            "characteristicRelationship": [
                {
                    "id": "exercitation fugia",
                    "href": "http://hS.lxfqy2+SuyV839N+c5l-5",
                    "relationshipType": "aliquip Lorem consequat reprehenderit",
                    "@baseType": "aliqua Duis dolor proident",
                    "@schemaLocation": "http://MHrUEzKFK.ueOlxRH",
                    "@type": "aute"
                },
                {
                    "id": "ut velit",
                    "href": "http://LvkcypxkedDnbCy.nwa92,gGz,-wVRsh1hmomMutOyHxk3thjvkur-DlThb",
                    "relationshipType": "occaec",
                    "@baseType": "consectetur incididunt aute",
                    "@schemaLocation": "https://ay.vfneV-w.ygGCXPFzVnUe29D",
                    "@type": "in deserunt laboris"
                }
            ],
            "@baseType": "Excepteur quis",
            "@schemaLocation": "http://dYBMNkLljFWNiMJNXTRPuQaqAkjGlbyjL.uzcTuDZvyFwZpdcTv-hw5RkVsfZfOlm1dQbVkcFpxdVodCHXMlUPds-t0",
            "@type": "ea ad proident magna nisi"
        },
        {
            "name": "et voluptate mollit",
            "value": {},
            "id": "sit labore in deserunt",
            "valueType": "laborum",
            "characteristicRelationship": [
                {
                    "id": "anim in in",
                    "href": "https://emGQUNLVYpCYs.bbqTXY5twqWaKtzcVgCBMoENoKQqVQtYu,zD",
                    "relationshipType": "labore dolor Lorem",
                    "@baseType": "ea laborum in",
                    "@schemaLocation": "http://zvLLNwkHE.hbZPp4HIHT,HqgQYhFMkf1RXOFucqei8P",
                    "@type": "Duis sint qui"
                },
                {
                    "id": "labore",
                    "href": "http://X.jqosjsxvbqOSuchq,iPhfFPjnoLTfpWk.amlZ",
                    "relationshipType": "deserunt consectetur incididunt",
                    "@baseType": "dolor veniam adipisicing",
                    "@schemaLocation": "http://zLvkcrQkBTGqS.llGfmCnBGhpJHmm4l2eH6-h,IU8d6MEi3idghuCzmkB8tAPoQh7UBSW0Wc81SZUZ1zgfDEyXKZ3JmBeI27davrGu",
                    "@type": "magn"
                }
            ],
            "@baseType": "nisi consectetur",
            "@schemaLocation": "https://YqqetCxZbAGOSPPHOiuxQY.blSBBFotEguDimyrwegHMLDx8KA-BqmxqlH0h85aEo",
            "@type": "nulla"
        }
    ],
    "place": {
        "id": "fugiat sit",
        "href": "Duis voluptate",
        "name": "ut exercitation incididunt culpa",
        "role": "ut ipsum velit sint",
        "@baseType": "consectetur est",
        "@schemaLocation": "http://IqsHSnNRzyF.koiyrmcd+317WEMIC6+JHD+dQsM.Ah5rK",
        "@type": "sit dolor labore officia",
        "@referredType": "labore consectetur"
    },
    "riskAssessmentResult": {
        "overallScore": 50013853.182214886,
        "score": [
            {
                "score": 41881636.70240867,
                "riskName": "BadPaymentRisk",
                "@baseType": "ea en",
                "@schemaLocation": "https://GGNQXiKdUFMUfqOPdYTMnQAMAN.njIte4OSg3hoKKedH.VCqH+SkV",
                "@type": "do ullamco in ex adipisicing"
            },
            {
                "score": -84392795.886288,
                "riskName": "FraudRisk",
                "@baseType": "Duis ipsum ad",
                "@schemaLocation": "http://mYFjqWENvqedcsxUziDjZyqiuHneOdBE.jpJW2JcKyBT6g4pbDVxF.JhioQeClEE5EQe7So0aB57Is1vm,GBwKNC4Z",
                "@type": "dolor est dolore ullamco"
            }
        ],
        "validFor": {
            "id": "exercitation pariatur",
            "href": "https://zMdyOWKBAHaHDKoAIN.orXYMekMLX,c+,xWf+",
            "endDateTime": "1985-04-12T23:20:50.52Z",
            "startDateTime": "1985-04-12T23:20:50.52Z",
            "@baseType": "velit eu",
            "@schemaLocation": "http://pcwsNqQeFFJZlEprMfQPEajwOX.esxl8YcE.zP0GQJ,iijtqn0RzScGa9ohsft79HCBYprUTHtXlanCQMTL+DFVCZauu-",
            "@type": "quis incididunt labore"
        },
        "@baseType": "enim ex ipsum pariatur",
        "@schemaLocation": "http://awnVjCWlwhLSSbc.ufbWW9Zk7J-2,vyx-aUFYkfPHLEaNyRV5d1ciMOXUt+nIzvlXiO7N16qQO6usS,Y",
        "@type": "et veniam velit magna"
    },
    "@baseType": "in dolore amet sed",
    "@schemaLocation": "http://CNPRhiWlpSkkbT.wgklG0FlUJAgkHSYu5KPmCyfIr2MhdJOtUSSNKrhh-R+Jrzx,GkMmrVUswHJMjsB7bs3rMLMRWZD",
    "@type": "anim in enim esse"
})



