#!/usr/bin/env dothttp

# imported from 35240-f27f798d-07bf-410e-bc36-81f925cac47d.postman_collection.json

// .

@name("Get EBS Default Kms Key ID")
GET "https://{{aws_ec2_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "Action"= "GetEbsDefaultKmsKeyId"


// .

@name("Modify EBS Default Kms Key ID")
GET "https://{{aws_ec2_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "Action"= "ModifyEbsDefaultKmsKeyId"


// .

@name("Reset EBS Default Kms Key ID")
GET "https://{{aws_ec2_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "Action"= "ResetEbsDefaultKmsKeyId"



