#!/usr/bin/env dothttp

# imported from 35240-e79ac4fd-58b9-40e6-880c-b6647b9028e7.postman_collection.json

@name("Catalog")
GET "https://catalog.archives.gov/api/v1"
? "action"= "search"
? "q"= "<your query>"



