#!/usr/bin/env dothttp

# imported from 35240-af938bfe-d636-455e-9182-83ae080c0f19.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"
"Authorization": "Bearer <Bearer Token>"


// Retrieves all analyses

@name("Get all analyses") : "base-inherit-auth"
GET "https://{{baseUrl}}/v2/analyses"
"Authorization": "Bearer <Bearer Token>"
? "q"= "Excepteur nisi in"
? "sort"= "Excepteur nisi in"
? "limit"= "20033802"
? "offset"= "20033802"


// Delete given list of analysis

@name("Deletes given list of analysis") : "base-inherit-auth"
DELETE "https://{{baseUrl}}/v2/analyses"
"Authorization": "Bearer <Bearer Token>"
"Content-Type": "application/json"
json([
    45831674,
    2250844
])



