#!/usr/bin/env dothttp

# imported from 35240-5af4ed67-4654-4363-a86d-3c7bcff23c51.postman_collection.json

// List contact departments.

@name("List contact departments")
GET "https://{{baseUrl}}/rest/accounts/contacts/departments"


// Deletes a contact department. The ID of the department must be specified.

@name("Delete a contact department")
DELETE "https://{{baseUrl}}/rest/accounts/contacts/departments/:departmentId"



