#!/usr/bin/env dothttp

# imported from 35240-20909047-00c3-478c-8e02-1c3f510f50c3.postman_collection.json

// Verify content. Please provide the content in the request. You also have to provide whether you have hashed the content yourself, or whether is should be done on the server side

@name("Verify content")
POST "https://{{baseUrl}}/existence/:configName/content"



