#!/usr/bin/env dothttp

# imported from 35240-7220de83-d124-4fe7-bf21-ae3a128a5b57.postman_collection.json

// # Delete CA Certificate [konghq](https://docs.konghq.com/2.0.x/admin-api/#delete-ca-certificate-1)
// 
// # Path parameters
// <table style="width:50%">
//   <tr>
//     <th>Attributes</th>
//     <th>Mandatory</th>
//     <th>Type</th>
//     <th>Description</th> 
//   </tr>
//   <tr>
//     <td>certificate id</td>
//     <td>required</td>
//     <td>path</td>
//     <td>The unique identifier of the CA Certificate to delete.</td>
//   </tr>
// </table>

@name("Delete CA Certificate")
DELETE "http://localhost/ca_/certificates/:ca_certificateId"



