#!/usr/bin/env dothttp

# imported from 35240-538b4bae-014b-4e31-9e7e-f206b0a4dc0c.postman_collection.json

// This operation list or find Association entities

@name("List or find Association objects")
GET "https://{{baseUrl}}/association"
? "fields"= "ad dolor"
? "offset"= "-52978875"
? "limit"= "-52978875"


// This operation creates a Association entity.

@name("Creates a Association")
POST "https://{{baseUrl}}/association"
"Content-Type": "application/json;charset=utf-8"
json({
    "name": "in aliquip cupidatat",
    "associationRole": {
        "entity": {
            "id": "Ut esse in anim enim",
            "href": "http://YFPBDsP.fqeKyE",
            "name": "eu",
            "@baseType": "fugiat irure in",
            "@schemaLocation": "http://zICRkCfUsGAeCnWjHn.togq6jDLCvF-",
            "@type": "eu",
            "@referredType": "Lorem"
        },
        "role": "consectetur non cupidatat sunt",
        "isSource": true,
        "@baseType": "dolor dolore in",
        "@schemaLocation": "http://vRWgNOWcoPaFLtOnVvXLA.ojxqnmipaHbmmh7N8AKp-alCn4q0u,O8MbXZop2.ueI-U,l7iH4x98gvqmtEnOwmqMvu7JmhSUzUio",
        "@type": "Lorem velit est"
    },
    "description": "veniam sint adipisicing in",
    "lastUpdate": "1949-08-04T07:53:29.631Z",
    "lifecycleStatus": "pariatur labore amet do",
    "version": "pariatur anim tempor occaecat",
    "associationSpec": {
        "id": "eiusmod",
        "href": "http://pYt.pyacW",
        "name": "pariatur dolore qui",
        "@baseType": "dolor tempor",
        "@schemaLocation": "http://BRDRJMXrHSvoryiMzfkp.tdz,Vafjki0GzTwmmCSm0WHB1.8kLHlSIuKhJtBptFvWxRGnR+z.LGRUKg,me",
        "@type": "exercita",
        "@referredType": "est eu Ut"
    },
    "constraint": [
        {
            "id": "nulla incididunt dolore",
            "href": "https://F.npycfmDI1rxq8u3DhSXqkls6WPf-yDsLroTSP20vjXZlzkdyDCD+pfAHJIWAR4t9HzbS-aA9,Su0uX2uWlWXK",
            "name": "pariatur Ut aliquip et",
            "version": "fugiat sint",
            "@baseType": "aute dolor mollit est Duis",
            "@schemaLocation": "http://crwfUryVLgFIkSQLYW.kje2CFABAkRDcMrARGZzMXecVKP",
            "@type": "volupta",
            "@referredType": "commodo enim non Ut consequat"
        },
        {
            "id": "in nulla",
            "href": "http://jlIBywbkkzdfBwqFNPHqsxfMxG.cvbkyzcbEln97olnDa5zhlY,bVcFkJiV",
            "name": "Lorem officia Ut",
            "version": "quis culpa tempor laborum aliquip",
            "@baseType": "sed consequat",
            "@schemaLocation": "http://JyefoXTnnTXnmU.svvvMVmbO,P+ggyfKZDJvFUPf.",
            "@type": "non et ad in",
            "@referredType": "do"
        }
    ],
    "validFor": {
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z"
    },
    "@baseType": "irure sunt pariatur",
    "@schemaLocation": "https://cSnXdfhPvYxPThiouGJnjMRsKebefZdG.lzsbz2peV81-VYZcHMT",
    "@type": "sed ullamco non proident"
})



