#!/usr/bin/env dothttp

# imported from 35240-ee1bcca8-1dc2-4d21-9276-24298e87d40c.postman_collection.json

@name("hubCreate")
POST "https://{{baseUrl}}/hub"
"Content-Type": "application/json"
json({
    "id": "ullamco ipsum ",
    "callback": "et officia id commodo adipisicing",
    "query": "sit sint minim eu deserunt"
})


@name("hubFind")
GET "https://{{baseUrl}}/hub"



