#!/usr/bin/env dothttp

# imported from 35240-5da4bd40-1308-4c08-9688-8cbdcd14f62d.postman_collection.json

@name("Searchparam")
GET "https://{{baseUrl}}/api/search/"
? "matrix"= "ALL"
? "token"= "anim commodo Ut ad"


@name("Deprecatedsearch")
GET "https://{{baseUrl}}/api/search/:params"
? "matrix"= "ALL"
? "token"= "anim commodo Ut ad"



