#!/usr/bin/env dothttp

# imported from 35240-4ff70fc9-8539-43e5-b513-382f49f2c6a5.postman_collection.json

// This operation list or find TestEnvironmentProvisioningExecution entities

@name("List or find TestEnvironmentProvisioningExecution objects")
GET "https://{{baseUrl}}/testEnvironmentProvisioningExecution"
? "fields"= "ex aute dolore dolore"
? "offset"= "-66922574"
? "limit"= "-66922574"


// This operation creates a TestEnvironmentProvisioningExecution entity.

@name("Creates a TestEnvironmentProvisioningExecution")
POST "https://{{baseUrl}}/testEnvironmentProvisioningExecution"
"Content-Type": "application/json;charset=utf-8"
json({
    "testEnvironmentAllocationExecution": {
        "resourceManagerUrl": "https://myserver.com/resourceManager",
        "id": "cillum exercitation laboris",
        "href": "https://BJiRFFpNZLdeJpsoWhKlCxwnagVZayMQn.kwveTwLyEFRwqzUY4",
        "dataCorrelationId": "aac9969d-219d-4ff1-b256-1765dcf9b342",
        "abstractEnvironment": {
            "id": "ut ea",
            "href": "http://lAgFyruXxITFQ.vpyhmzWikNWL-6Ky8",
            "name": "minim exercitation eu Lorem",
            "@baseType": "Excepteur tempor",
            "@schemaLocation": "https://rzKwlplyizktpJcPbdsj.cqnwVyZuxqB4PZ2keZx4bBtiFrOQpCWtKdakGbcHrWwSpaGnnxrysZ1zMblptFPeCcnq5b1.udmJT",
            "@type": "est ullamco",
            "@referredType": "dolore non veniam u"
        },
        "concreteResourceMapping": [
            {
                "id": "minim aliqua ea dolor",
                "href": "http://bvvIapxLjglQyMrpwh.hgraPCFAwBTojT22xc-tSxlx2husMCDrngO1m",
                "abstractResource": "phone",
                "concreteResource": [
                    {
                        "name": "iPhone_1289",
                        "id": "dolore fugiat aliqua do",
                        "href": "http://toFnVxOfPBLgioMALZl.tozzIvP1M,hbdKFNeFLKlaVSxA+kikv4JUgX4",
                        "@baseType": "cupidatat d",
                        "@schemaLocation": "http://BeaMcoVwGJdnUQhaOZKbXZVkDbjUJ.kaN",
                        "@type": "cupidatat Excepteur"
                    },
                    {
                        "name": "iPhone_1289",
                        "id": "et aute officia",
                        "href": "http://ATQzUDshc.jnpluZrzJa4GUGZqb84M1+R",
                        "@baseType": "pariatur dolor aliqua",
                        "@schemaLocation": "https://vvVlHtRCibBJYuALYlF.fkcOmPbDUdOmX5Sc8oXnepa+zMhurYtzrTzVvo1pN7l",
                        "@type": "sunt aliquip est irure"
                    }
                ],
                "@baseType": "ullamco labore",
                "@schemaLocation": "http://uFkgeiUJWDxBdjHUULOWQbetJCUMhL.nejwU8VzU9ycrvWLs0aTkdwG5Gz0b-GUTIv2ObQoa",
                "@type": "dolor mollit"
            },
            {
                "id": "dolore in Lorem",
                "href": "http://Ysg.tgfQntO5h.Ns",
                "abstractResource": "phone",
                "concreteResource": [
                    {
                        "name": "iPhone_1289",
                        "id": "dolore pariatur",
                        "href": "https://FrvSexFagjPxAdiLIJmHQekQhIFgtQq.xiMNr6M",
                        "@baseType": "cupidatat in",
                        "@schemaLocation": "http://plZvIBkRJWkuqgoE.hrffbWUeUmciEzAuz9u2IdSuyjM0BQtVfwDNUqobEeSN",
                        "@type": "magna dolore"
                    },
                    {
                        "name": "iPhone_1289",
                        "id": "deserunt ",
                        "href": "https://NUmCAABjLRdqHcyvAvJiVS.uezDzTktqJ",
                        "@baseType": "sed incididunt",
                        "@schemaLocation": "https://MkWILuU.iztin9,kr",
                        "@type": "non nulla nisi Ut"
                    }
                ],
                "@baseType": "ut voluptate",
                "@schemaLocation": "http://MSCcZRIxVerqzZyGBTKsOCPeqHsjrJDmb.xhuzZGAk57D",
                "@type": "elit ex i"
            }
        ],
        "generalTestArtifact": [
            {
                "id": "sun",
                "href": "http://YJHrdz.itHf5sIfnpWSAhDe+w4WGIS0KWxrhGJqPxHq,tmr-1shjYLkmVIwCheBcs+",
                "name": "magna culpa est in adipisicing",
                "@baseType": "deserunt",
                "@schemaLocation": "https://bpBGjdRKsHfMLiBoqmmklLQhaELpR.roqHwi.QZmOJwe0otuUC8Tveo0-6zFKNgdHqc9Uv5G9rehrtcYuoGJTVww8.s30CDChBqvvI95FH5Yw",
                "@type": "nisi",
                "@referredType": "cupidat"
            },
            {
                "id": "sint ullamco consequat Ut",
                "href": "https://l.ttpCo+swRY65gVGs",
                "name": "Dui",
                "@baseType": "cupidatat exercitation laborum nulla deserunt",
                "@schemaLocation": "http://iFaTBsgIWcqKx.zfszTSNM4Nhp5JMCRuZmKNqlV3BaQ.",
                "@type": "in exercitation incididunt dolor",
                "@referredType": "id reprehenderit cupidatat magna"
            }
        ],
        "state": "completed",
        "testScenario": {
            "id": "eiusmod aute",
            "href": "https://UzOcIpkvmnhvdCRWkwVGumRjtnSeWaU.fivtNmoQcq3ihmtfN,r4Nnv0pk",
            "name": "ullamco ut",
            "@baseType": "consectetur in",
            "@schemaLocation": "http://NTmMOHCEtFwGJJcfVxGVaNFbziAnwaus.bakEC6gVphXAQliVDjLYVQBjIv5hAI85iebJh",
            "@type": "sed officia eiusmod",
            "@referredType": "Lorem"
        },
        "@baseType": "officia consequat irure q",
        "@schemaLocation": "http://MTvwdLmzFqEtPG.pfLrD",
        "@type": "sunt reprehenderit fugiat in irure"
    },
    "dataCorrelationId": "aac9969d-219d-4ff1-b256-1765dcf9b342",
    "generalTestArtifact": [
        {
            "id": "quis",
            "href": "https://rY.jdeLWa52",
            "name": "culpa dolor exercitation",
            "@baseType": "c",
            "@schemaLocation": "https://C.ylJxncX3+ql30+dTOhec1YD31T+9A",
            "@type": "eiusmod Lorem",
            "@referredType": "aute reprehenderit"
        },
        {
            "id": "irure in",
            "href": "https://RfS.syjvWITHiS3bjEsEvCyh9-bqPG30RJ0BB-THfjsIEpIIOchnMhhT",
            "name": "in amet sint",
            "@baseType": "aliquip adipisicing culpa",
            "@schemaLocation": "https://pndNEgdOguKdfgJZbeUEwDVKg.fnz7h,koSrSgtPhMVXlusr2MszvzUG5c3onX-qh",
            "@type": "fugiat nulla tempor ex sed",
            "@referredType": "eiusmod est"
        }
    ],
    "provisioningArtifact": [
        {
            "id": "amet pariatur magna",
            "href": "https://QqESqCpLdDXIwaYo.yuvr05cirKbdG7RojXo0s4WeHU-VkUcPFj+PFRos-eC1Ficv",
            "name": "sunt sint",
            "@baseType": "Lorem et",
            "@schemaLocation": "https://UywDsPHpCh.jceakHMrPgnv",
            "@type": "sunt dolore pro",
            "@referredType": "sunt"
        },
        {
            "id": "pariatur dolor consequat anim",
            "href": "https://TZSXEgMlOniaMTiRnWFkSWuME.hyjJIoUQJO5fmnczqe-hdzp,",
            "name": "eiusmod pariatur magna",
            "@baseType": "elit incididunt Duis consectetur",
            "@schemaLocation": "http://FOTURuOsYPBolBvc.oobCYZpCc,kK9ykThdRJMRgxkQ,toKm2Ma",
            "@type": "fugiat nulla ut",
            "@referredType": "do elit"
        }
    ],
    "state": "pending",
    "@baseType": "anim esse sed adipisicing sit",
    "@schemaLocation": "http://CT.ahoC0PwvGeCrjWgO0xR42lpe0+kBzi0PsQ1Ry,bVPEFjKH",
    "@type": "id ut in Excepteur"
})



