#!/usr/bin/env dothttp

# imported from 35240-d76987fb-f2f9-425d-9645-ecebd487c07d.postman_collection.json

// Change the Roles of a Pending Invite

@name("Change the Roles of a Pending Invite")
PATCH "https://{{baseUrl}}/organizations/:organization_identifier/invite/:identifier"
"X": "<>"
? "roles"= "<>"



