#!/usr/bin/env dothttp

# imported from 35240-6135048e-d8f2-4063-a921-e9f54a73ef03.postman_collection.json

// **This endpoint allows you to retrieve all of your email statistics for each of your categories.**
// 
// If you do not define any query parameters, this endpoint will return a sum for each category in groups of 10.
// 
// Categories allow you to group your emails together according to broad topics that you define. For more information, please see our [User Guide](https://sendgrid.com/docs/User_Guide/Statistics/categories.html).

@name("Retrieve Email Statistics for Categories")
GET "https://{{baseUrl}}/categories/stats"
? "start_date"= "<string>"
? "end_date"= "<string>"
? "categories"= "<string>"
? "limit"= "<string>"
? "offset"= "<string>"
? "aggregated_by"= "<string>"


// **This endpoint allows you to retrieve the total sum of each email statistic for every category over the given date range.**
// 
// If you do not define any query parameters, this endpoint will return a sum for each category in groups of 10.
// 
// Categories allow you to group your emails together according to broad topics that you define. For more information, please see our [User Guide](https://sendgrid.com/docs/User_Guide/Statistics/categories.html).

@name("Retrieve sums of email stats for each category [Needs: Stats object defined, has category ID?]")
GET "https://{{baseUrl}}/categories/stats/sums"
? "sort_by_metric"= "<string>"
? "sort_by_direction"= "<string>"
? "start_date"= "<string>"
? "end_date"= "<string>"
? "limit"= "<string>"
? "offset"= "<string>"
? "aggregated_by"= "<string>"



