#!/usr/bin/env dothttp

# imported from 35240-175bce79-8928-437d-8db8-aad1709514f2.postman_collection.json

// This operation retrieves a ResourceSpecification entity. Attribute selection is enabled for all first level attributes.

@name("Retrieves a ResourceSpecification by ID")
GET "https://{{baseUrl}}/resourceSpecification/:id"
? "fields"= "tempor sint Ut"


// This operation updates partially a ResourceSpecification entity.

@name("Updates partially a ResourceSpecification")
PATCH "https://{{baseUrl}}/resourceSpecification/:id"
"Content-Type": "application/json;charset=utf-8"
json({
    "category": "sed ea",
    "description": "do aliqua exercitation",
    "isBundle": true,
    "lastUpdate": "1952-10-30T09:28:41.395Z",
    "lifecycleStatus": "exercitation",
    "name": "nulla tempor laboris sit",
    "version": "id ex eu Duis nulla",
    "attachment": [
        {
            "id": "4aafacbd-11ff-4dc8-b445-305f2215715f",
            "href": "http://host/Attachment/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "attachmentType": "video",
            "content": "ipsum eiusmod dolore minim",
            "description": "Photograph of the Product",
            "mimeType": "c",
            "name": "aliquip lab",
            "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "size": {
                "amount": 1,
                "units": ""
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "aute tempo",
            "@schemaLocation": "http://ozfsvejcxDTPSu.oeHBOTIxPyjMyFYViKMxzpy.Kdt,sNpmbLHlJ5oXBaSEdT6UVna2ZhmqBWInXrNq.VYGg",
            "@type": "fugiat sed et irure dolor",
            "@referredType": "magna tempor"
        },
        {
            "id": "4aafacbd-11ff-4dc8-b445-305f2215715f",
            "href": "http://host/Attachment/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "attachmentType": "video",
            "content": "ad",
            "description": "Photograph of the Product",
            "mimeType": "magna quis aliqua",
            "name": "do",
            "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "size": {
                "amount": 1,
                "units": "aliqua laboris sint commodo dolor"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "eu do est quis",
            "@schemaLocation": "http://cbLHtxkKEWtzYXppdDVUmFzYsWkadNuM.iefiXtePkYBQEPNtRuvVkOBVrI2ST5CYY1J",
            "@type": "anim qui eu",
            "@referredType": "esse nostrud aute do fugiat"
        }
    ],
    "featureSpecification": [
        {
            "id": "Excepteur magna nulla",
            "isBundle": false,
            "isEnabled": false,
            "name": "est",
            "version": "exercitation in ad",
            "constraint": [
                {
                    "id": "aliquip labore consectetur culpa",
                    "href": "enim",
                    "name": "Ut est ",
                    "version": "amet",
                    "@baseType": "officia",
                    "@schemaLocation": "http://vqGs.qqOAKuTpJaNexcsW9I7om7,YSQhNbusaNtJnPTDlN",
                    "@type": "dolore",
                    "@referredType": "commodo aute nisi Ut"
                },
                {
                    "id": "incididunt tempor elit sint eiusmod",
                    "href": "Ut anim dolore Duis",
                    "name": "deserunt sint nostrud",
                    "version": "sit dolore sint officia",
                    "@baseType": "conse",
                    "@schemaLocation": "http://UoqBgzpSZjXelHD.zeaEVO-LLjcQ",
                    "@type": "sit aliqua Duis",
                    "@referredType": "aliqua ea ex aute"
                }
            ],
            "featureSpecCharacteristic": [
                {
                    "name": "nisi incididunt",
                    "configurable": true,
                    "extensible": true,
                    "isUnique": false,
                    "maxCardinality": 78361769,
                    "minCardinality": 42636573,
                    "regex": "in minim pariatur",
                    "valueType": "dolor esse",
                    "featureSpecCharRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "featureSpecCharacteristicValue": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "aliquip minim cillum qui",
                    "@schemaLocation": "https://XepCUTKJncQOpcjBoaTsijFOUDTO.hupu.s2vb+Rucp5SmDxwxu8pN+Y196U5yG",
                    "@type": "ut ad",
                    "@valueSchemaLocation": "labore consequat non nulla"
                },
                {
                    "name": "consectet",
                    "configurable": false,
                    "extensible": true,
                    "isUnique": true,
                    "maxCardinality": 40750028,
                    "minCardinality": -44776688,
                    "regex": "incididunt",
                    "valueType": "incididunt",
                    "featureSpecCharRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "featureSpecCharacteristicValue": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "dolore est aliquip in",
                    "@schemaLocation": "http://OkBT.rjxhAspTVDBhBbv5A+33UfNsAjZOEQPMLGNnZZJ+",
                    "@type": "anim",
                    "@valueSchemaLocation": "mollit Excepteur n"
                }
            ],
            "featureSpecRelationship": [
                {
                    "name": "eu",
                    "relationshipType": "minim laborum do",
                    "featureId": "laborum",
                    "resourceSpecificationHref": "aliquip voluptate ea incididunt",
                    "resourceSpecificationId": "eu sint consectetur deserunt ad",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "est commodo Excepteur aliqua",
                    "@schemaLocation": "http://bmAjZSnwVEAGNgpWIDAv.yacz4rFC2jjGz+N-wF",
                    "@type": "proident ipsum dolore"
                },
                {
                    "name": "dolor adipisicing eiusmod ad",
                    "relationshipType": "cupidatat do",
                    "featureId": "veniam",
                    "resourceSpecificationHref": "in minim qui",
                    "resourceSpecificationId": "mollit et",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "laborum est ullamco",
                    "@schemaLocation": "https://aNeglFwZaKdwhoxyGnoiSweYGqZzc.tmfew0ww6plUA5WXw4NpH.Zwdqw3WiuwvpIOmj+TxJ1WiyPE3XRj3a",
                    "@type": "d"
                }
            ],
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "ad aute",
            "@schemaLocation": "http://EciCwTwWsjF.cwodVA-pU4g+LuChBkdgANj.Xol6egmBwQgT9bzZRBsCswO6Pd1hOsoOCw",
            "@type": "sint quis in ea"
        },
        {
            "id": "fugiat qui",
            "isBundle": true,
            "isEnabled": true,
            "name": "id in ullamco",
            "version": "in labore in",
            "constraint": [
                {
                    "id": "in voluptate",
                    "href": "veniam elit esse",
                    "name": "aliqua ullamco",
                    "version": "dolore Ut ex",
                    "@baseType": "eu qui sit ex",
                    "@schemaLocation": "http://AO.uvzogh+xM6qCGTD2OHqNVCdVQDISSd,xQ.aqXMCdO",
                    "@type": "officia ex",
                    "@referredType": "aliqua pariatur fugiat"
                },
                {
                    "id": "ad ut officia",
                    "href": "occaecat officia in est ut",
                    "name": "aliquip aliqua nostrud",
                    "version": "dolor dolore reprehenderit amet minim",
                    "@baseType": "enim ad",
                    "@schemaLocation": "http://QRpdeaZXUEIBD.eenx6a.WbrmkmilfNbrt9hpDZ1g2Q9+Oy9BsSq5AleDq8Nk2lHqouZZlrDAIGLvHDFwgtbuBcs5R,Qn",
                    "@type": "anim pariatur aliquip",
                    "@referredType": "id anim irure sint officia"
                }
            ],
            "featureSpecCharacteristic": [
                {
                    "name": "mollit quis labore",
                    "configurable": true,
                    "extensible": false,
                    "isUnique": false,
                    "maxCardinality": 63367007,
                    "minCardinality": -13831666,
                    "regex": "dolore esse officia ea",
                    "valueType": "et fugiat Duis",
                    "featureSpecCharRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "featureSpecCharacteristicValue": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "minim sint",
                    "@schemaLocation": "https://tWceXMyTsmExIfbGvrARpjWuqnRzR.fnBoSwBC+A-yraTlza5QgR0fMehGy7iq6dITqoksICeltMrEbhz,gpgVe8",
                    "@type": "sunt Lorem do amet in",
                    "@valueSchemaLocation": "Ut nulla aute"
                },
                {
                    "name": "id in amet",
                    "configurable": true,
                    "extensible": false,
                    "isUnique": false,
                    "maxCardinality": -26371060,
                    "minCardinality": 14718874,
                    "regex": "elit",
                    "valueType": "sit ipsum",
                    "featureSpecCharRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "featureSpecCharacteristicValue": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "mollit nisi",
                    "@schemaLocation": "http://FxnkbegSllWf.fiT",
                    "@type": "tempor eiusmod",
                    "@valueSchemaLocation": "occaecat id"
                }
            ],
            "featureSpecRelationship": [
                {
                    "name": "culp",
                    "relationshipType": "qui ",
                    "featureId": "te",
                    "resourceSpecificationHref": "dolor fugiat cupidatat",
                    "resourceSpecificationId": "anim proident incididunt",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "nulla exercitation sint esse",
                    "@schemaLocation": "https://vAiSdoUWVtrjLadYF.vquraUXz3dsxG2Lf-tebmAWHNUBfs",
                    "@type": "adipisicing exercitation"
                },
                {
                    "name": "ex esse aliquip nisi",
                    "relationshipType": "sunt reprehenderit",
                    "featureId": "ex dolore",
                    "resourceSpecificationHref": "in dolore incididunt eiusmod sit",
                    "resourceSpecificationId": "minim",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "proident ip",
                    "@schemaLocation": "http://dPGvzHzJUhCMSCzCr.mlRiI.OAAS.Xs",
                    "@type": "exercitation eu labore fugiat"
                }
            ],
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "nisi labore aute enim",
            "@schemaLocation": "http://CzVkgeJx.hrTChOH7PTNVWsW9vFr5LxuBsNmL3xug,PKsUO+Kn.zksGL.en31W,cU,x",
            "@type": "pariatur nisi reprehenderit adipisicing"
        }
    ],
    "relatedParty": [
        {
            "@referredType": "ut Ut commodo non",
            "id": "fugiat",
            "href": "aliqua id",
            "name": "qui enim",
            "role": "id veniam voluptate magna sed",
            "@baseType": "incididunt in",
            "@schemaLocation": "http://BEzwYUIIMnNnFAJpWgIhTjwwp.zvVMaKYDIsKmEopYVnv4cnakBz3,",
            "@type": "officia ullamco eu elit qui"
        },
        {
            "@referredType": "pariatur aliquip amet cillum",
            "id": "in consequat magna",
            "href": "incididunt",
            "name": "irure esse cupidatat laboris",
            "role": "ut aliquip",
            "@baseType": "sed ea",
            "@schemaLocation": "http://eFINVUoraQcOnlCxyEgLxWPAxohyVmqKp.lkixSzYwSDEnx1-IxsMag-+NdAlVNtwen+q7u6wSCVIYj.TJ",
            "@type": "Duis sint"
        }
    ],
    "resourceSpecCharacteristic": [
        {
            "id": "consectetur amet ex",
            "configurable": false,
            "description": "Excepteur consectetur",
            "extensible": true,
            "isUnique": true,
            "maxCardinality": -67701421,
            "minCardinality": 37352469,
            "name": "aute proident veniam nisi",
            "regex": "cupidatat in incididunt consectetur",
            "valueType": "anim sit irure consequat",
            "resourceSpecCharRelationship": [
                {
                    "characteristicSpecificationId": "tempor voluptate mollit",
                    "name": "aliquip adipisicing",
                    "relationshipType": "exercitation",
                    "resourceSpecificationHref": "pariatur do aliquip laborum",
                    "resourceSpecificationId": "in enim fugiat",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "commodo esse cillum",
                    "@schemaLocation": "https://fjZuAbqSXLNWSWstnpcZPJnrXIZWIBnZ.kqkA-ZmFw7oNXGLA.Fo7WK+wz05gzIjvKizcp7WunI3Hx35NLjXLZRshW4T7z8+re9NplzM",
                    "@type": "laborum in"
                },
                {
                    "characteristicSpecificationId": "sed adipisicin",
                    "name": "voluptate tempor velit ut",
                    "relationshipType": "eu eiusmod velit Excepteur",
                    "resourceSpecificationHref": "Lorem labore",
                    "resourceSpecificationId": "consequat non",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "est",
                    "@schemaLocation": "http://tnrNmdTzJhyG.xtxeoQ4qzvBXVnqHEK5FyOpTNYU8cp0fJ5PU1E",
                    "@type": "sunt dolor"
                }
            ],
            "resourceSpecCharacteristicValue": [
                {
                    "isDefault": false,
                    "rangeInterval": "Ut adipisicing commodo laborum ut",
                    "regex": "sint Ut",
                    "unitOfMeasure": "mollit anim ad",
                    "valueFrom": 52847072,
                    "valueTo": -23862403,
                    "valueType": "velit eiusmod occaecat qui",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "ea quis",
                    "@schemaLocation": "http://AtzayhXsGIucWc.ynMBU",
                    "@type": "non velit voluptate reprehenderit dolore"
                },
                {
                    "isDefault": false,
                    "rangeInterval": "aliqua labore",
                    "regex": "laboris magna reprehenderit non",
                    "unitOfMeasure": "enim",
                    "valueFrom": 35224301,
                    "valueTo": -47507791,
                    "valueType": "aliquip",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "occaecat cillum",
                    "@schemaLocation": "http://rxEaJLOOqSbffNzODfq.rhhpaNtlee1,Uk+eWh+db7hgC",
                    "@type": "do Lorem occaecat ex"
                }
            ],
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "Excepteur tempor aliqua nulla",
            "@schemaLocation": "http://tLOqgFNvVGHtCJfhsHdMVNhq.dvPnQlAGKYAakrDwFFWS.CSavTzrn",
            "@type": "tempor laboris",
            "@valueSchemaLocation": "dolor"
        },
        {
            "id": "sint laborum pariatur",
            "configurable": false,
            "description": "magna in",
            "extensible": true,
            "isUnique": false,
            "maxCardinality": 67784309,
            "minCardinality": -34725613,
            "name": "dolor ex",
            "regex": "cupidatat ipsum",
            "valueType": "aliquip minim",
            "resourceSpecCharRelationship": [
                {
                    "characteristicSpecificationId": "laboris exercitation",
                    "name": "officia in",
                    "relationshipType": "ipsum ",
                    "resourceSpecificationHref": "veniam laborum in",
                    "resourceSpecificationId": "irure proident",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "sunt",
                    "@schemaLocation": "http://mhgbjpXFIoCNhUjaQufbnpQIPx.grtXQy5tKiW9crxRK3yVXqU8lZoIOJbSHO2x.nCvb8FLzd7",
                    "@type": "in commodo Ut"
                },
                {
                    "characteristicSpecificationId": "cillum minim aliquip",
                    "name": "eiusmod ",
                    "relationshipType": "qui cillum et",
                    "resourceSpecificationHref": "dolore",
                    "resourceSpecificationId": "deserunt laborum enim",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "enim elit nulla",
                    "@schemaLocation": "http://bFqUszzDRScXBPckuHQmgaPxRDIredvKI.khtvJzqA24ofZw6",
                    "@type": "laboris"
                }
            ],
            "resourceSpecCharacteristicValue": [
                {
                    "isDefault": false,
                    "rangeInterval": "dolor qui nostrud",
                    "regex": "et pariatur consequat",
                    "unitOfMeasure": "consequat",
                    "valueFrom": 91747666,
                    "valueTo": -87252133,
                    "valueType": "et reprehenderit",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "laborum",
                    "@schemaLocation": "http://jCq.use3viMymDZWq0APNtNJC1.MrY,NOXHA.ySLRBUAJoem7FrMxKZJ",
                    "@type": "non exercitation"
                },
                {
                    "isDefault": false,
                    "rangeInterval": "minim incididunt",
                    "regex": "non",
                    "unitOfMeasure": "cupidatat dolor non in",
                    "valueFrom": -59538792,
                    "valueTo": 42434337,
                    "valueType": "nostrud culpa in",
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": "labore voluptate officia",
                    "@schemaLocation": "https://bIsBhdERbCAuIvDKTTvB.wamfA10Ia9rskXxN-GOkNFtXxDX.1Vyx.We7Fo+h8qYdNZFB6NmzDAYlHWU4CJdCYB",
                    "@type": "tempor sit labore in"
                }
            ],
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "sed est officia",
            "@schemaLocation": "http://ayeZbYWJO.xtaNRzwscugGUAfd7jyDtMJc5+L2VQE,2nnsuoh4JCbPPFH0sDbUcf,+b",
            "@type": "qui magna pariatur",
            "@valueSchemaLocation": "anim dolore aliqua sed ut"
        }
    ],
    "resourceSpecRelationship": [
        {
            "id": "cupidatat ut tempor consequat",
            "href": "quis voluptate do nisi qui",
            "defaultQuantity": -85944322,
            "maximumQuantity": -13231928,
            "minimumQuantity": -64659345,
            "name": "anim ullamco",
            "relationshipType": "nisi sint aliquip est sunt",
            "role": "sit eu tempor laborum",
            "characteristic": [
                {
                    "id": "nulla pariatur",
                    "configurable": true,
                    "description": "culpa magna ut commodo deserunt",
                    "extensible": true,
                    "isUnique": false,
                    "maxCardinality": -31375023,
                    "minCardinality": 59594074,
                    "name": "id amet anim",
                    "regex": "reprehenderit dolore",
                    "valueType": "cupidatat",
                    "resourceSpecCharRelationship": [
                        {
                            "characteristicSpecificationId": "consequat ea sunt incididunt",
                            "name": "officia",
                            "relationshipType": "tempor Duis sint nostrud nisi",
                            "resourceSpecificationHref": "labore mollit aliqua ut",
                            "resourceSpecificationId": "minim fugiat in eiusmod nulla",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "@baseType": "in minim sint velit dolor",
                            "@schemaLocation": "http://Hcskr.ebhlbzJaT+r+zz5AOlNPsVIkj3mO,kOn51ZVOp",
                            "@type": "quis Lorem"
                        },
                        {
                            "characteristicSpecificationId": "dolor irure ut",
                            "name": "voluptate labore est cupidatat",
                            "relationshipType": "id eiusmod esse consequat",
                            "resourceSpecificationHref": "magna",
                            "resourceSpecificationId": "labore ea tempor mollit anim",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "@baseType": "laborum veniam",
                            "@schemaLocation": "http://kZdPkiuGWWPzPEWc.abWNuAF2zrG0BqG16cn9whByVKiuGSk9ggXyxfKGJqFjbHIM1rg.rE",
                            "@type": "in non culpa in eu"
                        }
                    ],
                    "resourceSpecCharacteristicValue": [
                        {
                            "isDefault": false,
                            "rangeInterval": "veniam incididunt Lorem",
                            "regex": "consectetur",
                            "unitOfMeasure": "veniam est magna ad",
                            "valueFrom": -81361107,
                            "valueTo": -3325048,
                            "valueType": "ipsum proident officia nulla",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "Ut laboris quis",
                            "@schemaLocation": "https://IVdnXIG.wgkM-2SsLZrjRGd,KLXInrCkAeUqGwmM6EAZ8SC+4ssSrK",
                            "@type": "in et id voluptate"
                        },
                        {
                            "isDefault": true,
                            "rangeInterval": "ut ipsum nostrud",
                            "regex": "aliquip voluptate",
                            "unitOfMeasure": "ipsum dolor occaecat ad ut",
                            "valueFrom": -35004288,
                            "valueTo": 21387173,
                            "valueType": "cupidatat qui",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "laboris",
                            "@schemaLocation": "https://DEeLIsOJm.fhnapLptEEpQo1K2FLUFDDaA3xSJGnY",
                            "@type": "qui"
                        }
                    ],
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "deserunt qui nisi proident",
                    "@schemaLocation": "http://ZTLkORiZhrmnM.oiRegx-tJf.VC1agkBK-tfByZ4anJfUK1qCaIlQjIFvCwWKb-gCzxRiA7mBRdW4JUkdOox",
                    "@type": "sunt laboris",
                    "@valueSchemaLocation": "Ut aliquip deserunt sint culpa"
                },
                {
                    "id": "eiusmod ea ad et",
                    "configurable": true,
                    "description": "exercitation cupidata",
                    "extensible": false,
                    "isUnique": true,
                    "maxCardinality": 85665566,
                    "minCardinality": 25869862,
                    "name": "Excepteur ea sunt",
                    "regex": "s",
                    "valueType": "sit anim velit sint",
                    "resourceSpecCharRelationship": [
                        {
                            "characteristicSpecificationId": "elit sunt eiusmod velit",
                            "name": "ullamco adipis",
                            "relationshipType": "ea",
                            "resourceSpecificationHref": "id culpa do",
                            "resourceSpecificationId": "cillum eiusmod ea sit",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "@baseType": "reprehenderit aute ",
                            "@schemaLocation": "https://naNYBwHbTYsEbLE.aqpih-",
                            "@type": "Excep"
                        },
                        {
                            "characteristicSpecificationId": "Excepteur sed eu",
                            "name": "in pariatur",
                            "relationshipType": "in velit minim",
                            "resourceSpecificationHref": "sint",
                            "resourceSpecificationId": "dolore",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "@baseType": "aute proident amet incididunt",
                            "@schemaLocation": "https://ps.faiBAL.41KCz13eF.5Z2PYHbY3TU40dYDT8uKblwbRMPN9YFv1lvg5w",
                            "@type": "exercitation pariatur"
                        }
                    ],
                    "resourceSpecCharacteristicValue": [
                        {
                            "isDefault": true,
                            "rangeInterval": "nisi Duis in sunt",
                            "regex": "laboris Excepteur in Duis",
                            "unitOfMeasure": "do eiusmod amet",
                            "valueFrom": 99511144,
                            "valueTo": -4770602,
                            "valueType": "fugiat dolore",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "fugiat ad Excepteur est velit",
                            "@schemaLocation": "https://adEnPcpxrKHuhvkMjHGNhd.dizpTB+4sdJXlplMVjc2fLzbUPTFvG",
                            "@type": "mollit adipisicing non Duis"
                        },
                        {
                            "isDefault": true,
                            "rangeInterval": "officia culpa reprehenderit sit",
                            "regex": "fugiat incididunt sit cillum",
                            "unitOfMeasure": "quis sit eiusmod dolor nostrud",
                            "valueFrom": 44471338,
                            "valueTo": -8764798,
                            "valueType": "mollit dolor in Excepteur",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "nostrud",
                            "@schemaLocation": "http://JJCFiIyKECluuGUnQABSjutjFfYoW.augXy1Fud2ICgKVU+lHoL2tfwkJ",
                            "@type": "Ut"
                        }
                    ],
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "nulla ut laborum",
                    "@schemaLocation": "http://DLTq.zipiuPDcD604eYCBhROKisIY",
                    "@type": "irure nostrud exercitation culpa dolor",
                    "@valueSchemaLocation": "fugiat tempor"
                }
            ],
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "reprehenderit veniam dolore quis",
            "@schemaLocation": "http://nIVZGopPRxdowDzoLG.ohkpX2neRw7f4copTSwxgGrkF0w4FhWfEuOvP4Pa,l,GbPewLEA189vZH9",
            "@type": "fugiat veniam do Excepteur"
        },
        {
            "id": "ipsum do",
            "href": "nulla e",
            "defaultQuantity": -6400899,
            "maximumQuantity": -31374171,
            "minimumQuantity": 50594158,
            "name": "ex sed",
            "relationshipType": "nostrud minim",
            "role": "ad",
            "characteristic": [
                {
                    "id": "reprehenderit irure consequat enim",
                    "configurable": false,
                    "description": "sint labore",
                    "extensible": false,
                    "isUnique": false,
                    "maxCardinality": 68554702,
                    "minCardinality": 50576051,
                    "name": "dolore",
                    "regex": "ad",
                    "valueType": "tempor Ut",
                    "resourceSpecCharRelationship": [
                        {
                            "characteristicSpecificationId": "amet ea adipisicing eiusmod id",
                            "name": "ut irure labore cillum",
                            "relationshipType": "consequat",
                            "resourceSpecificationHref": "ipsum",
                            "resourceSpecificationId": "velit",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "@baseType": "quis magna nisi ut",
                            "@schemaLocation": "http://heJftjSWIAXBUthyOVAMNUY.hpRpAKfXQbjIAcHJul5",
                            "@type": "Duis fugiat et"
                        },
                        {
                            "characteristicSpecificationId": "magna sit in",
                            "name": "cillum proident irure",
                            "relationshipType": "adipisicing sit proident",
                            "resourceSpecificationHref": "non Excepteur",
                            "resourceSpecificationId": "voluptate ex",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "@baseType": "irure in enim",
                            "@schemaLocation": "http://O.ytutnbE.cDM7on4TvuRFj1YBFdLCP7nkFgdoHA0qebg0iO,C",
                            "@type": "quis est qui aliqua cu"
                        }
                    ],
                    "resourceSpecCharacteristicValue": [
                        {
                            "isDefault": false,
                            "rangeInterval": "Lorem qui deserunt laboris quis",
                            "regex": "aliquip ullamco in aliqua dolor",
                            "unitOfMeasure": "commodo labore",
                            "valueFrom": 99136310,
                            "valueTo": -11914822,
                            "valueType": "irure",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "aliquip nisi consequat",
                            "@schemaLocation": "https://JSIcNfwIZaDlPdXdLZLoKlIIij.wbsvWB-kkWc9.FYly3oT7+jXT,.dBmPD8Zsw+FHPiBw,",
                            "@type": "in ipsum"
                        },
                        {
                            "isDefault": false,
                            "rangeInterval": "dolor in",
                            "regex": "exercitation eu officia dolore id",
                            "unitOfMeasure": "occaecat in mollit amet in",
                            "valueFrom": 31752613,
                            "valueTo": 1590301,
                            "valueType": "cillum esse consectetur",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "minim aliquip occaecat",
                            "@schemaLocation": "http://CvQvIbFnMdfaMcznz.dztBW2zD8atrR6Xb",
                            "@type": "consectetur pariatur nostrud amet"
                        }
                    ],
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "enim in",
                    "@schemaLocation": "http://QoXTWOoaVixtIbxbMstOvmuLtss.uruHWHDE-pK5ROkHd,0Ii",
                    "@type": "sint Excepteur pariatur ea",
                    "@valueSchemaLocation": "cill"
                },
                {
                    "id": "exercitation nulla nisi quis",
                    "configurable": false,
                    "description": "labore commodo magna enim",
                    "extensible": false,
                    "isUnique": false,
                    "maxCardinality": 59049500,
                    "minCardinality": -74706978,
                    "name": "incididunt ipsum",
                    "regex": "dolor",
                    "valueType": "non consequat enim eiusmod",
                    "resourceSpecCharRelationship": [
                        {
                            "characteristicSpecificationId": "et in",
                            "name": "commodo qui laboris aute",
                            "relationshipType": "magna eiusmod",
                            "resourceSpecificationHref": "nulla irure quis labore",
                            "resourceSpecificationId": "aliqua laborum",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "@baseType": "deserunt consectetur elit occaecat",
                            "@schemaLocation": "http://QnYYwbHwfFUUYXTckJkmxvTS.gtkMchmprg3Hx1FNhrEIpTFm-hYua,Flz229FiH1DXtTIDBnMw0ro.rLjE7oRIbhI0dpeXD",
                            "@type": "dolor"
                        },
                        {
                            "characteristicSpecificationId": "elit qui ipsu",
                            "name": "aliqua labore eu",
                            "relationshipType": "adipisicing eu dolor amet",
                            "resourceSpecificationHref": "laboris aliqua ipsum Lorem",
                            "resourceSpecificationId": "nisi cupidatat dolor",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "@baseType": "in ",
                            "@schemaLocation": "https://vYWUEiQua.jvd7IINAAj7gNBKtmlI8d+uTpgyPHi8agvMilRWnHehxkaglXFDNfQyb",
                            "@type": "id laboris voluptate"
                        }
                    ],
                    "resourceSpecCharacteristicValue": [
                        {
                            "isDefault": false,
                            "rangeInterval": "nostrud in dolore sed cillum",
                            "regex": "laboris enim nostrud ullamco",
                            "unitOfMeasure": "mollit",
                            "valueFrom": -32299209,
                            "valueTo": 89978124,
                            "valueType": "nulla ullamco non ut dolor",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "laborum eu",
                            "@schemaLocation": "https://RpPxqGuKjmYEXfklu.elkjQ9QOlWbK,aL4QzXPkcqoSSrORmWpv0LiC,,JoVlSyGItd0xfgkKX7",
                            "@type": "laboris nulla id"
                        },
                        {
                            "isDefault": false,
                            "rangeInterval": "enim pariatur",
                            "regex": "sint in laborum",
                            "unitOfMeasure": "id minim Duis ad",
                            "valueFrom": 60923640,
                            "valueTo": -67971829,
                            "valueType": "ut Ut velit dolor elit",
                            "validFor": {
                                "endDateTime": "1985-04-12T23:20:50.52Z",
                                "startDateTime": "1985-04-12T23:20:50.52Z"
                            },
                            "value": {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            "@baseType": "qui",
                            "@schemaLocation": "http://eKTHLRbaRVCihcmuYmwFiTdyTSzcGR.dqupLaYNKIAMEp5AAuxeZ0BkxvKwwPtawHEjN4cWb,XKVXHBY",
                            "@type": "occaecat aliqua sint"
                        }
                    ],
                    "validFor": {
                        "endDateTime": "1985-04-12T23:20:50.52Z",
                        "startDateTime": "1985-04-12T23:20:50.52Z"
                    },
                    "@baseType": "repreh",
                    "@schemaLocation": "http://DSdmkLMbTUuvhGDSlh.pkluTQ7GRSivYON5EE9TxQIXmsBqGGPmpV+LrSokiKPtJcWyDo7",
                    "@type": "ipsum ve",
                    "@valueSchemaLocation": "minim consectetur Ut"
                }
            ],
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "magna proident",
            "@schemaLocation": "http://vu.oxryGR4Uv,W+VaEvyqbLObPXdAwxpa5SWrPFAnc+pX,PAjD",
            "@type": "ullamco eu anim est dolor"
        }
    ],
    "targetResourceSchema": {
        "@schemaLocation": "ut",
        "@type": "velit sunt aliqua",
        "@baseType": "in consequ"
    },
    "validFor": {
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z"
    },
    "@baseType": "nulla id",
    "@schemaLocation": "https://CcdgxWjbBDAdRtZOzdxLSOW.nnenr8TfxUQsf29+RpOy+Pxw",
    "@type": "ea magna"
})


// This operation deletes a ResourceSpecification entity.

@name("Deletes a ResourceSpecification")
DELETE "https://{{baseUrl}}/resourceSpecification/:id"



