#!/usr/bin/env dothttp

# imported from 35240-d76987fb-f2f9-425d-9645-ecebd487c07d.postman_collection.json

// Get information about a specific organization that you are a member of

@name("Get information about a specific organization that you are a member of")
GET "https://{{baseUrl}}/organizations/:identifier"



