#!/usr/bin/env dothttp

# imported from 35240-0100df38-567e-4c29-9c56-293119ed67af.postman_collection.json

// The platform allows you to retrieve supported metrics by sending a HTTP GET to /metrics. nThe string-values for the attribute id can be used as a metricId path parameter in the City Layer operations. nThe attribute granularity indicates how fine grained temporal pages should be split up when querying individual sources (and can be ignored here).

@name("Retrieving supported metrics")
GET "https://{{baseUrl}}/metrics"



