#!/usr/bin/env dothttp

# imported from 35240-51f1663f-4022-4c8f-b62e-1b4823b27806.postman_collection.json

@name("Get Snowball Usage")
POST "https://{{aws_snowball_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_snowball_service}}", region="{{aws_snowball_region}}")
data('null')



