#!/usr/bin/env dothttp

# imported from 35240-3abc9a78-733b-4c0c-8e67-86b81dc5a077.postman_collection.json

// Add collections to a collection.

@name("Add collections to a collection")
POST "https://{{baseUrl}}/collections/:collectionId/collections"
? "No Name"= "<string>"


// Remove a collection from a parent collection.

@name("Remove a collection from a collection")
DELETE "https://{{baseUrl}}/collections/:collectionId/collections/:childCollectionId"
? "No Name"= "<string>"



