#!/usr/bin/env dothttp

# imported from 35240-dd87bfa6-db1a-4bc7-933b-f90982450ad5.postman_collection.json

// Lists all of a location's modifier lists.

@name("Get Location Modifier Lists")
GET "https://{{baseUrl}}/v1/:location_id/modifier-lists"



