#!/usr/bin/env dothttp

# imported from 35240-6fb6fa21-14d5-40cc-96e1-22dcb99955f3.postman_collection.json

@name("Prisoner Mental Illness")
GET "https://{{url}}/prisons/mental-illness/"



@name("Prisoner Population by State")
GET "https://{{url}}/prisons/population-by-state/"


@name("Prisoners with HIV")
GET "https://{{url}}/prisons/hiv/"


@name("Supervised Population")
GET "https://{{url}}/prisons/supervised/"



