#!/usr/bin/env dothttp

# imported from 35240-32ced5f7-e4d1-46f1-acad-6349d837288f.postman_collection.json

// This operation list or find Permission entities

@name("List or find Permission objects")
GET "https://{{baseUrl}}/permission"
? "fields"= "est minim"
? "offset"= "-2291917"
? "limit"= "-2291917"


// This operation creates a Permission entity.

@name("Creates a Permission")
POST "https://{{baseUrl}}/permission"
"Content-Type": "application/json;charset=utf-8"
json({
    "user": {
        "@referredType": "culpa",
        "id": "",
        "href": "officia minim in aliquip",
        "name": "do id aliqua in sint",
        "role": "reprehenderit cupidatat cillum dolor",
        "@baseType": "reprehenderit",
        "@schemaLocation": "https://uuIcnsRFsvXrQOYSlVllIQXq.hlnRERNAWkFhgFIXmSco3oOzQ3zuP0t7GOL3",
        "@type": "sint mol"
    },
    "validFor": {
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z"
    },
    "description": "deserunt dolor quis occaecat elit",
    "assetUserRole": [
        {
            "manageableAsset": {
                "id": "irure magna velit",
                "href": "eu dolor",
                "name": "laboris et",
                "@baseType": "amet consectetur ad eiusmod sint",
                "@schemaLocation": "https://oKUFgPmFzHEjrNvlAc.voys6lbftZeHyTq317VbN",
                "@type": "ex ut amet",
                "@referredType": "in officia qui labore"
            },
            "userRole": {
                "id": "ullamco do ut quis",
                "href": "pariatur",
                "@baseType": "ea dolore cillum sunt dolor",
                "@schemaLocation": "http://RYjrzDtPOEYOHakGzdV.rifOcd1frYpy3UNd7jhZn-9eQzuziPXwwtPobBHMuhCOwuXNOdu.y6SVfOPNsWXYQWHZlT608",
                "@type": "dolor ipsum esse eiusmod voluptate",
                "@referredType": "reprehende"
            },
            "@baseType": "dolore sunt Lorem anim adipisic",
            "@schemaLocation": "https://zbwpniwB.pstts0Jo6VLoGlv4CiQYNWhhlXbPuo2x9x-nJJbMsH+71E",
            "@type": "veniam"
        },
        {
            "manageableAsset": {
                "id": "quis incididunt proiden",
                "href": "qui cupidatat dolore",
                "name": "ea nostrud dolor adipisic",
                "@baseType": "dolore occaecat nisi tempor",
                "@schemaLocation": "https://eGpfrLrbeenLTLYuTNqZ.ema8ZfD0,iMSLrfTjGkzzwKlldJrVaoBxOVKuqRBlvhTXPtbA",
                "@type": "nulla voluptate",
                "@referredType": "culpa nostrud eu"
            },
            "userRole": {
                "id": "aute consectetu",
                "href": "voluptate officia",
                "@baseType": "elit in",
                "@schemaLocation": "http://dyEddDNWsVycqBHkEyPQrd.mkbjhlP,IGYTAo.jqYUyOxiCOHNpc11dL+Koij0",
                "@type": "ea sunt in",
                "@referredType": "mollit non fugiat ex"
            },
            "@baseType": "esse veniam tempor quis exercitation",
            "@schemaLocation": "https://YMYjfknuXncsBxXvIcgjGml.xxwkUk+ywuPNNf-j6k3cCl",
            "@type": "ipsum in"
        }
    ],
    "granter": {
        "@referredType": "cillum sint",
        "id": "labore veniam",
        "href": "reprehenderit fugiat aliqua",
        "name": "deserunt voluptate ipsum",
        "role": "fugiat dolore",
        "@baseType": "nulla id reprehenderit",
        "@schemaLocation": "http://HNyqdZuPQKkyDrEuFAJIphgTZT.hzjH+RADxy6Wv8vwUvjsNsp51ri2ABkXBj",
        "@type": "incididun"
    },
    "privilege": [
        {
            "manageableAsset": {
                "id": "laboris dolore",
                "href": "et voluptate",
                "name": "aliquip aliqua proident",
                "@baseType": "consequat in",
                "@schemaLocation": "http://IbNzcCOK.wbttqja26styIOMLC.YuBzfzEVGKdkFjue1-n.Uji6yQh5UTDSi.a4XxzklZekm",
                "@type": "dolore ipsum qui laboris",
                "@referredType": "cillum aute"
            },
            "action": "eu sunt in adipisicing",
            "function": "ad eiusmod ut",
            "id": "ex aliqua occaecat cupidatat",
            "@baseType": "ut veniam cupidatat deserunt",
            "@schemaLocation": "https://RrXDUJO.vaIrU5XEuFUtSvVPiTnDfeYW7AntoX6KlBl5M6DCRJ",
            "@type": "dolor ad deserunt"
        },
        {
            "manageableAsset": {
                "id": "irure aliqua non",
                "href": "esse in",
                "name": "tempor dolore ",
                "@baseType": "amet in velit est dolore",
                "@schemaLocation": "https://ndCkkhoYAsQjmOhiPkrYS.dop+7Rb49IBC7yaSy5M+c46SfG4IyHr+ovcwRVFyyqt",
                "@type": "voluptate",
                "@referredType": "in"
            },
            "action": "pariatur",
            "function": "nulla Ut si",
            "id": "aute qui Duis",
            "@baseType": "sint culpa",
            "@schemaLocation": "http://udFfPJ.knbx8apiXyC0HtmyyJw.",
            "@type": "qui laborum proident ea"
        }
    ],
    "@baseType": "proident exercitation qui",
    "@schemaLocation": "http://pNulGbXxaAopsLs.zmMynvrriTFO,km0tFlKJRqvwpMw0LzfF6ovBmfiZTdT0d,Q",
    "@type": "ut dolor qui sint"
})



