#!/usr/bin/env dothttp

# imported from 35240-10c0a3a1-a4b5-4b4e-a83f-05d8a5e056fb.postman_collection.json

// BETA - By default the API will only return basic People information. Additional objects can be included by passing the object in the Includes parameter.

@name("Returns information on a person.")
GET "https://{{baseUrl}}/People/:Id"
? "Includes"= "<get>"


// Requires a valid Person ID.

@name("Get a Person's Filmography.")
GET "https://{{baseUrl}}/People/:Id/Filmography"



