#!/usr/bin/env dothttp

# imported from 35240-70cbed27-4ba9-4a22-82b9-822ae0e61858.postman_collection.json

// This operation list or find CustomerBill entities

@name("List or find CustomerBill objects")
GET "https://{{baseUrl}}/customerBill"
? "fields"= "veniam aliqua"
? "offset"= "-66130548"
? "limit"= "-66130548"



