#!/usr/bin/env dothttp

# imported from 35240-cc491087-45e6-46ba-aa93-9f2f2cc44068.postman_collection.json

// Get a specific project's deploy keys

@name("Get Projects  Deploy Keys")
GET "https://{{baseUrl}}/projects/:id/deploy_keys"



