#!/usr/bin/env dothttp

# imported from 35240-5c55623d-8457-49a6-aa88-825447c3d4ee.postman_collection.json

// Sets the accelerate configuration of an existing bucket. Amazon S3 Transfer Acceleration is a bucket-level feature that enables you to perform faster data transfers to Amazon S3. 

@name("Bucket Accelerate Configuration")
PUT "https://s3.amazonaws.com/{{bucket}}/"
awsauth(access_id="AKIAIVHZOWYJ3P3IBXNA", secret_key="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", service="s3", region="us-east-1")
"x-amz-content-sha256": "UNSIGNED-PAYLOAD"
? "accelerate"= ""
data('<?xml version="1.0" encoding="UTF-8"?>
<AccelerateConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
   <Status>Enabled</Status>
</AccelerateConfiguration>')


// Sets the accelerate configuration of an existing bucket. Amazon S3 Transfer Acceleration is a bucket-level feature that enables you to perform faster data transfers to Amazon S3. 

@name("Bucket Accelerate Configuration")
GET "https://s3.amazonaws.com/{{bucket}}/"
awsauth(access_id="AKIAIVHZOWYJ3P3IBXNA", secret_key="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", service="s3", region="us-east-1")
"x-amz-content-sha256": "UNSIGNED-PAYLOAD"
? "accelerate"= ""



// This implementation of the GET operation uses the accelerate subresource to return the Transfer Acceleration state of a bucket, which is either Enabled or Suspended. Amazon S3 Transfer Acceleration is a bucket-level feature that enables you to perform faster data transfers to and from Amazon S3. 

@name("Get Bucket Accelerate Configuration")
DELETE "https://s3.amazonaws.com/{{bucket}}/"
awsauth(access_id="AKIAIVHZOWYJ3P3IBXNA", secret_key="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", service="s3", region="{{region}}")
"x-amz-content-sha256": "UNSIGNED-PAYLOAD"
? "accelerate"= ""



