#!/usr/bin/env dothttp

# imported from 35240-cc491087-45e6-46ba-aa93-9f2f2cc44068.postman_collection.json

// Get projects  milestones milestone

@name("Get Projects  Milestones Milestone")
GET "https://{{baseUrl}}/projects/:id/milestones/:milestone_id"


// Get all issues for a single project milestone

@name("Get Projects  Milestones Milestone  Issues")
GET "https://{{baseUrl}}/projects/:id/milestones/:milestone_id/issues"
? "page"= "<>"
? "per_page"= "<>"



