#!/usr/bin/env dothttp

# imported from 35240-30e1be77-9844-4b74-bf90-bfab68be417c.postman_collection.json

@name("By Id Client Certificate")
GET "https://{{aws_api_gateway_base_url}}/clientcertificates/9ao60f&clientcertificate_id="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")
? "clientcertificate_id"= ""


@name("By Id Client Certificate Copy Copy")
GET "https://{{aws_api_gateway_base_url}}/clientcertificates"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")


@name("Delete Client Certificate")
DELETE "https://{{aws_api_gateway_base_url}}/clientcertificates/qrzg9z"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")


@name("Generate Client Certificate")
POST "https://{{aws_api_gateway_base_url}}/clientcertificates"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")


@name("Update Client Certificate")
PATCH "https://{{aws_api_gateway_base_url}}/clientcertificates/9ao60f"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_api_gateway_control_plane_service}}", region="{{aws_api_gateway_control_plane_region}}")



