#!/usr/bin/env dothttp

# imported from 35240-cdb56144-caaa-4d88-bf69-74da565813ea.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// **Deprecated!** Tenable.io Container Security API v1 is deprecated. Use the [GET /container-security/api/v2/repositories](ref:container-security-v2-list-repositories) endpoint instead.
// Returns a list of repositories.<p>Requires BASIC [16] user permissions. See [Permissions](doc:permissions).</p>

@name("List repositories") : "base-inherit-auth"
GET "https://{{baseUrl}}/container-security/api/v1/repositories"
? "offset"= "18528013"
? "limit"= "18528013"


// **Deprecated!** Tenable.io Container Security API v1 is deprecated. Use the [GET /container-security/api/v2/images](ref:container-security-v2-list-images) endpoint with the repository filter instead.
// Returns a list of images inside a specific repository.<p>Requires BASIC [16] user permissions. See [Permissions](doc:permissions).</p>

@name("List images in repository") : "base-inherit-auth"
GET "https://{{baseUrl}}/container-security/api/v1/repositories/:id/images"
? "offset"= "18528013"
? "limit"= "18528013"



