#!/usr/bin/env dothttp

# imported from 35240-edf4e52a-d167-4c2f-bb89-c42269bd9481.postman_collection.json

// Checks if the user with the id contact_id is a follower of the logged-in user

@name("Get Me Followers Contact")
GET "https://{{baseUrl}}/me/followers/{{contact_id}}.json"


// Checks if the user with the id contact_id is a follower of the logged-in user

@name("Get Me Followers Contact . Format")
GET "https://{{baseUrl}}/me/followers/{{contact_id}}.{{format}}"



