#!/usr/bin/env dothttp

# imported from 35240-c8161683-162b-464d-93d4-c3362e384b6c.postman_collection.json

// Returns an array of ratings for the given user.

@name("/user/ratings")
GET "https://{{baseUrl}}/user/ratings"



