#!/usr/bin/env dothttp

# imported from 35240-c5e56645-bf09-4e5c-8f01-15f069cbfb0f.postman_collection.json

// Parameters application releases.

@name("Parameters Application Releases")
GET "https://{{baseUrl}}/apps/:app/releases"


// Parameters application releases.

@name("Parameters Application Releases")
GET "https://{{baseUrl}}/apps/:app/releases/:release"



