#!/usr/bin/env dothttp

# imported from 35240-4ff70fc9-8539-43e5-b513-382f49f2c6a5.postman_collection.json

// This operation retrieves a TestEnvironmentAllocationExecution entity. Attribute selection is enabled for all first level attributes.

@name("Retrieves a TestEnvironmentAllocationExecution by ID")
GET "https://{{baseUrl}}/testEnvironmentAllocationExecution/:id"
? "fields"= "ex aute dolore dolore"


// This operation deletes a TestEnvironmentAllocationExecution entity.

@name("Deletes a TestEnvironmentAllocationExecution")
DELETE "https://{{baseUrl}}/testEnvironmentAllocationExecution/:id"



