#!/usr/bin/env dothttp

# imported from 35240-a96221e2-b43c-4973-9be0-3ec0566f4cd9.postman_collection.json

// Get a list of all articles from a certain blog.

@name("Get a list of all articles from a certain blog")
GET "https://{{baseUrl}}/admin/blogs/62581763/articles.json"
"Content": "<>"



