#!/usr/bin/env dothttp

# imported from 35240-c0b81c98-7930-4b6a-9b69-98d8407da2e9.postman_collection.json

// View your fund sources.

@name("View Your Fund Sources")
GET "https://{{baseUrl}}/api/funds"



