#!/usr/bin/env dothttp

# imported from 35240-cc491087-45e6-46ba-aa93-9f2f2cc44068.postman_collection.json

// Get a list of project issues

@name("Get Projects  Issues")
GET "https://{{baseUrl}}/projects/:id/issues"
? "state"= "<get>"
? "iid"= "<get>"
? "labels"= "<get>"
? "milestone"= "<object>"
? "order_by"= "<>"
? "sort"= "<>"
? "page"= "<>"
? "per_page"= "<>"


// Delete projects  issues subscribable  subscription

@name("Delete Projects  Issues Subscribable  Subscription")
DELETE "https://{{baseUrl}}/projects/:id/issues/:subscribable_id/subscription"



