#!/usr/bin/env dothttp

# imported from 35240-1567eedc-ffdd-444b-8874-76b0d18f2951.postman_collection.json

@name("Climate Risk Index")
GET "https://postman-open-technologies.github.io/environment/apis/climate-risk-index/"



