#!/usr/bin/env dothttp

# imported from 35240-c446a4c9-8dd6-45c4-99f2-688a96fe76ae.postman_collection.json

// Get the total number of clones and breakdown per day or week for the last 14 days. Timestamps are aligned to UTC midnight of the beginning of the day or week. Week begins on Monday.

@name("Get repository clones")
GET "https://{{baseUrl}}/repos/:owner/:repo/traffic/clones"
? "per"= "day"


// Get the total number of views and breakdown per day or week for the last 14 days. Timestamps are aligned to UTC midnight of the beginning of the day or week. Week begins on Monday.

@name("Get page views")
GET "https://{{baseUrl}}/repos/:owner/:repo/traffic/views"
? "per"= "day"



