#!/usr/bin/env dothttp

# imported from 35240-4cff9dbd-dc9e-457a-8421-41b9b4a7bdef.postman_collection.json

// Get a list of the user's preferences.n##### PermissionsnMust be logged in as the user being updated or have the `edit_other_users` permission.n

@name("Get the user's preferences")
GET "https://{{baseUrl}}/users/:user_id/preferences"


// Delete a list of the user's preferences.n##### PermissionsnMust be logged in as the user being updated or have the `edit_other_users` permission.n

@name("Delete user's preferences")
POST "https://{{baseUrl}}/users/:user_id/preferences/delete"



