#!/usr/bin/env dothttp

# imported from 35240-ee1bcca8-1dc2-4d21-9276-24298e87d40c.postman_collection.json

@name("hubDelete")
DELETE "https://{{baseUrl}}/hub/:hubId"


@name("hubGet")
GET "https://{{baseUrl}}/hub/:hubId"



