#!/usr/bin/env dothttp

# imported from 35240-175bce79-8928-437d-8db8-aad1709514f2.postman_collection.json

// This operation list or find ResourceCatalog entities

@name("List or find ResourceCatalog objects")
GET "https://{{baseUrl}}/resourceCatalog"
? "fields"= "tempor sint Ut"
? "offset"= "-48829778"
? "limit"= "-48829778"


// This operation creates a ResourceCatalog entity.

@name("Creates a ResourceCatalog")
POST "https://{{baseUrl}}/resourceCatalog"
"Content-Type": "application/json;charset=utf-8"
json({
    "name": "non in sunt Excepteur",
    "description": "consectetur",
    "lastUpdate": "1952-12-29T11:34:57.522Z",
    "lifecycleStatus": "sint quis",
    "version": "ut amet ad",
    "category": [
        {
            "id": "nulla anim",
            "href": "consectetur eu cupidatat Excep",
            "name": "culpa in eu cupidatat",
            "version": "Duis reprehenderit deserunt irure",
            "@baseType": "id nulla culpa",
            "@schemaLocation": "https://LaEtJYEKAdJqsnTjkYqCKGPLkOOrcVNoz.tfwcFvg-5oQqdMhQxFhpKG-ss2GEO5wE3Z7C-XkwjXvEVWDXi5E5",
            "@type": "in nostrud nulla",
            "@referredType": "consectetur in ut veniam nisi"
        },
        {
            "id": "laborum quis",
            "href": "nostrud reprehenderit esse fugiat nisi",
            "name": "in id labore",
            "version": "qui non",
            "@baseType": "tempor",
            "@schemaLocation": "https://OHoD.arkyuODFLvlBKkP.GCtSmayUM5PfG.enPfpDCPvBDOeDm6U8-H",
            "@type": "rep",
            "@referredType": "sed ullamco esse"
        }
    ],
    "relatedParty": [
        {
            "@referredType": "elit",
            "id": "dolore amet",
            "href": "Excepteur et sed occaecat qui",
            "name": "dolor",
            "role": "Duis sunt labore Excepteur",
            "@baseType": "proident",
            "@schemaLocation": "https://wFpzTZFNWLnUFDulfTs.pvaqh,23FIwyEkIsVrSJJ6JN4V",
            "@type": "irure qui nisi"
        },
        {
            "@referredType": "qui fugiat",
            "id": "pro",
            "href": "ut cillum",
            "name": "ea",
            "role": "labore dolor nostrud esse",
            "@baseType": "adipisicing ",
            "@schemaLocation": "https://XzhoXJhiLgjIvtTmOyKJzbzUyhamTDQa.thfcBbEjzAMsTR0wHNMTHtCIZ6zW-19elbHyIeblyspSqx1VtiCs5O,qU",
            "@type": "deserunt sit non q"
        }
    ],
    "validFor": {
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z"
    },
    "@baseType": "dolor cillum",
    "@schemaLocation": "http://wlrH.qphaS40,Gw6KM7E",
    "@type": "ut Lorem"
})



