#!/usr/bin/env dothttp

# imported from 35240-33af5de4-dc9a-486d-b92d-1eaf85678dac.postman_collection.json

// A worker is terminated involuntarily.

@name("Terminate Worker")
POST "https://{{baseUrl}}/events/hr/v1/worker.terminate"
? "No Name"= "<string>"


// Returns an event metadata

@name("Terminate Worker Meta")
GET "https://{{baseUrl}}/events/hr/v1/worker.terminate/meta"
? "No Name"= "<string>"



