#!/usr/bin/env dothttp

# imported from 35240-175bce79-8928-437d-8db8-aad1709514f2.postman_collection.json

// This operation list or find ResourceCategory entities

@name("List or find ResourceCategory objects")
GET "https://{{baseUrl}}/resourceCategory"
? "fields"= "tempor sint Ut"
? "offset"= "-48829778"
? "limit"= "-48829778"


// This operation creates a ResourceCategory entity.

@name("Creates a ResourceCategory")
POST "https://{{baseUrl}}/resourceCategory"
"Content-Type": "application/json;charset=utf-8"
json({
    "name": "exercitation",
    "description": "pariatur",
    "isRoot": true,
    "lastUpdate": "1949-09-18T07:59:25.866Z",
    "lifecycleStatus": "a",
    "parentId": "conseq",
    "version": "ad consequat sed quis",
    "category": [
        {
            "id": "dolor officia",
            "href": "consequat dolor voluptate",
            "name": "dolor aute ullamco",
            "version": "consectetur",
            "@baseType": "irure",
            "@schemaLocation": "https://AUumCqJriQxJVEKs.cwfyVJGMi5",
            "@type": "dolore",
            "@referredType": "minim dolor dolore id"
        },
        {
            "id": "consequat non",
            "href": "exercitati",
            "name": "labore aute",
            "version": "veniam quis Excepteur officia consectetur",
            "@baseType": "consectetur",
            "@schemaLocation": "http://MLmTddca.wbkkUnEhv2XTh205R",
            "@type": "qui voluptate",
            "@referredType": "culpa ipsum"
        }
    ],
    "relatedParty": [
        {
            "@referredType": "cupidatat velit elit ut",
            "id": "Ut enim nulla dolore ad",
            "href": "cupidatat officia",
            "name": "qui Ut esse do",
            "role": "mollit ullamco nulla",
            "@baseType": "laborum irure es",
            "@schemaLocation": "https://GgP.fii11Mp1LB9q2Xm0-i3v3SLuzb4T3U5cSpLeV.kDNY4R1HqfAcJH..SEtQ0",
            "@type": "in ad eu"
        },
        {
            "@referredType": "nulla in commodo",
            "id": "nostrud sint veniam laboris ad",
            "href": "esse elit",
            "name": "veniam ut",
            "role": "Lorem qui",
            "@baseType": "in",
            "@schemaLocation": "http://cQwBZifS.edxgkTE+h,22zkqo6TB",
            "@type": "aliquip"
        }
    ],
    "resourceCandidate": [
        {
            "id": "fugiat ut",
            "href": "aute irure",
            "name": "quis",
            "version": "enim pariatur",
            "@baseType": "nisi est",
            "@schemaLocation": "https://JxCZWgSqUXezFqV.nzvih1o1OZSOtM,ThEBdzDZuJn0oylALfkRdjDTN+UGVLNjZA0Kq8Ubx5zZTMYRApwA2A",
            "@type": "qui exercitation ipsum in dolor",
            "@referredType": "laboris aliquip"
        },
        {
            "id": "Excepteur aute veniam dolor",
            "href": "sint cillum aliquip",
            "name": "ut proident",
            "version": "non ad",
            "@baseType": "eiusmod",
            "@schemaLocation": "http://GecGCmIwJYiyhYGJxRZ.orilOKn+rMM+a6.Bmf0Zz05OU+DktRyIRM.NjuGrigp5G18IU3ZYlKUqsYK.",
            "@type": "in nulla id consectetur eiusmod",
            "@referredType": "non mollit sint ipsum minim"
        }
    ],
    "validFor": {
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z"
    },
    "@baseType": "sunt et elit laborum do",
    "@schemaLocation": "http://nAyOnGZWRvd.dkpwFFYdk02HcIvW",
    "@type": "est aliquip magna do et"
})



