#!/usr/bin/env dothttp

# imported from 35240-02fae580-11a1-41da-afdc-655537d58f8f.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


@name("Get user details") : "base-inherit-auth"
GET "https://{{baseUrl}}/v2/user"


@name("Get access token details") : "base-inherit-auth"
GET "https://{{baseUrl}}/v2/user/access_token"


@name("List user subscriptions") : "base-inherit-auth"
GET "https://{{baseUrl}}/v2/user/subscriptions"



