#!/usr/bin/env dothttp

# imported from 35240-e04c6fb1-e891-4983-80ec-38175b6c944e.postman_collection.json

// Get api wallets.

@name("Get API Wallets")
GET "https://{{baseUrl}}/api/Wallets"
"Authorization": "<>"


// Get api wallets.

@name("Get API Wallets")
GET "https://{{baseUrl}}/api/Wallets/:id"
"Authorization": "<>"


// Add api wallets depositaddress asset.

@name("Add API Wallets Depositaddress Asset")
POST "https://{{baseUrl}}/api/Wallets/depositaddress/:assetId"
"Authorization": "<>"



