#!/usr/bin/env dothttp

# imported from 35240-4ff70fc9-8539-43e5-b513-382f49f2c6a5.postman_collection.json

// This operation retrieves a NonFunctionalTestExecution entity. Attribute selection is enabled for all first level attributes.

@name("Retrieves a NonFunctionalTestExecution by ID")
GET "https://{{baseUrl}}/nonFunctionalTestExecution/:id"
? "fields"= "ex aute dolore dolore"


// This operation deletes a NonFunctionalTestExecution entity.

@name("Deletes a NonFunctionalTestExecution")
DELETE "https://{{baseUrl}}/nonFunctionalTestExecution/:id"



