#!/usr/bin/env dothttp

# imported from 35240-3ca33a76-32ee-4ece-82de-9c2b44a7a53d.postman_collection.json

// GET users/@me

@name("GET users/@me")
GET "https://{{baseUrl}}/userprofile/v1/users/@me"



