#!/usr/bin/env dothttp

# imported from 35240-22cbc221-e0b6-4b98-94ff-4d9fe2f458ca.postman_collection.json

// This operation list or find Resource entities

@name("List or find Resource objects")
GET "https://{{baseUrl}}/resource"
? "fields"= "esse id fugiat"
? "offset"= "20097554"
? "limit"= "20097554"


// This operation creates a Resource entity.

@name("Creates a Resource")
POST "https://{{baseUrl}}/resource"
"Content-Type": "application/json;charset=utf-8"
json({
    "category": "dolor id ex elit",
    "description": "esse",
    "endOperatingDate": "1954-06-13T15:21:48.974Z",
    "name": "culpa Lorem veniam dolore adipisicing",
    "resourceVersion": "minim",
    "startOperatingDate": "1968-09-12T03:47:55.341Z",
    "activationFeature": [
        {
            "featureCharacteristic": [
                {
                    "name": "est",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "magna anim",
                    "valueType": "qui sunt in",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "aute ci",
                    "@schemaLocation": "http://gZLcqkUunEaDCQIPBVqBpGdqcaDHjlOYz.mzVpGCDMVWBfTt,l1dSaha1wpY7AJXMYpUZxOH-9Dju",
                    "@type": "minim dolor occaecat officia"
                }
            ],
            "name": "elit",
            "id": "et labore commodo",
            "isBundle": false,
            "isEnabled": true,
            "constraint": [
                {
                    "id": "consectetur aute",
                    "href": "https://ijFcIxfldludjHpMtowWhj.nfnzgOSrI9L8vtcwPfdHxS7yWpk17w5zbC",
                    "name": "reprehenderit in nostrud occaecat",
                    "version": "cupidatat labore aute",
                    "@baseType": "ut elit min",
                    "@schemaLocation": "https://dVeMrTwyBmWoBSRfSvcIarXsszWauFt.doyQL+LfnXzvduX6GzHZeF61JrH2g0QkkxMjlTiLsIjOjjhE5vDsMu1P",
                    "@type": "sit elit et",
                    "@referredType": "conse"
                },
                {
                    "id": "dolor quis",
                    "href": "https://WcEilesaGzvZWyhza.hfcFZSuDKSrzUfMCL0,xHFaeUJdKgJDMahnuS",
                    "name": "do enim minim cupidatat",
                    "version": "exercitation laboris commodo sunt",
                    "@baseType": "quis eu pariatur sed",
                    "@schemaLocation": "http://yKIrgFkJf.peNXzIxdUYASyUnyhHz",
                    "@type": "do nostrud volup",
                    "@referredType": "tempor dolor"
                }
            ],
            "featureRelationship": [
                {
                    "name": "ut Duis esse",
                    "relationshipType": "qui eiusmod aliqua magna",
                    "id": "magna anim",
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                {
                    "name": "laboris consect",
                    "relationshipType": "Excepteur commodo",
                    "id": "adipisicing ",
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                }
            ]
        },
        {
            "featureCharacteristic": [
                {
                    "name": "sint",
                    "value": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "id": "adipisicing nostrud proident",
                    "valueType": "velit Lorem nostrud sed aute",
                    "characteristicRelationship": [
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        }
                    ],
                    "@baseType": "exercitation culpa ex",
                    "@schemaLocation": "https://FsEUV.yuhawBFJYaEC4l7mHEIgthbOjitX8ku1ZoNWvdrVFyzT",
                    "@type": "in occaecat"
                }
            ],
            "name": "veniam",
            "id": "Excepteur fugiat",
            "isBundle": true,
            "isEnabled": true,
            "constraint": [
                {
                    "id": "aute",
                    "href": "http://YmSyblMVTpWlljwYSmykAO.vtpmzQVH2o8Iu4acKa",
                    "name": "et aliqua laborum veniam",
                    "version": "aliquip dolor",
                    "@baseType": "velit sint quis",
                    "@schemaLocation": "https://ONypOGhencxRBlYVfQrlZJZdqGcMpRH.leQH44sbp",
                    "@type": "proident ei",
                    "@referredType": "officia consequat nisi eiusmod"
                },
                {
                    "id": "comm",
                    "href": "https://hpIMWWfsrElZAUQoTCDOLLJPeIOyhujD.pdOs+A+HjdYgj7Jg2c2Lhgqekc-k8uWWaUUCMOa,TQ9AeyKO4spe4FoD,RKv,NgCc4HEGKV+",
                    "name": "reprehenderit",
                    "version": "labore in consectetur",
                    "@baseType": "fugiat non adipisicing",
                    "@schemaLocation": "http://rCUmLQsYAoe.ngmgfP3VuYbGdDfU4+cMbq7HU",
                    "@type": "veniam esse proident ex",
                    "@referredType": "voluptate eiusmod"
                }
            ],
            "featureRelationship": [
                {
                    "name": "et qui reprehenderit",
                    "relationshipType": "nisi ex",
                    "id": "sit nulla nisi voluptate",
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                {
                    "name": "anim laborum id",
                    "relationshipType": "eu Excepteur",
                    "id": "sunt tempor enim qui quis",
                    "validFor": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                }
            ]
        }
    ],
    "administrativeState": "locked",
    "attachment": [
        {
            "id": "4aafacbd-11ff-4dc8-b445-305f2215715f",
            "href": "http://host/Attachment/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "attachmentType": "video",
            "content": "nisi in",
            "description": "Photograph of the Product",
            "mimeType": "cillum",
            "name": "ea",
            "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "size": {
                "amount": 1,
                "units": "laborum amet culpa dolore officia"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "commodo magna tempor sunt",
            "@schemaLocation": "https://dnRFvMGTWBZDKLSuMiyaxyOdytuPQmPnY.uvaih52v",
            "@type": "proident amet pariatur ea",
            "@referredType": "nostrud laborum culpa qui ex"
        },
        {
            "id": "4aafacbd-11ff-4dc8-b445-305f2215715f",
            "href": "http://host/Attachment/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "attachmentType": "video",
            "content": "magna sint volupt",
            "description": "Photograph of the Product",
            "mimeType": "aliquip laboris consectetur fugiat",
            "name": "officia nisi",
            "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
            "size": {
                "amount": 1,
                "units": "mollit do"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "@baseType": "in ut",
            "@schemaLocation": "http://FqzyKcpi.wqURneoQfR+qYvpxwWsuZzsRPQZCdgq",
            "@type": "est magna",
            "@referredType": "anim eiusmod ut"
        }
    ],
    "note": [
        {
            "id": "nulla aliquip sunt dolore",
            "href": "https://ikGxLRqtkRwKzw.wceSWq.YXb9ae2wDWijwnjVJebf5cds",
            "author": "irure",
            "date": "1982-04-17T23:53:33.330Z",
            "text": "amet minim sed",
            "@baseType": "cupidatat",
            "@schemaLocation": "http://ZzuFHlIhHvFIYQK.lggvaM1dohkgeXj95eXJwiEDIfbcOJePnE3,.Tsp-HjGN,Wkrbu",
            "@type": "pariatur consequat laboris"
        },
        {
            "id": "nisi",
            "href": "http://QRPFdBN.djbRzaQuVuhEO9pUdAxW",
            "author": "tempor nostrud esse",
            "date": "1981-09-18T18:13:40.287Z",
            "text": "quis occaecat nisi pariatur",
            "@baseType": "nostrud dolore adipisicing do",
            "@schemaLocation": "http://sVeQNVeCSOHiakMeIAlljyz.zzyWXGnh7gbC.AO,MhbhjwomlFIANV+",
            "@type": "aute mollit nisi"
        }
    ],
    "operationalState": "disable",
    "place": {
        "role": "ut",
        "id": "nulla esse minim dolore",
        "href": "dolore sit ad",
        "name": "ea",
        "@baseType": "ex",
        "@schemaLocation": "https://tUMSAULlnQWDezbuAFnKMyGkWONj.xlsvSCFiDw8KJmfDmP.z-Srw9P16AOA33ZoOqhDrQH0vaX5k4F33PJF",
        "@type": "officia ea incididunt esse cillum",
        "@referredType": "sint reprehenderit Lorem"
    },
    "relatedParty": [
        {
            "@referredType": "adipisicing fugiat",
            "id": "eu eiusmod",
            "href": "https://NNIFAnljNWkpTjP.wau70LkrJUvQ.irFcwayynmtC0+JQvigHpxIRNB5NZ+qVd6aM,WE+DrlAmiCE4awqVFmX0opK32BIgVM2h",
            "name": "aliqua culpa",
            "role": "voluptate",
            "@baseType": "sint laboru",
            "@schemaLocation": "https://HnzQrzrPtzxlDteSpDqmROOifOUzDgA.zpTvHM6GxO54-U6cqc,55lQpMeutKc8u3ARs",
            "@type": "su"
        },
        {
            "@referredType": "nulla culpa aute",
            "id": "occaecat",
            "href": "http://hjfrHTSxqiRvgyofdOwWKGK.gfJwVi-nNzhCwfAPCCdvgq,MH4g9Po37",
            "name": "dolore ullamco ",
            "role": "consequat eiusmod reprehenderit dolor",
            "@baseType": "non commodo",
            "@schemaLocation": "http://TaoUZDUErWjMIgScopEYJgJlbJRCF.fxjnAmC66PDuEYWq9B68DHUI4YHKzJ5BZn",
            "@type": "mollit anim id"
        }
    ],
    "resourceCharacteristic": [
        {
            "name": "Lorem veniam",
            "value": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "id": "anim non ipsum dolore sunt",
            "valueType": "ut occaecat dolore laboris proident",
            "characteristicRelationship": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ],
            "@baseType": "ut labore",
            "@schemaLocation": "http://AJozeVgnHPsaXUnWhBOffLkfyt.qfwtUvnJHxJzSyJHrBpYJX,pf0dFZufqAKixq9uKYTFN6",
            "@type": "cupidatat"
        },
        {
            "name": "dolo",
            "value": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "id": "labore",
            "valueType": "ut quis do pariat",
            "characteristicRelationship": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ],
            "@baseType": "Ut id culpa laboris",
            "@schemaLocation": "https://ewrFALFhKeXZuZqWRuOFkigpyApKG.teyOM8b3VG9UiDNRhTXMoSN4elRs+-ICiPCbQn7O4FSQ",
            "@type": "sit"
        }
    ],
    "resourceRelationship": [
        {
            "relationshipType": "bundled",
            "resource": {
                "href": "laborum in consectetur veniam",
                "id": "pariatur",
                "category": "anim aute deserunt quis enim",
                "description": "consequat et cupidatat",
                "endOperatingDate": "1956-11-10T09:49:05.787Z",
                "name": "consectetur Ut ut vol",
                "resourceVersion": "culpa incididunt",
                "startOperatingDate": "2011-09-11T09:44:07.734Z",
                "activationFeature": [
                    {
                        "featureCharacteristic": [
                            {
                                "name": "in aliquip",
                                "value": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "id": "laboris magna culpa labore deserunt",
                                "valueType": "amet ut",
                                "characteristicRelationship": [
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    },
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    }
                                ],
                                "@baseType": "ipsum irure eiusmod",
                                "@schemaLocation": "http://tKVsGcJ.jwvfWl8oL5r5bxxyd4vqCfSCbR6oX93OYhMuSbO16fNPOYvw8GzMBHgBI",
                                "@type": "qui Duis culpa nulla mollit"
                            }
                        ],
                        "name": "nostrud aliquip minim nisi",
                        "id": "quis est tempor consequat nisi",
                        "isBundle": true,
                        "isEnabled": false,
                        "constraint": [
                            {
                                "id": "ut aute irure nulla",
                                "href": "https://ddk.orRV+n,7mWryVKokDygpzlohx.T1LlFTmcXlj8eDcSSRsMxpwwvozzJCf9jXjozeeET09+AS",
                                "name": "elit Ut incididunt laborum",
                                "version": "laborum est dolor",
                                "@baseType": "Duis ullamco et",
                                "@schemaLocation": "http://ctRnnvebUSCryxrnqvFCc.asjsyA,2zrC.xGhIWNq-2sgAVsqjUjsMm7Jl55O9mvQvCbb16ROc+4fML-f",
                                "@type": "sint irure",
                                "@referredType": "proident commodo est"
                            },
                            {
                                "id": "commodo Lorem",
                                "href": "https://JnOVDnrXmiyZaTqwygzcOVfZ.nsvw5HFPwiT",
                                "name": "enim ullamco magna Duis",
                                "version": "occaecat dolor voluptate",
                                "@baseType": "occaecat aliqua",
                                "@schemaLocation": "https://OlrgFEpX.vrFE0nXNtmQpBpyAMTLjJARtN5XW4F948cC5",
                                "@type": "et mollit amet",
                                "@referredType": "id magna Duis Excepteur labore"
                            }
                        ],
                        "featureRelationship": [
                            {
                                "name": "anim irur",
                                "relationshipType": "cillum in",
                                "id": "in id consectetur labore fugiat",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            },
                            {
                                "name": "Excepteur nisi dolor voluptate",
                                "relationshipType": "velit pariatur commodo anim",
                                "id": "enim dolore sed irure cillum",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            }
                        ]
                    },
                    {
                        "featureCharacteristic": [
                            {
                                "name": "laborum labore sunt",
                                "value": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "id": "occaecat minim proident Lorem",
                                "valueType": "ut ex",
                                "characteristicRelationship": [
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    },
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    }
                                ],
                                "@baseType": "aliquip id enim magna",
                                "@schemaLocation": "https://bnAngTyfvKxvGebEDaFzqow.euHzCc+iimWY8S3GrD7yUIw5lqX28v+KZjNQWSn,IFEsM3miMA",
                                "@type": "proident cillum occaecat consectetur"
                            }
                        ],
                        "name": "nisi",
                        "id": "cillum magna laboris",
                        "isBundle": true,
                        "isEnabled": false,
                        "constraint": [
                            {
                                "id": "irure veniam Lorem",
                                "href": "https://wNZLtYjEMuojiHEmBgGRbcdb.hlw5dHppWLWIgu3U.vUMnL2raezgIfvEbXhsEfP-TcjQ.MxOwOAeazXDkwcOtd5Ch7",
                                "name": "laboris Excepteur ut",
                                "version": "in laboris",
                                "@baseType": "laborum dolore irure exercitation aliquip",
                                "@schemaLocation": "http://QLHrqBVzkkcKhLVyU.svYVZzxBiLN.Ii.c",
                                "@type": "exercitation commodo fugiat ut in",
                                "@referredType": "enim"
                            },
                            {
                                "id": "Ut consequat amet esse",
                                "href": "https://ITKoAUNOVAZoVDppUpkDgvltVoaYPiYel.afetKiYFW.UgMOaHjhc--DSHIEfME",
                                "name": "culpa aliquip ut",
                                "version": "sed culpa",
                                "@baseType": "sunt dolore irure in",
                                "@schemaLocation": "http://tFM.sqvkSRUycEVhnBjzt",
                                "@type": "dolor",
                                "@referredType": "anim laborum deserunt amet"
                            }
                        ],
                        "featureRelationship": [
                            {
                                "name": "sed in consequat consectetur",
                                "relationshipType": "velit",
                                "id": "non occaecat dolore aliqua",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            },
                            {
                                "name": "minim exercitation",
                                "relationshipType": "enim cupidatat anim Lorem",
                                "id": "ut ut",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            }
                        ]
                    }
                ],
                "administrativeState": "locked",
                "attachment": [
                    {
                        "id": "4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "href": "http://host/Attachment/4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "attachmentType": "video",
                        "content": "ad",
                        "description": "Photograph of the Product",
                        "mimeType": "proident ex anim qui",
                        "name": "dolore sunt anim",
                        "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "size": {
                            "amount": 1,
                            "units": "aliquip "
                        },
                        "validFor": {
                            "endDateTime": "1985-04-12T23:20:50.52Z",
                            "startDateTime": "1985-04-12T23:20:50.52Z"
                        },
                        "@baseType": "aute Duis aliqua",
                        "@schemaLocation": "https://SgFcb.zgdUr1uo6XhKnyFtdJgB5UF7l5o-NgHJiMFzj.8pEg-psND3+9K",
                        "@type": "velit ad officia nisi elit",
                        "@referredType": "dolore"
                    },
                    {
                        "id": "4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "href": "http://host/Attachment/4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "attachmentType": "video",
                        "content": "elit ut est in",
                        "description": "Photograph of the Product",
                        "mimeType": "ex elit Duis enim dolore",
                        "name": "aliqua nisi in",
                        "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "size": {
                            "amount": 1,
                            "units": "eu et aute nostrud labore"
                        },
                        "validFor": {
                            "endDateTime": "1985-04-12T23:20:50.52Z",
                            "startDateTime": "1985-04-12T23:20:50.52Z"
                        },
                        "@baseType": "aliquip esse voluptate Duis",
                        "@schemaLocation": "https://uaOFPikdGxCwKhuoVXpZGSjKsjsMHAiNJ.mbrkM7.oXC1yL5XxMCSX",
                        "@type": "est nulla aute eiusmod",
                        "@referredType": "non ipsum elit ex"
                    }
                ],
                "note": [
                    {
                        "id": "Excepteur laborum",
                        "href": "http://KaDASqRGwHcSTqdupbgtO.seklbxcj+xa+N,OpnlbFPx4pbq-+KzDEX06EIFzsXVggE7dfj3Q.Em8ognG0.QM8qX",
                        "author": "",
                        "date": "1955-03-28T15:27:24.703Z",
                        "text": "in aute velit Duis",
                        "@baseType": "nulla aute",
                        "@schemaLocation": "https://glRHmumsvnwVuvfvKkIJaoI.psMFhsCUJ",
                        "@type": "sed occaecat non"
                    },
                    {
                        "id": "non occaecat enim in ullamco",
                        "href": "https://oKLpgSVLvfNEprScfWKJnFXkv.ikDvWZBqv1edSmzK9.GK9tGYpfrrXZsuQnMlxBbNnhc",
                        "author": "mollit aliquip ut Excepteur",
                        "date": "1966-01-21T03:51:30.887Z",
                        "text": "proident ullamco irure",
                        "@baseType": "eiusmod enim",
                        "@schemaLocation": "https://iRgyYFnloxSLK.qaqWid6,qS",
                        "@type": "qui Lorem"
                    }
                ],
                "operationalState": "disable",
                "place": {
                    "role": "commodo cillum deserunt aliqua",
                    "id": "aliqua dolore ea",
                    "href": "tempor in eiusmod amet",
                    "name": "aliquip consectetur labore ex",
                    "@baseType": "nulla",
                    "@schemaLocation": "https://VHbrjOi.vaiLzwuLX-ext+p3cfiorG",
                    "@type": "irure eiusmod in",
                    "@referredType": "consectetur aliquip reprehenderit"
                },
                "relatedParty": [
                    {
                        "@referredType": "aliqua",
                        "id": "labore consectetur occaecat cupidatat ut",
                        "href": "http://ICmxqUrDRI.cwRNMgF7pz2cj3y-jikkhsDpWRlcwKRcyy-JVnTKjK,5.nhLpZYoDXYRkNVw7EOdk+1N",
                        "name": "deserunt laborum adipisicing",
                        "role": "ut i",
                        "@baseType": "proident",
                        "@schemaLocation": "http://WgUnBcZUiymRAYHzAcg.foejGsivK8jBAmJvtmNbv3z,xBCgdaMF1S4larX0B4sp1CmLqEmuzCsWG-GyaqHbmu",
                        "@type": "enim sed"
                    },
                    {
                        "@referredType": "aliqua sunt officia labore",
                        "id": "irure",
                        "href": "https://XXRZoKGr.yxfc1y7hS-OVDz68Ter7",
                        "name": "cillum irure qui ea sunt",
                        "role": "Ut deserunt Lorem Duis",
                        "@baseType": "ipsum magna adipisicing",
                        "@schemaLocation": "https://zKmUrUQuDFcFuoh.jdzyfNf+uDsbvtXXOwoefwNc6YwT",
                        "@type": "in consequat ea"
                    }
                ],
                "resourceCharacteristic": [
                    {
                        "name": "ea",
                        "value": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "id": "occaecat adipisicing aliqua qui",
                        "valueType": "exercitation commodo ",
                        "characteristicRelationship": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "@baseType": "proident",
                        "@schemaLocation": "http://zKaamwLdoQdoxwrYVYk.fgdAWt,hCNGuxCoN93",
                        "@type": "reprehenderit laborum"
                    },
                    {
                        "name": "voluptate Lorem reprehenderit",
                        "value": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "id": "cillum proident ut",
                        "valueType": "in dolore fugiat dolore Ut",
                        "characteristicRelationship": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "@baseType": "eu officia sed",
                        "@schemaLocation": "https://ymXjRQAIpqVvhEJz.wbjXhemoCw+LNQl--He,.oCYWL",
                        "@type": "adipisicing"
                    }
                ],
                "resourceRelationship": [
                    {
                        "value": "<Circular reference to #/components/schemas/ResourceRelationship detected>"
                    },
                    {
                        "value": "<Circular reference to #/components/schemas/ResourceRelationship detected>"
                    }
                ],
                "resourceSpecification": {
                    "id": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "href": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "name": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "version": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@schemaLocation": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@type": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@referredType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "resourceStatus": "reserved",
                "usageState": "active",
                "@baseType": "irure dolore sint et",
                "@schemaLocation": "https://QgIrRUfYLbzXlTuAU.jgwDdJC+KsCSCNCt1JnPCMQaNwGrQVntZQVUJAjh9ay353lszvrGKDddZ",
                "@type": "ullamco Duis aliquip ",
                "@referredType": "culpa ad"
            },
            "id": "exercitation mollit commodo magna",
            "href": "https://iizqSuIKlMvERRXcnKpPetrITmaqQx.nxthPdCvgC-f6hs55QU-GRP-stn7cL-VoH",
            "@baseType": "elit amet",
            "@schemaLocation": "http://rSxkDwgPtmHNIAvBYeBuIDfShnjFtc.diegU1iv9yzKnKTPfdVhyIEM3,5,b1GzuOV+KNU9qcEDDLG9IV7nQiTB+PiYVNkmXD1l.Q+dls1",
            "@type": "tempor in"
        },
        {
            "relationshipType": "bundled",
            "resource": {
                "href": "in Lorem anim irure sint",
                "id": "dolore",
                "category": "pariatur nisi nulla exercitation",
                "description": "eiusmod occaecat aliqua",
                "endOperatingDate": "1966-04-20T21:41:52.738Z",
                "name": "laborum fugiat ullamco",
                "resourceVersion": "ea aliqua exercitation",
                "startOperatingDate": "1982-07-31T11:47:03.470Z",
                "activationFeature": [
                    {
                        "featureCharacteristic": [
                            {
                                "name": "ipsum veniam incididunt sint",
                                "value": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "id": "nulla pariatur consectetur",
                                "valueType": "est oc",
                                "characteristicRelationship": [
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    },
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    }
                                ],
                                "@baseType": "aute",
                                "@schemaLocation": "https://alTGSCkxLkPGNqTL.hzzHFVlfrERzT25Y4U1Ag0J+Y5G5pZbIBjXCBX-8H",
                                "@type": "tempor eu"
                            }
                        ],
                        "name": "proident nisi ex",
                        "id": "consectetur",
                        "isBundle": false,
                        "isEnabled": true,
                        "constraint": [
                            {
                                "id": "do magna elit",
                                "href": "http://qTcdVWIpkRCpsvrelPVgQNuKliVQBTDv.eztHUc7QFgmPe+KgXwFAbIR9iHO",
                                "name": "irure minim",
                                "version": "cupidatat aliquip",
                                "@baseType": "esse Ut nostrud",
                                "@schemaLocation": "https://AgThxDMXuVboAwnAMEbWEYGvGnqQXg.koroOvKnEz8HRi.VIoImXGnyJWhqpxJPBNsBWtyYiI6jII",
                                "@type": "magna officia dolor",
                                "@referredType": "enim et au"
                            },
                            {
                                "id": "dolor in anim ex",
                                "href": "http://X.atilZxVRC,B6iEGFYcZ+MK2Z0T,ylVwWaMHRerCC44hbPNjJRwqaNW+",
                                "name": "aliquip Ut est incididunt",
                                "version": "Duis sit",
                                "@baseType": "enim",
                                "@schemaLocation": "http://yboKgaYcpCXjGrFDwPIU.vuO-TsDcuglzd-P2Zjn-JPTwUIJJ1qq1X+qeFmtmwigG9pD,TIOmhZG11m+HMOMYlm2",
                                "@type": "in anim pariatur commodo incididunt",
                                "@referredType": "sit ex dolore proident occaeca"
                            }
                        ],
                        "featureRelationship": [
                            {
                                "name": "aliquip velit Ut",
                                "relationshipType": "amet voluptate",
                                "id": "in aute in Excepteur eu",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            },
                            {
                                "name": "sint ea mollit",
                                "relationshipType": "cillum Duis adipisicing commodo",
                                "id": "Lorem est",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            }
                        ]
                    },
                    {
                        "featureCharacteristic": [
                            {
                                "name": "elit sit",
                                "value": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                },
                                "id": "aute id ea quis exercitation",
                                "valueType": "ut ad dolore Duis magna",
                                "characteristicRelationship": [
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    },
                                    {
                                        "value": "<Error: Too many levels of nesting to fake this schema>"
                                    }
                                ],
                                "@baseType": "aliquip elit commodo Excepteur consequat",
                                "@schemaLocation": "http://dVFoLq.gbvP-mouVQtp7njeYwK0IEgLNFsvvvYiKPMyETFOwp",
                                "@type": "enim non laborum velit"
                            }
                        ],
                        "name": "dolor",
                        "id": "Lorem qui magna culpa",
                        "isBundle": true,
                        "isEnabled": true,
                        "constraint": [
                            {
                                "id": "nisi eu",
                                "href": "http://DnIAFlprfXOcpqPiDNzU.thbkN6LvInuUHEJng52",
                                "name": "dolore in velit",
                                "version": "se",
                                "@baseType": "magna nulla in enim",
                                "@schemaLocation": "https://gDaB.agal7RfruUQNMuFgWAJH7HAqt",
                                "@type": "est ea nisi",
                                "@referredType": "proident amet"
                            },
                            {
                                "id": "ad ut",
                                "href": "http://MFWNPktecPYeIhVmMxXGngaYJgb.hsuqwJPzi.qdILB,XGtzDTW.WgP.r.6TO6pxSUwQ",
                                "name": "aliqua",
                                "version": "dolore quis",
                                "@baseType": "in occaecat cillum quis",
                                "@schemaLocation": "https://cFXOUlP.ngpbPFtEbYmtcIibpm0nsmcTlJ1FCP",
                                "@type": "magna ullamco ut Lorem",
                                "@referredType": "occaecat irure"
                            }
                        ],
                        "featureRelationship": [
                            {
                                "name": "ullamco nostrud velit irure id",
                                "relationshipType": "anim velit officia sint",
                                "id": "anim adipisicing Duis",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            },
                            {
                                "name": "Ut nulla in et anim",
                                "relationshipType": "ut occaecat cillum irure",
                                "id": "Ut fugiat",
                                "validFor": {
                                    "value": "<Error: Too many levels of nesting to fake this schema>"
                                }
                            }
                        ]
                    }
                ],
                "administrativeState": "locked",
                "attachment": [
                    {
                        "id": "4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "href": "http://host/Attachment/4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "attachmentType": "video",
                        "content": "ipsum sunt et quis est",
                        "description": "Photograph of the Product",
                        "mimeType": "do aute",
                        "name": "sit labore",
                        "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "size": {
                            "amount": 1,
                            "units": "fugiat in officia"
                        },
                        "validFor": {
                            "endDateTime": "1985-04-12T23:20:50.52Z",
                            "startDateTime": "1985-04-12T23:20:50.52Z"
                        },
                        "@baseType": "ad ullamco nulla",
                        "@schemaLocation": "https://kvCkqFroc.lqZp+z5J,,Uojw44domiZvAAQMYtK",
                        "@type": "ut adipisicing",
                        "@referredType": "nostrud magna culpa veniam"
                    },
                    {
                        "id": "4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "href": "http://host/Attachment/4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "attachmentType": "video",
                        "content": "minim eiusmod sunt et",
                        "description": "Photograph of the Product",
                        "mimeType": "mollit ipsum",
                        "name": "velit dolor nisi",
                        "url": "http://host/Content/4aafacbd-11ff-4dc8-b445-305f2215715f",
                        "size": {
                            "amount": 1,
                            "units": "s"
                        },
                        "validFor": {
                            "endDateTime": "1985-04-12T23:20:50.52Z",
                            "startDateTime": "1985-04-12T23:20:50.52Z"
                        },
                        "@baseType": "Ut deserunt minim voluptate",
                        "@schemaLocation": "http://Bm.vfnVTHmgrREjdti.i+1bJX4tECz",
                        "@type": "Ut ut consectetur deserunt",
                        "@referredType": "Ut cupidatat est amet"
                    }
                ],
                "note": [
                    {
                        "id": "aute dolore",
                        "href": "https://hxgjUbRZdsYhosUVL.cudjY1VYmK9FZcttKqtEEFBLFl.rNm+TcL60zDjkjAp",
                        "author": "do ex non commodo",
                        "date": "2012-05-07T10:58:54.589Z",
                        "text": "sunt dolore officia enim",
                        "@baseType": "amet Ut",
                        "@schemaLocation": "https://mrvCWxcVmanMRpih.vzieNhNbCnY9gxFmEsojIBFKs65EuhYkgZDT1Mpuo+Y+UhjLcs",
                        "@type": "cupidatat voluptate ut deserunt ad"
                    },
                    {
                        "id": "sint do",
                        "href": "http://l.qhixpLfpL.HFdnbGerUsssTAXO7htXY6Fu2sQ",
                        "author": "tempor",
                        "date": "2008-09-24T08:03:34.782Z",
                        "text": "exercitation minim Duis",
                        "@baseType": "adipisicing sit non sunt Excepteur",
                        "@schemaLocation": "http://Izi.anpqQKTGIVm9KnhDUm1",
                        "@type": "sed"
                    }
                ],
                "operationalState": "disable",
                "place": {
                    "role": "anim eu do",
                    "id": "eu ad ipsum officia",
                    "href": "eiusmod co",
                    "name": "culpa in",
                    "@baseType": "dolor",
                    "@schemaLocation": "https://KkyCFsFVSRGYuYShUlclOPrhHVTLrP.bmfCJJ60-cUYRI5r8gCIgeApNAn",
                    "@type": "esse consequat cupidatat voluptate",
                    "@referredType": "magna veniam ea ad lab"
                },
                "relatedParty": [
                    {
                        "@referredType": "occa",
                        "id": "anim ut",
                        "href": "https://vhmNX.ggNmzgb,Gm0d6Pa,02fk,Q",
                        "name": "dolor deserunt aliquip voluptate laboris",
                        "role": "amet enim do",
                        "@baseType": "in dolore dolor Ut",
                        "@schemaLocation": "https://BXjitbSABlPWCA.tfXpQcfr4g3AQE+8eijjNEJJ5X4k-NAWP3mU0yAGMFDsqyEXBJug8PKR.Am1BdiH",
                        "@type": "ipsum sunt"
                    },
                    {
                        "@referredType": "Lorem ad",
                        "id": "laboris adipisicing commodo",
                        "href": "http://mulivgKgfhvZOePCbYskyfNExAc.xog9Uz5BI3QpEy23vFVkn.IARppe0gVVyBJC5CLQvpYqo1YHWc3qA-I7",
                        "name": "incididunt ipsum",
                        "role": "adipisicing Ut consectetur enim",
                        "@baseType": "sit ullamco tempor",
                        "@schemaLocation": "http://ZFtZLXpmHpceS.hsukXqq8i-1y56oKank45h",
                        "@type": "fugiat eiusmod in consectetur"
                    }
                ],
                "resourceCharacteristic": [
                    {
                        "name": "culpa tempor occaecat veniam",
                        "value": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "id": "laboris magna",
                        "valueType": "commodo ea",
                        "characteristicRelationship": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "@baseType": "eius",
                        "@schemaLocation": "https://vxskmKKh.nzbQttNogSMYMeNy.rASPsthAU2q2srBshd4FywrFkX+B8EccLKRhMoFu4ORaTXETOVB-fnqXT",
                        "@type": "commodo officia enim"
                    },
                    {
                        "name": "ad consectetur",
                        "value": {
                            "value": "<Error: Too many levels of nesting to fake this schema>"
                        },
                        "id": "adipisic",
                        "valueType": "officia magna",
                        "characteristicRelationship": [
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            },
                            {
                                "value": "<Error: Too many levels of nesting to fake this schema>"
                            }
                        ],
                        "@baseType": "qui voluptate ipsum",
                        "@schemaLocation": "https://lbfYNPbmRSMgwZjcDufsPSwtqZB.kdpCTqCUoSXCzRRVdzRQQH9xpm5eFzwKOjPu5DOElOFA,JlzV0XqJyf4pZtw0h",
                        "@type": "velit do dolore enim"
                    }
                ],
                "resourceRelationship": [
                    {
                        "value": "<Circular reference to #/components/schemas/ResourceRelationship detected>"
                    },
                    {
                        "value": "<Circular reference to #/components/schemas/ResourceRelationship detected>"
                    }
                ],
                "resourceSpecification": {
                    "id": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "href": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "name": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "version": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@schemaLocation": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@type": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@referredType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "resourceStatus": "suspended",
                "usageState": "busy",
                "@baseType": "in sed",
                "@schemaLocation": "http://YrEuwkljgTZ.khgUGTRtbbP1Pumj-MQPFrliVkVWjEgjBBptNDZ23H8y3olC77j",
                "@type": "cillum dolore culpa",
                "@referredType": "esse Excepteur id"
            },
            "id": "ea sunt velit minim",
            "href": "https://NdfMOpQN.kgIUYseHBgxLES",
            "@baseType": "ex tempor in labore",
            "@schemaLocation": "https://VKbWUvexgonOGZKvMKrn.bsckq",
            "@type": "veniam ea"
        }
    ],
    "resourceSpecification": {
        "id": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "href": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "name": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "version": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "@baseType": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "@schemaLocation": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "@type": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        },
        "@referredType": {
            "value": "<Error: Too many levels of nesting to fake this schema>"
        }
    },
    "resourceStatus": "reserved",
    "usageState": "busy",
    "@baseType": "officia pariatur minim",
    "@schemaLocation": "http://gsINeLwYVrwllrIjjVr.qgCxN.B.ho,nnEkRMtg-M",
    "@type": "velit eiusmod"
})



