#!/usr/bin/env dothttp

# imported from 35240-5742bcb1-7df5-4c70-8656-2527a102ef1c.postman_collection.json

// Reloads the target database table with the source data.

@name("Reload Tables")
POST "https://{{aws_database_migration_service_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_database_migration_service_service}}", region="{{aws_database_migration_service_region}}")
"Content-Type": "application/x-amz-json-1.1"
"X-Amz-Target": "AmazonDMSv20160101.ReloadTables"
? "Action"= "ReloadTables"
data('{
   "ReloadOption": "string",
   "ReplicationTaskArn": "string",
   "TablesToReload": [ 
      { 
         "SchemaName": "string",
         "TableName": "string"
      }
   ]
}')


// Returns table statistics on the database migration task, including table name, rows inserted, rows updated, and rows deleted.

@name("Describe Table Statistics")
POST "https://{{aws_database_migration_service_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_database_migration_service_service}}", region="{{aws_database_migration_service_region}}")
"Content-Type": "application/x-amz-json-1.1"
"X-Amz-Target": "AmazonDMSv20160101.DescribeTableStatistics"
? "Action"= "DescribeTableStatistics"
data('{
   "Filters": [ 
      { 
         "Name": "string",
         "Values": [ "string" ]
      }
   ],
   "Marker": "string",
   "MaxRecords": number,
   "ReplicationTaskArn": "string"
}')



