#!/usr/bin/env dothttp

# imported from 35240-c49a34ba-ca49-4e12-bd50-71617960cf26.postman_collection.json

// This operation list or find ExportJob entities

@name("List or find ExportJob objects")
GET "https://{{baseUrl}}/exportJob"
? "fields"= "id Ut Excepteur"
? "offset"= "256391"
? "limit"= "256391"


// This operation creates a ExportJob entity.

@name("Creates a ExportJob")
POST "https://{{baseUrl}}/exportJob"
"Content-Type": "application/json;charset=utf-8"
json({
    "url": "https://yjTFnNMILsqQqgPGcEQqngK.ienjEMMQ+YkExsKNL9oa8o7GK",
    "completionDate": "1968-11-06T02:13:36.619Z",
    "contentType": "elit sed velit",
    "creationDate": "1947-11-03T10:06:38.482Z",
    "errorLog": "mollit",
    "path": "fugiat minim laboris elit",
    "query": "amet incididunt",
    "status": "Not Started",
    "@baseType": "aliqua minim Lorem",
    "@schemaLocation": "http://ySUdxSUn.jhwHHYO7D5zrYGu0GaXgwe9F0zT78Ejlp7Ir",
    "@type": "aute deserunt"
})



