#!/usr/bin/env dothttp

# imported from 35240-4cff9dbd-dc9e-457a-8421-41b9b4a7bdef.postman_collection.json

// Get a team based on provided name stringn##### PermissionsnMust be authenticated, team type is open and have the `view_team` permission.n

@name("Get a team by name")
GET "https://{{baseUrl}}/teams/name/:name"


// Check if the team exists based on a team name.n

@name("Check if team exists")
GET "https://{{baseUrl}}/teams/name/:name/exists"



