#!/usr/bin/env dothttp

# imported from 35240-ac6561cd-0334-4ee5-8280-57b4086d4c3d.postman_collection.json

// Get the top 10 popular contents over the last 14 days.

@name("Get top referral paths")
GET "https://{{baseUrl}}/repos/:owner/:repo/traffic/popular/paths"


// Get the top 10 referrers over the last 14 days.

@name("Get top referral sources")
GET "https://{{baseUrl}}/repos/:owner/:repo/traffic/popular/referrers"



