#!/usr/bin/env dothttp

# imported from 35240-d7e889e2-45ea-4b46-badd-0b496c4a983f.postman_collection.json

// Get a list of AVM snapshot records that fall within an Onboard GeoID with a specific value range. Use propertytpe to select a specific property type for your search.

@name("Returns AVM details within a geography.")
GET "https://{{baseUrl}}/avm/snapshot"
"apikey": "<>"
"accept": "<>"
? "geoid"= "<>"
? "minavmvalue"= "<>"
? "maxavmvalue"= "<>"
? "propertytype"= "<>"


// Get AVM details for a specific address.

@name("Returns AVM details for a property.")
GET "https://{{baseUrl}}/avm/detail"
"apikey": "<>"
"accept": "<>"
? "address1"= "<>"
? "address2"= "<>"



