#!/usr/bin/env dothttp

# imported from 35240-c8161683-162b-464d-93d4-c3362e384b6c.postman_collection.json

// Returns basic information about the currently authenticated user.

@name("/user")
GET "https://{{baseUrl}}/user"



