#!/usr/bin/env dothttp

# imported from 35240-a77dedb4-46a5-45af-82f5-6b2d6366b543.postman_collection.json

// A multiget version of the get GIF by ID endpoint.n

@name("Get GIFs by ID")
GET "https://{{baseUrl}}/gifs"
? "No Name"= "<string>"
? "api_key"= "<string>"
? "ids"= "<string>"


// Returns a random GIF, limited by tag. Excluding the tag parameter will return a random GIF from the GIPHY catalog.n

@name("Random GIF")
GET "https://{{baseUrl}}/gifs/random"
? "No Name"= "<string>"
? "api_key"= "<string>"
? "tag"= "<string>"


// Search all GIPHY GIFs for a word or phrase. Punctuation will be stripped and ignored.  Use a plus or url encode for phrases. Example paul+rudd, ryan+gosling or american+psycho.n

@name("Search GIFs")
GET "https://{{baseUrl}}/gifs/search"
? "No Name"= "<string>"
? "api_key"= "<string>"
? "q"= "<string>"
? "limit"= "<integer>"
? "offset"= "<get>"


// The translate API draws on search, but uses the GIPHY `special sauce` to handle translating from one vocabulary to another. In this case, words and phrases to GIFn

@name("Translate phrase to GIF")
GET "https://{{baseUrl}}/gifs/translate"
? "No Name"= "<string>"
? "api_key"= "<string>"
? "s"= "<string>"


// Fetch GIFs currently trending online. Hand curated by the GIPHY editorial team.  The data returned mirrors the GIFs showcased on the GIPHY homepage. Returns 25 results by default.n

@name("Trending GIFs")
GET "https://{{baseUrl}}/gifs/trending"
? "No Name"= "<string>"
? "api_key"= "<string>"
? "limit"= "<integer>"
? "offset"= "<get>"


// Returns a GIF given that GIF's unique IDn

@name("Get GIF by Id")
GET "https://{{baseUrl}}/gifs/:gifId"
? "No Name"= "<string>"



