#!/usr/bin/env dothttp

# imported from 35240-5742bcb1-7df5-4c70-8656-2527a102ef1c.postman_collection.json

// Returns information about the schema for the specified endpoint.

@name("Describe Schemas")
POST "https://{{aws_database_migration_service_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
"Content-Type": "application/x-amz-json-1.1"
"X-Amz-Target": "AmazonDMSv20160101.DescribeSchemas"
? "Action"= "DescribeSchemas"
data('{
   "EndpointArn": "string",
   "Marker": "string",
   "MaxRecords": number
}')


// Populates the schema for the specified endpoint. This is an asynchronous operation and can take several minutes. You can check the status of this operation by calling the DescribeRefreshSchemasStatus operation.

@name("Refresh Schemas")
POST "https://{{aws_database_migration_service_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_database_migration_service_service}}", region="{{aws_database_migration_service_region}}")
"Content-Type": "application/x-amz-json-1.1"
"X-Amz-Target": "AmazonDMSv20160101.RefreshSchemas"
? "Action"= "RefreshSchemas"
data('{
   "EndpointArn": "string",
   "ReplicationInstanceArn": "string"
}')



