#!/usr/bin/env dothttp

# imported from 35240-88ac1dc0-36c3-4a4a-99dc-96fc8b7c0608.postman_collection.json

@name("Batch Disassociate Service Action From Provisioning Artifact")
POST "https://{{aws_service_catalog_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_service_catalog_service}}", region="{{aws_service_catalog_region}}")
? "Action"= "BatchDisassociateServiceActionFromProvisioningArtifact"
data('{"AcceptLanguage":"string","ServiceActionAssociations":[{"ProductId":"string","ProvisioningArtifactId":"string","ServiceActionId":"string"}]}')



