#!/usr/bin/env dothttp

# imported from 35240-538b4bae-014b-4e31-9e7e-f206b0a4dc0c.postman_collection.json

// This operation list or find Entity entities

@name("List or find Entity objects")
GET "https://{{baseUrl}}/entity"
? "fields"= "ad dolor"
? "offset"= "-52978875"
? "limit"= "-52978875"


// This operation creates a Entity entity.

@name("Creates a Entity")
POST "https://{{baseUrl}}/entity"
"Content-Type": "application/json;charset=utf-8"
json({
    "@type": "ullamco dolor",
    "@baseType": "consequat anim elit in irure",
    "@schemaLocation": "http://XWz.swgqti.C-g5"
})



