#!/usr/bin/env dothttp

# imported from 35240-f15eb0b0-8456-4c8c-b7eb-e8c210aa11fb.postman_collection.json

@name("List Instances")
POST "https://{{aws_emr_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_emr_service}}", region="{{aws_emr_region}}")
"Content-Type": "application/x-amz-json-1.1"
"User-Agent": "Postman-Collection"
"X-Amz-Target": "ElasticMapReduce.ListInstances"
? "Action"= "ListInstances"
data('{"ClusterId":"string","InstanceFleetId":"string","InstanceFleetType":"string","InstanceGroupId":"string","InstanceGroupTypes":["string"],"InstanceStates":["string"],"Marker":"string"}')



