#!/usr/bin/env dothttp

# imported from 35240-eabc5422-b0c4-42fc-9bd9-335695a573f1.postman_collection.json

// Provides the match scoring for all matches played on a given day

@name("Provides the match scoring for all matches played ...")
GET "https://{{baseUrl}}/schedules/{{year-}}{{month-}}{{day}}/results{{format}}"
? "year"= "<number>"
? "month"= "<number>"


// Provides the schedule for all matches played on a given day

@name("Provides the schedule for all matches played on a ...")
GET "https://{{baseUrl}}/schedules/{{year-}}{{month-}}{{day}}/schedule{{format}}"
? "year"= "<number>"
? "month"= "<number>"



