#!/usr/bin/env dothttp

# imported from 35240-10c0a3a1-a4b5-4b4e-a83f-05d8a5e056fb.postman_collection.json

// By default the API will only return basic title information. Additional objects can be included by passing the object in the Includes parameter. 
// 
// 
// `Subscriptions with "Limited" data will only be able to include basic title information, Videos, EpisodicVideos, and SeasonVideos.`

@name("Returns a paged list of all TV shows.")
GET "https://{{baseUrl}}/Shows/All"
? "Take"= "<get>"
? "Skip"= "<get>"
? "Includes"= "<get>"


// Alternate Id types refer to the 3rd party ID sets IVA data has matched.  **Ex: IMDB**

@name("Get all AlternateIdTypes.")
GET "https://{{baseUrl}}/Shows/AlternateIdTypes"


// Use to match IVA show data to another data source using title, director, cast, etc.

@name("Perform a match to Entertainment using Title, Year, Cast and Director. Returns best match and score for the match.")
GET "https://{{baseUrl}}/Shows/Match/"
? "Title"= "<get>"
? "AlternateTitles"= "<get>"
? "Year"= "<get>"
? "Cast"= "<get>"
? "Directors"= "<get>"
? "StringDistance"= "<get>"


// Release types refer to the type of release and are used in the releases object for a show.

@name("Returns a list of Show Release Types.")
GET "https://{{baseUrl}}/Shows/ReleaseTypes"


// Searchable Fields: Title, AlternateTitles, Genres, Tags, Cast, Directors, Descriptions, Ratings, OriginalLanguage. [Syntax Ref](https://docs.microsoft.com/en-us/rest/api/searchservice/simple-query-syntax-in-azure-search)
// 
// Filterable Fields: Id, Title, AlternateTitles, Genres, OriginalAirDate, Year, Tags, Cast, Directors, Descriptions, HasVideo, ImageFilePath, Ratings, OriginalLanguage, Created, Modified, NumberOfSeasons, NumberOfEpisodes. [Syntax Ref](https://docs.microsoft.com/en-us/rest/api/se

@name("Search and discover shows.")
GET "https://{{baseUrl}}/Shows/SearchAndDiscover"
? "term"= "<get>"
? "SelectFields"= "<get>"
? "SearchFields"= "<get>"
? "Filter"= "<get>"
? "OrderBy"= "<get>"
? "Top"= "<get>"
? "Skip"= "<get>"
? "IncludeTotalResultCount"= "<get>"
? "SearchMode"= "<get>"


// Use the IVA ShowId and a season number to get a season details and video asset data.

@name("Get Season by ShowId and Season Number.")
GET "https://{{baseUrl}}/Shows/Season/"
? "Id"= "<get>"
? "SeasonNumber"= "<get>"


// List of Show Certifications and definitions.

@name("Returns a list of Show Certifications.")
GET "https://{{baseUrl}}/Shows/ShowCertifications"


// Returns a list of all the show genres used in the IVA database.

@name("Get all Show Genres.")
GET "https://{{baseUrl}}/Shows/ShowGenres"



