#!/usr/bin/env dothttp

# imported from 35240-4daf4441-eb91-41fe-b023-1dfb7909acdb.postman_collection.json

@name("Delete Lifecycle Hook")
GET "https://{{aws_auto_scaling_api_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "AutoScalingGroupName"= ""
? "LifecycleHookName"= ""
? "Action"= "DeleteLifecycleHook"


@name("Describe Lifecycle Hooks")
GET "https://{{aws_auto_scaling_api_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "AutoScalingGroupName"= ""
? "LifecycleHookNames.member.N"= ""
? "Action"= "DescribeLifecycleHooks"


@name("Put Lifecycle Hook")
GET "https://{{aws_auto_scaling_api_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{serviceName}}", region="{{region}}")
? "AutoScalingGroupName"= ""
? "DefaultResult"= ""
? "HeartbeatTimeout"= ""
? "LifecycleHookName"= ""
? "LifecycleTransition"= ""
? "NotificationMetadata"= ""
? "NotificationTargetARN"= ""
? "RoleARN"= ""
? "Action"= "PutLifecycleHook"



