#!/usr/bin/env dothttp

# imported from 35240-818a03fb-de85-44f9-b9ff-91e699ac9756.postman_collection.json

// Get Last Trade Tick for a Currency Pair.n

@name("Last Trade for a Currency Pair")
GET "https://{{baseUrl}}/v1/last/currencies/:from/:to"


// Get the last trade for a given stock.n

@name("Last Trade for a Symbol")
GET "https://{{baseUrl}}/v1/last/stocks/:symbol"



