#!/usr/bin/env dothttp

# imported from 35240-297ee2af-41bb-4515-ae99-0bc6025d90f7.postman_collection.json

// Basic registrant, server, and registration data for a domain name, plus preview data for other products

@name("Domain Profile")
GET "https://{{baseUrl}}/:domain"



