#!/usr/bin/env dothttp

# imported from 35240-cf05d8c7-fffb-4a7c-923b-c06517c2b783.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// Return the group user list.<p>Requires ADMINISTRATOR [64] user permissions. See [Permissions](doc:permissions).</p>

@name("List users in group") : "base-inherit-auth"
GET "https://{{baseUrl}}/groups/:group_id/users"



