#!/usr/bin/env dothttp

# imported from 35240-3de643e0-77af-41e6-9270-0b386f4ca61d.postman_collection.json

// Used to create new and read existing RIBs of a monetary account

@name("DELETE Export Rib for User Monetary Account")
DELETE "https://{{baseUrl}}/user/:userID/monetary-account/:monetary-accountID/export-rib/:itemId"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"


// Get a RIB for a monetary account by its id.

@name("READ Export Rib for User Monetary Account")
GET "https://{{baseUrl}}/user/:userID/monetary-account/:monetary-accountID/export-rib/:itemId"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"



