#!/usr/bin/env dothttp

# imported from 35240-7d2c214b-77c4-4e90-8dc4-3cd4493a1c9a.postman_collection.json

// Search AngelList.

@name("Search AngelList")
GET "https://{{baseUrl}}/search"
? "query"= "<>"
? "type"= "<get>"


// Search by slug

@name("Search Slugs")
GET "https://{{baseUrl}}/search/slugs"
? "query"= "<>"



