#!/usr/bin/env dothttp

# imported from 35240-32ced5f7-e4d1-46f1-acad-6349d837288f.postman_collection.json

// Example of a client listener for receiving the notification PermissionCreateEvent

@name("Client listener for entity PermissionCreateEvent")
POST "https://{{baseUrl}}/listener/permissionCreateEvent"
"Content-Type": "application/json;charset=utf-8"
json({
    "id": "eu eiusmod quis",
    "href": "amet incididunt",
    "eventId": "Ut pariatur sunt",
    "eventTime": "2020-07-31T21:20:30.926Z",
    "eventType": "do ex",
    "correlationId": "labore fugiat commodo",
    "domain": "elit laborum sit",
    "title": "officia deserunt",
    "description": "magna occaecat",
    "priority": "aute",
    "timeOcurred": "2011-02-18T12:36:21.618Z",
    "event": {
        "permission": {
            "user": {
                "@referredType": "in cillum Lorem dolor",
                "id": "sit fugiat tempor",
                "href": "aute",
                "name": "veniam mollit dolor exercitation",
                "role": "amet ipsum esse",
                "@baseType": "qui incididunt",
                "@schemaLocation": "https://JImcApcYaHy.mjxqUOwr1Op7W8+SypetoLfi.fTmruzWTt",
                "@type": "Lorem culp"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "id": "ut adipisicing magna est",
            "href": "elit commo",
            "creationDate": "1948-12-12T22:20:05.391Z",
            "description": "laborum exercitation occaecat dolore",
            "assetUserRole": [
                {
                    "manageableAsset": {
                        "id": "id",
                        "href": "fugiat eu aute in occaecat",
                        "name": "ut",
                        "@baseType": "velit est laboris",
                        "@schemaLocation": "https://fGWIOOPs.kzhu5qwcGVjFDFRKjLlzHB.Kq.JC3Fqb7JObg.iX41Q94S67N70E1Dde",
                        "@type": "deserunt dolor",
                        "@referredType": "in Excepteur elit proident"
                    },
                    "userRole": {
                        "id": "ex cupidatat consectetur",
                        "href": "dolore irure minim consectetur",
                        "@baseType": "eu Excepteur laboris nisi",
                        "@schemaLocation": "http://XliSmtdxTCGNjYDMdyhoe.tgrcYVD-.jwnGLoVZxx",
                        "@type": "elit incidi",
                        "@referredType": "commodo dolore"
                    },
                    "@baseType": "ipsum et exercitation",
                    "@schemaLocation": "http://yF.tplWbKVSpGZLNOZv3ZBwXrs55qvMIQ93HwsmszRfb5lHtnYc+AvgZ1.FXR",
                    "@type": "ad consectetur enim deserunt"
                },
                {
                    "manageableAsset": {
                        "id": "sit",
                        "href": "nulla nisi reprehenderit in Lorem",
                        "name": "consequat elit aliquip",
                        "@baseType": "dolor",
                        "@schemaLocation": "https://HrbkKhGvDhrgoz.iflogF+7h+m6WeyVbetY0UNJRNQ+7ZrjBFbd+ItkyP9FUuDVU,h1+L-vvw-nBn.qTL9TsqoMUdMFiJVdN10zH",
                        "@type": "officia in",
                        "@referredType": "minim cons"
                    },
                    "userRole": {
                        "id": "enim",
                        "href": "minim est aliquip",
                        "@baseType": "nisi",
                        "@schemaLocation": "http://Q.egcOyScuONL7.U2uXWOwM6F5t84QR4.uc0",
                        "@type": "reprehenderit mollit",
                        "@referredType": "Lorem"
                    },
                    "@baseType": "occaecat aute deserunt",
                    "@schemaLocation": "https://opNvGKITxcBeHHROFwiTDtnh.htfgkotxXA24vt.gWGz3,6TLhjyT,lQ6lxykzT1JEsEGEKqhjv5.,GBvGOKyXr",
                    "@type": "nulla pariatur sit incididunt aliquip"
                }
            ],
            "granter": {
                "@referredType": "ea volupt",
                "id": "consectetur nost",
                "href": "Excepteur in Duis nostrud",
                "name": "voluptate",
                "role": "Exc",
                "@baseType": "d",
                "@schemaLocation": "https://kXNCdqMiLSoFnZLYjParJBUr.gunBP+B3lrk4Qpb",
                "@type": "cupidatat fugiat"
            },
            "privilege": [
                {
                    "manageableAsset": {
                        "id": "sit ",
                        "href": "aliquip",
                        "name": "ut nostrud et veniam",
                        "@baseType": "veniam ullamco",
                        "@schemaLocation": "https://fyNSSalZoObBpgTbFW.jqvaV9vVpyOZ7hSarMZghUSpELc,R6Pg",
                        "@type": "dolor",
                        "@referredType": "velit"
                    },
                    "action": "anim aliqua dolore consectetur nostrud",
                    "function": "consequat tempor laborum occaecat",
                    "id": "nisi",
                    "@baseType": "s",
                    "@schemaLocation": "https://KYltcGQqTLSU.hzchP1BYFnye9isRBJVOGgHns4qCuobpwyqnbE6QohbWX",
                    "@type": "voluptate deserunt Excepteur"
                },
                {
                    "manageableAsset": {
                        "id": "veniam non eu",
                        "href": "ipsum ullamco",
                        "name": "eu",
                        "@baseType": "est do",
                        "@schemaLocation": "https://eTsMptFyCwmFYlzm.utaKmOh0bm",
                        "@type": "sed consequat dolor culpa",
                        "@referredType": "voluptate non enim"
                    },
                    "action": "cupidatat id Duis",
                    "function": "labore dolore nisi in",
                    "id": "dolor nulla eiusmod id proident",
                    "@baseType": "in do dolor incididunt amet",
                    "@schemaLocation": "http://iSswvcksOlou.ssvUypQsdf6m4n0L,ywp.LhxTMntypby39X1xfTTf",
                    "@type": "consequat q"
                }
            ],
            "@baseType": "aliquip culpa",
            "@schemaLocation": "https://mZFFGhBRzHzyYwEBTzAkNMS.pjyqaFsM97NNhRjmcAWjEUWHA9+NWJWBKoMzEwW",
            "@type": "anim elit proident"
        }
    }
})


// Example of a client listener for receiving the notification PermissionAttributeValueChangeEvent

@name("Client listener for entity PermissionAttributeValueChangeEvent")
POST "https://{{baseUrl}}/listener/permissionAttributeValueChangeEvent"
"Content-Type": "application/json;charset=utf-8"
json({
    "eventId": "aliquip culpa sunt eu",
    "eventTime": "1977-11-14T00:16:37.327Z",
    "eventType": "Excepteur",
    "correlationId": "in incididunt",
    "domain": "enim Excepteur fugiat cil",
    "title": "minim nulla",
    "description": "anim sunt Lorem nulla",
    "priority": "Ut consequat laborum qui",
    "timeOcurred": "1986-06-09T12:37:52.309Z",
    "fieldPath": "magna laboris",
    "event": {
        "permission": {
            "user": {
                "@referredType": "aute",
                "id": "officia in ",
                "href": "veniam aliquip consectetur",
                "name": "esse commodo est nostrud",
                "role": "reprehenderit qui amet nisi",
                "@baseType": "esse consequat irure voluptate aute",
                "@schemaLocation": "http://tsDDxBKRKiPsfNHTcXzivg.beggkiGHoEKxDSYU-2LAyv3qBCUgBW9cXfQYix65ESZLl8fm+",
                "@type": "eu labore"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "id": "enim laboris velit ut",
            "href": "aliqua",
            "creationDate": "1976-12-24T00:31:22.933Z",
            "description": "nulla anim ea",
            "assetUserRole": [
                {
                    "manageableAsset": {
                        "id": "velit",
                        "href": "occaecat laborum officia anim",
                        "name": "do dolore in reprehenderit",
                        "@baseType": "qui Excepteu",
                        "@schemaLocation": "http://BTUHvjWvfEMhnBoFmXPGMYg.ysuqCU7is.NVLxdlZd3uojOY",
                        "@type": "id",
                        "@referredType": "ut officia dolor"
                    },
                    "userRole": {
                        "id": "cillum sit",
                        "href": "et sed",
                        "@baseType": "fugiat",
                        "@schemaLocation": "https://tPARFTpKlZVIRAZZM.thzV6AfkY1IjIALrv7izhz.",
                        "@type": "nostrud eiusmod aute",
                        "@referredType": "reprehenderit amet"
                    },
                    "@baseType": "mollit fugiat",
                    "@schemaLocation": "http://MvKXSqApEijD.agrdNyZbIaDJx3GSpiYlvD34Lto1mhaxTJDD,jkOYs,hj1ckfDyVNWwu.1",
                    "@type": "proident reprehenderit"
                },
                {
                    "manageableAsset": {
                        "id": "in quis",
                        "href": "aute Excepteur magna sunt",
                        "name": "ad eu dolor",
                        "@baseType": "dolore",
                        "@schemaLocation": "https://NxGayYTppBtiKlUQCAy.kkhrPzNQ3kMLuznuub0fu2QJ4qZTp5sgoMrxSClKhS4Kt+GStSz",
                        "@type": "anim sit et consectetu",
                        "@referredType": "aliquip in eu ut Excepteur"
                    },
                    "userRole": {
                        "id": "labori",
                        "href": "Lorem esse cillum",
                        "@baseType": "nulla et mollit dolore",
                        "@schemaLocation": "http://GaCPV.iySO6Oo,a1w-YhRL-c7pKd2YlpvY.BneESYphYN8",
                        "@type": "in sint Excepteur",
                        "@referredType": "ea est do fugiat ipsum"
                    },
                    "@baseType": "Duis in sit do",
                    "@schemaLocation": "https://NCqPnqgbhbZhtPxcYVsXzCnfmzStYiRs.cinbGtVhrR9OtypH8ByX1dXE.qPM",
                    "@type": "labore esse aute Lorem"
                }
            ],
            "granter": {
                "@referredType": "aliq",
                "id": "sed enim d",
                "href": "incididunt magna consequat",
                "name": "ullamco proident dolore culpa",
                "role": "magna do",
                "@baseType": "exercitation eiusmod aute anim pariatur",
                "@schemaLocation": "http://HyZ.beiYtaLSb5STlYIjScYIXVgplhVT-dnHwRdaQU7MM",
                "@type": "pariatur quis non"
            },
            "privilege": [
                {
                    "manageableAsset": {
                        "id": "aliqua occaecat",
                        "href": "veniam do ad",
                        "name": "qui irure in Excepteur",
                        "@baseType": "in culpa",
                        "@schemaLocation": "http://MaYGQEHtUZxUu.fqzwUDuw4RXk0+MczvJPnpFbKBhU.PuHhRafC1k,ERQomuLizwpjpgCiXWkf9s5",
                        "@type": "sunt et qui ullamco ut",
                        "@referredType": "laborum dolore"
                    },
                    "action": "pariatur Lorem adipisicing do nisi",
                    "function": "nisi dolore Excepteur",
                    "id": "Lorem esse sit",
                    "@baseType": "enim ad dolor dolore",
                    "@schemaLocation": "http://kDdjSRwQPSyUctIaEPWnT.myimBmm+JpOXGx99hZ3",
                    "@type": "quis nostrud de"
                },
                {
                    "manageableAsset": {
                        "id": "dolore",
                        "href": "elit magna esse",
                        "name": "nisi do incididunt veniam",
                        "@baseType": "et minim dolor",
                        "@schemaLocation": "https://wOSAoAmFCRUQEJkBxOnajiQjHxRNeOjqg.stcUAC5r,ybZaUDzmeuYUNLZUJOjhJAffEwVQub7uXxsweIAuh5",
                        "@type": "laborum quis cillum",
                        "@referredType": "in velit minim ad"
                    },
                    "action": "ut aliquip",
                    "function": "sit culpa",
                    "id": "aute Lorem",
                    "@baseType": "ut veniam adipisicing velit",
                    "@schemaLocation": "https://FlTtjtdA.jfk1tIatzGtwRYvDpmRznTCPNMtqe8NmdP5ynYbYme0DOaOtn+RXClId2fviorz",
                    "@type": "culpa eu sint laboris"
                }
            ],
            "@baseType": "occaecat",
            "@schemaLocation": "https://YJLKcHqYeiATUntaOdvFwiuRg.ofwqaqKWxvwkVmsOOT0LqUTCxrHkneyLwam",
            "@type": "non amet pariatur ea"
        }
    }
})


// Example of a client listener for receiving the notification PermissionStateChangeEvent

@name("Client listener for entity PermissionStateChangeEvent")
POST "https://{{baseUrl}}/listener/permissionStateChangeEvent"
"Content-Type": "application/json;charset=utf-8"
json({
    "id": "eu eiusmod quis",
    "href": "amet incididunt",
    "eventId": "Ut pariatur sunt",
    "eventTime": "2020-07-31T21:20:30.926Z",
    "eventType": "do ex",
    "correlationId": "labore fugiat commodo",
    "domain": "elit laborum sit",
    "title": "officia deserunt",
    "description": "magna occaecat",
    "priority": "aute",
    "timeOcurred": "2011-02-18T12:36:21.618Z",
    "event": {
        "permission": {
            "user": {
                "@referredType": "in cillum Lorem dolor",
                "id": "sit fugiat tempor",
                "href": "aute",
                "name": "veniam mollit dolor exercitation",
                "role": "amet ipsum esse",
                "@baseType": "qui incididunt",
                "@schemaLocation": "https://JImcApcYaHy.mjxqUOwr1Op7W8+SypetoLfi.fTmruzWTt",
                "@type": "Lorem culp"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "id": "ut adipisicing magna est",
            "href": "elit commo",
            "creationDate": "1948-12-12T22:20:05.391Z",
            "description": "laborum exercitation occaecat dolore",
            "assetUserRole": [
                {
                    "manageableAsset": {
                        "id": "id",
                        "href": "fugiat eu aute in occaecat",
                        "name": "ut",
                        "@baseType": "velit est laboris",
                        "@schemaLocation": "https://fGWIOOPs.kzhu5qwcGVjFDFRKjLlzHB.Kq.JC3Fqb7JObg.iX41Q94S67N70E1Dde",
                        "@type": "deserunt dolor",
                        "@referredType": "in Excepteur elit proident"
                    },
                    "userRole": {
                        "id": "ex cupidatat consectetur",
                        "href": "dolore irure minim consectetur",
                        "@baseType": "eu Excepteur laboris nisi",
                        "@schemaLocation": "http://XliSmtdxTCGNjYDMdyhoe.tgrcYVD-.jwnGLoVZxx",
                        "@type": "elit incidi",
                        "@referredType": "commodo dolore"
                    },
                    "@baseType": "ipsum et exercitation",
                    "@schemaLocation": "http://yF.tplWbKVSpGZLNOZv3ZBwXrs55qvMIQ93HwsmszRfb5lHtnYc+AvgZ1.FXR",
                    "@type": "ad consectetur enim deserunt"
                },
                {
                    "manageableAsset": {
                        "id": "sit",
                        "href": "nulla nisi reprehenderit in Lorem",
                        "name": "consequat elit aliquip",
                        "@baseType": "dolor",
                        "@schemaLocation": "https://HrbkKhGvDhrgoz.iflogF+7h+m6WeyVbetY0UNJRNQ+7ZrjBFbd+ItkyP9FUuDVU,h1+L-vvw-nBn.qTL9TsqoMUdMFiJVdN10zH",
                        "@type": "officia in",
                        "@referredType": "minim cons"
                    },
                    "userRole": {
                        "id": "enim",
                        "href": "minim est aliquip",
                        "@baseType": "nisi",
                        "@schemaLocation": "http://Q.egcOyScuONL7.U2uXWOwM6F5t84QR4.uc0",
                        "@type": "reprehenderit mollit",
                        "@referredType": "Lorem"
                    },
                    "@baseType": "occaecat aute deserunt",
                    "@schemaLocation": "https://opNvGKITxcBeHHROFwiTDtnh.htfgkotxXA24vt.gWGz3,6TLhjyT,lQ6lxykzT1JEsEGEKqhjv5.,GBvGOKyXr",
                    "@type": "nulla pariatur sit incididunt aliquip"
                }
            ],
            "granter": {
                "@referredType": "ea volupt",
                "id": "consectetur nost",
                "href": "Excepteur in Duis nostrud",
                "name": "voluptate",
                "role": "Exc",
                "@baseType": "d",
                "@schemaLocation": "https://kXNCdqMiLSoFnZLYjParJBUr.gunBP+B3lrk4Qpb",
                "@type": "cupidatat fugiat"
            },
            "privilege": [
                {
                    "manageableAsset": {
                        "id": "sit ",
                        "href": "aliquip",
                        "name": "ut nostrud et veniam",
                        "@baseType": "veniam ullamco",
                        "@schemaLocation": "https://fyNSSalZoObBpgTbFW.jqvaV9vVpyOZ7hSarMZghUSpELc,R6Pg",
                        "@type": "dolor",
                        "@referredType": "velit"
                    },
                    "action": "anim aliqua dolore consectetur nostrud",
                    "function": "consequat tempor laborum occaecat",
                    "id": "nisi",
                    "@baseType": "s",
                    "@schemaLocation": "https://KYltcGQqTLSU.hzchP1BYFnye9isRBJVOGgHns4qCuobpwyqnbE6QohbWX",
                    "@type": "voluptate deserunt Excepteur"
                },
                {
                    "manageableAsset": {
                        "id": "veniam non eu",
                        "href": "ipsum ullamco",
                        "name": "eu",
                        "@baseType": "est do",
                        "@schemaLocation": "https://eTsMptFyCwmFYlzm.utaKmOh0bm",
                        "@type": "sed consequat dolor culpa",
                        "@referredType": "voluptate non enim"
                    },
                    "action": "cupidatat id Duis",
                    "function": "labore dolore nisi in",
                    "id": "dolor nulla eiusmod id proident",
                    "@baseType": "in do dolor incididunt amet",
                    "@schemaLocation": "http://iSswvcksOlou.ssvUypQsdf6m4n0L,ywp.LhxTMntypby39X1xfTTf",
                    "@type": "consequat q"
                }
            ],
            "@baseType": "aliquip culpa",
            "@schemaLocation": "https://mZFFGhBRzHzyYwEBTzAkNMS.pjyqaFsM97NNhRjmcAWjEUWHA9+NWJWBKoMzEwW",
            "@type": "anim elit proident"
        }
    }
})


// Example of a client listener for receiving the notification PermissionDeleteEvent

@name("Client listener for entity PermissionDeleteEvent")
POST "https://{{baseUrl}}/listener/permissionDeleteEvent"
"Content-Type": "application/json;charset=utf-8"
json({
    "id": "eu eiusmod quis",
    "href": "amet incididunt",
    "eventId": "Ut pariatur sunt",
    "eventTime": "2020-07-31T21:20:30.926Z",
    "eventType": "do ex",
    "correlationId": "labore fugiat commodo",
    "domain": "elit laborum sit",
    "title": "officia deserunt",
    "description": "magna occaecat",
    "priority": "aute",
    "timeOcurred": "2011-02-18T12:36:21.618Z",
    "event": {
        "permission": {
            "user": {
                "@referredType": "in cillum Lorem dolor",
                "id": "sit fugiat tempor",
                "href": "aute",
                "name": "veniam mollit dolor exercitation",
                "role": "amet ipsum esse",
                "@baseType": "qui incididunt",
                "@schemaLocation": "https://JImcApcYaHy.mjxqUOwr1Op7W8+SypetoLfi.fTmruzWTt",
                "@type": "Lorem culp"
            },
            "validFor": {
                "endDateTime": "1985-04-12T23:20:50.52Z",
                "startDateTime": "1985-04-12T23:20:50.52Z"
            },
            "id": "ut adipisicing magna est",
            "href": "elit commo",
            "creationDate": "1948-12-12T22:20:05.391Z",
            "description": "laborum exercitation occaecat dolore",
            "assetUserRole": [
                {
                    "manageableAsset": {
                        "id": "id",
                        "href": "fugiat eu aute in occaecat",
                        "name": "ut",
                        "@baseType": "velit est laboris",
                        "@schemaLocation": "https://fGWIOOPs.kzhu5qwcGVjFDFRKjLlzHB.Kq.JC3Fqb7JObg.iX41Q94S67N70E1Dde",
                        "@type": "deserunt dolor",
                        "@referredType": "in Excepteur elit proident"
                    },
                    "userRole": {
                        "id": "ex cupidatat consectetur",
                        "href": "dolore irure minim consectetur",
                        "@baseType": "eu Excepteur laboris nisi",
                        "@schemaLocation": "http://XliSmtdxTCGNjYDMdyhoe.tgrcYVD-.jwnGLoVZxx",
                        "@type": "elit incidi",
                        "@referredType": "commodo dolore"
                    },
                    "@baseType": "ipsum et exercitation",
                    "@schemaLocation": "http://yF.tplWbKVSpGZLNOZv3ZBwXrs55qvMIQ93HwsmszRfb5lHtnYc+AvgZ1.FXR",
                    "@type": "ad consectetur enim deserunt"
                },
                {
                    "manageableAsset": {
                        "id": "sit",
                        "href": "nulla nisi reprehenderit in Lorem",
                        "name": "consequat elit aliquip",
                        "@baseType": "dolor",
                        "@schemaLocation": "https://HrbkKhGvDhrgoz.iflogF+7h+m6WeyVbetY0UNJRNQ+7ZrjBFbd+ItkyP9FUuDVU,h1+L-vvw-nBn.qTL9TsqoMUdMFiJVdN10zH",
                        "@type": "officia in",
                        "@referredType": "minim cons"
                    },
                    "userRole": {
                        "id": "enim",
                        "href": "minim est aliquip",
                        "@baseType": "nisi",
                        "@schemaLocation": "http://Q.egcOyScuONL7.U2uXWOwM6F5t84QR4.uc0",
                        "@type": "reprehenderit mollit",
                        "@referredType": "Lorem"
                    },
                    "@baseType": "occaecat aute deserunt",
                    "@schemaLocation": "https://opNvGKITxcBeHHROFwiTDtnh.htfgkotxXA24vt.gWGz3,6TLhjyT,lQ6lxykzT1JEsEGEKqhjv5.,GBvGOKyXr",
                    "@type": "nulla pariatur sit incididunt aliquip"
                }
            ],
            "granter": {
                "@referredType": "ea volupt",
                "id": "consectetur nost",
                "href": "Excepteur in Duis nostrud",
                "name": "voluptate",
                "role": "Exc",
                "@baseType": "d",
                "@schemaLocation": "https://kXNCdqMiLSoFnZLYjParJBUr.gunBP+B3lrk4Qpb",
                "@type": "cupidatat fugiat"
            },
            "privilege": [
                {
                    "manageableAsset": {
                        "id": "sit ",
                        "href": "aliquip",
                        "name": "ut nostrud et veniam",
                        "@baseType": "veniam ullamco",
                        "@schemaLocation": "https://fyNSSalZoObBpgTbFW.jqvaV9vVpyOZ7hSarMZghUSpELc,R6Pg",
                        "@type": "dolor",
                        "@referredType": "velit"
                    },
                    "action": "anim aliqua dolore consectetur nostrud",
                    "function": "consequat tempor laborum occaecat",
                    "id": "nisi",
                    "@baseType": "s",
                    "@schemaLocation": "https://KYltcGQqTLSU.hzchP1BYFnye9isRBJVOGgHns4qCuobpwyqnbE6QohbWX",
                    "@type": "voluptate deserunt Excepteur"
                },
                {
                    "manageableAsset": {
                        "id": "veniam non eu",
                        "href": "ipsum ullamco",
                        "name": "eu",
                        "@baseType": "est do",
                        "@schemaLocation": "https://eTsMptFyCwmFYlzm.utaKmOh0bm",
                        "@type": "sed consequat dolor culpa",
                        "@referredType": "voluptate non enim"
                    },
                    "action": "cupidatat id Duis",
                    "function": "labore dolore nisi in",
                    "id": "dolor nulla eiusmod id proident",
                    "@baseType": "in do dolor incididunt amet",
                    "@schemaLocation": "http://iSswvcksOlou.ssvUypQsdf6m4n0L,ywp.LhxTMntypby39X1xfTTf",
                    "@type": "consequat q"
                }
            ],
            "@baseType": "aliquip culpa",
            "@schemaLocation": "https://mZFFGhBRzHzyYwEBTzAkNMS.pjyqaFsM97NNhRjmcAWjEUWHA9+NWJWBKoMzEwW",
            "@type": "anim elit proident"
        }
    }
})


// Example of a client listener for receiving the notification UserRoleCreateEvent

@name("Client listener for entity UserRoleCreateEvent")
POST "https://{{baseUrl}}/listener/userRoleCreateEvent"
"Content-Type": "application/json;charset=utf-8"
json({
    "id": "deserun",
    "href": "tempor pariatur ipsum",
    "eventId": "Duis",
    "eventTime": "1959-06-03T02:24:14.336Z",
    "eventType": "in et nostrud consequat",
    "correlationId": "qui in do non",
    "domain": "consectetur ipsum cillum",
    "title": "non mollit",
    "description": "veniam",
    "priority": "tempor consectetur",
    "timeOcurred": "1964-01-01T06:38:58.364Z",
    "event": {
        "userRole": {
            "id": "pariatur ex",
            "href": "consequat in amet",
            "involvementRole": "dolor eiusmod ipsum aliqua",
            "entitlement": [
                {
                    "id": "do velit",
                    "action": "velit veniam",
                    "function": "est Ut voluptate minim",
                    "@baseType": "dolore proident",
                    "@schemaLocation": "https://RoExbH.sdUYYPb7aeqX.qXfS",
                    "@type": "exercitation non Ut ipsum"
                },
                {
                    "id": "",
                    "action": "cillum labore",
                    "function": "in eu",
                    "@baseType": "Lorem Duis aliquip officia",
                    "@schemaLocation": "http://ZRItdiVJEUk.jdqqz.oddI8qHOcUjXDCIoyTFEKxb.OoelXrktIN9AV-SqmBLDA7shK,Dv-H+f",
                    "@type": "irure"
                }
            ],
            "@baseType": "officia",
            "@schemaLocation": "https://QszKQzEYbioZgowfakYuVUmTdMyMt.wgdt-I0yyr4EYf7q+YQw,PRBw",
            "@type": "magna"
        }
    }
})


// Example of a client listener for receiving the notification UserRoleAttributeValueChangeEvent

@name("Client listener for entity UserRoleAttributeValueChangeEvent")
POST "https://{{baseUrl}}/listener/userRoleAttributeValueChangeEvent"
"Content-Type": "application/json;charset=utf-8"
json({
    "eventId": "dolor in",
    "eventTime": "1999-05-23T12:16:01.972Z",
    "eventType": "commodo culpa",
    "correlationId": "occaecat ullamco cupidatat",
    "domain": "aute incididunt",
    "title": "voluptate cillum",
    "description": "do dolore consectetur",
    "priority": "ad anim est exercitation",
    "timeOcurred": "1987-03-10T18:50:02.273Z",
    "fieldPath": "esse aliquip amet est",
    "event": {
        "userRole": {
            "id": "irure ipsum",
            "href": "quis qui",
            "involvementRole": "Duis commodo sunt",
            "entitlement": [
                {
                    "id": "ut ad",
                    "action": "labore amet exercitation Lorem aliqua",
                    "function": "tempor aliquip veniam sint",
                    "@baseType": "aute Excepteur deserunt",
                    "@schemaLocation": "http://NsJpwBzWOTdSVvLgIOY.eihlV5kYz,KZ9He8GOv2ug+ue.ew",
                    "@type": "irure elit"
                },
                {
                    "id": "cupidatat ad",
                    "action": "ex nisi non exercitation",
                    "function": "nisi incididunt magna",
                    "@baseType": "labore in sit commodo quis",
                    "@schemaLocation": "http://PsvLTHGZfXGhCZtAhOmiZi.znaeZXx3g2cB1TbTqTQH-gpIIRb9gBLd",
                    "@type": "eiusmod nisi in incididun"
                }
            ],
            "@baseType": "in dese",
            "@schemaLocation": "http://TXFLqcjTJRcAqTpxKPfzCSEKtu.xpanNIC5YH2XEbr8k.KiDfaEEILIQH,v0lKh9+Bv6QVsjUqFWSx",
            "@type": "deserunt irure Duis tempor cupidatat"
        }
    }
})


// Example of a client listener for receiving the notification UserRoleStateChangeEvent

@name("Client listener for entity UserRoleStateChangeEvent")
POST "https://{{baseUrl}}/listener/userRoleStateChangeEvent"
"Content-Type": "application/json;charset=utf-8"
json({
    "id": "deserun",
    "href": "tempor pariatur ipsum",
    "eventId": "Duis",
    "eventTime": "1959-06-03T02:24:14.336Z",
    "eventType": "in et nostrud consequat",
    "correlationId": "qui in do non",
    "domain": "consectetur ipsum cillum",
    "title": "non mollit",
    "description": "veniam",
    "priority": "tempor consectetur",
    "timeOcurred": "1964-01-01T06:38:58.364Z",
    "event": {
        "userRole": {
            "id": "pariatur ex",
            "href": "consequat in amet",
            "involvementRole": "dolor eiusmod ipsum aliqua",
            "entitlement": [
                {
                    "id": "do velit",
                    "action": "velit veniam",
                    "function": "est Ut voluptate minim",
                    "@baseType": "dolore proident",
                    "@schemaLocation": "https://RoExbH.sdUYYPb7aeqX.qXfS",
                    "@type": "exercitation non Ut ipsum"
                },
                {
                    "id": "",
                    "action": "cillum labore",
                    "function": "in eu",
                    "@baseType": "Lorem Duis aliquip officia",
                    "@schemaLocation": "http://ZRItdiVJEUk.jdqqz.oddI8qHOcUjXDCIoyTFEKxb.OoelXrktIN9AV-SqmBLDA7shK,Dv-H+f",
                    "@type": "irure"
                }
            ],
            "@baseType": "officia",
            "@schemaLocation": "https://QszKQzEYbioZgowfakYuVUmTdMyMt.wgdt-I0yyr4EYf7q+YQw,PRBw",
            "@type": "magna"
        }
    }
})


// Example of a client listener for receiving the notification UserRoleDeleteEvent

@name("Client listener for entity UserRoleDeleteEvent")
POST "https://{{baseUrl}}/listener/userRoleDeleteEvent"
"Content-Type": "application/json;charset=utf-8"
json({
    "id": "deserun",
    "href": "tempor pariatur ipsum",
    "eventId": "Duis",
    "eventTime": "1959-06-03T02:24:14.336Z",
    "eventType": "in et nostrud consequat",
    "correlationId": "qui in do non",
    "domain": "consectetur ipsum cillum",
    "title": "non mollit",
    "description": "veniam",
    "priority": "tempor consectetur",
    "timeOcurred": "1964-01-01T06:38:58.364Z",
    "event": {
        "userRole": {
            "id": "pariatur ex",
            "href": "consequat in amet",
            "involvementRole": "dolor eiusmod ipsum aliqua",
            "entitlement": [
                {
                    "id": "do velit",
                    "action": "velit veniam",
                    "function": "est Ut voluptate minim",
                    "@baseType": "dolore proident",
                    "@schemaLocation": "https://RoExbH.sdUYYPb7aeqX.qXfS",
                    "@type": "exercitation non Ut ipsum"
                },
                {
                    "id": "",
                    "action": "cillum labore",
                    "function": "in eu",
                    "@baseType": "Lorem Duis aliquip officia",
                    "@schemaLocation": "http://ZRItdiVJEUk.jdqqz.oddI8qHOcUjXDCIoyTFEKxb.OoelXrktIN9AV-SqmBLDA7shK,Dv-H+f",
                    "@type": "irure"
                }
            ],
            "@baseType": "officia",
            "@schemaLocation": "https://QszKQzEYbioZgowfakYuVUmTdMyMt.wgdt-I0yyr4EYf7q+YQw,PRBw",
            "@type": "magna"
        }
    }
})



