#!/usr/bin/env dothttp

# imported from 35240-bd1a5667-9165-48e8-9c3c-1bd94c10517b.postman_collection.json

// Returns all attachments for this issue.
// 
// This returns the files' meta data. This does not return the files'
// actual contents.
// 
// The files are always ordered by their upload date.

@name("/repositories/:username/:repo_slug/issues/:issue_id/attachments")
GET "https://{{baseUrl}}/repositories/:username/:repo_slug/issues/:issue_id/attachments"


// Upload new issue attachments.
// 
// To upload files, perform a `multipart/form-data` POST containing one
// or more file fields.
// 
// When a file is uploaded with the same name as an existing attachment,
// then the existing file will be replaced.

@name("/repositories/:username/:repo_slug/issues/:issue_id/attachments")
POST "https://{{baseUrl}}/repositories/:username/:repo_slug/issues/:issue_id/attachments"



