#!/usr/bin/env dothttp

# imported from 35240-3659b137-52c3-4941-8c35-36a1a993a79b.postman_collection.json

// Get recommended listings for an authenticated member. The number of listings returned may not match the specified limit if there is no activity from recommended shops.

@name("Get Users User Recommended Listings")
GET "https://{{baseUrl}}/users/:user_id/recommended_listings"
? "limit"= "<>"
? "excluded_listing_ids"= "<>"


// Registers rejections of recommended listings. Affects future recommended listings.

@name("Post Users User Recommended Listings Rejects Listing S")
POST "https://{{baseUrl}}/users/:user_id/recommended_listings/rejects/:listing_ids"


// Register viewings of recommended listings. Affects future recommended listings.

@name("Post Users User Recommended Listings Views Listing S")
POST "https://{{baseUrl}}/users/:user_id/recommended_listings/views/:listing_ids"



