#!/usr/bin/env dothttp

# imported from 35240-a96221e2-b43c-4973-9be0-3ec0566f4cd9.postman_collection.json

// Update a country.

@name("update a country")
PUT "https://{{baseUrl}}/admin/countries/444574734.json"
"Content": "<>"


// Show country.

@name("Show Country")
GET "https://{{baseUrl}}/admin/countries/261414723.json"
"Content": "<>"


// Get a count of all countries.

@name("Get a count of all countries")
GET "https://{{baseUrl}}/admin/countries/count.json"
"Content": "<>"



