#!/usr/bin/env dothttp

# imported from 35240-180f91eb-1001-48c8-8579-83b031bdc301.postman_collection.json

// Returns an equipment using its identifier.

@name("Get Equipment")
GET "https://{{baseUrl}}/gear/:id"



