#!/usr/bin/env dothttp

# imported from 35240-66d8dc5a-504e-4f74-b3df-9ef8c95ff2fd.postman_collection.json

// 
// 
// * node_id: A UUID representing the running Kong node. This UUID is randomly generated when Kong starts, so the node will have a different node_id each time it is restarted.
// * available_on_server: Names of plugins that are installed on the node.
// * nabled_in_cluster: Names of plugins that are enabled/configured. That is, the plugins configurations currently in the datastore shared by all Kong nodes.

@name("Retrieve Node Information")
GET "https://{{baseUrl}}/"


// 
// 
// * Retrieve usage information about a node, with some basic information about the connections being processed by the underlying nginx process, the status of the database connection, and node’s memory usage.
// * If you want to monitor the Kong process, since Kong is built on top of nginx, every existing nginx monitoring tool or agent can be used.
// 
// * memory: Metrics about the memory usage. 	* workers_lua_vms: An array with all workers of the Kong node, where each entry contains: 	* http_allocated

@name("Retrieve Node Status")
GET "https://{{baseUrl}}/status"


// # Delete CA Certificate [konghq](https://docs.konghq.com/2.0.x/admin-api/#delete-ca-certificate-1)
// 
// # Path parameters
// <table style="width:50%">
//   <tr>
//     <th>Attributes</th>
//     <th>Mandatory</th>
//     <th>Type</th>
//     <th>Description</th> 
//   </tr>
//   <tr>
//     <td>certificate id</td>
//     <td>required</td>
//     <td>path</td>
//     <td>The unique identifier of the CA Certificate to delete.</td>
//   </tr>
// </table>

@name("Delete CA Certificate")
DELETE "https://{{baseUrl}}/ca_/certificates/:ca_certificateId"


// # Retrieve Upstream Associated to a Specific Target [konghq](https://docs.konghq.com/2.0.x/admin-api/#retrieve-upstream-associated-to-a-specific-target)
// <table style="width:50%">
//   <tr>
//     <th>Attributes</th>
//     <th>Mandatory</th>
//     <th>Type</th>
//     <th>Description</th> 
//   </tr>
//   <tr>
//     <td>target host:port or id</td>
//     <td>required</td>
//     <td>path</td>
//     <td>The unique identifier or the host:port of the Target associated to the Upstream to be retrieved.</td>
//   </tr>
// </table>

@name("Retrieve Upstream Associated to a Specific Target")
GET "https://{{baseUrl}}/targets/:targetHost:portOrId/upstream"



