#!/usr/bin/env dothttp

# imported from 35240-01e79e8b-0f05-4fff-860a-a88d8c927eac.postman_collection.json

@name("/self/mfa/:kind")
DELETE "https://{{baseUrl}}/self/mfa/:kind"


@name("/self/mfa/:kind/backupcodes")
GET "https://{{baseUrl}}/self/mfa/:kind/backupcodes"


@name("/self/mfa/:kind/confirmation")
POST "https://{{baseUrl}}/self/mfa/:kind/confirmation"



