#!/usr/bin/env dothttp

# imported from 35240-5da4bd40-1308-4c08-9688-8cbdcd14f62d.postman_collection.json

@name("Read Api")
GET "https://{{baseUrl}}/api/"


@name("Query")
GET "https://{{baseUrl}}/api/explore/:treepath"
? "token"= "anim commodo Ut ad"



