#!/usr/bin/env dothttp

# imported from 35240-ac6561cd-0334-4ee5-8280-57b4086d4c3d.postman_collection.json

@name("Get all repository topics")
GET "https://{{baseUrl}}/repos/:owner/:repo/topics"


@name("Replace all repository topics")
PUT "https://{{baseUrl}}/repos/:owner/:repo/topics"
"Content-Type": "application/json"
json({
    "names": [
        "<string>",
        "<string>"
    ]
})



