#!/usr/bin/env dothttp

# imported from 35240-3de643e0-77af-41e6-9270-0b386f4ca61d.postman_collection.json

// Used to list bunq invoices by user.

@name("List all Invoice for User")
GET "https://{{baseUrl}}/user/:userID/invoice"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"


// Get a PDF export of an invoice.

@name("List all Pdf Content for User Invoice")
GET "https://{{baseUrl}}/user/:userID/invoice/:invoiceID/pdf-content"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"


// Used to list bunq invoices by user.

@name("READ Invoice for User")
GET "https://{{baseUrl}}/user/:userID/invoice/:itemId"
"Cache-Control": "<string>"
"User-Agent": "<string>"
"X-Bunq-Language": "<string>"
"X-Bunq-Region": "<string>"
"X-Bunq-Client-Request-Id": "<string>"
"X-Bunq-Geolocation": "<string>"
"X-Bunq-Client-Authentication": "<string>"



