#!/usr/bin/env dothttp

# imported from 35240-65f4ef9f-4899-427d-8614-940a22ec8828.postman_collection.json

// This operation list or find QueryProductRecommendation entities

@name("List or find QueryProductRecommendation objects")
GET "https://{{baseUrl}}/queryProductRecommendation"
? "fields"= "ut Excepteur"
? "offset"= "-49487780"
? "limit"= "-49487780"


// This operation creates a QueryProductRecommendation entity.

@name("Creates a QueryProductRecommendation")
POST "https://{{baseUrl}}/queryProductRecommendation"
"Content-Type": "application/json;charset=utf-8"
json({
    "description": "dolor nulla quis aute iru",
    "instantSyncRecommendation": true,
    "name": "dolor officia labore",
    "recommendationType": "fugiat minim qui labore",
    "category": [
        {
            "id": "esse ad labore dese",
            "href": "proident sint quis laborum enim",
            "name": "anim repr",
            "version": "laboris magna",
            "@baseType": "laborum i",
            "@schemaLocation": "https://fVEGv.yetM",
            "@type": "si",
            "@referredType": "velit mollit cupidatat"
        },
        {
            "id": "ipsum velit nulla fugiat pariatur",
            "href": "et cillum inci",
            "name": "ipsum",
            "version": "non ipsum pariatur veniam",
            "@baseType": "in proident eu irure",
            "@schemaLocation": "http://iCKOGo.fecaSTW",
            "@type": "sint nisi pariatu",
            "@referredType": "magna cillum"
        }
    ],
    "channel": [
        {
            "id": "veniam sed",
            "href": "cupidatat dolore dolor ex",
            "name": "ullamco ea Duis",
            "@baseType": "velit voluptate aliquip culpa",
            "@schemaLocation": "https://vXoFVmsrzdBsYSCTljhJhJpwiQ.jmmRM1ukZ8G8tCUNiQF8ZLc7nDzhrbSH0",
            "@type": "dolor irure laborum non mollit",
            "@referredType": "officia ad"
        },
        {
            "id": "laborum qui sint amet",
            "href": "sint officia anim",
            "name": "culpa fugiat",
            "@baseType": "fugiat",
            "@schemaLocation": "http://LQVJuw.yejczKv2Xt",
            "@type": "sunt voluptate Ut incididunt ullamco",
            "@referredType": "labore nostrud"
        }
    ],
    "place": {
        "role": "ex commodo nisi quis Excepteur",
        "id": "ad sit dolor eiusmod do",
        "href": "ea velit minim in",
        "name": "mollit e",
        "@baseType": "et",
        "@schemaLocation": "https://INGTMfpDzBvLF.mfneB-1jgltt-nWWr",
        "@type": "laborum qui amet",
        "@referredType": "in"
    },
    "productOrder": [
        {
            "id": "ipsum consectetur commodo voluptate",
            "href": "velit mollit cillum",
            "name": "cillum nostrud aliquip",
            "@baseType": "aliqua fugiat sunt laboris",
            "@schemaLocation": "https://jFywovtOoCDqt.mvveVgdXnZEDxijDRcRsC-8PMPeSIxTYhiLoAE7nZUZaGRpdMXJanm21goUJ4",
            "@type": "occaecat",
            "@referredType": "anim occaecat consectetur aliquip"
        },
        {
            "id": "aliqua sed Excepteur in",
            "href": "deserunt",
            "name": "reprehenderit esse",
            "@baseType": "anim laboris",
            "@schemaLocation": "http://S.muhWnCivx87pRUZP1a-EBcMPOsbamZ0J2G8ZWBGOcuzBJEicE",
            "@type": "id laborum cillum amet reprehenderit",
            "@referredType": "aute"
        }
    ],
    "productOrderItem": [
        {
            "entityHref": "nulla labore sit Ut",
            "entityId": "consequat do adipisicing mollit",
            "itemId": "enim pariatur nulla consequat",
            "name": "qui Duis sint",
            "@baseType": "adipisicing eu",
            "@schemaLocation": "http://vOmQohWzLdBIJWZLoAJeleERudPcVX.nzdVGNiFa9rRxgwDfeZMJtSBkLG",
            "@type": "eu quis ullamco",
            "@referredType": "consectetur culpa aliqua"
        },
        {
            "entityHref": "cupi",
            "entityId": "in mollit do ex aliqua",
            "itemId": "cillum laboris enim ut",
            "name": "proident",
            "@baseType": "sed Lorem qui ut",
            "@schemaLocation": "https://LlxNwBSXZTFVgBhPnRAUnCyvmwJB.ulyHEVlto9-HAcBYx+cgV+C,pEsaTCoeraucg",
            "@type": "aliqua",
            "@referredType": "ut consequat elit"
        }
    ],
    "recommendationItem": [
        {
            "product": {
                "id": "tempor quis dolor",
                "href": "aliquip incidid",
                "description": "velit dolor",
                "isBundle": true,
                "isCustomerVisible": true,
                "name": "aliquip non",
                "orderDate": "2005-07-26T00:01:25.800Z",
                "productSerialNumber": "sunt reprehenderit",
                "startDate": "1953-08-09T05:59:54.194Z",
                "terminationDate": "1979-12-19T11:50:27.736Z",
                "agreement": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "billingAccount": {
                    "id": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "href": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "name": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@schemaLocation": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@type": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@referredType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "place": [
                    {
                        "role": "laboris",
                        "id": "irure nostrud commodo",
                        "href": "dolore",
                        "name": "est ut ad",
                        "@baseType": "nulla esse amet",
                        "@schemaLocation": "http://pMbUcoFnDEKDB.geyiyoslMEQObKBFn3tO,zt7J",
                        "@type": "sunt do Ut cupidatat veniam",
                        "@referredType": "Lorem velit"
                    },
                    {
                        "role": "reprehenderit labore",
                        "id": "sunt ipsum consectetur",
                        "href": "dolore eiusmod fugiat",
                        "name": "minim veniam in exercitation",
                        "@baseType": "ullamco consequat cillum",
                        "@schemaLocation": "https://kiesETfScwWFJL.awI,Y+xBMa9jqiKb7H",
                        "@type": "in deserunt magna",
                        "@referredType": "nostrud amet Duis ea"
                    }
                ],
                "product": [
                    {
                        "value": "<Circular reference to #/components/schemas/ProductRefOrValue detected>"
                    },
                    {
                        "value": "<Circular reference to #/components/schemas/ProductRefOrValue detected>"
                    }
                ],
                "productCharacteristic": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "productOffering": {
                    "id": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "href": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "name": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@schemaLocation": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@type": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@referredType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "productOrderItem": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "productPrice": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "productRelationship": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "productSpecification": {
                    "id": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "href": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "name": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "version": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "targetProductSchema": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@schemaLocation": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@type": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@referredType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "productTerm": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "realizingResource": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "realizingService": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "relatedParty": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "status": "cancelled",
                "@baseType": "ipsum ad aliqua esse in",
                "@schemaLocation": "http://BLsX.vsniQzTREmb.XqWEWOn6TJ9hT4jf4HshtPcoPStiafZLJE3gUM",
                "@type": "ea in",
                "@referredType": "elit laborum"
            },
            "id": "Ut",
            "priority": -89910058,
            "productOffering": {
                "id": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "href": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "name": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@baseType": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@schemaLocation": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@type": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@referredType": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            },
            "@baseType": "pariatur adipisicing in culpa",
            "@schemaLocation": "http://aoQeAM.vqpVXzEWjiu+Eghroyg5FjAxRKPNqg8tdf1,qn+wm-+gg1",
            "@type": "sed anim"
        },
        {
            "product": {
                "id": "sit culpa non officia",
                "href": "elit in a",
                "description": "ex do",
                "isBundle": false,
                "isCustomerVisible": false,
                "name": "cupidatat ullamco esse ea",
                "orderDate": "2011-08-21T08:35:40.005Z",
                "productSerialNumber": "reprehenderit cupidatat irure proident",
                "startDate": "2008-02-19T20:37:49.570Z",
                "terminationDate": "2000-02-16T07:00:06.315Z",
                "agreement": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "billingAccount": {
                    "id": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "href": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "name": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@schemaLocation": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@type": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@referredType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "place": [
                    {
                        "role": "do",
                        "id": "est ut",
                        "href": "sint Excepteur ea",
                        "name": "enim sit laborum anim",
                        "@baseType": "mollit Duis",
                        "@schemaLocation": "https://YwbvFu.fmnCmntigRg9Ih1fF-hCE8TG",
                        "@type": "proident aute commodo",
                        "@referredType": "esse minim"
                    },
                    {
                        "role": "enim",
                        "id": "dolor dolore",
                        "href": "ut mollit Lorem",
                        "name": "est velit eu dolor",
                        "@baseType": "ex magna esse",
                        "@schemaLocation": "https://qHxebKFrobMpAojEc.jupaN4JQqHAIrDOlnB3MNVvR5mPje6W-2bwsbzak,-Rcl6,kRzqtV+,4voLMM,1A7mnabcBfJ.7RgmEx",
                        "@type": "ipsum",
                        "@referredType": "dolore ut officia dolor"
                    }
                ],
                "product": [
                    {
                        "value": "<Circular reference to #/components/schemas/ProductRefOrValue detected>"
                    },
                    {
                        "value": "<Circular reference to #/components/schemas/ProductRefOrValue detected>"
                    }
                ],
                "productCharacteristic": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "productOffering": {
                    "id": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "href": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "name": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@schemaLocation": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@type": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@referredType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "productOrderItem": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "productPrice": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "productRelationship": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "productSpecification": {
                    "id": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "href": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "name": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "version": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "targetProductSchema": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@baseType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@schemaLocation": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@type": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    "@referredType": {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                },
                "productTerm": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "realizingResource": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "realizingService": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "relatedParty": [
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    },
                    {
                        "value": "<Error: Too many levels of nesting to fake this schema>"
                    }
                ],
                "status": "aborted ",
                "@baseType": "voluptate elit",
                "@schemaLocation": "https://YBwGOJZzskeNuHd.vjJJXiLO-uFUUDbQzLyE3PW5a9TgnMa.5FibU.xlZl4dkhnvytPa,LjhbnB3zW8",
                "@type": "eu es",
                "@referredType": "aliquip"
            },
            "id": "offic",
            "priority": 3020351,
            "productOffering": {
                "id": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "href": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "name": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@baseType": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@schemaLocation": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@type": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                "@referredType": {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            },
            "@baseType": "velit",
            "@schemaLocation": "https://ogpwWstjigYUoKACo.ksSzXcdwOLEXg,gNDtQRRVwVSht2z",
            "@type": "enim"
        }
    ],
    "relatedParty": {
        "@referredType": "culpa",
        "id": "ipsum",
        "href": "in laborum quis",
        "name": "Excepteur deserunt enim proident",
        "role": "laborum",
        "@baseType": "Excepteur enim reprehenderit commodo",
        "@schemaLocation": "http://YJyNCoLWpElDWmjwjDinGNee.dnfafLdWoS92Zj9uK",
        "@type": "velit ut occaecat pariatur"
    },
    "shoppingCart": [
        {
            "id": "culpa et velit aute proident",
            "href": "dolore cupidatat Lorem incididunt",
            "@baseType": "do occaecat",
            "@schemaLocation": "http://YxhyLTlfllcGLxTve.vvkqHmMl.xb9TNFJiga0Ds0IVSLoUp6y3F6s3M",
            "@type": "aliqua eiusmod laboris eu",
            "@referredType": "quis aliquip cupidatat eiusmod proident"
        },
        {
            "id": "in ex elit",
            "href": "enim anim sunt magna pariatur",
            "@baseType": "do adipisicing",
            "@schemaLocation": "http://l.jlgagL8.S.TKB.tcemfSk6qGlPYKNA7Bw.",
            "@type": "Duis adipisicing",
            "@referredType": "est amet elit mollit"
        }
    ],
    "shoppingCartItem": [
        {
            "entityHref": "velit qui",
            "entityId": "quis incididunt",
            "itemId": "deserunt",
            "name": "amet ut",
            "@baseType": "Excepteur in",
            "@schemaLocation": "https://EfouuUubcecokGNeF.bxhpFqEGSCJ2i-IYDIyDmSOl,A1L7cwvDIORRt6RMM,XH8BnOxgN.Y87lgzNeOC1Q3YjXFa",
            "@type": "esse fugiat eiusmod mollit",
            "@referredType": "magna dolore commodo aute"
        },
        {
            "entityHref": "ut laborum mollit irure",
            "entityId": "deserunt enim in reprehenderit officia",
            "itemId": "in in culpa",
            "name": "minim id Ut",
            "@baseType": "nisi Excepteur labore",
            "@schemaLocation": "http://SIGgaGvQivKLargbIQ.jkqT.s.dO85YP3XwlWTGvZnptYK1giS2fXFFVIsLXqfk6EdQ5U4pNyCkSKTHIQDlJnx4oH",
            "@type": "mini",
            "@referredType": "reprehenderit sint dolore id pariatur"
        }
    ],
    "state": "inProgress",
    "@baseType": "proident",
    "@schemaLocation": "http://cIoQOrjUjbupAWndQHeAddvJSSHSO.atBESy4AEtBjluxe+Fz7vWMFJ0hSxsxtT68v9INWHBVC+2mN-eYykGYYMB,-zYr6YU5IlxFVUBKci",
    "@type": "labore "
})


// This operation retrieves a QueryProductRecommendation entity. Attribute selection is enabled for all first level attributes.

@name("Retrieves a QueryProductRecommendation by ID")
GET "https://{{baseUrl}}/queryProductRecommendation/:id"
? "fields"= "ut Excepteur"



