#!/usr/bin/env dothttp

# imported from 35240-dd87bfa6-db1a-4bc7-933b-f90982450ad5.postman_collection.json

// Lists a business's customers.

@name("Get Customers")
GET "https://{{baseUrl}}/v2/customers"
? "cursor"= "<string>"



