#!/usr/bin/env dothttp

# imported from 35240-ae8d3219-5d98-4ce1-a73c-5c0bdc96ce37.postman_collection.json

// Upload the first image file.

@name("Upload first file")
POST "https://{{baseUrl}}/recognition/ocr/1.0/ocr"



