#!/usr/bin/env dothttp

# imported from 35240-e2e2501d-8339-4a48-97c8-c5ab15e26155.postman_collection.json

// Get a list of recent comments on a media object.

@name("Get a list of recent comments on a media object.")
GET "https://{{baseUrl}}/media/:media-id/comments"


// Remove a comment either on the authenticated user's media object or authored by the authenticated user.

@name("Remove a comment.")
DELETE "https://{{baseUrl}}/media/:media-id/comments/:comment-id"



