#!/usr/bin/env dothttp

# imported from 35240-9b526cd3-0f35-4ef8-ad1e-b13d97933210.postman_collection.json

@name("Authorize DB Security Group Ingress")
GET "https://{{aws_rds_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_rds_service}}", region="{{aws_rds_region}}")
? "Action"= "AuthorizeDBSecurityGroupIngress"
? "Version"= "2014-10-31"


@name("Revoke DB Security Group Ingress")
GET "https://{{aws_rds_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_rds_service}}", region="{{aws_rds_region}}")
? "Action"= "RevokeDBSecurityGroupIngress"
? "Version"= "2014-10-31"



