#!/usr/bin/env dothttp

# imported from 35240-c91dd83d-104d-4e80-addf-681b006b972a.postman_collection.json

@name("Delete Config Rule")
POST "https://{{aws_config_and_aws_config_rules_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_config_and_aws_config_rules_service}}", region="{{aws_config_and_aws_config_rules_region}}")
? "Action"= "DeleteConfigRule"
data('{
   "ConfigRuleName": "string"
}')


@name("Describe Config Rules")
POST "https://{{aws_config_and_aws_config_rules_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_config_and_aws_config_rules_service}}", region="{{aws_config_and_aws_config_rules_region}}")
? "Action"= "DescribeConfigRules"
data('{
   "ConfigRuleNames": [ "string" ],
   "NextToken": "string"
}')


@name("Put Config Rule")
POST "https://{{aws_config_and_aws_config_rules_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_config_and_aws_config_rules_service}}", region="{{aws_config_and_aws_config_rules_region}}")
? "Action"= "PutConfigRule"
data('{
   "ConfigRule": { 
      "ConfigRuleArn": "string",
      "ConfigRuleId": "string",
      "ConfigRuleName": "string",
      "ConfigRuleState": "string",
      "CreatedBy": "string",
      "Description": "string",
      "InputParameters": "string",
      "MaximumExecutionFrequency": "string",
      "Scope": { 
         "ComplianceResourceId": "string",
         "ComplianceResourceTypes": [ "string" ],
         "TagKey": "string",
         "TagValue": "string"
      },
      "Source": { 
         "Owner": "string",
         "SourceDetails": [ 
            { 
               "EventSource": "string",
               "MaximumExecutionFrequency": "string",
               "MessageType": "string"
            }
         ],
         "SourceIdentifier": "string"
      }
   },
   "Tags": [ 
      { 
         "Key": "string",
         "Value": "string"
      }
   ]
}')



