#!/usr/bin/env dothttp

# imported from 35240-bb47693c-cb5d-4c67-9555-2ec7317f9794.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// Starts maintenance mode of instances belonging to a Deployment Resource.

@name("Start maintenance mode") : "base-inherit-auth"
POST "https://{{baseUrl}}/deployments/:deployment_id/:resource_kind/:ref_id/instances/:instance_ids/maintenance-mode/_start"
? "ignore_missing"= "false"


// Stops maintenance mode of instances belonging to a Resource.

@name("Stop maintenance mode") : "base-inherit-auth"
POST "https://{{baseUrl}}/deployments/:deployment_id/:resource_kind/:ref_id/instances/:instance_ids/maintenance-mode/_stop"
? "ignore_missing"= "false"



