#!/usr/bin/env dothttp

# imported from 35240-d47c7988-a7de-44ff-ba08-7608a9285ad4.postman_collection.json

@name("By Sol")
GET "https://api.nasa.gov/mars-photos/api/v1/rovers/spirit/photos"
? "sol"= "1000"
? "api_key"= "{{api_key}}"
? "page"= "1"
? "camera"= ""


@name("By Earth Date")
GET "https://api.nasa.gov/mars-photos/api/v1/rovers/spirit/photos"
? "earth_date"= "2009-01-01"
? "api_key"= "{{api_key}}"



