#!/usr/bin/env dothttp

# imported from 35240-baa21855-56c4-411b-b54e-86741f2e4115.postman_collection.json

// Get shoppers me orders.

@name("Get Shoppers Me Orders")
GET "https://{{baseUrl}}/v1/shoppers/me/orders"



