#!/usr/bin/env dothttp

# imported from 35240-9c081086-8dbf-4804-b7c8-4341ba1c240d.postman_collection.json

// Get a list of type ids
// 
// ---
// Alternate route: `/legacy/universe/types/`
// 
// Alternate route: `/v1/universe/types/`
// 
// ---
// This route expires daily at 11:05

@name("Get types")
GET "https://{{baseUrl}}/universe/types/"
"If-None-Match": "commodo irure"
? "datasource"= "tranquility"
? "page"= "1"


// Get information on a type
// 
// ---
// Alternate route: `/dev/universe/types/{type_id}/`
// 
// Alternate route: `/v3/universe/types/{type_id}/`
// 
// ---
// This route expires daily at 11:05

@name("Get type information")
GET "https://{{baseUrl}}/universe/types/:type_id/"
"Accept-Language": "en"
"If-None-Match": "commodo irure"
? "datasource"= "tranquility"
? "language"= "en"



