#!/usr/bin/env dothttp

# imported from 35240-afbc2083-42c9-4108-83db-0b859aa69233.postman_collection.json

@name("Deactivate M F A Device")
GET "https://{{aws_identtity_and_access_management_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_identtity_and_access_management_service}}", region="{{aws_identtity_and_access_management_region}}")
? "Version"= "2010-05-08"


@name("Enable M F A Device")
GET "https://{{aws_identtity_and_access_management_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_identtity_and_access_management_service}}", region="{{aws_identtity_and_access_management_region}}")
? "Version"= "2010-05-08"


@name("List M F A Devices")
GET "https://{{aws_identtity_and_access_management_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_identtity_and_access_management_service}}", region="{{aws_identtity_and_access_management_region}}")
? "Version"= "2010-05-08"


@name("Resync M F A Device")
GET "https://{{aws_identtity_and_access_management_base_url}}/"
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_identtity_and_access_management_service}}", region="{{aws_identtity_and_access_management_region}}")
? "Version"= "2010-05-08"



