#!/usr/bin/env dothttp

# imported from 35240-5f0de24a-12d4-4bb7-a222-68e7bfdfd2e8.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// Add a class to the prioritized entry points list. The body class name must match the resource identifier

@name("Add a class to the prioritized entry points list") : "base-inherit-auth"
PUT "https://{{baseUrl}}/services/:env_id/settings/entrypoints/prioritized/classes/:class_name"
"Content-Type": "application/json"
json({
    "name": "com.company.ClassName"
})


// Remove a class from the prioritized entry points list

@name("Remove a class from the prioritized entry points list") : "base-inherit-auth"
DELETE "https://{{baseUrl}}/services/:env_id/settings/entrypoints/prioritized/classes/:class_name"



