#!/usr/bin/env dothttp

# imported from 35240-153b1edc-7cd0-4f1f-a8a3-bd5fb65bc144.postman_collection.json

@name("Users")
GET "https://{{baseUrl}}/users"
? "q"= "<string>"
? "client_id"= "<string>"



