#!/usr/bin/env dothttp

# imported from 35240-b4284fc2-719c-44f6-8790-5e73e68963c4.postman_collection.json

// Retrieve the list of active property mappings for the specified device
// type.  A property mapping defines how properties from inbound events are
// mapped to properties defined on an logical interface associated with
// the device type.

@name("Get the list of active property mappings for the device type")
GET "https://{{baseUrl}}/device/types/:typeId/mappings"


// Retrieves the active property mappings for a specific logical
// interface for the device type.

@name("Get the active property mappings for a specific logical interface
for a device type.
")
GET "https://{{baseUrl}}/device/types/:typeId/mappings/:logicalInterfaceId"



