#!/usr/bin/env dothttp

# imported from 35240-eebe2b77-bc21-4c11-b32e-e737757a52b2.postman_collection.json

// Get the privileges information

@name("Get the privileges information")
GET "https://{{baseUrl}}/privileges"


// Update the privileges information

@name("Update the privileges information")
PUT "https://{{baseUrl}}/privileges/:uuid"



