#!/usr/bin/env dothttp

# imported from 35240-5af4ed67-4654-4363-a86d-3c7bcff23c51.postman_collection.json

// Get category trees.

@name("Get category trees")
GET "https://{{baseUrl}}/rest/category_branches"
? "page"= "<post>"
? "itemsPerPage"= "<>"
? "type"= "<post>"


// Gets the category tree of a category. The ID of the category must be specified.

@name("Get category tree")
GET "https://{{baseUrl}}/rest/category_branches/:id"



