#!/usr/bin/env dothttp

# imported from 35240-7d2c214b-77c4-4e90-8dc4-3cd4493a1c9a.postman_collection.json

// Get Startup Followers

@name("Get Startup Followers")
GET "https://{{baseUrl}}/startups/:startup_id/followers"


// Get Startup Followers IDs

@name("Get Startup Followers IDs")
GET "https://{{baseUrl}}/startups/:startup_id/followers/ids"



