#!/usr/bin/env dothttp

# imported from 35240-69935689-abac-4ca3-a7a8-e89ccfe72173.postman_collection.json

// This operation list or find AiContract entities

@name("List or find AiContract objects")
GET "https://{{baseUrl}}/aiContract"
? "fields"= "ex ullamco ad"
? "offset"= "-82478083"
? "limit"= "-82478083"


// This operation creates a AiContract entity.

@name("Creates a AiContract")
POST "https://{{baseUrl}}/aiContract"
"Content-Type": "application/json;charset=utf-8"
json({
    "state": "eiusmod officia eu velit",
    "aiContractSpecification": {
        "id": "ut in voluptat",
        "href": "http://zFyGmupdzDZzUGLQFwX.ojqVdkvhViBk.Xm3Zfvwt82rP+-CdGxUo2.hLRHHu,spmaoZh9xnr3",
        "name": "Lorem minim",
        "@baseType": "Excepteur eiusmod Ut",
        "@schemaLocation": "http://CbzYogahLYKstiEYMAafpXaVnJPNzK.ijyjFb",
        "@type": "enim id Duis",
        "@referredType": "in cupidatat"
    },
    "relatedParty": [
        {
            "@referredType": "exercitation ut sit",
            "id": "cillum dolore nulla",
            "href": "https://IqIcceEkzskcDsbHVKGReCaPQNwj.hsE-Zb4XTzxLIgq.jSVOKExkI3",
            "name": "non Excepteur Lorem",
            "role": "ut",
            "@baseType": "amet nostrud dolore nulla",
            "@schemaLocation": "https://MHOuoLC.enjdC3aZYW9bbQyMuNsTTrgDAQvmbTIKA.VEs4R.6AmCY2qGg2I0kdvd2i",
            "@type": "dolore"
        }
    ],
    "aiModel": {
        "id": "",
        "href": "http://BmTOUCZoFKOpUPEzC.jmYJKzT+CmFVEkU4X48dBTK9gZD",
        "name": "nostrud nulla Lorem labore",
        "@baseType": "eu aliqua",
        "@schemaLocation": "https://oKrvFFeiouwNKSl.omecTkKl53.tuq+sLBRxN+kxyd4d1kMRBr,w0-A4sTdoSR3Fz72ss",
        "@type": "Excepteur esse officia",
        "@referredType": "in sed cil"
    },
    "approvalDate": "1961-11-05T22:40:41.855Z",
    "approved": true,
    "description": "laborum consequat esse elit",
    "name": "temp",
    "version": "Excepteur tempor dolore",
    "characteristic": [
        {
            "name": "esse sunt adipisicing occaecat",
            "value": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "id": "non nisi anim",
            "valueType": "eiusmod qui quis",
            "characteristicRelationship": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ],
            "@baseType": "eiusmod ad ea do",
            "@schemaLocation": "https://zXRGNuUyRAUhfmcLDAeXWFyP.uwfmF3pzrV0-HAwIr+",
            "@type": "Excepteur officia eu"
        },
        {
            "name": "in nulla reprehenderit",
            "value": {
                "value": "<Error: Too many levels of nesting to fake this schema>"
            },
            "id": "aliqua officia sed cupidatat magna",
            "valueType": "fugiat ullamco cupidatat",
            "characteristicRelationship": [
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                },
                {
                    "value": "<Error: Too many levels of nesting to fake this schema>"
                }
            ],
            "@baseType": "cupidatat",
            "@schemaLocation": "http://g.igglim3nN4IlfyYIrh6hjTxV,x-+TL5,mO6sxEBKdySuiLnRtSX.Qd",
            "@type": "nisi proident"
        }
    ],
    "rule": [
        {
            "id": "et laboris officia",
            "href": "http://mvfAWCrPVRaOLmZpcwYLSPBNLTPQJnExy.idwab5HhR.18Rqc1NwYmEQMPNnyC+pawc8Icb9+mAueNOAkG8Nfv4f",
            "name": "Ut dolor aliqua",
            "@baseType": "ea Ut aliquip",
            "@schemaLocation": "http://VOgnyhTVZGZkzNHwrghUoNoLXgEGKDwat.krAUOnfZwb1jlnkV0gX",
            "@type": "reprehenderit quis"
        },
        {
            "id": "voluptate",
            "href": "http://XGmwOXEJgwLQgzMn.srnsNJac8ufbUyoJj7Fwl3bUQH5umkA0Cjc1axO,xB5RG6",
            "name": "proident exercitation ad ut",
            "@baseType": "est dolor",
            "@schemaLocation": "http://Kcftj.cubITn",
            "@type": "laborum minim ex in"
        }
    ],
    "template": {
        "id": "laboris sint sit",
        "href": "aliquip",
        "description": "commodo eiusmod laborum sed",
        "name": "aliqua",
        "@baseType": "fugiat ",
        "@schemaLocation": "https://kJciRhbnYnNE.ichNACZBUOYHMkShWYRD-DvjRk.,",
        "@type": "anim do",
        "@referredType": "culpa"
    },
    "validFor": {
        "endDateTime": "1985-04-12T23:20:50.52Z",
        "startDateTime": "1985-04-12T23:20:50.52Z"
    },
    "@baseType": "id dolor in",
    "@schemaLocation": "http://wwBQD.qkrjoN-CdEgprqzCyaKF0.",
    "@type": "laborum sint proident sed"
})



