#!/usr/bin/env dothttp

# imported from 35240-620eadc5-dd17-4511-931c-1df38f41a835.postman_collection.json

@name("codeOfConduct")
POST "https://{{url}}/"



@name("codesOfConduct")
POST "https://{{url}}/"



@name("enterprise")
POST "https://{{url}}/"



@name("enterpriseAdministratorInvitation")
POST "https://{{url}}/"



@name("enterpriseAdministratorInvitationByToken")
POST "https://{{url}}/"



@name("license")
POST "https://{{url}}/"



@name("licenses")
POST "https://{{url}}/"



@name("marketplaceCategories")
POST "https://{{url}}/"



@name("marketplaceCategory")
POST "https://{{url}}/"



@name("marketplaceListing")
POST "https://{{url}}/"



@name("marketplaceListings")
POST "https://{{url}}/"



@name("meta")
POST "https://{{url}}/"



@name("node")
POST "https://{{url}}/"



@name("nodes")
POST "https://{{url}}/"



@name("organization")
POST "https://{{url}}/"



@name("rateLimit")
POST "https://{{url}}/"



@name("relay")
POST "https://{{url}}/"



@name("repository")
POST "https://{{url}}/"



@name("repositoryOwner")
POST "https://{{url}}/"



@name("resource")
POST "https://{{url}}/"



@name("search")
POST "https://{{url}}/"



@name("securityAdvisories")
POST "https://{{url}}/"



@name("securityAdvisory")
POST "https://{{url}}/"



@name("securityVulnerabilities")
POST "https://{{url}}/"



@name("sponsorsListing")
POST "https://{{url}}/"



@name("topic")
POST "https://{{url}}/"



@name("user")
POST "https://{{url}}/"



@name("viewer")
POST "https://{{url}}/"




