#!/usr/bin/env dothttp

# imported from 35240-73f434f4-ed4e-4c94-87a0-83dd941103cd.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"
basicauth("<Basic Auth Username>", "<Basic Auth Password>")


// Create a global type & type version manager

@name("composer rest type global create") : "base-inherit-auth"
POST "https://{{baseUrl}}/composer/rest/type/global/"



