#!/usr/bin/env dothttp

# imported from 35240-5af4ed67-4654-4363-a86d-3c7bcff23c51.postman_collection.json

// Deletes a task..

@name("Deletes a task.")
DELETE "https://{{baseUrl}}/rest/boards/:boardId/columns/:columnId/tasks/:taskId"


// Updates the position of a task..

@name("Updates the position of a task.")
PUT "https://{{baseUrl}}/rest/boards/:boardId/columns/:columnId/tasks/:taskId/position"
? "position"= "<post>"



