#!/usr/bin/env dothttp

# imported from 35240-889839f2-e009-4638-ada6-41f119b9f6c7.postman_collection.json

@name("Core Tooling")
GET "https://{{tooling_url}}/collections/tooling/core/"


@name("Community Tooling")
GET "https://{{tooling_url}}/tooling/community/"



