#!/usr/bin/env dothttp

# imported from 35240-a96221e2-b43c-4973-9be0-3ec0566f4cd9.postman_collection.json

// Update an existing product variant.

@name("Update an existing product variant")
PUT "https://{{baseUrl}}/admin/variants/34705478094.json"
"Content": "<>"


// Get a product variant by id.

@name("Get a product variant by id")
GET "https://{{baseUrl}}/admin//variants/25831837123.json"
"Content": "<>"



