#!/usr/bin/env dothttp

# imported from 35240-c446a4c9-8dd6-45c4-99f2-688a96fe76ae.postman_collection.json

// Issue Comments are ordered by ascending ID.

@name("List issue comments")
GET "https://{{baseUrl}}/repos/:owner/:repo/issues/:issue_number/comments"
? "since"= "<string>"
? "per_page"= "30"
? "page"= "1"


// This endpoint triggers [notifications](https://help.github.com/articles/about-notifications/). Creating content too quickly using this endpoint may result in abuse rate limiting. See "[Abuse rate limits](https://developer.github.com/v3/#abuse-rate-limits)" and "[Dealing with abuse rate limits](https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits)" for details.

@name("Create an issue comment")
POST "https://{{baseUrl}}/repos/:owner/:repo/issues/:issue_number/comments"
"Content-Type": "application/json"
json({
    "body": "<string>"
})



