#!/usr/bin/env dothttp

# imported from 35240-5af4ed67-4654-4363-a86d-3c7bcff23c51.postman_collection.json

// Gets the shopping cart for the current customer session.

@name("Get basket")
GET "https://{{baseUrl}}/rest/basket"



