#!/usr/bin/env dothttp

# imported from 35240-01e79e8b-0f05-4fff-860a-a88d8c927eac.postman_collection.json

@name("get Password Forgotten")
GET "https://{{baseUrl}}/password_forgotten"


@name("get Password Forgotten Key")
GET "https://{{baseUrl}}/password_forgotten/:key"



