#!/usr/bin/env dothttp

# imported from 35240-9a62c01e-3db2-4f66-b90d-a4df9dd9bd07.postman_collection.json

// Enumerates group assignments for an application.

@name("List Groups Assigned to Application")
GET "https://{{baseUrl}}/api/v1/apps/:appId/groups"
? "q"= "<string>"
? "after"= "<string>"
? "limit"= "<integer>"
? "expand"= "<string>"


// Removes a group assignment from an application.

@name("Remove Group from Application")
DELETE "https://{{baseUrl}}/api/v1/apps/:appId/groups/:groupId"



