#!/usr/bin/env dothttp

# imported from 35240-9dab0145-9066-4a7b-90a7-7a8a94bce777.postman_collection.json

@name("On sandbox only - Create a test merchant to work with on sandbox.")
POST "https://{{baseUrl}}/merchant"



