#!/usr/bin/env dothttp

# imported from 35240-01e79e8b-0f05-4fff-860a-a88d8c927eac.postman_collection.json

@name("get Self Payments Methods")
GET "https://{{baseUrl}}/self/payments/methods"


@name("/self/payments/methods/default")
GET "https://{{baseUrl}}/self/payments/methods/default"


@name("delete Self Payments Methods M Id")
DELETE "https://{{baseUrl}}/self/payments/methods/:mId"



