#!/usr/bin/env dothttp

# imported from 35240-6765e1cc-2c5d-40bb-8932-494c6fbb000a.postman_collection.json

// Create new contact

@name("Create contact")
POST "https://{{baseUrl}}/api/v1/contacts/contact"
"Authorization": "Bearer <Bearer Token>"
"Content-Type": "application/json"
json({
    "properties": [
        {
            "property": "labore fugiat qui dolore",
            "value": {}
        },
        {
            "property": "c",
            "value": {}
        }
    ],
    "listRelations": [
        "adipisicing veniam deserunt eiusmo",
        "elit Duis dolor"
    ]
})



