#!/usr/bin/env dothttp

# imported from 35240-396d9363-dad9-4f4b-8418-119dc20d1211.postman_collection.json

@name("Describe Event Configurations")
GET "https://{{aws_internet_of_things_base_url}}/event-configurations&creationDate=&eventConfigurations=&lastModifiedDate="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")


@name("Update Event Configurations")
GET "https://{{aws_internet_of_things_base_url}}/event-configurations&eventConfigurations="
awsauth(access_id="{{accessKey}}", secret_key="{{secretKey}}", service="{{aws_internet_of_things_service}}", region="{{aws_internet_of_things_region}}")



