#!/usr/bin/env dothttp

# imported from 35240-c446a4c9-8dd6-45c4-99f2-688a96fe76ae.postman_collection.json

// Lists the public SSH keys for the authenticated user's GitHub account. Requires that you are authenticated via Basic Auth or via OAuth with at least `read:public_key` [scope](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).

@name("List public SSH keys for the authenticated user")
GET "https://{{baseUrl}}/user/keys"
? "per_page"= "30"
? "page"= "1"


// Adds a public SSH key to the authenticated user's GitHub account. Requires that you are authenticated via Basic Auth, or OAuth with at least `write:public_key` [scope](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/).

@name("Create a public SSH key for the authenticated user")
POST "https://{{baseUrl}}/user/keys"
"Content-Type": "application/json"
json({
    "key": "<string>",
    "title": "<string>"
})



