#!/usr/bin/env dothttp

# imported from 35240-81e3517b-5c56-4500-b086-0e52eb5d86ca.postman_collection.json

// Currencies (2.x only).

@name("currencies (2.x only)")
GET "https://{{baseUrl}}/rest/v1/currencies"


// Assuming that the given code is the code of an existing currency

@name("currency (2.x only)")
GET "https://{{baseUrl}}/rest/v1/currencies/USD"



