#!/usr/bin/env dothttp

# imported from 35240-02fae580-11a1-41da-afdc-655537d58f8f.postman_collection.json

// base-inherit-auth

@name("base-inherit-auth")
GET "https://"


// This endpoint lists featured video collections and a name and cover video for each collection.

@name("List featured video collections") : "base-inherit-auth"
GET "https://{{baseUrl}}/v2/videos/collections/featured"
? "embed"= "<string>"


// This endpoint gets more detailed information about a featured video collection, including its cover video and timestamps for its creation and most recent update. To get the videos, use `GET /v2/videos/collections/featured/{id}/items`.

@name("Get the details of featured video collections") : "base-inherit-auth"
GET "https://{{baseUrl}}/v2/videos/collections/featured/:id"
? "embed"= "<string>"


// This endpoint lists the IDs of videos in a featured collection and the date that each was added.

@name("Get the contents of featured video collections") : "base-inherit-auth"
GET "https://{{baseUrl}}/v2/videos/collections/featured/:id/items"
? "page"= "1"
? "per_page"= "100"



